<?php

//This file is automatically generated. Do not modify.

return [
  'title' => 'हमारे सभी गंतव्य',
  'subtitle' => 'जहाँ भी आप जाएँ, हम हर गंतव्य के लिए eSIMs के साथ आपका ध्यान रखते हैं। शुरू करने के लिए नीचे अपने गंतव्य का चयन करें।',
];
