<?php

//This file is automatically generated. Do not modify.

return [
  'faq' => 'अक्सर पूछे जाने वाले प्रश्न',
  'subtitle' => 'क्या आपके पास प्रश्न हैं? हमारे पास उत्तर हैं। हमारे eSIMs के बारे में जानने के लिए आपको जो कुछ भी चाहिए, वह सब कुछ खोजें।',
];
