<?php

//This file is automatically generated. Do not modify.

return [
  'all_rights_reserved' => 'सभी अधिकार सुरक्षित हैं।',
  'foreign_currencies_for_reference_only' => 'विदेशी मुद्राएँ केवल संदर्भ के लिए हैं। चालान यूरो में होगा।',
];
