<?php

//This file is automatically generated. Do not modify.

return [
  'home' => 'घर',
  'supported-devices' => 'समर्थित उपकरण',
  'destinations' => 'सभी गंतव्य',
  'about' => 'के बारे में',
  'contact' => 'संपर्क',
  'portal_link' => 'मेरा Portal',
];
