<?php

//This file is automatically generated. Do not modify.

return [
  'days' => 'दिन',
  'buy_plan' => 'अभी खरीदें!',
  'perks' => [
    'instant' => 'प्रत्यक्ष डिलीवरी',
    'advanced_self_service' => 'उन्नत आत्म-सेवा पोर्टल',
    '247_support' => '24/7 लाइव चैट समर्थन',
    'prepaid' => 'पूर्वभुगतान, कोई शर्तें नहीं जुड़ी',
    'no_roaming' => 'कोई रोमिंग शुल्क नहीं',
  ],
  'local_for' => ':countryName के लिए स्थानीय eSIMs',
  'not_available_yet' => 'हम वर्तमान में इस देश के लिए eSIMs की पेशकश नहीं करते हैं।',
  'not_available_yet_contact_us' => 'हम अपने वैश्विक कवरेज का विस्तार करने के लिए कड़ी मेहनत कर रहे हैं। यदि आप इस देश के लिए eSIMs में रुचि रखते हैं, तो कृपया हमसे संपर्क करें।',
  'top_plan' => 'सबसे लोकप्रिय',
  'all_features' => 'सभी कार्य',
  'features' => [
    'feature_one' => 'संभावित हॉटस्पॉट',
    'feature_two' => 'सभी राष्ट्रीय नेटवर्क में कवरेज',
    'feature_three' => 'आपके व्यक्तिगत पोर्टल में सरल अपग्रेड',
  ],
  'buy_now' => 'अब खरीदें',
  'starting_from' => 'शुरू करते हुए',
  'choose_destination' => 'एक गंतव्य खोजें',
  'how_esim_works' => [
    'title' => 'eSIM कैसे काम करता है',
    'subtitle' => 'eSIM के साथ शुरुआत करना आसान है! जुड़े रहने के लिए इन सरल चरणों का पालन करें।',
    'steps' => [
      [
        'title' => 'अपने eSIM खरीदें',
        'description' => 'अपने गंतव्य का चयन करें, एक ऐसा बंडल चुनें जो आपकी डेटा आवश्यकताओं को पूरा करता हो, और अपनी खरीदारी पूरी करें।',
        'image' => '/images/howesimworks/1.png',
      ],
      [
        'title' => 'अपने eSIM प्राप्त करें',
        'description' => 'अपने eSIM QR कोड को सीधे अपने ईमेल में प्राप्त करें। तुरंत उपयोग के लिए तैयार।',
        'image' => '/images/howesimworks/2.png',
      ],
      [
        'title' => 'सक्रिय करें और कनेक्ट करें',
        'description' => 'QR कोड स्कैन करें, अपने eSIM को सक्रिय करें, और जहां भी आप यात्रा करें, तेज, विश्वसनीय डेटा का आनंद लें।',
        'image' => '/images/howesimworks/3.png',
      ],
    ],
  ],
  'sub_description' => 'नीचे अपना बंडल चुनें और :countryName में सबसे अच्छे नेटवर्क पर सबसे अच्छे मूल्य पर निर्बाध कनेक्टिविटी का आनंद लें।',
];
