<?php

//This file is automatically generated. Do not modify.

return [
  'title' => 'eSIM-सेवा - यात्रियों के लिए प्रीपेड वर्चुअल सिम कार्ड - :site_name',
  'description' => 'eSIM-सर्विस ⏩ पर्यटन और व्यवसाय के लिए प्रीपेड डिजिटल सिम-कार्ड ⏩ मानक और असीमित, स्थानीय और वैश्विक मोबाइल डेटा योजनाएँ ⏩ कोई अनुबंध नहीं ✅ कोई छिपी हुई रोमिंग लागत और शुल्क नहीं ✅ - :site_name',
  'keywords' => 'eSIM, eSIM-service, eSIM-kaart, eSIM-gegevens, eSIM-gegevensplan, eSIM-gegevensplannen, eSIM-gegevensplan voor reizigers, eSIM-gegevensplan voor toeristen, eSIM-gegevensplan voor bedrijven, eSIM-gegevensplan voor reizen, eSIM-gegevensplan voor Europa, eSIM-gegevensplan voor de VS, eSIM-gegevensplan voor Azië, eSIM-gegevensplan voor Afrika, eSIM-gegevensplan voor Australië, eSIM-gegevensplan voor Zuid-Amerika, eSIM-gegevensplan voor Noord-Amerika, eSIM-gegevensplan voor het Midden-Oosten, eSIM-gegevensplan voor Rusland, eSIM-gegevensplan voor China, eSIM-gegevensplan voor India, eSIM-gegevensplan voor Japan',
  'routes' => [
    'home' => [
      'title' => 'eSIM-सेवा - यात्रियों के लिए प्रीपेड वर्चुअल सिम कार्ड - :site_name',
      'description' => 'eSIM-सेवा ⏩ पर्यटन और व्यवसाय के लिए प्रीपेड डिजिटल सिम कार्ड ⏩ मानक और अनलिमिटेड, स्थानीय और वैश्विक मोबाइल डेटा योजनाएँ ⏩ कोई अनुबंध नहीं ✅ कोई छिपी हुई रोमिंग लागत और शुल्क नहीं ✅ - :site_name',
    ],
    'about' => [
      'title' => 'हमारे बारे में - :site_name',
      'description' => 'हमारे बारे में ⏩ पर्यटन और व्यवसाय के लिए प्रीपेड डिजिटल सिम कार्ड ⏩ मानक और असीमित, स्थानीय और वैश्विक मोबाइल डेटा योजनाएँ ⏩ कोई अनुबंध नहीं ✅ कोई छिपी हुई रोमिंग लागत और शुल्क नहीं ✅ - :site_name',
    ],
    'supported-devices' => [
      'title' => 'समर्थित उपकरण - :site_name',
      'description' => 'समर्थित उपकरण ⏩ पर्यटन और व्यवसाय के लिए प्रीपेड डिजिटल सिम कार्ड ⏩ मानक और असीमित, स्थानीय और वैश्विक मोबाइल डेटा योजनाएँ ⏩ कोई अनुबंध नहीं ✅ कोई छिपी हुई रोमिंग लागत और शुल्क नहीं ✅ - :site_name',
    ],
    'esim-bundle-per-country' => [
      'title' => 'eSIM :countryName - :site_name',
      'description' => 'eSIM :countryName ⏩ पर्यटन और व्यवसाय के लिए प्रीपेड डिजिटल सिम कार्ड ⏩ मानक और असीमित, स्थानीय और वैश्विक मोबाइल डेटा योजनाएँ ⏩ कोई अनुबंध नहीं ✅ कोई छिपी हुई रोमिंग लागत और शुल्क नहीं ✅ - :site_name',
    ],
  ],
];
