<?php

//This file is automatically generated. Do not modify.

return [
  'Rens' => [
    'role' => 'सह-संस्थापक',
    'image' => '/images/team/rens.png',
  ],
  'Luuk' => [
    'role' => 'सह-संस्थापक',
    'image' => '/images/team/luuk.png',
  ],
  'Fleur' => [
    'role' => 'ग्राहक सहायता',
    'image' => '/images/team/fleur.png',
  ],
  'Patrick' => [
    'role' => 'डेवलपर',
    'image' => '/images/team/patrick.png',
  ],
];
