<?php

//This file is automatically generated. Do not modify.

return [
  'title' => 'O nama',
  'subtitle' => 'Navigirajte svijetom bez granica s nama. Mi smo vaš ultimativni partner koji vas drži povezanim gdje god vas vaša strast odvede.',
  'our_team' => 'Naš tim',
  'our_team_subtitle' => 'Vjerujemo u osnaživanje putnika pouzdanim i pristupačnim globalnim podatkovnim povezivanjem. Naš raznolik tim ujedinjen je u stvaranju povezanijeg i dostupnijeg svijeta za sve koji su u pokretu.',
  'why_us' => 'Zašto odabrati nas',
  'why_us_subtitle' => 'Ponosni smo na našu pouzdanu uslugu, konkurentne cijene i pristup orijentiran na kupca. Vaše zadovoljstvo je naš najveći prioritet.',
  'why_us_reasons' => [
    [
      'title' => 'Fleksibilni planovi dizajnirani za vaše putne potrebe',
      'subtitle' => 'Odaberite iz niza povoljnih paketa prilagođenih različitim zemljama i regijama. Dajemo vam fleksibilnost da odaberete savršen plan podataka, tako da plaćate samo ono što vam treba, bez skrivenih troškova.',
      'image' => '/images/whyus/nlo2.png',
    ],
    [
      'title' => 'Izravna aktivacija, nema potrebe za fizičkim SIM karticama',
      'subtitle' => 'Dani zamjene fizičkih SIM kartica su prošli. S nama, vaš eSIM se isporučuje izravno putem e-pošte i može se aktivirati unutar nekoliko minuta. Samo skenirajte QR kod i spremni ste za povezivanje.',
      'image' => '/images/whyus/nlo3.png',
    ],
  ],
  'contact' => 'Kontaktirajte nas',
  'contact_subtitle' => 'Ovdje smo da vam pomognemo. Ako imate bilo kakvih pitanja ili trebate pomoć, molimo kontaktirajte nas.',
];
