<?php

//This file is automatically generated. Do not modify.

return [
  'title' => 'Sve naše destinacije',
  'subtitle' => 'Gdje god da idete, imamo vas pokrivene s eSIM-ovima za svaku destinaciju. Odaberite svoju destinaciju u nastavku da biste započeli.',
];
