<?php

//This file is automatically generated. Do not modify.

return [
  'title' => 'Podržani uređaji',
  'subtitle' => 'Podržavamo širok spektar uređaja. Provjerite je li vaš uređaj na popisu u nastavku. Uređaji su organizirani prema proizvođaču.',
  'models_below' => 'Podržani modeli su navedeni u nastavku.',
];
