<?php

//This file is automatically generated. Do not modify.

return [
  'faq' => 'Česta pitanja',
  'subtitle' => 'Imate li pitanja? Imamo odgovore. Pronađite sve što trebate znati o našim eSIM-ovima.',
];
