<?php

//This file is automatically generated. Do not modify.

return [
  [
    'question' => 'Što je eSIM i kako mogu koristiti :organisationName?',
    'answer' => 'eSIM, ili ugrađeni SIM, je digitalna SIM kartica koja korisnicima omogućuje aktivaciju i upravljanje višestrukim mobilnim planovima na jednom uređaju bez potrebe za fizičkom SIM karticom. S eSIM-om možete lako prelaziti između mobilnih pružatelja i uživati u značajkama poput dodavanja dodatne linije za međunarodna putovanja ili održavanja odvojenih podatkovnih planova za osobnu i poslovnu upotrebu.',
  ],
  [
    'question' => 'Kako aktivirati eSIM mobilni internet s :organisationName?',
    'answer' => 'Da biste se povezali na internet koristeći :organisationName eSIM, slijedite ove korake: 1. Idite na postavke mobilnih podataka. 2. Uključite :organisationName mobilnu liniju. 3. Aktivirajte roaming podataka. 4. Odaberite :organisationName Internet liniju kao vašu primarnu vezu. *Izbjegavajte odabrati opciju "Ukloni plan podataka," jer će to izbrisati vaš eSIM profil.*',
  ],
  [
    'question' => 'Mogu li obavljati telefonske pozive ili slati tekstualne poruke?',
    'answer' => ':organisationName\'s prepaid eSIM plans are designed for data-only use and do not include a mobile phone number for traditional calls or SMS messages. We recommend using VoIP applications such as Facebook Messenger, WhatsApp, Viber, Telegram, or Skype to stay connected worldwide without the need for a standard international SIM card.',
  ],
  [
    'question' => 'Može li se eSIM kartica ponovo koristiti?',
    'answer' => 'Svaki QR kod za eSIM je jedinstven i može se koristiti samo na jednom uređaju. Kada se eSIM profil izbriše, QR kod se ne može ponovo koristiti na istom ili drugom uređaju, osiguravajući sigurnost i ekskluzivnost.',
  ],
  [
    'question' => 'Kada počinje trajanje eSIM mobilnih podataka?',
    'answer' => 'Trajanje vašeg eSIM podatkovnog plana započinje odmah nakon što se vaš uređaj prvi put poveže na mobilnu mrežu s eSIM-om.',
  ],
  [
    'question' => 'Mogu li produžiti datum isteka svog trenutnog eSIM mobilnog podatkovnog plana?',
    'answer' => 'Naravno! Primat ćete više obavijesti kada vam se paket gotovo isprazni. Možete lako dopuniti putem svog osobnog portala.',
  ],
  [
    'question' => 'Mogu li koristiti dijeljenje interneta ili Osobnu pristupnu točku s :organisationName?',
    'answer' => 'Da, možete dijeliti svoje mobilne podatke s drugim uređajima putem vaše :organisationName-eSIM. Jednostavno instalirajte :organisationName-eSIM na svoj uređaj i omogućite Osobnu točku pristupa u svojim postavkama. Ova funkcija je uključena bez dodatnih troškova, ali imajte na umu da će korištenje vezanih podataka biti oduzeto od vašeg plana.',
  ],
  [
    'question' => 'Mogu li zadržati brojeve iz svoje aplikacije za osobne poruke dok koristim eSIM iz :organisationName?',
    'answer' => 'Da, možete nastaviti koristiti svoj WhatsApp, Snapchat, Telegram i druge aplikacije za razmjenu poruka zajedno sa svojim :organisationName prepaid eSIM bez ikakvih problema.',
  ],
  [
    'question' => 'Kako mogu prenijeti svoj eSIM na novi telefon?',
    'answer' => 'Prije nego što prenesete, provjerite podržava li vaš novi pametni telefon eSIM tehnologiju. Kontaktirajte naš tim za podršku kako biste stvorili novi eSIM profil, a zatim se prijavite na svoj :organisationName račun na novom uređaju kako biste instalirali QR kod. Provjerite da li potvrđujete da koristite drugi uređaj za točne ažuriranja postavki.',
  ],
  [
    'question' => 'Postoje li ugovori poput onih tradicionalnih eSIM pružatelja?',
    'answer' => 'Ne, :organisationName ne zahtijeva da potpisujete ugovore. Možete aktivirati ili deaktivirati svoju eSIM karticu kako želite, ovisno o vašim planovima. Rado ćemo vam pomoći.',
  ],
  [
    'question' => 'Koja je razlika između :organisationName-ove eSIM i standardnih roaming podataka iz fizičkih mobilnih operatera?',
    'answer' => ':organisationName nudi podatkovne planove bez ugovora bez skrivenih troškova roaminga. Plaćate samo za podatke koje koristite, ovisno o paketu koji odaberete, što često čini ovu opciju ekonomičnijom.',
  ],
  [
    'question' => 'Zašto je moja brzina podataka spora?',
    'answer' => 'Brzina podataka može biti pogođena raznim faktorima, uključujući vrstu pametnog telefona koji imate, mrežnu tehnologiju, web stranice ili aplikacije koje koristite, te doba dana. Osim toga, brzine se mogu razlikovati ovisno o mrežnoj infrastrukturi zemlje. Ako doživljavate spore brzine, pokušajte ponovno pokrenuti svoj telefon i podijelite s nama rezultate brzine, posebno usporedbe s :LTE načinom uključenim i isključenim.',
  ],
  [
    'question' => 'Kako mogu pregledati svoje pakete?',
    'answer' => 'Možete pratiti svoje preostale podatke i limite u našem korisničkom panelu.',
  ],
  [
    'question' => 'Što čini :organisationName drugačijom od drugih eSIM usluga?',
    'answer' => ':organisationName se ističe suradnjom s lokalnim operaterima u više od 200 zemalja, nudeći isplative podatkovne pakete bez posrednika. Pružamo robusnu pokrivenost i jednostavan proces aktivacije. :organisationName je savršen za putnike koji traže rješenja za mobilni internet.',
  ],
];
