<?php

//This file is automatically generated. Do not modify.

return [
  'title' => 'Ostanite povezani online u :countryName',
  'subtitle' => 'Putujete u :countryName? Ostanite povezani s našim eSIM-om, osiguravajući vam trenutni pristup internetu po dolasku.',
  'features' => [
    [
      'title' => 'Pouzdano i brzo online u :countryName',
      'subtitle' => ':countryName je prekrasna destinacija, koja se ponosi živopisnim modernim gradovima i zadivljujućim prirodnim krajolicima. Poboljšajte svoje putno iskustvo s našim eSIM-om, osiguravajući da ostanete povezani odmah po dolasku.  
        Recite zbogom neugodnostima traženja lokalne SIM kartice ili suočavanju s skupim roamingom podataka. S našim eSIM-om uživat ćete u neometanom pristupu 4G/5G mrežama od najboljih pružatelja u zemlji, držeći vas online gdje god vas putovanje odvede.',
      'image' => 'images/features/feature1.jpg',
    ],
    [
      'title' => 'Ostanite povezani s voljenima',
      'subtitle' => 'Naš eSIM je dizajniran za neometan pristup internetu, omogućujući vam da ostanete povezani za sve vaše online aktivnosti bez potrebe za novim brojem telefona. Lako kreirajte hotspot kako biste podijelili svoju vezu s drugim putnicima ili obitelji, značajka koju često blokiraju drugi pružatelji, ali koju mi u potpunosti podržavamo. Uživajte u pogodnosti trenutne povezanosti na uređajima koji podržavaju eSIM, osiguravajući da vi i vaši voljeni ostanete online bilo kada, bilo gdje. Molimo vas da potvrdite podržava li vaš uređaj eSIM kako biste bili sigurni da ste spremni za naše internetske ponude. Imajte na umu da pozivanje i slanje poruka nisu podržani s našim eSIM-om.',
      'image' => 'images/features/feature2.jpg',
    ],
  ],
];
