<?php

//This file is automatically generated. Do not modify.

return [
  'all_rights_reserved' => 'Sva prava zadržana.',
  'foreign_currencies_for_reference_only' => 'Strane valute su samo za referencu. Fakturiranje će biti u eurima.',
];
