<?php

//This file is automatically generated. Do not modify.

return [
  'from' => ':price/GB',
  'title' => 'Povežite se globalno s našim eSIM-ima',
  'subtitle' => 'Istražite naše eSIM pakete i ostanite povezani, gdje god bili!',
  'search_destination' => 'Pronađite odredište',
  'show_all_esim' => 'Prikaži sve eSIM planove',
  'how_it_works' => 'Kako to funkcionira?',
  'steps' => [
    [
      'title' => 'Korak 1',
      'description' => 'Provjerite je li vaš uređaj kompatibilan s eSIM-om na našem popisu kompatibilnosti.',
    ],
    [
      'title' => 'Korak 2',
      'description' => 'Odaberite svoju destinaciju i željeni eSIM podatkovni plan',
    ],
    [
      'title' => 'Korak 3',
      'description' => 'Kupite eSIM karticu koja najbolje odgovara vašim potrebama',
    ],
    [
      'title' => 'Korak 4',
      'description' => 'Vaša eSIM će biti automatski isporučena. Slijedite upute u svom e-mailu.',
    ],
    [
      'title' => 'Korak 5',
      'description' => 'Instalirajte svoj eSIM profil i uživajte u svom putovanju!',
    ],
  ],
  'supported_networks' => 'Podržani mrežni pružatelji',
  'supported_networks_description' => 'Tijesno surađujemo s pouzdanim vodećim brendovima za povezivanje, medije i tehnologiju diljem svijeta.',
  'and_many_more' => 'i još mnogo toga...',
  'user_reviews' => 'Što naši zadovoljni korisnici kažu',
  'user_reviews_subtitle' => 'Pogledajte zašto putnici širom svijeta oslanjaju na naš eSIM za neprekidnu, pouzdanu povezivost u pokretu.',
  'faq' => 'Često postavljana pitanja',
  'popular_destinations' => 'Popularna odredišta',
  'popular_destinations_description' => 'Otkrijte naše najpopularnije eSIM destinacije i ostanite povezani, bez obzira kuda idete!',
  'see_all_destinations' => 'Pogledajte sve destinacije',
];
