<?php

//This file is automatically generated. Do not modify.

return [
  'home' => 'Dom',
  'supported-devices' => 'Podržani uređaji',
  'destinations' => 'Sve destinacije',
  'about' => 'O',
  'contact' => 'Kontakt',
  'portal_link' => 'Moj Portal',
];
