<?php

//This file is automatically generated. Do not modify.

return [
  'days' => 'dani',
  'buy_plan' => 'Kupite sada!',
  'perks' => [
    'instant' => 'Izravna dostava',
    'advanced_self_service' => 'Napredni portal za samoposluživanje',
    '247_support' => '24/7 podrška putem chata uživo',
    'prepaid' => 'Prepaid, bez uvjeta',
    'no_roaming' => 'Nema troškova za roaming',
  ],
  'local_for' => 'Lokalni eSIM-ovi za :countryName',
  'not_available_yet' => 'Trenutno ne nudimo eSIM-ove za ovu zemlju.',
  'not_available_yet_contact_us' => 'Radimo naporno na širenju naše globalne pokrivenosti. Ako ste zainteresirani za eSIM-ove za ovu zemlju u međuvremenu, molimo kontaktirajte nas.',
  'top_plan' => 'Najpopularniji',
  'all_features' => 'Sve funkcije',
  'features' => [
    'feature_one' => 'Moguća točka vrućine',
    'feature_two' => 'Pokriće na svim nacionalnim mrežama',
    'feature_three' => 'Jednostavna nadogradnja u vašem osobnom portalu',
  ],
  'buy_now' => 'Kupi sada',
  'starting_from' => 'Počinjući od',
  'choose_destination' => 'Pronađite odredište',
  'how_esim_works' => [
    'title' => 'Kako eSIM radi',
    'subtitle' => 'Započeti s eSIM-om je lako! Slijedite ove jednostavne korake kako biste ostali povezani.',
    'steps' => [
      [
        'title' => 'Kupite svoj eSIM',
        'description' => 'Odaberite svoju destinaciju, odaberite paket koji zadovoljava vaše potrebe za podacima i dovršite svoju kupnju.',
        'image' => '/images/howesimworks/1.png',
      ],
      [
        'title' => 'Primite svoj eSIM',
        'description' => 'Primite svoj eSIM QR kod izravno na svoju e-poštu. Spreman za korištenje odmah.',
        'image' => '/images/howesimworks/2.png',
      ],
      [
        'title' => 'Aktiviraj i poveži',
        'description' => 'Skenirajte QR kod, aktivirajte svoju eSIM i uživajte u brzom, pouzdanom internetu gdje god putovali.',
        'image' => '/images/howesimworks/3.png',
      ],
    ],
  ],
  'sub_description' => 'Odaberite svoj paket u nastavku i uživajte u besprijekornoj povezanosti u :countryName na najboljim mrežama po najboljoj cijeni.',
];
