<?php

//This file is automatically generated. Do not modify.

return [
  'title' => 'eSIM-usluga - Prepaid virtualne SIM kartice za putnike - :site_name',
  'description' => 'eSIM-usluga ⏩ Prepaid digitalne SIM kartice za turizam i posao ⏩ Standardni i neograničeni, lokalni i globalni mobilni podatkovni planovi ⏩ Nema ugovora ✅ Nema skrivenih troškova za roaming i naknada ✅ - :site_name',
  'keywords' => 'eSIM, eSIM-usluga, eSIM-kartica, eSIM-podaci, eSIM-podaci plan, eSIM-podaci planovi, eSIM-podaci plan za putnike, eSIM-podaci plan za turiste, eSIM-podaci plan za tvrtke, eSIM-podaci plan za putovanja, eSIM-podaci plan za Europu, eSIM-podaci plan za SAD, eSIM-podaci plan za Aziju, eSIM-podaci plan za Afriku, eSIM-podaci plan za Australiju, eSIM-podaci plan za Južnu Ameriku, eSIM-podaci plan za Sjevernu Ameriku, eSIM-podaci plan za Bliski Istok, eSIM-podaci plan za Rusiju, eSIM-podaci plan za Kinu, eSIM-podaci plan za Indiju, eSIM-podaci plan za Japan',
  'routes' => [
    'home' => [
      'title' => 'eSIM-usluga - Pretplatne virtualne SIM kartice za putnike - :site_name',
      'description' => 'eSIM-usluga ⏩ Prepaid digitalne SIM kartice za turizam i posao ⏩ Standardni i neograničeni, lokalni i globalni mobilni podatkovni planovi ⏩ Nema ugovora ✅ Nema skrivenih troškova i naknada za roaming ✅ - :site_name',
    ],
    'about' => [
      'title' => 'O nama - :site_name',
      'description' => 'O nama ⏩ Prepaid digitalne SIM kartice za turizam i posao ⏩ Standardni i neograničeni, lokalni i globalni mobilni podatkovni planovi ⏩ Nema ugovora ✅ Nema skrivenih troškova za roaming i naknada ✅ - :site_name',
    ],
    'supported-devices' => [
      'title' => 'Podržani uređaji - :site_name',
      'description' => 'Podržani uređaji ⏩ Prepaid digitalne SIM kartice za turizam i poslovanje ⏩ Standardni i neograničeni, lokalni i globalni mobilni podatkovni planovi ⏩ Nema ugovora ✅ Nema skrivenih troškova i naknada za roaming ✅ - :site_name',
    ],
    'esim-bundle-per-country' => [
      'title' => 'eSIM :countryName - :site_name',
      'description' => 'eSIM :countryName ⏩ Prepaid digitalne SIM kartice za turizam i posao ⏩ Standardni i neograničeni, lokalni i globalni mobilni podatkovni planovi ⏩ Nema ugovora ✅ Nema skrivenih troškova za roaming i naknada ✅ - :site_name',
    ],
  ],
];
