<?php

//This file is automatically generated. Do not modify.

return [
  'title' => 'eSIM usluga - Pretplaćene virtualne SIM kartice za putnike - :site_name',
  'description' => 'eSIM usluga ⏩ Pretplaćene digitalne SIM kartice za turizam i poslovanje ⏩ Standardni i neograničeni, lokalni i globalni mobilni podatkovni planovi ⏩ Nema ugovora ✅ Nema skrivenih troškova i naknada za roaming ✅ - :site_name',
  'keywords' => 'eSIM, eSIM usluga, eSIM kartica, eSIM podaci, eSIM podatkovni plan, eSIM podatkovni planovi, eSIM podatkovni plan za putnike, eSIM podatkovni plan za turiste, eSIM podatkovni plan za poslovanje, eSIM podatkovni plan za putovanje, eSIM podatkovni plan za Europu, eSIM podatkovni plan za SAD, eSIM podatkovni plan za Aziju, eSIM podatkovni plan za Afriku, eSIM podatkovni plan za Australiju, eSIM podatkovni plan za Južnu Ameriku, eSIM podatkovni plan za Sjevernu Ameriku, eSIM podatkovni plan za Bliski Istok, eSIM podatkovni plan za Rusiju, eSIM podatkovni plan za Kinu, eSIM podatkovni plan za Indiju, eSIM podatkovni plan za Japan',
  'routes' => [
    'home' => [
      'title' => 'eSIM usluga - Pretplatne virtualne SIM kartice za putnike - :site_name',
      'description' => 'eSIM usluga ⏩ Pretplatne digitalne SIM kartice za turizam i poslovanje ⏩ Standardni i neograničeni, lokalni i globalni mobilni podatkovni planovi ⏩ Nema ugovora ✅ Nema skrivenih troškova i naknada za roaming ✅ - :site_name',
    ],
    'about' => [
      'title' => 'O nama - :site_name',
      'description' => 'O nama ⏩ Pretplaćene digitalne SIM kartice za turizam i poslovanje ⏩ Standardni i neograničeni, lokalni i globalni mobilni podatkovni planovi ⏩ Nema ugovora ✅ Nema skrivenih troškova i naknada za roaming ✅ - :site_name',
    ],
    'supported-devices' => [
      'title' => 'Podržani uređaji - :site_name',
      'description' => 'Podržani uređaji ⏩ Predplaćene digitalne SIM kartice za turizam i poslovanje ⏩ Standardni i neograničeni, lokalni i globalni mobilni podatkovni planovi ⏩ Nema ugovora ✅ Nema skrivenih troškova i naknada za roaming ✅ - :site_name',
    ],
    'esim-bundle-per-country' => [
      'title' => 'Povoljne lokalne eSIM ponude za :countryName - :site_name',
      'description' => 'Povoljni lokalni eSIM paketi za :countryName ⏩ Pretpaid digitalne SIM kartice za turizam i poslovanje ⏩ Standardni i neograničeni, lokalni i globalni mobilni podatkovni paketi ⏩ Bez ugovora ✅ Nema skrivenih troškova i naknada za roaming ✅ - :site_name',
    ],
  ],
];
