<?php

//This file is automatically generated. Do not modify.

return [
  'Rens' => [
    'role' => 'Suosnivač',
    'image' => '/images/team/rens.png',
  ],
  'Luuk' => [
    'role' => 'Suosnivač',
    'image' => '/images/team/luuk.png',
  ],
  'Fleur' => [
    'role' => 'Podrška za korisnike',
    'image' => '/images/team/fleur.png',
  ],
  'Patrick' => [
    'role' => 'Razvijač',
    'image' => '/images/team/patrick.png',
  ],
];
