<?php

//This file is automatically generated. Do not modify.

return [
  'title' => 'Par mums',
  'subtitle' => 'Pārvietojieties pa pasauli bez robežām kopā ar mums. Mēs esam jūsu galīgais partneris, kas uztur jūs savienotu, kur vien jūsu kaislība jūs ved.',
  'our_team' => 'Mūsu komanda',
  'our_team_subtitle' => 'Mēs ticam ceļotāju pilnvarošana ar uzticamu un pieejamu globālo datu savienojamību. Mūsu daudzveidīgā komanda ir apvienota, lai radītu savienotāku un pieejamāku pasauli ikvienam, kurš ir ceļā.',
  'why_us' => 'Kāpēc izvēlēties mūs',
  'why_us_subtitle' => 'Mēs esam lepni par mūsu uzticamo pakalpojumu, konkurētspējīgajām cenām un klientu orientēto pieeju. Jūsu apmierinātība ir mūsu augstākā prioritāte.',
  'why_us_reasons' => [
    [
      'title' => 'Elastīgi plāni, kas izstrādāti jūsu ceļojumu vajadzībām',
      'subtitle' => 'Izvēlieties no dažādiem pieejamiem komplektiem, kas pielāgoti dažādām valstīm un reģioniem. Mēs sniedzam jums elastību izvēlēties ideālu datu plānu, tāpēc jūs maksājat tikai par to, kas jums nepieciešams, bez slēptām izmaksām.',
      'image' => '/images/whyus/nlo2.png',
    ],
    [
      'title' => 'Tieša aktivācija, nav nepieciešamas fiziskās SIM kartes',
      'subtitle' => 'Fizisko SIM karšu maiņas dienas ir beigušās. Ar mums jūsu eSIM tiek piegādāta tieši pa e-pastu un to var aktivizēt dažu minūšu laikā. Vienkārši noskenējiet QR kodu un esat gatavs pieslēgties.',
      'image' => '/images/whyus/nlo3.png',
    ],
  ],
  'contact' => 'Sazinieties ar mums',
  'contact_subtitle' => 'Mēs esam šeit, lai jums palīdzētu. Ja jums ir kādi jautājumi vai nepieciešama palīdzība, lūdzu, sazinieties ar mums.',
];
