<?php

//This file is automatically generated. Do not modify.

return [
  'title' => 'Visas mūsu galamērķi',
  'subtitle' => 'Kur vien jūs dodos, mēs esam jūs nodrošinājuši ar eSIM kartēm katram galamērķim. Izvēlieties savu galamērķi zemāk, lai sāktu.',
];
