<?php

//This file is automatically generated. Do not modify.

return [
  'title' => 'Atbalstītās ierīces',
  'subtitle' => 'Mēs atbalstām plašu ierīču klāstu. Pārbaudiet, vai jūsu ierīce ir zemāk esošajā sarakstā. Ierīces ir organizētas pēc ražotāja.',
  'models_below' => 'Atbalstītie modeļi ir uzskaitīti zemāk.',
];
