<?php

//This file is automatically generated. Do not modify.

return [
  [
    'question' => 'Kas ir eSIM un kā es varu izmantot :organisationName?',
    'answer' => 'eSIM, vai iebūvēta SIM, ir digitālā SIM karte, kas ļauj lietotājiem aktivizēt un pārvaldīt vairākus mobilos plānus vienā ierīcē, neizmantojot fizisku SIM karti. Ar eSIM jūs varat viegli pāriet starp mobilajiem pakalpojumu sniedzējiem un baudīt tādas funkcijas kā papildu līnijas pievienošana starptautiskai ceļošanai vai atsevišķu datu plānu uzturēšana personiskai un biznesa lietošanai.',
  ],
  [
    'question' => 'Kā aktivizēt eSIM mobilo internetu ar :organisationName?',
    'answer' => 'Lai savienotos ar internetu, izmantojot :organisationName eSIM, veiciet šādas darbības: 1. Dodieties uz saviem Mobilajiem datu iestatījumiem. 2. Ieslēdziet :organisationName mobilās līnijas. 3. Aktivizējiet Datu romingu. 4. Izvēlieties :organisationName Interneta līniju kā savu primāro savienojumu. *Izvairieties no opcijas "Noņemt datu plānu", jo tas dzēsīs jūsu eSIM profilu.*',
  ],
  [
    'question' => 'Vai es varu veikt telefona zvanus vai sūtīt īsziņas?',
    'answer' => ':organisationName priekšapmaksas eSIM plāni ir paredzēti tikai datu lietošanai un nesatur mobilā tālruņa numuru tradicionālām zvanām vai SMS ziņojumiem. Mēs iesakām izmantot VoIP lietotnes, piemēram, Facebook Messenger, WhatsApp, Viber, Telegram vai Skype, lai paliktu savienotam visā pasaulē bez nepieciešamības pēc standarta starptautiskās SIM kartes.',
  ],
  [
    'question' => 'Vai eSIM karte var tikt atkārtoti izmantota?',
    'answer' => 'Katrs QR kods eSIM ir unikāls un to var izmantot tikai vienā ierīcē. Kad eSIM profils ir dzēsts, QR kodu nevar atkārtoti izmantot tajā pašā vai citā ierīcē, nodrošinot drošību un ekskluzivitāti.',
  ],
  [
    'question' => 'Kad sākas eSIM mobilā datu plānu ilgums?',
    'answer' => 'Jūsu eSIM datu plāna ilgums sākas tūlīt pēc tam, kad jūsu ierīce pirmo reizi pieslēdzas mobilajam tīklam ar eSIM.',
  ],
  [
    'question' => 'Vai es varu pagarināt sava pašreizējā eSIM mobilā datu plāna derīguma termiņu?',
    'answer' => 'Protams! Jūs saņemsiet vairākas paziņojumu par push, kad būsiet gandrīz iztērējis savu paketi. Jūs varat viegli papildināt caur savu personīgo portālu.',
  ],
  [
    'question' => 'Vai es varu izmantot tethering vai Personal Hotspot ar :organisationName?',
    'answer' => 'Jā, jūs varat dalīties ar savu mobilā datiem ar citām ierīcēm, izmantojot savu :organisationName-eSIM. Vienkārši instalējiet :organisationName-eSIM savā ierīcē un aktivizējiet Personal Hotspot savās iestatījumos. Šī funkcija ir iekļauta bez papildu maksas, taču lūdzu ņemiet vērā, ka, izmantojot piesaistītos datus, tie tiks atskaitīti no jūsu plāna.',
  ],
  [
    'question' => 'Vai es varu saglabāt savas personīgās ziņojumapmaiņas lietotnes numurus, lietojot :organisationName eSIM?',
    'answer' => 'Jā, jūs varat turpināt izmantot savu WhatsApp, Snapchat, Telegram un citas ziņojumapmaiņas lietotnes kopā ar savu :organisationName priekšapmaksas eSIM bez jebkādām problēmām.',
  ],
  [
    'question' => 'Kā es varu pārsūtīt savu eSIM uz jaunu tālruni?',
    'answer' => 'Pirms pārsūtīšanas pārliecinieties, ka jūsu jaunais viedtālrunis atbalsta eSIM tehnoloģiju. Sazinieties ar mūsu atbalsta komandu, lai izveidotu jaunu eSIM profilu, pēc tam piesakieties savā :organisationName kontā jaunajā ierīcē, lai instalētu QR kodu. Pārliecinieties, ka apstiprināt, ka izmantojat citu ierīci precīziem iestatījumu atjauninājumiem.',
  ],
  [
    'question' => 'Vai pastāv līgumi, kas līdzīgi tradicionālo eSIM pakalpojumu sniedzēju līgumiem?',
    'answer' => 'Nē, :organisationName neprasa, lai jūs parakstītu līgumus. Jūs varat aktivizēt vai deaktivizēt savu eSIM karti pēc saviem ieskatiem, atkarībā no jūsu plāniem. Mēs esam priecīgi jums palīdzēt.',
  ],
  [
    'question' => 'Kāda ir atšķirība starp :organisationName eSIM un standarta viesabonēšanas datu plāniem no fiziskajiem mobilajiem operatoriem?',
    'answer' => ':organisationName piedāvā līgumus nesaturošus datu plānus bez slēptām ceļojumu izmaksām. Jūs maksājat tikai par datiem, kurus izmantojat, atkarībā no izvēlētā komplekta, padarot to bieži par izdevīgāku iespēju.',
  ],
  [
    'question' => 'Kāpēc mana datu ātrums ir lēns?',
    'answer' => 'Datu ātrumu var ietekmēt dažādi faktori, tostarp jūsu izmantotā viedtālruņa veids, tīkla tehnoloģija, vietnes vai lietotnes, ko izmantojat, un diennakts laiks. Turklāt ātrumi var atšķirties atkarībā no valsts tīkla infrastruktūras. Ja jūs piedzīvojat lēnus ātrumus, mēģiniet restartēt savu tālruni un dalieties ar jebkādiem ātruma rezultātiem ar mums, īpaši salīdzinājumos ar un bez :LTE režīma aktivizēšanas.',
  ],
  [
    'question' => 'Kā es varu skatīt savus bundles?',
    'answer' => 'Jūs varat sekot līdzi saviem atlikušajiem datiem un ierobežojumiem mūsu klientu panelī.',
  ],
  [
    'question' => 'Kas padara :organisationName atšķirīgu no citām eSIM pakalpojumu sniedzējām?',
    'answer' => ':organisationName izceļas, sadarbojoties ar vietējiem operatoriem vairāk nekā 200 valstīs, piedāvājot izmaksu ziņā efektīvus datu paketus bez starpniekiem. Mēs nodrošinām stabilu pārklājumu un vienkāršu aktivizācijas procesu. :organisationName ir ideāls ceļotājiem, kuri meklē mobilā interneta risinājumus.',
  ],
];
