<?php

//This file is automatically generated. Do not modify.

return [
  'title' => 'Palieciet savienoti tiešsaistē :countryName',
  'subtitle' => 'Ceļojot uz :countryName? Palieciet savienoti ar mūsu eSIM, nodrošinot, ka jums ir tūlītēja interneta piekļuve ierodoties.',
  'features' => [
    [
      'title' => 'Uzticami un ātri tiešsaistē :countryName',
      'subtitle' => ':countryName ir skaista galamērķis, kas lepojas ar dzīvīgām mūsdienīgām pilsētām un elpu aizraujošām dabas ainavām. Uzlabojiet savu ceļojuma pieredzi ar mūsu eSIM, nodrošinot, ka jūs nekavējoties paliksiet savienots ierodoties.
        Atvadieties no neērtībām, meklējot vietējo SIM karti vai saskaroties ar dārgu datu romingu. Ar mūsu eSIM jūs baudīsiet nevainojamu piekļuvi 4G/5G tīkliem no valsts labākajiem pakalpojumu sniedzējiem, saglabājot savienojumu, kurp vien jūsu ceļojums jūs aizvedīs.',
      'image' => 'images/features/feature1.jpg',
    ],
    [
      'title' => 'Palieciet saistīti ar mīļajiem',
      'subtitle' => 'Mūsu eSIM ir izstrādāta, lai nodrošinātu nevainojamu piekļuvi internetam, ļaujot jums palikt savienotam visām jūsu tiešsaistes aktivitātēm bez nepieciešamības pēc jauna telefona numura. Vieglā veidā izveidojiet hotspot, lai dalītos ar savu savienojumu ar citiem ceļotājiem vai ģimenes locekļiem, funkcija, ko bieži bloķē citi pakalpojumu sniedzēji, bet pilnībā atbalsta mēs. Izbaudiet tūlītējas savienojamības ērtības eSIM saderīgās ierīcēs, nodrošinot, ka jūs un jūsu mīļie paliekat tiešsaistē jebkurā laikā, jebkur. Lūdzu, apstipriniet, vai jūsu ierīce atbalsta eSIM, lai nodrošinātu, ka esat gatavs mūsu interneta piedāvājumiem. Lūdzu, ņemiet vērā, ka zvani un īsziņas mūsu eSIM nav atbalstīti.',
      'image' => 'images/features/feature2.jpg',
    ],
  ],
];
