<?php

//This file is automatically generated. Do not modify.

return [
  'all_rights_reserved' => 'Visas tiesības aizsargātas.',
  'foreign_currencies_for_reference_only' => 'Ārvalstu valūtas ir tikai atsaucei. Rēķināšana notiks eiro.',
];
