<?php

//This file is automatically generated. Do not modify.

return [
  'from' => ':price/GB',
  'title' => 'Savienojieties globāli ar mūsu eSIM.',
  'subtitle' => 'Izpētiet mūsu eSIM paketes un palieciet savienoti, kur vien esat!',
  'search_destination' => 'Atrodiet galamērķi',
  'show_all_esim' => 'Rādīt visus eSIM plānus',
  'how_it_works' => 'Kā tas darbojas?',
  'steps' => [
    [
      'title' => '1. solis',
      'description' => 'Pārbaudiet, vai jūsu ierīce ir saderīga ar eSIM mūsu saderības sarakstā.',
    ],
    [
      'title' => '2. solis',
      'description' => 'Izvēlieties savu galamērķi un vēlamo eSIM datu plānu',
    ],
    [
      'title' => '3. solis',
      'description' => 'Iegādājieties eSIM karti, kas vislabāk atbilst jūsu vajadzībām',
    ],
    [
      'title' => '4. solis',
      'description' => 'Jūsu eSIM tiks piegādāta automātiski. Sekojiet norādījumiem savā e-pastā.',
    ],
    [
      'title' => '5. solis',
      'description' => 'Instalējiet savu eSIM profilu un izbaudiet ceļojumu!',
    ],
  ],
  'supported_networks' => 'Atbalstītie tīkla pakalpojumu sniedzēji',
  'supported_networks_description' => 'Mēs cieši sadarbojamies ar uzticamiem tirgus līderiem savienojamības, mediju un tehnoloģiju zīmolu jomā visā pasaulē.',
  'and_many_more' => 'un daudz vairāk...',
  'user_reviews' => 'Ko saka mūsu apmierinātie lietotāji',
  'user_reviews_subtitle' => 'Uzziniet, kāpēc ceļotāji visā pasaulē paļaujas uz mūsu eSIM, lai nodrošinātu nevainojamu un uzticamu savienojamību ceļojuma laikā.',
  'faq' => 'Bieži uzdotie jautājumi',
  'popular_destinations' => 'Populāras galamērķi',
  'popular_destinations_description' => 'Atklājiet mūsu populārākās eSIM galamērķus un palieciet savienoti, neatkarīgi no tā, kur dodaties!',
  'see_all_destinations' => 'Skatīt visas galamērķus',
];
