<?php

//This file is automatically generated. Do not modify.

return [
  'home' => 'Mājas',
  'supported-devices' => 'Atbalstītās ierīces',
  'destinations' => 'Visas galamērķi',
  'about' => 'Par',
  'contact' => 'Sazinieties',
  'portal_link' => 'Mans Portal',
];
