<?php

//This file is automatically generated. Do not modify.

return [
  'days' => 'dienas',
  'buy_plan' => 'Pērc tagad!',
  'perks' => [
    'instant' => 'Tiešā piegāde',
    'advanced_self_service' => 'Uzlabota pašapkalpošanās portāls',
    '247_support' => '24/7 tiešsaistes čata atbalsts',
    'prepaid' => 'Iepriekš apmaksāts, bez nosacījumiem',
    'no_roaming' => 'Nav viesabonēšanas maksas',
  ],
  'local_for' => 'Vietējie eSIMs :countryName',
  'not_available_yet' => 'Pašlaik mēs nepiedāvājam eSIM kartes šai valstij.',
  'not_available_yet_contact_us' => 'Mēs smagi strādājam, lai paplašinātu mūsu globālo pārklājumu. Ja jūs interesē eSIMs šai valstij, lūdzu, sazinieties ar mums.',
  'top_plan' => 'Vispopulārākais',
  'all_features' => 'Visas funkcijas',
  'features' => [
    'feature_one' => 'Iespējamā karstā vieta',
    'feature_two' => 'Pārklājums visās valsts tīklos',
    'feature_three' => 'Vienkārša jaunināšana jūsu personīgajā portālā',
  ],
  'buy_now' => 'Pērc tagad',
  'starting_from' => 'Sākot no',
  'choose_destination' => 'Atrodiet galamērķi',
  'how_esim_works' => [
    'title' => 'Kā darbojas eSIM',
    'subtitle' => 'Sākt lietot eSIM ir viegli! Izpildiet šos vienkāršos soļus, lai paliktu savienots.',
    'steps' => [
      [
        'title' => 'Pērciet savu eSIM',
        'description' => 'Izvēlieties savu galamērķi, izvēlieties komplektu, kas atbilst jūsu datu vajadzībām, un pabeidziet savu pirkumu.',
        'image' => '/images/howesimworks/1.png',
      ],
      [
        'title' => 'Saņemiet savu eSIM',
        'description' => 'Saņemiet savu eSIM QR kodu tieši savā e-pastā. Gatavs lietošanai nekavējoties.',
        'image' => '/images/howesimworks/2.png',
      ],
      [
        'title' => 'Aktivizēt un savienot',
        'description' => 'Skenējiet QR kodu, aktivizējiet savu eSIM un izbaudiet ātru, uzticamu datus, kurp vien ceļojat.',
        'image' => '/images/howesimworks/3.png',
      ],
    ],
  ],
  'sub_description' => 'Izvēlieties savu komplektu zemāk un izbaudiet nevainojamu savienojamību :countryName labākajos tīklos par labāko cenu.',
];
