<?php

//This file is automatically generated. Do not modify.

return [
  'title' => 'eSIM pakalpojums - Priekšapmaksas virtuālās SIM kartes ceļotājiem - :site_name',
  'description' => 'eSIM-pakalpojums ⏩ Priekšapmaksas digitālās SIM kartes tūrisma un biznesa vajadzībām ⏩ Standarta un neierobežoti, vietējie un globālie mobilie datu plāni ⏩ Nav līgumu ✅ Nav slēptu roaming maksu un atlīdzību ✅ - :site_name',
  'keywords' => 'eSIM, eSIM-pakalpojums, eSIM-kartes, eSIM-dati, eSIM-datu plāns, eSIM-datu plāni, eSIM-datu plāns ceļotājiem, eSIM-datu plāns tūristiem, eSIM-datu plāns uzņēmumiem, eSIM-datu plāns ceļojumiem, eSIM-datu plāns Eiropai, eSIM-datu plāns ASV, eSIM-datu plāns Āzijai, eSIM-datu plāns Āfrikai, eSIM-datu plāns Austrālijai, eSIM-datu plāns Dienvidamerikai, eSIM-datu plāns Ziemeļamerikai, eSIM-datu plāns Tuvajiem Austrumiem, eSIM-datu plāns Krievijai, eSIM-datu plāns Ķīnai, eSIM-datu plāns Indijai, eSIM-datu plāns Japānai',
  'routes' => [
    'home' => [
      'title' => 'eSIM pakalpojums - Priekšapmaksas virtuālās SIM kartes ceļotājiem - :site_name',
      'description' => 'eSIM-pakalpojums ⏩ Priekšapmaksas digitālās SIM kartes tūrisma un biznesa vajadzībām ⏩ Standarta un neierobežoti, vietējie un globālie mobilie datu plāni ⏩ Nav līgumu ✅ Nav slēptu rominga maksu un kompensāciju ✅ - :site_name',
    ],
    'about' => [
      'title' => 'Par mums - :site_name',
      'description' => 'Par mums ⏩ Priekšapmaksas digitālās SIM kartes tūrisma un biznesa vajadzībām ⏩ Standarta un neierobežoti, vietējie un globālie mobilie datu plāni ⏩ Nav līgumu ✅ Nav slēptu roaming maksu un kompensāciju ✅ - :site_name',
    ],
    'supported-devices' => [
      'title' => 'Atbalstītās ierīces - :site_name',
      'description' => 'Atbalstītās ierīces ⏩ Priekšapmaksas digitālās SIM kartes tūrisma un biznesa vajadzībām ⏩ Standarta un neierobežoti, vietējie un globālie mobilie datu plāni ⏩ Nav līgumu ✅ Nav slēptu rominga izmaksu un atlīdzību ✅ - :site_name',
    ],
    'esim-bundle-per-country' => [
      'title' => 'eSIM :countryName - :site_name',
      'description' => 'eSIM :countryName ⏩ Priekšapmaksas digitālās SIM kartes tūrisma un biznesa vajadzībām ⏩ Standarta un neierobežoti, vietējie un globālie mobilie datu plāni ⏩ Nav līgumu ✅ Nav slēptu roaminģa izmaksu un atlīdzību ✅ - :site_name',
    ],
  ],
];
