<?php

//This file is automatically generated. Do not modify.

return [
  'title' => 'eSIM pakalpojums - iepriekš apmaksātas virtuālās SIM kartes ceļotājiem - :site_name',
  'description' => 'eSIM pakalpojums ⏩ Priekšapmaksas digitālās SIM kartes tūrisma un biznesa vajadzībām ⏩ Standarta un neierobežoti, vietējie un globālie mobilā tālruņa datu plāni ⏩ Nav līgumu ✅ Nav slēptu ceļojumu maksājumu un maksu ✅ - :site_name',
  'keywords' => 'eSIM, eSIM pakalpojums, eSIM karte, eSIM dati, eSIM datu plāns, eSIM datu plāni, eSIM datu plāns ceļotājiem, eSIM datu plāns tūristiem, eSIM datu plāns uzņēmumiem, eSIM datu plāns ceļojumiem, eSIM datu plāns Eiropai, eSIM datu plāns ASV, eSIM datu plāns Āzijai, eSIM datu plāns Āfrikai, eSIM datu plāns Austrālijai, eSIM datu plāns Dienvidamerikai, eSIM datu plāns Ziemeļamerikai, eSIM datu plāns Tuvajiem Austrumiem, eSIM datu plāns Krievijai, eSIM datu plāns Ķīnai, eSIM datu plāns Indijai, eSIM datu plāns Japānai',
  'routes' => [
    'home' => [
      'title' => 'eSIM pakalpojums - priekšapmaksas virtuālās SIM kartes ceļotājiem - :site_name',
      'description' => 'eSIM pakalpojums ⏩ Priekšapmaksas digitālās SIM kartes tūrisma un biznesa vajadzībām ⏩ Standarta un neierobežoti, vietējie un globālie mobilā tālruņa datu plāni ⏩ Nav līgumu ✅ Nav slēptu rominga maksājumu un maksu ✅ - :site_name',
    ],
    'about' => [
      'title' => 'Par mums - :site_name',
      'description' => 'Par mums ⏩ Priekšapmaksas digitālās SIM kartes tūrisma un biznesa vajadzībām ⏩ Standarta un neierobežoti, vietējie un globālie mobilo telefonu datu plāni ⏩ Nav līgumu ✅ Nav slēptu ceļojumu maksas un maksu ✅ - :site_name',
    ],
    'supported-devices' => [
      'title' => 'Atbalstītās ierīces - :site_name',
      'description' => 'Atbalstītās ierīces ⏩ Priekšapmaksas digitālās SIM kartes tūrisma un biznesa vajadzībām ⏩ Standarta un neierobežoti, vietējie un globālie mobilā tālruņa datu plāni ⏩ Nav līgumu ✅ Nav slēptu rominga maksu un maksājumu ✅ - :site_name',
    ],
    'esim-bundle-per-country' => [
      'title' => 'Lēti vietējie eSIM piedāvājumi :countryName - :site_name',
      'description' => 'Lēti vietējie eSIM piedāvājumi :countryName ⏩ Priekšapmaksas digitālās SIM kartes tūristiem un uzņēmumiem ⏩ Standarta un neierobežoti, vietējie un globālie mobilā tālruņa datu plāni ⏩ Nav līgumu ✅ Nav slēptu ceļojumu maksu un nodevu ✅ - :site_name',
    ],
  ],
];
