<?php

//This file is automatically generated. Do not modify.

return [
  'Rens' => [
    'role' => 'Līdzīpašnieks',
    'image' => '/images/team/rens.png',
  ],
  'Luuk' => [
    'role' => 'Līdzīpašnieks',
    'image' => '/images/team/luuk.png',
  ],
  'Fleur' => [
    'role' => 'Klientu atbalsts',
    'image' => '/images/team/fleur.png',
  ],
  'Patrick' => [
    'role' => 'Izstrādātājs',
    'image' => '/images/team/patrick.png',
  ],
];
