<?php

//This file is automatically generated. Do not modify.

return [
  'title' => 'Все наши направления',
  'subtitle' => 'Куда бы вы ни поехали, мы обеспечим вас eSIM для каждой точки назначения. Выберите ваше направление ниже, чтобы начать.',
];
