<?php

//This file is automatically generated. Do not modify.

return [
  'faq' => 'Часто задаваемые вопросы',
  'subtitle' => 'У вас есть вопросы? У нас есть ответы. Найдите все, что вам нужно знать о наших eSIM.',
];
