<?php

//This file is automatically generated. Do not modify.

return [
  'all_rights_reserved' => 'Все права защищены.',
  'foreign_currencies_for_reference_only' => 'Иностранные валюты приведены только для справки. Выставление счетов будет в евро.',
];
