<?php

//This file is automatically generated. Do not modify.

return [
  'home' => 'Дом',
  'supported-devices' => 'Поддерживаемые устройства',
  'destinations' => 'Все направления',
  'about' => 'О нас',
  'contact' => 'Контакт',
  'portal_link' => 'Мой Portal',
];
