<?php

//This file is automatically generated. Do not modify.

return [
  'title' => 'O nas',
  'subtitle' => 'Nawiguj się po świecie bez granic z nami. Jesteśmy twoim ostatecznym partnerem, który utrzymuje cię w kontakcie, gdziekolwiek twoja pasja cię prowadzi.',
  'our_team' => 'Nasz Zespół',
  'our_team_subtitle' => 'Wierzymy w umożliwienie podróżnym korzystania z niezawodnej i przystępnej cenowo globalnej łączności danych. Nasz zróżnicowany zespół jest zjednoczony w tworzeniu bardziej połączonego i dostępnego świata dla każdego w ruchu.',
  'why_us' => 'Dlaczego wybrać nas',
  'why_us_subtitle' => 'Jesteśmy dumni z naszej niezawodnej obsługi, konkurencyjnych cen i podejścia zorientowanego na klienta. Twoje zadowolenie jest dla nas najwyższym priorytetem.',
  'why_us_reasons' => [
    [
      'title' => 'Elastyczne plany zaprojektowane z myślą o Twoich potrzebach podróżniczych',
      'subtitle' => 'Wybierz spośród różnych przystępnych pakietów dostosowanych do różnych krajów i regionów. Dajemy Ci elastyczność w wyborze idealnego planu danych, dzięki czemu płacisz tylko za to, czego potrzebujesz, bez ukrytych kosztów.',
      'image' => '/images/whyus/nlo2.png',
    ],
    [
      'title' => 'Bezpośrednia aktywacja, nie są potrzebne fizyczne karty SIM',
      'subtitle' => 'Czasy wymiany fizycznych kart SIM minęły. Z nami, twoja eSIM jest dostarczana bezpośrednio na email i może być aktywowana w ciągu kilku minut. Wystarczy zeskanować kod QR i jesteś gotowy do połączenia.',
      'image' => '/images/whyus/nlo3.png',
    ],
  ],
  'contact' => 'Skontaktuj się z nami',
  'contact_subtitle' => 'Jesteśmy tutaj, aby Ci pomóc. Jeśli masz jakiekolwiek pytania lub potrzebujesz pomocy, skontaktuj się z nami.',
];
