<?php

//This file is automatically generated. Do not modify.

return [
  'title' => 'Wszystkie nasze destynacje',
  'subtitle' => 'Gdziekolwiek się udasz, mamy dla Ciebie eSIMy na każdą destynację. Wybierz swoją destynację poniżej, aby rozpocząć.',
];
