<?php

//This file is automatically generated. Do not modify.

return [
  'title' => 'Obsługiwane urządzenia',
  'subtitle' => 'Obsługujemy szeroki zakres urządzeń. Sprawdź, czy Twoje urządzenie znajduje się na poniższej liście. Urządzenia są uporządkowane według producenta.',
  'models_below' => 'Obsługiwane modele są wymienione poniżej.',
];
