<?php

//This file is automatically generated. Do not modify.

return [
  [
    'question' => 'Czym jest eSIM i jak mogę użyć :organisationName?',
    'answer' => 'eSIM, czyli wbudowana karta SIM, to cyfrowa karta SIM, która pozwala użytkownikom aktywować i zarządzać wieloma planami mobilnymi na jednym urządzeniu bez potrzeby posiadania fizycznej karty SIM. Dzięki eSIM możesz łatwo przełączać się między dostawcami mobilnymi i cieszyć się takimi funkcjami, jak dodawanie dodatkowej linii na podróże międzynarodowe lub utrzymywanie oddzielnych planów danych do użytku osobistego i biznesowego.',
  ],
  [
    'question' => 'Jak aktywować internet mobilny eSIM z :organisationName?',
    'answer' => 'Aby połączyć się z internetem za pomocą eSIM :organisationName, wykonaj następujące kroki: 1. Przejdź do ustawień danych mobilnych. 2. Włącz linię mobilną :organisationName. 3. Aktywuj roaming danych. 4. Wybierz linię internetową :organisationName jako swoje główne połączenie. *Unikaj wybierania opcji "Usuń plan danych", ponieważ spowoduje to usunięcie profilu eSIM.*',
  ],
  [
    'question' => 'Czy mogę wykonywać połączenia telefoniczne lub wysyłać wiadomości tekstowe?',
    'answer' => ':organisationName\'s plany eSIM na przedpłatę są zaprojektowane do użytku tylko z danymi i nie zawierają numeru telefonu komórkowego do tradycyjnych połączeń lub wiadomości SMS. Zalecamy korzystanie z aplikacji VoIP, takich jak Facebook Messenger, WhatsApp, Viber, Telegram lub Skype, aby pozostać w kontakcie na całym świecie bez potrzeby posiadania standardowej międzynarodowej karty SIM.',
  ],
  [
    'question' => 'Czy kartę eSIM można ponownie wykorzystać?',
    'answer' => 'Każdy kod QR dla eSIM jest unikalny i może być używany tylko na jednym urządzeniu. Po usunięciu profilu eSIM kod QR nie może być ponownie użyty na tym samym lub innym urządzeniu, co zapewnia bezpieczeństwo i ekskluzywność.',
  ],
  [
    'question' => 'Kiedy zaczyna się okres ważności planów danych mobilnych eSIM?',
    'answer' => 'Czas trwania Twojego planu danych eSIM zaczyna się natychmiast po pierwszym połączeniu Twojego urządzenia z siecią komórkową za pomocą eSIM.',
  ],
  [
    'question' => 'Czy mogę przedłużyć datę wygaśnięcia mojego obecnego planu danych mobilnych eSIM?',
    'answer' => 'Oczywiście! Otrzymasz wiele powiadomień push, gdy będziesz prawie na wyczerpaniu swojego pakietu. Możesz łatwo doładować przez swój osobisty portal.',
  ],
  [
    'question' => 'Czy mogę używać tetheringu lub Personal Hotspot z :organisationName?',
    'answer' => 'Tak, możesz udostępnić swoje dane mobilne innym urządzeniom za pomocą swojej :organisationName-eSIM. Po prostu zainstaluj :organisationName-eSIM na swoim urządzeniu i włącz Personal Hotspot w ustawieniach. Ta funkcja jest dostępna bez dodatkowych opłat, ale pamiętaj, że korzystanie z danych tethered będzie odliczane od twojego planu.',
  ],
  [
    'question' => 'Czy mogę zachować numery mojej osobistej aplikacji do wiadomości podczas korzystania z eSIM od :organisationName?',
    'answer' => 'Tak, możesz nadal korzystać ze swojego WhatsApp, Snapchat, Telegram i innych aplikacji do wiadomości obok swojej :organisationName prepaid eSIM bez żadnych problemów.',
  ],
  [
    'question' => 'Jak mogę przenieść mój eSIM na nowy telefon?',
    'answer' => 'Zanim dokonasz przeniesienia, upewnij się, że twój nowy smartfon obsługuje technologię eSIM. Skontaktuj się z naszym zespołem wsparcia, aby utworzyć nowy profil eSIM, a następnie zaloguj się na swoje konto :organisationName na nowym urządzeniu, aby zainstalować kod QR. Upewnij się, że potwierdzasz, że używasz innego urządzenia w celu dokładnych aktualizacji ustawień.',
  ],
  [
    'question' => 'Czy istnieją umowy podobne do tych oferowanych przez tradycyjnych dostawców eSIM?',
    'answer' => 'Nie, :organisationName nie wymaga od Ciebie podpisywania umów. Możesz aktywować lub dezaktywować swoją kartę eSIM według własnego uznania, w zależności od swoich planów. Chętnie Ci pomożemy.',
  ],
  [
    'question' => 'Jaka jest różnica między eSIM :organisationName a standardowymi planami roamingowymi od fizycznych operatorów komórkowych?',
    'answer' => ':organisationName oferuje plany danych bez umowy, bez ukrytych kosztów roamingowych. Płacisz tylko za dane, które wykorzystujesz, w zależności od wybranego pakietu, co często czyni to bardziej ekonomiczną opcją.',
  ],
  [
    'question' => 'Dlaczego moja prędkość danych jest wolna?',
    'answer' => 'Prędkość danych może być wpływana przez różne czynniki, w tym typ smartfona, który posiadasz, technologię sieciową, strony internetowe lub aplikacje, z których korzystasz, oraz porę dnia. Ponadto prędkości mogą się różnić w zależności od infrastruktury sieciowej w danym kraju. Jeśli doświadczasz wolnych prędkości, spróbuj zrestartować swój telefon i podziel się z nami wynikami prędkości, szczególnie porównaniami z włączonym i wyłączonym LTE.',
  ],
  [
    'question' => 'Jak mogę zobaczyć moje pakiety?',
    'answer' => 'Możesz śledzić swoje pozostałe dane i limity w naszym panelu klienta.',
  ],
  [
    'question' => 'Co sprawia, że :organisationName różni się od innych usług eSIM?',
    'answer' => ':organisationName wyróżnia się współpracą z lokalnymi operatorami w ponad 200 krajach, oferując opłacalne pakiety danych bez pośredników. Zapewniamy solidny zasięg i prosty proces aktywacji. :organisationName jest idealne dla podróżnych szukających rozwiązań mobilnego internetu.',
  ],
];
