<?php

//This file is automatically generated. Do not modify.

return [
  'all_rights_reserved' => 'Wszelkie prawa zastrzeżone.',
  'foreign_currencies_for_reference_only' => 'Waluty obce są tylko do celów informacyjnych. Fakturowanie będzie w Euro.',
];
