<?php

//This file is automatically generated. Do not modify.

return [
  'from' => ':price/GB',
  'title' => 'Połącz się globalnie z naszymi eSIM-ami',
  'subtitle' => 'Odkryj nasze pakiety eSIM i bądź w kontakcie, gdziekolwiek jesteś!',
  'search_destination' => 'Znajdź miejsce docelowe',
  'show_all_esim' => 'Pokaż wszystkie plany eSIM',
  'how_it_works' => 'Jak to działa?',
  'steps' => [
    [
      'title' => 'Krok 1',
      'description' => 'Sprawdź, czy Twoje urządzenie jest zgodne z eSIM w naszej liście zgodności.',
    ],
    [
      'title' => 'Krok 2',
      'description' => 'Wybierz swoje miejsce docelowe i pożądany plan danych eSIM',
    ],
    [
      'title' => 'Krok 3',
      'description' => 'Kup kartę eSIM, która najlepiej odpowiada Twoim potrzebom.',
    ],
    [
      'title' => 'Krok 4',
      'description' => 'Twoja eSIM zostanie dostarczona automatycznie. Postępuj zgodnie z instrukcjami w swoim e-mailu.',
    ],
    [
      'title' => 'Krok 5',
      'description' => 'Zainstaluj swój profil eSIM i ciesz się podróżą!',
    ],
  ],
  'supported_networks' => 'Obsługiwane dostawcy sieci',
  'supported_networks_description' => 'Pracujemy blisko z zaufanymi, wiodącymi na rynku markami w dziedzinie łączności, mediów i technologii na całym świecie.',
  'and_many_more' => 'i wiele więcej...',
  'user_reviews' => 'Co mówią nasi zadowoleni użytkownicy',
  'user_reviews_subtitle' => 'Zobacz, dlaczego podróżnicy na całym świecie polegają na naszej eSIM, aby uzyskać bezproblemowe, niezawodne połączenie w podróży.',
  'faq' => 'Najczęściej zadawane pytania',
  'popular_destinations' => 'Popularne miejsca docelowe',
  'popular_destinations_description' => 'Odkryj nasze najpopularniejsze destynacje eSIM i bądź w kontakcie, niezależnie od tego, dokąd się wybierasz!',
  'see_all_destinations' => 'Zobacz wszystkie miejsca docelowe',
];
