<?php

//This file is automatically generated. Do not modify.

return [
  'home' => 'Strona główna',
  'supported-devices' => 'Obsługiwane urządzenia',
  'destinations' => 'Wszystkie miejsca docelowe',
  'about' => 'O nas',
  'contact' => 'Kontakt',
  'portal_link' => 'Mój Portal',
];
