<?php

//This file is automatically generated. Do not modify.

return [
  'days' => 'dni',
  'buy_plan' => 'Kup teraz!',
  'perks' => [
    'instant' => 'Bezpośrednia dostawa',
    'advanced_self_service' => 'Zaawansowany portal samoobsługowy',
    '247_support' => '24/7 wsparcie czatu na żywo',
    'prepaid' => 'Przedpłacone, bez żadnych warunków',
    'no_roaming' => 'Brak opłat za roaming',
  ],
  'local_for' => 'Lokalne eSIM-y dla :countryName',
  'not_available_yet' => 'Obecnie nie oferujemy eSIM-ów dla tego kraju.',
  'not_available_yet_contact_us' => 'Pracujemy ciężko, aby rozszerzyć naszą globalną obecność. Jeśli jesteś zainteresowany eSIMami w tym kraju w międzyczasie, skontaktuj się z nami.',
  'top_plan' => 'Najbardziej popularny',
  'all_features' => 'Wszystkie funkcje',
  'features' => [
    'feature_one' => 'Możliwy hotspot',
    'feature_two' => 'Zasięg we wszystkich krajowych sieciach',
    'feature_three' => 'Prosta aktualizacja w twoim osobistym portalu',
  ],
  'buy_now' => 'Kup teraz',
  'starting_from' => 'Zaczynając od',
  'choose_destination' => 'Znajdź miejsce docelowe',
  'how_esim_works' => [
    'title' => 'Jak działa eSIM',
    'subtitle' => 'Rozpoczęcie korzystania z eSIM jest proste! Postępuj zgodnie z tymi prostymi krokami, aby pozostać w kontakcie.',
    'steps' => [
      [
        'title' => 'Kup swoją eSIM',
        'description' => 'Wybierz swoje miejsce docelowe, wybierz pakiet, który spełnia Twoje potrzeby danych, i sfinalizuj zakupy.',
        'image' => '/images/howesimworks/1.png',
      ],
      [
        'title' => 'Odbierz swoją eSIM',
        'description' => 'Odbierz swój kod QR eSIM bezpośrednio w swoim e-mailu. Gotowy do natychmiastowego użycia.',
        'image' => '/images/howesimworks/2.png',
      ],
      [
        'title' => 'Aktywuj i Połącz',
        'description' => 'Skanuj kod QR, aktywuj swoją eSIM i ciesz się szybkim, niezawodnym dostępem do danych, gdziekolwiek podróżujesz.',
        'image' => '/images/howesimworks/3.png',
      ],
    ],
  ],
  'sub_description' => 'Wybierz swój pakiet poniżej i ciesz się bezproblemową łącznością w :countryName na najlepszych sieciach w najlepszej cenie.',
];
