<?php

//This file is automatically generated. Do not modify.

return [
  'title' => 'eSIM-service - Prepaid wirtualne karty SIM dla podróżnych - :site_name',
  'description' => 'eSIM-service ⏩ Prepaidowe cyfrowe karty SIM dla turystyki i biznesu ⏩ Standardowe i nielimitowane, lokalne i globalne plany danych mobilnych ⏩ Brak umów ✅ Brak ukrytych opłat i zwrotów za roaming ✅ - :site_name',
  'keywords' => 'eSIM, eSIM-usługa, eSIM-karta, eSIM-dane, eSIM-plan danych, eSIM-plany danych, eSIM-plan danych dla podróżnych, eSIM-plan danych dla turystów, eSIM-plan danych dla firm, eSIM-plan danych na podróże, eSIM-plan danych dla Europy, eSIM-plan danych dla USA, eSIM-plan danych dla Azji, eSIM-plan danych dla Afryki, eSIM-plan danych dla Australii, eSIM-plan danych dla Ameryki Południowej, eSIM-plan danych dla Ameryki Północnej, eSIM-plan danych dla Bliskiego Wschodu, eSIM-plan danych dla Rosji, eSIM-plan danych dla Chin, eSIM-plan danych dla Indii, eSIM-plan danych dla Japonii',
  'routes' => [
    'home' => [
      'title' => 'eSIM-service - Prepaid wirtualne karty SIM dla podróżnych - :site_name',
      'description' => 'eSIM-service ⏩ Prepaidowe cyfrowe karty SIM dla turystyki i biznesu ⏩ Standardowe i nielimitowane, lokalne i globalne plany danych mobilnych ⏩ Brak umów ✅ Brak ukrytych kosztów roamingowych i opłat ✅ - :site_name',
    ],
    'about' => [
      'title' => 'O nas - :site_name',
      'description' => 'O nas ⏩ Prepaidowe cyfrowe karty SIM dla turystyki i biznesu ⏩ Standardowe i nielimitowane, lokalne i globalne plany danych mobilnych ⏩ Brak umów ✅ Brak ukrytych kosztów roamingowych i opłat ✅ - :site_name',
    ],
    'supported-devices' => [
      'title' => 'Obsługiwane urządzenia - :site_name',
      'description' => 'Obsługiwane urządzenia ⏩ Prepaidowe karty SIM do turystyki i biznesu ⏩ Standardowe i nielimitowane, lokalne i globalne plany danych mobilnych ⏩ Brak umów ✅ Brak ukrytych kosztów roamingowych i opłat ✅ - :site_name',
    ],
    'esim-bundle-per-country' => [
      'title' => 'eSIM :countryName - :site_name',
      'description' => 'eSIM :countryName ⏩ Prepaidowe cyfrowe karty SIM dla turystyki i biznesu ⏩ Standardowe i nielimitowane, lokalne i globalne plany danych mobilnych ⏩ Brak umów ✅ Brak ukrytych opłat i zwrotów za roaming ✅ - :site_name',
    ],
  ],
];
