<?php

//This file is automatically generated. Do not modify.

return [
  'title' => 'eSIM Usługa - Prepaid Wirtualne Karty SIM dla Podróżnych - :site_name',
  'description' => 'usługa eSIM ⏩ Prepaidowe cyfrowe karty SIM dla turystyki i biznesu ⏩ Standardowe i nielimitowane, lokalne i globalne plany danych komórkowych ⏩ Brak umów ✅ Brak ukrytych opłat za roaming i opłat ✅ - :site_name',
  'keywords' => 'eSIM, usługa eSIM, karta eSIM, dane eSIM, plan danych eSIM, plany danych eSIM, plan danych eSIM dla podróżnych, plan danych eSIM dla turystów, plan danych eSIM dla biznesu, plan danych eSIM na podróż, plan danych eSIM dla Europy, plan danych eSIM dla USA, plan danych eSIM dla Azji, plan danych eSIM dla Afryki, plan danych eSIM dla Australii, plan danych eSIM dla Ameryki Południowej, plan danych eSIM dla Ameryki Północnej, plan danych eSIM dla Bliskiego Wschodu, plan danych eSIM dla Rosji, plan danych eSIM dla Chin, plan danych eSIM dla Indii, plan danych eSIM dla Japonii',
  'routes' => [
    'home' => [
      'title' => 'eSIM Usługa - Prepaid Wirtualne Karty SIM dla Podróżnych - :site_name',
      'description' => 'usługa eSIM ⏩ Prepaidowe cyfrowe karty SIM dla turystyki i biznesu ⏩ Plany danych komórkowych lokalnych i globalnych, standardowe i nielimitowane ⏩ Brak umów ✅ Brak ukrytych opłat i kosztów roamingowych ✅ - :site_name',
    ],
    'about' => [
      'title' => 'O nas - :site_name',
      'description' => 'O nas ⏩ Przedpłacone cyfrowe karty SIM dla turystyki i biznesu ⏩ Standardowe i nielimitowane, lokalne i globalne plany danych komórkowych ⏩ Brak umów ✅ Brak ukrytych opłat i kosztów roamingowych ✅ - :site_name',
    ],
    'supported-devices' => [
      'title' => 'Obsługiwane urządzenia - :site_name',
      'description' => 'Obsługiwane urządzenia ⏩ Przedpłacone cyfrowe karty SIM dla turystyki i biznesu ⏩ Standardowe i nielimitowane, lokalne i globalne plany danych komórkowych ⏩ Brak umów ✅ Brak ukrytych opłat i kosztów roamingowych ✅ - :site_name',
    ],
    'esim-bundle-per-country' => [
      'title' => 'Tanie lokalne oferty eSIM dla :countryName - :site_name',
      'description' => 'Tanie lokalne oferty eSIM dla :countryName ⏩ Prepaidowe karty SIM cyfrowe dla turystyki i biznesu ⏩ Standardowe i nielimitowane, lokalne i globalne plany danych dla telefonów komórkowych ⏩ Brak umów ✅ Brak ukrytych opłat i kosztów roamingowych ✅ - :site_name',
    ],
  ],
];
