<?php

//This file is automatically generated. Do not modify.

return [
  'title' => 'About us',
  'subtitle' => 'Navigate the world without borders with us. We are your ultimate partner that keeps you connected wherever your passion drives you.',
  'our_team' => 'Our Team',
  'our_team_subtitle' => 'We believe in empowering travelers with reliable and affordable global data connectivity. Our diverse team is united in creating a more connected and accessible world for everyone on the go.',
  'why_us' => 'Why choose us',
  'why_us_subtitle' => 'We are proud of our reliable service, competitive prices, and customer-oriented approach. Your satisfaction is our highest priority.',
  'why_us_reasons' => [
    [
      'title' => 'Flexible Plans Designed for Your Travel Needs',
      'subtitle' => 'Choose from a range of affordable bundles tailored to different countries and regions. We give you the flexibility to select the perfect data plan, so you only pay for what you need, with no hidden costs.',
      'image' => '/images/whyus/nlo2.png',
    ],
    [
      'title' => 'Direct activation, no physical SIM cards needed',
      'subtitle' => 'The days of swapping physical SIM cards are over. With us, your eSIM is delivered directly via email and can be activated within minutes. Just scan the QR code and you\'re ready to connect.',
      'image' => '/images/whyus/nlo3.png',
    ],
  ],
  'contact' => 'Contact us',
  'contact_subtitle' => 'We are here to help you. If you have any questions or need assistance, please contact us.',
];
