<?php

//This file is automatically generated. Do not modify.

return [
  'title' => 'All our destinations',
  'subtitle' => 'Wherever you go, we have you covered with eSIMs for every destination. Choose your destination below to get started.',
];
