<?php

//This file is automatically generated. Do not modify.

return [
  'title' => 'Supported devices',
  'subtitle' => 'We support a wide range of devices. Check if your device is on the list below. Devices are organized by manufacturer.',
  'models_below' => 'Supported models are listed below.',
];
