<?php

//This file is automatically generated. Do not modify.

return [
  'faq' => 'FAQ',
  'subtitle' => 'Do you have questions? We have answers. Find everything you need to know about our eSIMs.',
];
