<?php

//This file is automatically generated. Do not modify.

return [
  [
    'question' => 'What is an eSIM and how can I use :organisationName?',
    'answer' => 'An eSIM, or embedded SIM, is a digital SIM card that allows users to activate and manage multiple mobile plans on one device without needing a physical SIM card. With an eSIM, you can easily switch between mobile providers and enjoy features such as adding an extra line for international travel or maintaining separate data plans for personal and business use.',
  ],
  [
    'question' => 'How do I activate eSIM mobile internet with :organisationName?',
    'answer' => 'To connect to the internet using the :organisationName eSIM, follow these steps: 1. Go to your Mobile Data settings. 2. Turn on the :organisationName mobile line. 3. Activate Data roaming. 4. Select the :organisationName Internet line as your primary connection. *Avoid selecting the option "Remove data plan," as this will delete your eSIM profile.*',
  ],
  [
    'question' => 'Can I make phone calls or send text messages?',
    'answer' => ':organisationName\'s prepaid eSIM plans are designed for data-only use and do not include a mobile phone number for traditional calls or SMS messages. We recommend using VoIP applications such as Facebook Messenger, WhatsApp, Viber, Telegram, or Skype to stay connected worldwide without the need for a standard international SIM card.',
  ],
  [
    'question' => 'Can an eSIM card be reused?',
    'answer' => 'Each QR code for an eSIM is unique and can only be used on one device. Once the eSIM profile is deleted, the QR code cannot be reused on the same or another device, ensuring security and exclusivity.',
  ],
  [
    'question' => 'When does the duration of the eSIM mobile data plans start?',
    'answer' => 'The duration of your eSIM data plan begins immediately after your device first connects to a mobile network with the eSIM.',
  ],
  [
    'question' => 'Can I extend the expiration date of my current eSIM mobile data plan?',
    'answer' => 'Sure! You will receive multiple push notifications when you are almost out of your bundle. You can easily top up through your personal portal.',
  ],
  [
    'question' => 'Can I use tethering or Personal Hotspot with :organisationName?',
    'answer' => 'Yes, you can share your mobile data with other devices via your :organisationName-eSIM. Simply install the :organisationName-eSIM on your device and enable Personal Hotspot in your settings. This feature is included at no extra cost, but please note that using tethered data will be deducted from your plan.',
  ],
  [
    'question' => 'Can I keep my personal messaging app numbers while using the eSIM from :organisationName?',
    'answer' => 'Yes, you can continue to use your WhatsApp, Snapchat, Telegram, and other messaging apps alongside your :organisationName prepaid eSIM without any issues.',
  ],
  [
    'question' => 'How can I transfer my eSIM to a new phone?',
    'answer' => 'Before you transfer, make sure your new smartphone supports eSIM technology. Contact our support team to create a new eSIM profile, then log in to your :organisationName account on the new device to install the QR code. Make sure you confirm that you are using a different device for accurate settings updates.',
  ],
  [
    'question' => 'Are there contracts like those of traditional eSIM providers?',
    'answer' => 'No, :organisationName does not require you to sign contracts. You can activate or deactivate your eSIM card as you wish, depending on your plans. We are happy to help you.',
  ],
  [
    'question' => 'What is the difference between :organisationName\'s eSIM and standard roaming data plans from physical mobile operators?',
    'answer' => ':organisationName offers contract-free data plans without hidden roaming costs. You only pay for the data you use, depending on the bundle you choose, making it often a more economical option.',
  ],
  [
    'question' => 'Why is my data speed slow?',
    'answer' => 'Data speed can be affected by various factors, including the type of smartphone you have, network technology, the websites or apps you use, and the time of day. In addition, speeds can vary depending on the network infrastructure of the country. If you are experiencing slow speeds, try restarting your phone and share any speed results with us, especially comparisons with and without :LTE mode enabled.',
  ],
  [
    'question' => 'How can I view my bundles?',
    'answer' => 'You can track your remaining data and limits in our customer panel.',
  ],
  [
    'question' => 'What makes :organisationName different from other eSIM services?',
    'answer' => ':organisationName stands out by collaborating with local operators in over 200 countries, offering cost-effective data packages without intermediaries. We provide robust coverage and a simple activation process. :organisationName is perfect for travelers looking for mobile internet solutions.',
  ],
];
