<?php

//This file is automatically generated. Do not modify.

return [
  'title' => 'Stay connected online in :countryName',
  'subtitle' => 'Traveling to :countryName? Stay connected with our eSIM, ensuring you have instant internet access upon arrival.',
  'features' => [
    [
      'title' => 'Reliably and fast online in :countryName',
      'subtitle' => ':countryName is a beautiful destination, boasting vibrant modern cities and breathtaking natural landscapes. Enhance your travel experience with our eSIM, ensuring you stay connected instantly upon arrival.
        Say goodbye to the hassle of searching for a local SIM card or dealing with costly data roaming. With our eSIM, you\'ll enjoy seamless access to 4G/5G networks from the country\'s top providers, keeping you online wherever your journey takes you.',
      'image' => 'images/features/feature1.jpg',
    ],
    [
      'title' => 'Stay connected with loved ones',
      'subtitle' => 'Our eSIM is designed for seamless internet access, keeping you connected for all your online activities without the need for a new phone number. Easily create a hotspot to share your connection with fellow travelers or family, a feature often blocked by other providers but fully supported by us. Enjoy the convenience of instant connectivity on eSIM-compatible devices, ensuring you and your loved ones stay online anytime, anywhere. Please confirm whether your device supports eSIM to ensure you are ready for our internet offerings. Please note that calling and texting are not supported with our eSIM.',
      'image' => 'images/features/feature2.jpg',
    ],
  ],
];
