<?php

//This file is automatically generated. Do not modify.

return [
  'all_rights_reserved' => 'All rights reserved.',
  'foreign_currencies_for_reference_only' => 'Foreign currencies are for reference only. Billing will be in Euros.',
];
