<?php

//This file is automatically generated. Do not modify.

return [
  'from' => ':price/GB',
  'title' => 'Connect globally with our eSIMs',
  'subtitle' => 'Explore our eSIM packages and stay connected, wherever you are!',
  'search_destination' => 'Find a destination',
  'show_all_esim' => 'Show all eSIM plans',
  'how_it_works' => 'How does it work?',
  'steps' => [
    [
      'title' => 'Step 1',
      'description' => 'Check if your device is eSIM-compatible in our compatibility list.',
    ],
    [
      'title' => 'Step 2',
      'description' => 'Choose your destination and the desired eSIM data plan',
    ],
    [
      'title' => 'Step 3',
      'description' => 'Buy the eSIM card that best suits your needs',
    ],
    [
      'title' => 'Step 4',
      'description' => 'Your eSIM will be delivered automatically. Follow the instructions in your email.',
    ],
    [
      'title' => 'Step 5',
      'description' => 'Install your eSIM profile and enjoy your trip!',
    ],
  ],
  'supported_networks' => 'Supported network providers',
  'supported_networks_description' => 'We work closely with trusted market-leading connectivity, media, and technology brands around the world.',
  'and_many_more' => 'and much more...',
  'user_reviews' => 'What our satisfied users say',
  'user_reviews_subtitle' => 'See why travelers around the world rely on our eSIM for seamless, reliable connectivity on the go.',
  'faq' => 'Frequently Asked Questions',
  'popular_destinations' => 'Popular Destinations',
  'popular_destinations_description' => 'Discover our most popular eSIM destinations and stay connected, no matter where you go!',
  'see_all_destinations' => 'View all destinations',
];
