<?php

//This file is automatically generated. Do not modify.

return [
  'from' => 'From :price per GB',
  'title' => 'eSIM Mobile Data Plans for Tourism and Business',
  'subtitle' => 'Choose a destination and get connected instantly with affordable data plans.',
  'search_destination' => 'Search a destination',
  'popular_destinations' => 'Popular Destinations',
  'show_all_esim' => 'Show all eSIM plans',
  'how_it_works' => 'How does it work?',
  'steps' => [
    [
      'title' => 'Step 1',
      'description' => 'Check whether your device is eSIM-compatible in our compatibility list',
    ],
    [
      'title' => 'Step 2',
      'description' => 'Choose your destination and the desired eSIM data plan',
    ],
    [
      'title' => 'Step 3',
      'description' => 'Buy the eSIM card that is the most suitable for your needs',
    ],
    [
      'title' => 'Step 4',
      'description' => 'Your eSIM is delivered automatically. Follow instructions in your e-mail.',
    ],
    [
      'title' => 'Step 5',
      'description' => 'Install your eSIM profile and enjoy your trip!',
    ],
  ],
  'supported_networks' => 'Supported Networks',
  'and_many_more' => 'and many more...',
  'user_reviews' => 'User Reviews',
  'faq' => 'Frequently Asked Questions',
];
