<?php

//This file is automatically generated. Do not modify.

return [
  'home' => 'Home',
  'supported-devices' => 'Supported devices',
  'destinations' => 'All destinations',
  'about' => 'About',
  'contact' => 'Contact',
  'portal_link' => 'My Portal',
];
