<?php

//This file is automatically generated. Do not modify.

return [
  [
    'stars' => 5,
    'name' => 'Sander',
    'message' => 'eSIM worked perfectly in Albania, fast and reliable.',
  ],
  [
    'stars' => 5,
    'name' => 'Niels',
    'message' => 'With GoSim video calls abroad without any problems.',
  ],
  [
    'stars' => 4,
    'name' => 'Leticia',
    'message' => 'Good price for 10GB in Turkey, valid for 42 days.',
  ],
  [
    'stars' => 5,
    'name' => 'Jacques',
    'message' => 'Super handy, no hassle with multiple SIM cards in the Balkans.',
  ],
  [
    'stars' => 4,
    'name' => 'Marij',
    'message' => 'First time an issue, but customer service quickly resolved it.',
  ],
  [
    'stars' => 5,
    'name' => 'Kaar',
    'message' => 'Easy to install eSIM, worked perfectly during my trip.',
  ],
  [
    'stars' => 4,
    'name' => 'Yvonne',
    'message' => 'Call minutes and internet data were good, but no result.',
  ],
  [
    'stars' => 5,
    'name' => 'Ruud',
    'message' => 'Great, it worked as promised!',
  ],
  [
    'stars' => 5,
    'name' => 'Frank',
    'message' => 'Satisfied with GoSim, good support and internet worked well.',
  ],
  [
    'stars' => 5,
    'name' => 'Janette',
    'message' => 'Excellent service, problem quickly solved with new sim.',
  ],
  [
    'stars' => 4,
    'name' => 'Jeffrey',
    'message' => 'Upon arrival in Malaysia, the eSIM worked immediately.',
  ],
  [
    'stars' => 5,
    'name' => 'Willy',
    'message' => 'Great contact and service, I will use Gosim again!',
  ],
  [
    'stars' => 4,
    'name' => 'Noelle',
    'message' => 'Great experience, useful for backpackers in different countries.',
  ],
  [
    'stars' => 5,
    'name' => 'Emma',
    'message' => 'First time eSIM, worked perfectly for Google Maps!',
  ],
  [
    'stars' => 5,
    'name' => 'Ingrid',
    'message' => 'GoSim helped us to get the sim working in South Africa.',
  ],
  [
    'stars' => 4,
    'name' => 'Leo',
    'message' => 'Canada sim card did not work right away, but good customer service.',
  ],
  [
    'stars' => 5,
    'name' => 'Will',
    'message' => 'Short-term subscription worked fine, had a good connection.',
  ],
  [
    'stars' => 5,
    'name' => 'Wilma',
    'message' => 'Easy to install, good coverage while traveling to Turkey!',
  ],
  [
    'stars' => 5,
    'name' => 'Goedele',
    'message' => 'E-sim download, easily and quickly arranged!',
  ],
  [
    'stars' => 5,
    'name' => 'M. Jansen',
    'message' => 'Simple, good service, next time again!',
  ],
];
