<?php

//This file is automatically generated. Do not modify.

return [
  'days' => 'days',
  'buy_plan' => 'Buy now!',
  'perks' => [
    'instant' => 'Direct delivery',
    'advanced_self_service' => 'Advanced self-service portal',
    '247_support' => '24/7 live chat support',
    'prepaid' => 'Prepaid, no conditions attached',
    'no_roaming' => 'No roaming charges',
  ],
  'local_for' => 'Local eSIMs for :countryName',
  'not_available_yet' => 'We currently do not offer eSIMs for this country.',
  'not_available_yet_contact_us' => 'We are working hard to expand our global coverage. If you are interested in eSIMs for this country in the meantime, please contact us.',
  'top_plan' => 'Most popular',
  'all_features' => 'All functions',
  'features' => [
    'feature_one' => 'Possible hotspot',
    'feature_two' => 'Coverage across all national networks',
    'feature_three' => 'Simple upgrade in your personal portal',
  ],
  'buy_now' => 'Buy now',
  'starting_from' => 'Starting from',
  'choose_destination' => 'Find a destination',
  'how_esim_works' => [
    'title' => 'How eSIM works',
    'subtitle' => 'Getting started with eSIM is easy! Follow these simple steps to stay connected.',
    'steps' => [
      [
        'title' => 'Buy your eSIM',
        'description' => 'Choose your destination, select a bundle that meets your data needs, and complete your purchase.',
        'image' => '/images/howesimworks/1.png',
      ],
      [
        'title' => 'Receive your eSIM',
        'description' => 'Receive your eSIM QR code directly in your email. Ready to use immediately.',
        'image' => '/images/howesimworks/2.png',
      ],
      [
        'title' => 'Activate and Connect',
        'description' => 'Scan the QR code, activate your eSIM, and enjoy fast, reliable data wherever you travel.',
        'image' => '/images/howesimworks/3.png',
      ],
    ],
  ],
  'sub_description' => 'Choose your bundle below and enjoy seamless connectivity in :countryName on the best networks at the best price.',
];
