<?php

//This file is automatically generated. Do not modify.

return [
    'days' => 'days',
    'buy_plan' => 'Buy now!',
    'perks' => [
        'instant' => 'Instant delivery',
        'advanced_self_service' => 'Advanced self-service portal',
        '247_support' => '24/7 live chat support',
        'prepaid' => 'Prepaid, no strings attached',
        'no_roaming' => 'No roaming costs',
    ],
    'local_for' => 'Local eSIMs for :countryName',

    'not_available_yet' => 'We do currently not offer eSIMs for this country.',
    'not_available_yet_contact_us' => 'We work hard to expand our global coverage. If you are interested in eSIMs for this country in the meantime, please contact us.',
];
