<?php

//This file is automatically generated. Do not modify.

return [
  'title' => 'eSIM Service - Prepaid Virtual SIM Cards for Travelers - :site_name',
  'description' => 'eSIM service ⏩ Prepaid digital SIM cards for tourism and business ⏩ Standard and unlimited, local and global cell phone data plans ⏩ No contracts ✅ No hidden Roaming charges and fees ✅ - :site_name',
  'keywords' => 'eSIM, eSIM service, eSIM card, eSIM data, eSIM data plan, eSIM data plans, eSIM data plan for travelers, eSIM data plan for tourists, eSIM data plan for business, eSIM data plan for travel, eSIM data plan for Europe, eSIM data plan for USA, eSIM data plan for Asia, eSIM data plan for Africa, eSIM data plan for Australia, eSIM data plan for South America, eSIM data plan for North America, eSIM data plan for Middle East, eSIM data plan for Russia, eSIM data plan for China, eSIM data plan for India, eSIM data plan for Japan',
  'routes' => [
    'home' => [
      'title' => 'eSIM Service - Prepaid Virtual SIM Cards for Travelers - :site_name',
      'description' => 'eSIM service ⏩ Prepaid digital SIM cards for tourism and business ⏩ Standard and unlimited, local and global cell phone data plans ⏩ No contracts ✅ No hidden Roaming charges and fees ✅ - :site_name',
    ],
    'about' => [
      'title' => 'About Us - :site_name',
      'description' => 'About Us ⏩ Prepaid digital SIM cards for tourism and business ⏩ Standard and unlimited, local and global cell phone data plans ⏩ No contracts ✅ No hidden Roaming charges and fees ✅ - :site_name',
    ],
    'supported-devices' => [
      'title' => 'Supported Devices - :site_name',
      'description' => 'Supported Devices ⏩ Prepaid digital SIM cards for tourism and business ⏩ Standard and unlimited, local and global cell phone data plans ⏩ No contracts ✅ No hidden Roaming charges and fees ✅ - :site_name',
    ],
    'esim-bundle-per-country' => [
      'title' => 'Affordable Local eSIM Deals for :countryName - :site_name',
      'description' => 'Affordable local eSIM deals for :countryName ⏩ Prepaid digital SIM cards for tourism and business ⏩ Standard and unlimited, local and global cell phone data plans ⏩ No contracts ✅ No hidden Roaming charges and fees ✅ - :site_name',
    ],
  ],
];
