<?php

//This file is automatically generated. Do not modify.

return [
  'title' => 'À propos de nous',
  'subtitle' => 'Naviguez à travers le monde sans frontières avec nous. Nous sommes votre partenaire ultime qui vous garde connecté où que votre passion vous mène.',
  'our_team' => 'Notre Équipe',
  'our_team_subtitle' => 'Nous croyons en l\'autonomisation des voyageurs grâce à une connectivité de données mondiale fiable et abordable. Notre équipe diversifiée est unie dans la création d\'un monde plus connecté et accessible pour tous ceux qui sont en déplacement.',
  'why_us' => 'Pourquoi choisir notre entreprise',
  'why_us_subtitle' => 'Nous sommes fiers de notre service fiable, de nos prix compétitifs et de notre approche centrée sur le client. Ta satisfaction est notre plus haute priorité.',
  'why_us_reasons' => [
    [
      'title' => 'Plans flexibles conçus pour vos besoins de voyage',
      'subtitle' => 'Choisissez parmi une gamme de forfaits abordables adaptés à différents pays et régions. Nous vous offrons la flexibilité de sélectionner le plan de données parfait, afin que vous ne payiez que pour ce dont vous avez besoin, sans frais cachés.',
      'image' => '/images/whyus/nlo2.png',
    ],
    [
      'title' => 'Activation directe, pas de cartes SIM physiques nécessaires',
      'subtitle' => 'Les jours de l\'échange de cartes SIM physiques sont révolus. Chez nous, votre eSIM est livrée directement par e-mail et peut être activée en quelques minutes. Il vous suffit de scanner le code QR et vous êtes prêt à vous connecter.',
      'image' => '/images/whyus/nlo3.png',
    ],
  ],
  'contact' => 'Contactez-nous',
  'contact_subtitle' => 'Nous sommes ici pour vous aider. Si vous avez des questions ou avez besoin d\'aide, contactez-nous.',
];
