<?php

//This file is automatically generated. Do not modify.

return [
  'title' => 'Toutes nos destinations',
  'subtitle' => 'Où que vous alliez, nous vous avons couvert avec des eSIM pour chaque destination. Choisissez votre destination ci-dessous pour commencer.',
];
