<?php

//This file is automatically generated. Do not modify.

return [
  'title' => 'Appareils pris en charge',
  'subtitle' => 'Nous prenons en charge un large éventail d\'appareils. Vérifiez si votre appareil figure sur la liste ci-dessous. Les appareils sont organisés par fabricant.',
  'models_below' => 'Les modèles pris en charge sont mentionnés ci-dessous.',
];
