<?php

//This file is automatically generated. Do not modify.

return [
  'faq' => 'FAQ',
  'subtitle' => 'Avez-vous des questions ? Nous avons des réponses. Trouvez tout ce que vous devez savoir sur nos eSIMs.',
];
