<?php

//This file is automatically generated. Do not modify.

return [
  [
    'question' => 'Qu\'est-ce qu\'une eSIM et comment puis-je utiliser :organisationName ?',
    'answer' => 'Une eSIM, ou SIM intégrée, est une carte SIM numérique qui permet aux utilisateurs d\'activer et de gérer plusieurs forfaits mobiles sur un seul appareil sans avoir besoin d\'une carte SIM physique. Avec une eSIM, vous pouvez facilement basculer entre les fournisseurs de services mobiles et profiter de fonctionnalités telles que l\'ajout d\'une ligne supplémentaire pour les voyages internationaux ou le maintien de forfaits de données distincts pour un usage personnel et professionnel.',
  ],
  [
    'question' => 'Comment activer l\'internet mobile eSIM avec :organisationName ?',
    'answer' => 'Pour vous connecter à Internet en utilisant la :organisationName eSIM, suivez ces étapes : 1. Allez dans vos paramètres de données mobiles. 2. Activez la ligne mobile :organisationName. 3. Activez l\'itinérance des données. 4. Sélectionnez la ligne Internet :organisationName comme votre connexion principale. *Évitez de sélectionner l\'option "Supprimer la planification des données", car cela supprimera votre profil eSIM.*',
  ],
  [
    'question' => 'Puis-je passer des appels téléphoniques ou envoyer des SMS ?',
    'answer' => 'Les plans eSIM prépayés de :organisationName sont conçus pour un usage uniquement de données et ne contiennent pas de numéro de téléphone mobile pour les appels traditionnels ou les SMS. Nous recommandons d\'utiliser des applications VoIP telles que Facebook Messenger, WhatsApp, Viber, Telegram ou Skype pour rester connecté dans le monde entier sans avoir besoin d\'une carte SIM internationale standard.',
  ],
  [
    'question' => 'Une carte eSIM peut-elle être réutilisée ?',
    'answer' => 'Chaque QR code pour un eSIM est unique et ne peut être utilisé que sur un seul appareil. Une fois que le profil eSIM est supprimé, le QR code ne peut pas être réutilisé sur le même appareil ou un autre appareil, ce qui garantit la sécurité et l\'exclusivité.',
  ],
  [
    'question' => 'Quand commence la durée du eSIM forfait de données mobiles ?',
    'answer' => 'La durée de votre plan de données eSIM commence immédiatement après la première fois que votre appareil se connecte à un réseau mobile avec l\'eSIM.',
  ],
  [
    'question' => 'Puis-je prolonger la date d\'expiration de mon plan de données mobiles eSIM actuel ?',
    'answer' => 'Bien sûr ! Vous recevrez plusieurs notifications push lorsque vous serez presque à court de votre forfait. Vous pouvez facilement recharger via votre portail personnel.',
  ],
  [
    'question' => 'Puis-je utiliser le tethering ou le Point d\'accès personnel avec :organisationName ?',
    'answer' => 'Oui, vous pouvez partager vos données mobiles avec d\'autres appareils via votre :organisationName-eSIM. Installez simplement le :organisationName-eSIM sur votre appareil et activez le Point d\'accès personnel dans vos paramètres. Cette fonctionnalité est incluse sans frais supplémentaires, mais gardez à l\'esprit que l\'utilisation des données tethered sera déduite de votre forfait.',
  ],
  [
    'question' => 'Puis-je conserver mes numéros d\'application de messages personnels tout en utilisant l\'eSIM de :organisationName ?',
    'answer' => 'Oui, tu peux continuer à utiliser WhatsApp, Snapchat, Telegram et d\'autres applications de messagerie en parallèle avec ta :organisationName eSIM prépayée sans problème.',
  ],
  [
    'question' => 'Comment puis-je transférer mon eSIM vers un nouveau téléphone ?',
    'answer' => 'Avant de transférer, assurez-vous que votre nouveau smartphone prend en charge la technologie eSIM. Contactez notre équipe de support pour créer un nouveau profil eSIM, puis connectez-vous à votre compte :organisationName sur le nouvel appareil pour installer le code QR. Assurez-vous de confirmer que vous utilisez un autre appareil pour des mises à jour de paramètres précises.',
  ],
  [
    'question' => 'Y a-t-il des contrats comme ceux des fournisseurs d\'eSIM traditionnels ?',
    'answer' => 'Non, :organisationName n\'exige pas que vous signiez des contrats. Vous pouvez activer ou désactiver votre carte eSIM à votre convenance, en fonction de vos projets. Nous sommes heureux de vous aider.',
  ],
  [
    'question' => 'Quelle est la différence entre l\'eSIM de :organisationName et les forfaits de données de roaming standard des opérateurs mobiles physiques ?',
    'answer' => ':organisationName propose des forfaits de données sans contrat et sans frais d\'itinérance cachés. Vous ne payez que pour les données que vous utilisez, en fonction du forfait que vous choisissez, ce qui en fait souvent une option plus économique.',
  ],
  [
    'question' => 'Pourquoi ma vitesse de données est-elle lente ?',
    'answer' => 'La vitesse des données peut être influencée par différents facteurs, notamment le type de smartphone que vous avez, la technologie réseau, les sites Web ou les applications que vous utilisez, et l\'heure de la journée. De plus, les vitesses peuvent varier en fonction de l\'infrastructure réseau du pays. Si vous rencontrez des vitesses lentes, essayez de redémarrer votre téléphone et partagez avec nous les résultats de vitesse, en particulier les comparaisons avec et sans le mode LTE activé.',
  ],
  [
    'question' => 'Comment puis-je consulter mes bundels ?',
    'answer' => 'Vous pouvez suivre vos données restantes et vos limites dans notre panneau client.',
  ],
  [
    'question' => 'Qu\'est-ce qui rend :organisationName différent des autres services eSIM ?',
    'answer' => ':organisationName se distingue par sa collaboration avec des opérateurs locaux dans plus de 200 pays, et propose des forfaits de données rentables sans intermédiaires. Nous offrons une couverture robuste et un processus d\'activation simple. :organisationName est parfait pour les voyageurs à la recherche de solutions Internet mobile.',
  ],
];
