<?php

//This file is automatically generated. Do not modify.

return [
  'title' => 'Restez connecté en ligne dans :countryName',
  'subtitle' => 'Voyager vers :countryName ? Restez connecté avec notre eSIM, afin d\'avoir un accès Internet immédiat à votre arrivée.',
  'features' => [
    [
      'title' => 'Fiable et rapide en ligne dans :countryName',
      'subtitle' => ':countryName est une destination magnifique, avec des villes modernes vibrantes et des paysages naturels à couper le souffle. Améliorez votre expérience de voyage avec notre eSIM, afin de rester connecté dès votre arrivée. Dites adieu aux tracas de la recherche d\'une carte SIM locale ou de la gestion de l\'itinérance de données coûteuse. Avec notre eSIM, vous profitez d\'un accès fluide aux réseaux 4G/5G des meilleurs fournisseurs du pays, afin de rester en ligne, peu importe où votre voyage vous mène.',
      'image' => 'images/features/feature1.jpg',
    ],
    [
      'title' => 'Restez connecté avec vos proches',
      'subtitle' => 'Notre eSIM est conçue pour un accès Internet sans faille, afin que vous restiez connecté pour toutes vos activités en ligne sans avoir besoin d\'un nouveau numéro de téléphone. Créez facilement un point d\'accès pour partager votre connexion avec d\'autres voyageurs ou votre famille, une fonctionnalité souvent bloquée par d\'autres fournisseurs mais entièrement prise en charge par nous. Profitez de la commodité d\'une connectivité directe sur des appareils compatibles eSIM, afin que vous et vos proches restiez toujours et partout en ligne. Veuillez confirmer si votre appareil prend en charge l\'eSIM pour vous assurer que vous êtes prêt pour nos offres Internet. Veuillez noter que les appels et les SMS ne sont pas pris en charge avec notre eSIM.',
      'image' => 'images/features/feature2.jpg',
    ],
  ],
];
