<?php

//This file is automatically generated. Do not modify.

return [
  'all_rights_reserved' => 'Tous droits réservés.',
  'foreign_currencies_for_reference_only' => 'Les devises étrangères sont uniquement à titre de référence. La facturation sera en euros.',
];
