<?php

//This file is automatically generated. Do not modify.

return [
  'from' => ':price/GB',
  'title' => 'Connectez-vous dans le monde entier avec nos eSIMs',
  'subtitle' => 'Découvrez nos forfaits eSIM et restez connecté, où que vous soyez !',
  'search_destination' => 'Cherchez une destination',
  'show_all_esim' => 'Afficher tous les plans eSIM',
  'how_it_works' => 'Comment ça marche ?',
  'steps' => [
    [
      'title' => 'Étape 1',
      'description' => 'Vérifiez si votre appareil est compatible eSIM dans notre liste de compatibilité.',
    ],
    [
      'title' => 'Étape 2',
      'description' => 'Choisissez votre destination et le forfait de données eSIM souhaité',
    ],
    [
      'title' => 'Étape 3',
      'description' => 'Achetez la carte eSIM qui convient le mieux à vos besoins',
    ],
    [
      'title' => 'Étape 4',
      'description' => 'Votre eSIM est livrée automatiquement. Suivez les instructions dans votre e-mail.',
    ],
    [
      'title' => 'Étape 5',
      'description' => 'Installez votre profil eSIM et profitez de votre voyage !',
    ],
  ],
  'supported_networks' => 'Fournisseurs de réseau pris en charge',
  'supported_networks_description' => 'Nous travaillons en étroite collaboration avec des marques de connectivité, de médias et de technologie leaders sur le marché et de confiance dans le monde entier.',
  'and_many_more' => 'et encore beaucoup plus...',
  'user_reviews' => 'Ce que nos utilisateurs satisfaits disent',
  'user_reviews_subtitle' => 'Découvrez pourquoi les voyageurs du monde entier font confiance à notre eSIM pour une connectivité fluide et fiable en déplacement.',
  'faq' => 'Questions Fréquemment Posées',
  'popular_destinations' => 'Destinations Populaires',
  'popular_destinations_description' => 'Découvrez nos destinations eSIM les plus populaires et restez connecté, où que vous alliez !',
  'see_all_destinations' => 'Découvrez toutes les destinations',
];
