<?php

//This file is automatically generated. Do not modify.

return [
  'home' => 'Accueil',
  'supported-devices' => 'Appareils pris en charge',
  'about' => 'À propos de nous',
  'contact' => 'Contact',
  'portal_link' => 'Mon Portal',
  'destinations' => 'Toutes les destinations',
];
