<?php

//This file is automatically generated. Do not modify.

return [
  'days' => 'jours',
  'buy_plan' => 'Achetez maintenant !',
  'perks' => [
    'instant' => 'Livraison directe',
    'advanced_self_service' => 'Portail de self-service avancé',
    '247_support' => 'assistance par chat en direct 24/7',
    'prepaid' => 'Prépayé, sans conditions attachées',
    'no_roaming' => 'Pas de frais d\'itinérance',
  ],
  'local_for' => 'eSIM locales pour :countryName',
  'not_available_yet' => 'Nous ne proposons actuellement pas d\'eSIM pour ce pays.',
  'not_available_yet_contact_us' => 'Nous travaillons dur pour étendre notre couverture mondiale. Si vous êtes intéressé par les eSIMs pour ce pays en attendant, veuillez nous contacter.',
  'top_plan' => 'Le plus populaire',
  'all_features' => 'Toutes les fonctions',
  'features' => [
    'feature_one' => 'Point d\'accès possible',
    'feature_two' => 'Couverture sur tous les réseaux nationaux',
    'feature_three' => 'Mise à niveau simple dans votre portail personnel',
  ],
  'buy_now' => 'Achetez maintenant',
  'starting_from' => 'Commencer à partir de',
  'choose_destination' => 'Trouvez une destination',
  'how_esim_works' => [
    'title' => 'Comment fonctionne l\'eSIM',
    'subtitle' => 'Se mettre au travail avec eSIM est facile ! Suivez ces étapes simples pour rester connecté.',
    'steps' => [
      [
        'title' => 'Achetez votre eSIM',
        'description' => 'Choisissez votre destination, choisissez un forfait qui répond à vos besoins en données, et finalisez votre achat.',
        'image' => '/images/howesimworks/1.png',
      ],
      [
        'title' => 'Recevez votre eSIM',
        'description' => 'Recevez directement votre code QR eSIM dans votre e-mail. Prêt à l\'emploi immédiatement.',
        'image' => '/images/howesimworks/2.png',
      ],
      [
        'title' => 'Activez et Connectez',
        'description' => 'Scannez le code QR, activez votre eSIM et profitez de données rapides et fiables où que vous soyez.',
        'image' => '/images/howesimworks/3.png',
      ],
    ],
  ],
  'sub_description' => 'Choisissez votre forfait ci-dessous et profitez d\'une connectivité transparente en :countryName sur les meilleurs réseaux au meilleur prix.',
];
