<?php

//This file is automatically generated. Do not modify.

return [
  'title' => 'Über uns',
  'subtitle' => 'Navigiere ohne Grenzen durch die Welt mit uns. Wir sind dein ultimativer Partner, der dich verbunden hält, wo auch immer dich deine Leidenschaft hinführt.',
  'our_team' => 'Unser Team',
  'our_team_subtitle' => 'Wir glauben daran, Reisende mit zuverlässiger und erschwinglicher globaler Datenkonnektivität zu stärken. Unser diverses Team ist vereint in der Schaffung einer besser verbundenen und zugänglicheren Welt für alle, die unterwegs sind.',
  'why_us' => 'Warum uns wählen',
  'why_us_subtitle' => 'Wir sind stolz auf unseren zuverlässigen Service, wettbewerbsfähige Preise und kundenorientierte Vorgehensweise. Deine Zufriedenheit hat für uns oberste Priorität.',
  'why_us_reasons' => [
    [
      'title' => 'Flexible Pläne, die für deine Reisebedürfnisse entworfen wurden',
      'subtitle' => 'Wählen Sie aus einer Reihe von erschwinglichen Paketen, die auf verschiedene Länder und Regionen abgestimmt sind. Wir geben Ihnen die Flexibilität, den perfekten Datenplan auszuwählen, damit Sie nur für das bezahlen, was Sie benötigen, ohne versteckte Kosten.',
      'image' => '/images/whyus/nlo2.png',
    ],
    [
      'title' => 'Direkte Aktivierung, keine physischen SIM-Karten erforderlich',
      'subtitle' => 'Die Tage des Wechselns von physischen SIM-Karten sind vorbei. Bei uns wird deine eSIM direkt per E-Mail geliefert und kann innerhalb weniger Minuten aktiviert werden. Scanne einfach den QR-Code und du bist bereit, eine Verbindung herzustellen.',
      'image' => '/images/whyus/nlo3.png',
    ],
  ],
  'contact' => 'Nehmen Sie Kontakt mit uns auf',
  'contact_subtitle' => 'Wir sind hier, um dir zu helfen. Wenn du Fragen hast oder Hilfe benötigst, kontaktiere uns bitte.',
];
