<?php

//This file is automatically generated. Do not modify.

return [
  'first' => 'Bewertet mit 4.5/5 auf Trustpilot',
  'second' => '24/7 Unterstützung',
  'third' => 'Nur die besten Netzwerke',
];
