<?php

//This file is automatically generated. Do not modify.

return [
  'title' => 'Alle unsere Reiseziele',
  'subtitle' => 'Egal wohin du gehst, wir haben dich mit eSIMs für jedes Ziel abgedeckt. Wähle dein Ziel unten, um zu beginnen.',
];
