<?php

//This file is automatically generated. Do not modify.

return [
  'title' => 'Unterstützte Geräte',
  'subtitle' => 'Wir unterstützen eine breite Palette von Geräten. Überprüfen Sie, ob Ihr Gerät auf der untenstehenden Liste steht. Geräte sind nach Hersteller organisiert.',
  'models_below' => 'Unterstützte Modelle sind unten aufgeführt.',
];
