<?php

//This file is automatically generated. Do not modify.

return [
  'faq' => 'FAQ',
  'subtitle' => 'Hast du Fragen? Wir haben Antworten. Finde alles, was du über unsere eSIMs wissen musst.',
];
