<?php

//This file is automatically generated. Do not modify.

return [
  [
    'question' => 'Was ist eine eSIM und wie kann ich :organisationName verwenden?',
    'answer' => 'Eine eSIM, oder embedded SIM, ist eine digitale SIM-Karte, die es Benutzern ermöglicht, mehrere Mobilfunktarife auf einem Gerät zu aktivieren und zu verwalten, ohne eine physische SIM-Karte zu benötigen. Mit einer eSIM kannst du einfach zwischen Mobilfunkanbietern wechseln und Funktionen wie das Hinzufügen einer zusätzlichen Linie für internationale Reisen oder das Beibehalten separater Datenpläne für private und geschäftliche Nutzung genießen.',
  ],
  [
    'question' => 'Wie aktiviere ich eSIM mobiles Internet mit :organisationName?',
    'answer' => 'Um eine Verbindung zum Internet über die :organisationName eSIM herzustellen, befolgen Sie diese Schritte: 1. Gehen Sie zu Ihren mobilen Dateneinstellungen. 2. Aktivieren Sie die :organisationName Mobilfunkleitung. 3. Aktivieren Sie die Datenroaming. 4. Wählen Sie die :organisationName Internetleitung als Ihre primäre Verbindung. *Vermeiden Sie es, die Option "Datenplanung entfernen" auszuwählen, da dies Ihr eSIM-Profil löschen wird.*',
  ],
  [
    'question' => 'Kann ich Telefongespräche führen oder SMS senden?',
    'answer' => ':organisationName\'s Prepaid-eSIM-Pläne sind für die Nutzung von Daten-only konzipiert und enthalten keine Mobiltelefonnummer für traditionelle Anrufe oder SMS-Nachrichten. Wir empfehlen die Verwendung von VoIP-Anwendungen wie Facebook Messenger, WhatsApp, Viber, Telegram oder Skype, um weltweit verbunden zu bleiben, ohne die Notwendigkeit einer herkömmlichen internationalen SIM-Karte.',
  ],
  [
    'question' => 'Kann eine eSIM-Karte erneut verwendet werden?',
    'answer' => 'Jeder QR-Code für eine eSIM ist einzigartig und kann nur auf einem Gerät verwendet werden. Sobald das eSIM-Profil gelöscht wurde, kann der QR-Code nicht erneut auf demselben oder einem anderen Gerät verwendet werden, was für Sicherheit und Exklusivität sorgt.',
  ],
  [
    'question' => 'Wann beginnt die Dauer des eSIM-Mobilfunktarifs?',
    'answer' => 'Die Dauer Ihres eSIM-Datenplans beginnt sofort, nachdem Ihr Gerät zum ersten Mal mit der eSIM eine Verbindung zu einem mobilen Netzwerk hergestellt hat.',
  ],
  [
    'question' => 'Kann ich das Ablaufdatum meines aktuellen eSIM-Mobilfunktarifs verlängern?',
    'answer' => 'Sicher! Du erhältst mehrere Push-Benachrichtigungen, wenn du fast dein Kontingent aufgebraucht hast. Du kannst über dein persönliches Portal einfach aufladen.',
  ],
  [
    'question' => 'Kann ich Tethering oder Persönlicher Hotspot mit :organisationName verwenden?',
    'answer' => 'Ja, du kannst deine mobilen Daten mit anderen Geräten über deine :organisationName-eSIM teilen. Installiere einfach die :organisationName-eSIM auf deinem Gerät und aktiviere den persönlichen Hotspot in deinen Einstellungen. Diese Funktion ist ohne zusätzliche Kosten enthalten, aber beachte, dass die Nutzung von tethered Daten von deinem Kontingent abgezogen wird.',
  ],
  [
    'question' => 'Kann ich meine persönlichen Nachrichten-App-Nummern behalten, während ich die eSIM von :organisationName benutze?',
    'answer' => 'Ja, du kannst deine WhatsApp, Snapchat, Telegram und andere Nachrichten-Apps weiterhin problemlos neben deiner :organisationName Prepaid-eSIM verwenden.',
  ],
  [
    'question' => 'Wie kann ich meine eSIM auf ein neues Telefon übertragen?',
    'answer' => 'Bevor du überträgst, stelle sicher, dass dein neues Smartphone eSIM-Technologie unterstützt. Kontaktiere unser Support-Team, um ein neues eSIM-Profil zu erstellen, und melde dich dann bei deinem :organisationName-Konto auf dem neuen Gerät an, um den QR-Code zu installieren. Stelle sicher, dass du bestätigst, dass du ein anderes Gerät für genaue Einstellungsupdates verwendest.',
  ],
  [
    'question' => 'Gibt es Verträge wie die von traditionellen eSIM-Anbietern?',
    'answer' => 'Nein, :organisationName verlangt nicht, dass du Verträge unterschreibst. Du kannst deine eSIM-Karte nach Belieben aktivieren oder deaktivieren, je nach deinen Plänen. Wir denken gerne mit dir mit.',
  ],
  [
    'question' => 'Was ist der Unterschied zwischen :organisationName\'s eSIM und den Standard-Roaming-Datenplänen physischer Mobilfunkanbieter?',
    'answer' => ':organisationName bietet vertragsfreie Datenpläne ohne versteckte Roamingkosten. Du zahlst nur für die Daten, die du verwendest, abhängig von dem Paket, das du wählst, wodurch es oft eine wirtschaftlichere Option ist.',
  ],
  [
    'question' => 'Warum ist meine Datenrate langsam?',
    'answer' => 'Die Datenrate kann von verschiedenen Faktoren beeinflusst werden, darunter der Typ des Smartphones, das Sie haben, die Netzwerktechnologie, die Websites oder Apps, die Sie verwenden, und die Tageszeit. Darüber hinaus können die Geschwindigkeiten je nach Netzwerkinfrastruktur des Landes variieren. Wenn Sie langsame Geschwindigkeiten erleben, versuchen Sie, Ihr Telefon neu zu starten, und teilen Sie uns etwaige Geschwindigkeitsresultate mit, insbesondere Vergleiche mit und ohne aktivierten LTE-Modus.',
  ],
  [
    'question' => 'Wie kann ich meine Bundles einsehen?',
    'answer' => 'Du kannst deine verbleibenden Daten und Limits in unserem Kundenpanel verfolgen.',
  ],
  [
    'question' => 'Was macht :organisationName anders als andere eSIM-Dienste?',
    'answer' => ':organisationName fällt auf, weil sie mit lokalen Betreibern in mehr als 200 Ländern zusammenarbeitet und kosteneffektive Datenpakete ohne Zwischenhändler anbietet. Wir bieten robuste Abdeckung und einen einfachen Aktivierungsprozess. :organisationName ist perfekt für Reisende, die nach mobilen Internetlösungen suchen.',
  ],
];
