<?php

//This file is automatically generated. Do not modify.

return [
  'title' => 'Bleib online verbunden in :countryName',
  'subtitle' => 'Reisen nach :countryName? Bleiben Sie mit unserer eSIM verbunden, damit Sie bei Ihrer Ankunft sofort Internetzugang haben.',
  'features' => [
    [
      'title' => 'Zuverlässig und schnell online in :countryName',
      'subtitle' => ':countryName ist ein wunderschönes Reiseziel, mit lebhaften modernen Städten und atemberaubenden natürlichen Landschaften. Verbessern Sie Ihr Reiseerlebnis mit unserer eSIM, damit Sie direkt bei Ihrer Ankunft verbunden bleiben. 
        Verabschieden Sie sich von dem Aufwand, eine lokale SIM-Karte zu suchen oder mit teurem Datenroaming umzugehen. Mit unserer eSIM genießen Sie nahtlosen Zugang zu 4G/5G-Netzwerken der besten Anbieter des Landes, sodass Sie online bleiben, wohin Ihre Reise Sie auch führt.',
      'image' => 'images/features/feature1.jpg',
    ],
    [
      'title' => 'Bleiben Sie mit Ihren Lieben verbunden',
      'subtitle' => 'Unsere eSIM ist für nahtlosen Internetzugang konzipiert, damit Sie für all Ihre Online-Aktivitäten verbunden bleiben, ohne die Notwendigkeit einer neuen Telefonnummer. Erstellen Sie einfach einen Hotspot, um Ihre Verbindung mit Mitreisenden oder Familie zu teilen, eine Funktion, die oft von anderen Anbietern blockiert wird, aber von uns vollständig unterstützt wird. Genießen Sie den Komfort der direkten Konnektivität auf eSIM-kompatiblen Geräten, damit Sie und Ihre Lieben jederzeit und überall online bleiben. Bitte bestätigen Sie, ob Ihr Gerät eSIM unterstützt, um sicherzustellen, dass Sie für unsere Internetangebote bereit sind. Bitte beachten Sie, dass Anrufe und SMS mit unserer eSIM nicht unterstützt werden.',
      'image' => 'images/features/feature2.jpg',
    ],
  ],
];
