<?php

//This file is automatically generated. Do not modify.

return [
  'all_rights_reserved' => 'Alle Rechte vorbehalten.',
  'foreign_currencies_for_reference_only' => 'Ausländische Währungen dienen nur zur Referenz. Die Rechnungsstellung erfolgt in Euro.',
];
