<?php

//This file is automatically generated. Do not modify.

return [
  'from' => ':price/GB',
  'title' => 'Verbinden Sie sich weltweit mit unseren eSIMs',
  'subtitle' => 'Entdecken Sie unsere eSIM-Pakete und bleiben Sie verbunden, wo immer Sie sind!',
  'search_destination' => 'Such a destination',
  'show_all_esim' => 'Zeige alle eSIM-Pläne',
  'how_it_works' => 'Wie funktioniert das?',
  'steps' => [
    [
      'title' => 'Schritt 1',
      'description' => 'Überprüfen Sie, ob Ihr Gerät eSIM-kompatibel ist in unserer Kompatibilitätsliste',
    ],
    [
      'title' => 'Schritt 2',
      'description' => 'Wählen Sie Ihr Ziel und den gewünschten eSIM-Datenplan',
    ],
    [
      'title' => 'Schritt 3',
      'description' => 'Kaufen Sie die eSIM-Karte, die am besten zu Ihren Bedürfnissen passt.',
    ],
    [
      'title' => 'Schritt 4',
      'description' => 'Ihre eSIM wird automatisch geliefert. Befolgen Sie die Anweisungen in Ihrer E-Mail.',
    ],
    [
      'title' => 'Schritt 5',
      'description' => 'Installiere dein eSIM-Profil und genieße deine Reise!',
    ],
  ],
  'supported_networks' => 'Unterstützte Netzwerkprovider',
  'supported_networks_description' => 'Wir arbeiten eng mit vertrauenswürdigen marktführenden Marken für connectivity, media und technology auf der ganzen Welt zusammen.',
  'and_many_more' => 'und noch viel mehr...',
  'user_reviews' => 'Was unsere zufriedenen Benutzer sagen',
  'user_reviews_subtitle' => 'Sehen Sie, warum Reisende auf der ganzen Welt auf unsere eSIM für nahtlose, zuverlässige Konnektivität unterwegs vertrauen.',
  'faq' => 'Häufig gestellte Fragen',
  'popular_destinations' => 'Beliebte Reiseziele',
  'popular_destinations_description' => 'Entdecken Sie unsere beliebtesten eSIM-Destinationen und bleiben Sie verbunden, wo auch immer Sie hingehen!',
  'see_all_destinations' => 'Siehe alle Reiseziele',
];
