<?php

//This file is automatically generated. Do not modify.

return [
  'days' => 'Tage',
  'buy_plan' => 'Kaufe jetzt!',
  'perks' => [
    'instant' => 'Direkte Lieferung',
    'advanced_self_service' => 'Fortgeschrittenes Self-Service-Portal',
    '247_support' => '24/7 Live-Chat-Unterstützung',
    'prepaid' => 'Prepaid, keine Bedingungen verbunden',
    'no_roaming' => 'Keine Roaminggebühren',
  ],
  'local_for' => 'Lokale eSIMs für :countryName',
  'not_available_yet' => 'Wir bieten derzeit keine eSIMs für dieses Land an.',
  'not_available_yet_contact_us' => 'Wir arbeiten hart daran, unsere globale Abdeckung auszubauen. Wenn Sie in der Zwischenzeit an eSIMs für dieses Land interessiert sind, kontaktieren Sie uns bitte.',
  'top_plan' => 'Meist beliebt',
  'all_features' => 'Alle Funktionen',
  'features' => [
    'feature_one' => 'Hotspot möglich',
    'feature_two' => 'Abdeckung über alle nationalen Netzwerke',
    'feature_three' => 'Einfache Aufwertung in Ihrem persönlichen Portal',
  ],
  'buy_now' => 'Jetzt kaufen',
  'starting_from' => 'Beginnen ab',
  'choose_destination' => 'Finde ein Ziel',
  'how_esim_works' => [
    'title' => 'Wie eSIM funktioniert',
    'subtitle' => 'Loslegen mit eSIM ist einfach! Befolgen Sie diese einfachen Schritte, um verbunden zu bleiben.',
    'steps' => [
      [
        'title' => 'Kaufen Sie Ihre eSIM',
        'description' => 'Wähle dein Ziel, wähle ein Paket, das deinen Datenbedürfnissen entspricht, und schließe deinen Kauf ab.',
        'image' => '/images/howesimworks/1.png',
      ],
      [
        'title' => 'Erhalten Sie Ihre eSIM',
        'description' => 'Erhalten Sie direkt Ihren eSIM QR-Code per E-Mail. Sofort einsatzbereit.',
        'image' => '/images/howesimworks/2.png',
      ],
      [
        'title' => 'Aktivieren und Verbinden',
        'description' => 'Scanne den QR-Code, aktiviere deine eSIM und genieße schnelle, zuverlässige Daten, wo auch immer du reist.',
        'image' => '/images/howesimworks/3.png',
      ],
    ],
  ],
  'sub_description' => 'Wählen Sie Ihr Paket unten aus und genießen Sie nahtlose Konnektivität in :countryName über die besten Netzwerke zum besten Preis.',
];
