<?php

//This file is automatically generated. Do not modify.

return [
  'title' => 'eSIM-Service - Prepaid virtuelle SIM-Karten für Reisende - :site_name',
  'description' => 'eSIM-Dienst ⏩ Prepaid digitale SIM-Karten für Tourismus und Geschäft ⏩ Standard- und unbegrenzte, lokale und globale Mobilfunktarife ⏩ Keine Verträge ✅ Keine versteckten Roaminggebühren und -kosten ✅ - :site_name',
  'keywords' => 'eSIM, eSIM-Service, eSIM-Karte, eSIM-Daten, eSIM-Datenplan, eSIM-Datenpläne, eSIM-Datenplan für Reisende, eSIM-Datenplan für Touristen, eSIM-Datenplan für Unternehmen, eSIM-Datenplan für Reisen, eSIM-Datenplan für Europa, eSIM-Datenplan für die USA, eSIM-Datenplan für Asien, eSIM-Datenplan für Afrika, eSIM-Datenplan für Australien, eSIM-Datenplan für Südamerika, eSIM-Datenplan für Nordamerika, eSIM-Datenplan für den Nahen Osten, eSIM-Datenplan für Russland, eSIM-Datenplan für China, eSIM-Datenplan für Indien, eSIM-Datenplan für Japan',
  'routes' => [
    'home' => [
      'title' => 'eSIM-Service - Prepaid virtuelle SIM-Karten für Reisende - :site_name',
      'description' => 'eSIM-Service ⏩ Prepaid digitale SIM-Karten für Tourismus und Geschäft ⏩ Standard- und unbegrenzte, lokale und globale mobile Datenpläne ⏩ Keine Verträge ✅ Keine versteckten Roamingkosten und -gebühren ✅ - :site_name',
    ],
    'about' => [
      'title' => 'Über uns - :site_name',
      'description' => 'Über uns ⏩ Prepaid digitale SIM-Karten für Tourismus und Geschäft ⏩ Standard- und unbegrenzte, lokale und globale Mobilfunktarife ⏩ Keine Verträge ✅ Keine versteckten Roaminggebühren und -kosten ✅ - :site_name',
    ],
    'supported-devices' => [
      'title' => 'Unterstützte Geräte - :site_name',
      'description' => 'Unterstützte Geräte ⏩ Prepaid digitale SIM-Karten für Tourismus und Geschäft ⏩ Standard- und unbegrenzte, lokale und globale mobile Datentarife ⏩ Keine Verträge ✅ Keine versteckten Roaminggebühren und -kosten ✅ - :site_name',
    ],
    'esim-bundle-per-country' => [
      'title' => 'eSIM :countryName - :site_name',
      'description' => 'eSIM :countryName ⏩ Prepaid digitale SIM-Karten für Tourismus und Geschäft ⏩ Standard- und unbegrenzte, lokale und globale mobile Datenpläne ⏩ Keine Verträge ✅ Keine versteckten Roaminggebühren und -kosten ✅ - :site_name',
    ],
  ],
];
