<?php

//This file is automatically generated. Do not modify.

return [
  'Rens' => [
    'role' => 'Mitgründer',
    'image' => '/images/team/rens.png',
  ],
  'Luuk' => [
    'role' => 'Mitbegründer',
    'image' => '/images/team/luuk.png',
  ],
  'Fleur' => [
    'role' => 'Kundensupport',
    'image' => '/images/team/fleur.png',
  ],
  'Patrick' => [
    'role' => 'Entwickler',
    'image' => '/images/team/patrick.png',
  ],
];
