<?php

//This file is automatically generated. Do not modify.

return [
  'title' => 'Всички наши дестинации',
  'subtitle' => 'Където и да отидете, ние ви осигуряваме eSIM карти за всяка дестинация. Изберете вашата дестинация по-долу, за да започнете.',
];
