<?php

//This file is automatically generated. Do not modify.

return [
  'faq' => 'Често задавани въпроси',
  'subtitle' => 'Имате ли въпроси? Ние имаме отговори. Намерете всичко, което трябва да знаете за нашите eSIM.',
];
