<?php

//This file is automatically generated. Do not modify.

return [
  'all_rights_reserved' => 'Всички права запазени.',
  'foreign_currencies_for_reference_only' => 'Чуждите валути са само за справка. Фактурирането ще бъде в евро.',
];
