<?php

//This file is automatically generated. Do not modify.

return [
  'home' => 'Начало',
  'supported-devices' => 'Поддържани устройства',
  'destinations' => 'Всички дестинации',
  'about' => 'Относно',
  'contact' => 'Контакт',
  'portal_link' => 'Моят Portal',
];
