<?php

//This file is automatically generated. Do not modify.

return [
  'Rens' => [
    'role' => 'Съосновател',
    'image' => '/images/team/rens.png',
  ],
  'Luuk' => [
    'role' => 'Съосновател',
    'image' => '/images/team/luuk.png',
  ],
  'Fleur' => [
    'role' => 'Поддръжка на клиенти',
    'image' => '/images/team/fleur.png',
  ],
  'Patrick' => [
    'role' => 'Разработчик',
    'image' => '/images/team/patrick.png',
  ],
];
