<?php

//This file is automatically generated. Do not modify.

return [
  'title' => 'Over ons',
  'subtitle' => 'Navigeer over de wereld zonder grenzen met ons. Wij zijn je ultieme partner die je verbonden houdt waar je passie je ook naartoe drijft.',
  'our_team' => 'Ons Team',
  'our_team_subtitle' => 'Wij geloven in het empoweren van reizigers met betrouwbare en betaalbare wereldwijde dataconnectiviteit. Ons diverse team is verenigd in het creëren van een meer verbonden en toegankelijke wereld voor iedereen die onderweg is.',
  'why_us' => 'Waarom voor ons kiezen',
  'why_us_subtitle' => 'We zijn trots op onze betrouwbare service, concurrerende prijzen en klantgerichte aanpak. Jouw tevredenheid is onze hoogste prioriteit.',
  'why_us_reasons' => [
    [
      'title' => 'Flexibele Plannen Ontworpen voor Jouw Reisbehoeften',
      'subtitle' => 'Kies uit een reeks betaalbare bundels die zijn afgestemd op verschillende landen en regio\'s. We geven je de flexibiliteit om het perfecte data plan te selecteren, zodat je alleen betaalt voor wat je nodig hebt, zonder verborgen kosten.',
      'image' => '/images/whyus/nlo2.png',
    ],
    [
      'title' => 'Directe activatie, geen fysieke SIM-kaarten nodig',
      'subtitle' => 'De dagen van het verwisselen van fysieke SIM-kaarten zijn voorbij. Bij ons wordt je eSIM direct via e-mail geleverd en kan deze binnen enkele minuten worden geactiveerd. Scan gewoon de QR-code en je bent klaar om verbinding te maken.',
      'image' => '/images/whyus/nlo3.png',
    ],
  ],
  'contact' => 'Neem contact met ons op',
  'contact_subtitle' => 'We zijn hier om je te helpen. Als je vragen hebt of hulp nodig hebt, neem dan contact met ons op.',
];
