<?php

//This file is automatically generated. Do not modify.

return [
  'first' => 'Beoordeeld met 4.5/5 op Trustpilot',
  'second' => '24/7 Ondersteuning',
  'third' => 'Alleen de beste netwerken',
];
