<?php

//This file is automatically generated. Do not modify.

return [
  'title' => 'Al onze bestemmingen',
  'subtitle' => 'Waar je ook naartoe gaat, wij hebben je gedekt met eSIMs voor elke bestemming. Kies je bestemming hieronder om te beginnen.',
];
