<?php

//This file is automatically generated. Do not modify.

return [
  [
    'question' => 'Wat is een eSIM en hoe kan ik :organisationName gebruiken?',
    'answer' => 'Een eSIM, of embedded SIM, is een digitale SIM-kaart die gebruikers in staat stelt om meerdere mobiele plannen op één apparaat te activeren en te beheren zonder een fysieke SIM-kaart nodig te hebben. Met een eSIM kun je eenvoudig schakelen tussen mobiele providers en genieten van functies zoals het toevoegen van een extra lijn voor internationale reizen of het onderhouden van aparte dataplannen voor persoonlijk en zakelijk gebruik.',
  ],
  [
    'question' => 'Hoe activeer ik eSIM mobiele internet met :organisationName?',
    'answer' => 'Om verbinding te maken met internet met behulp van :organisationName eSIM, volg deze stappen: 1. Ga naar je Mobiele Data-instellingen. 2. Zet de :organisationName mobiele lijn aan. 3. Activeer Dataroaming. 4. Selecteer de :organisationName Internetlijn als je primaire verbinding. *Vermijd het selecteren van de optie "Verwijder dataplanning", omdat dit je eSIM-profiel zal verwijderen.*',
  ],
  [
    'question' => 'Kan ik telefoongesprekken voeren of sms\'jes versturen?',
    'answer' => ':organisationName\'s prepaid eSIM-plannen zijn ontworpen voor data-only gebruik en bevatten geen mobiel telefoonnummer voor traditionele oproepen of sms-berichten. We raden aan om VoIP-applicaties zoals Facebook Messenger, WhatsApp, Viber, Telegram of Skype te gebruiken om wereldwijd verbonden te blijven zonder de noodzaak van een standaard internationale SIM-kaart.',
  ],
  [
    'question' => 'Kan een eSIM-kaart opnieuw worden gebruikt?',
    'answer' => 'Elke QR-code voor een eSIM is uniek en kan alleen op één apparaat worden gebruikt. Zodra het eSIM-profiel is verwijderd, kan de QR-code niet opnieuw worden gebruikt op hetzelfde of een ander apparaat, wat zorgt voor veiligheid en exclusiviteit.',
  ],
  [
    'question' => 'Wanneer begint de duur van het eSIM mobiele dataplans?',
    'answer' => 'De duur van uw eSIM-dataplan begint onmiddellijk na de eerste keer dat jouw apparaat met de eSIM verbinding maakt met een mobiel netwerk.',
  ],
  [
    'question' => 'Kan ik de vervaldatum van mijn huidige eSIM mobiele dataplanning verlengen?',
    'answer' => 'Zeker! Je ontvangt meerdere een pushmeldingen wanneer je bijna door je bundel heen bent. Je kunt via jouw persoonlijke portal eenvoudig opwaarderen.',
  ],
  [
    'question' => 'Kan ik tethering of Persoonlijke Hotspot gebruiken met :organisationName?',
    'answer' => 'Ja, je kunt je mobiele data delen met andere apparaten via je :organisationName-eSIM. Installeer eenvoudig het :organisationName-eSIM op je apparaat en schakel Persoonlijke Hotspot in je instellingen in. Deze functie is inbegrepen zonder extra kosten, maar houd er rekening mee dat het gebruik van tethered data van je bundel zal worden afgetrokken.',
  ],
  [
    'question' => 'Kan ik mijn persoonlijke berichten-app nummers behouden terwijl ik de eSIM van :organisationName gebruik?',
    'answer' => 'Ja, je kunt je WhatsApp, Snapchat, Telegram en andere berichtenapps blijven gebruiken naast je :organisationName prepaid eSIM zonder problemen.',
  ],
  [
    'question' => 'Hoe kan ik mijn eSIM naar een nieuwe telefoon overzetten?',
    'answer' => 'Voordat je overdraagt, zorg ervoor dat je nieuwe smartphone eSIM-technologie ondersteunt. Neem contact op met ons ondersteuningsteam om een nieuw eSIM-profiel aan te maken, log vervolgens in op je :organisationName-account op het nieuwe apparaat om de QR-code te installeren. Zorg ervoor dat je bevestigt dat je een ander apparaat gebruikt voor nauwkeurige instellingenupdates.',
  ],
  [
    'question' => 'Zijn er contracten zoals die van traditionele eSIM-aanbieders?',
    'answer' => 'Nee, :organisationName vereist niet dat je contracten ondertekent. Je kunt je eSIM-kaart naar wens activeren of deactiveren, afhankelijk van jouw plannen. We denken graag met je mee.',
  ],
  [
    'question' => 'Wat is het verschil tussen :organisationName\'s eSIM en standaard roaming dataplannen van fysieke mobiele operators?',
    'answer' => ':organisationName biedt contractvrije dataplannen zonder verborgen roamingkosten. Je betaalt alleen voor de data die je gebruikt, afhankelijk van de bundel dat je kiest, waardoor het vaak een economischere optie is.',
  ],
  [
    'question' => 'Waarom is mijn datasnelheid traag?',
    'answer' => 'Gegevenssnelheid kan worden beïnvloed door verschillende factoren, waaronder het type smartphone dat je hebt, netwerktechnologie, de websites of apps die je gebruikt, en het tijdstip van de dag. Daarnaast kunnen snelheden variëren afhankelijk van de netwerkinfrastructuur van het land. Als je trage snelheden ervaart, probeer dan je telefoon opnieuw op te starten en deel eventuele snelheidsresultaten met ons, vooral vergelijkingen met en zonder LTE-modus ingeschakeld.',
  ],
  [
    'question' => 'Hoe kan ik mijn bundels inzien?',
    'answer' => 'Je kunt je resterende data en limieten volgen in ons klantenpaneel.',
  ],
  [
    'question' => 'Wat maakt :organisationName anders dan andere eSIM-diensten?',
    'answer' => ':organisationName valt op door samen te werken met lokale operators in meer dan 200 landen, en biedt kosteneffectieve datapakketten zonder tussenpersonen. We bieden robuuste dekking en een eenvoudig activatieproces. :organisationName is perfect voor reizigers die op zoek zijn naar mobiele internetoplossingen.',
  ],
];
