<?php

//This file is automatically generated. Do not modify.

return [
  'title' => 'Blijf online verbonden in :countryName',
  'subtitle' => 'Reizen naar :countryName? Blijf verbonden met onze eSIM, zodat je direct internettoegang hebt bij aankomst.',
  'features' => [
    [
      'title' => 'Betrouwbaar en snel online in :countryName',
      'subtitle' => ':countryName is een prachtige bestemming, met levendige moderne steden en adembenemende natuurlijke landschappen. Verbeter je reiservaring met onze eSIM, zodat je direct bij aankomst verbonden blijft. 
        Zeg vaarwel tegen de rompslomp van het zoeken naar een lokale SIM-kaart of het omgaan met dure dataroaming. Met onze eSIM geniet je van naadloze toegang tot 4G/5G-netwerken van de beste aanbieders van het land, zodat je online blijft, waar je reis je ook naartoe leidt.',
      'image' => 'images/features/feature1.jpg',
    ],
    [
      'title' => 'Blijf verbonden met dierbaren',
      'subtitle' => 'Onze eSIM is ontworpen voor naadloze internettoegang, zodat je verbonden blijft voor al je online activiteiten zonder de noodzaak van een nieuw telefoonnummer. Maak eenvoudig een hotspot om je verbinding te delen met medereizigers of familie, een functie die vaak door andere providers wordt geblokkeerd maar volledig door ons wordt ondersteund. Geniet van het gemak van directe connectiviteit op eSIM-compatibele apparaten, zodat jij en je dierbaren altijd en overal online blijven. Bevestig alstublieft of je apparaat eSIM ondersteunt om ervoor te zorgen dat je klaar bent voor onze internetaanbiedingen. Houd er rekening mee dat bellen en sms\'en niet worden ondersteund met onze eSIM.',
      'image' => 'images/features/feature2.jpg',
    ],
  ],
];
