<?php

//This file is automatically generated. Do not modify.

return [
  'all_rights_reserved' => 'Alle rechten voorbehouden.',
  'foreign_currencies_for_reference_only' => 'Buitenlandse valuta\'s zijn alleen ter referentie. Facturering zal in euro\'s zijn.',
];
