<?php

//This file is automatically generated. Do not modify.

return [
  'from' => ':price/GB',
  'title' => 'Verbind wereldwijd met onze eSIMs',
  'subtitle' => 'Verken onze eSIM-pakketten en blijf verbonden, waar je ook bent!',
  'search_destination' => 'Zoek een bestemming',
  'show_all_esim' => 'Toon alle eSIM-plannen',
  'how_it_works' => 'Hoe werkt het?',
  'steps' => [
    [
      'title' => 'Stap 1',
      'description' => 'Controleer of uw apparaat eSIM-compatibel is in onze compatibiliteitslijst',
    ],
    [
      'title' => 'Stap 2',
      'description' => 'Kies uw bestemming en het gewenste eSIM-dataplan',
    ],
    [
      'title' => 'Stap 3',
      'description' => 'Koop de eSIM-kaart die het meest geschikt is voor uw behoeften',
    ],
    [
      'title' => 'Stap 4',
      'description' => 'Je eSIM wordt automatisch geleverd. Volg de instructies in je e-mail.',
    ],
    [
      'title' => 'Stap 5',
      'description' => 'Installeer je eSIM-profiel en geniet van je reis!',
    ],
  ],
  'supported_networks' => 'Ondersteunde netwerkproviders',
  'supported_networks_description' => 'We werken nauw samen met vertrouwde marktleidende connectiviteit, media en technologie merken over de hele wereld.',
  'and_many_more' => 'en nog veel meer...',
  'user_reviews' => 'Wat onze tevereden gebruikers zeggen',
  'user_reviews_subtitle' => 'Zie waarom reizigers over de hele wereld vertrouwen op onze eSIM voor naadloze, betrouwbare connectiviteit onderweg.',
  'faq' => 'Veelgestelde Vragen',
  'popular_destinations' => 'Populaire Bestemmingen',
  'popular_destinations_description' => 'Ontdek onze populairste eSIM-bestemmingen en blijf verbonden, waar je ook gaat!',
  'see_all_destinations' => 'Bekijk alle bestemmingen',
];
