<?php

//This file is automatically generated. Do not modify.

return [
  'from' => 'vanaf :price per GB',
  'title' => 'eSIM Mobiele Data Plannen voor Toerisme en Zaken',
  'subtitle' => 'Kies een bestemming en maak direct verbinding met betaalbare dataplannen.',
  'search_destination' => 'Zoek een bestemming',
  'popular_destinations' => 'Populaire bestemmingen',
  'show_all_esim' => 'Toon alle eSIM-plannen',
  'how_it_works' => 'Hoe werkt het?',
  'steps' => [
    [
      'title' => 'Stap 1',
      'description' => 'Controleer of uw apparaat eSIM-compatibel is in onze compatibiliteitslijst',
    ],
    [
      'title' => 'Stap 2',
      'description' => 'Kies je bestemming en het gewenste eSIM-dataplan',
    ],
    [
      'title' => 'Stap 3',
      'description' => 'Koop de eSIM-kaart die het meest geschikt is voor jouw behoeften',
    ],
    [
      'title' => 'Stap 4',
      'description' => 'Je eSIM wordt automatisch geleverd. Volg de instructies in je e-mail.',
    ],
    [
      'title' => 'Stap 5',
      'description' => 'Installeer je eSIM-profiel en geniet van je reis!',
    ],
  ],
  'supported_networks' => 'Ondersteunde netwerken',
  'and_many_more' => 'en nog veel meer...',
  'user_reviews' => 'Gebruikersrecensies',
  'faq' => 'Veelgestelde vragen',
];
