<?php

//This file is automatically generated. Do not modify.

return [
  'home' => 'Home',
  'supported-devices' => 'Ondersteunde apparaten',
  'about' => 'Over ons',
  'contact' => 'Contact',
  'portal_link' => 'Mijn Portal',
  'destinations' => 'Alle bestemmingen',
];
