<?php

//This file is automatically generated. Do not modify.

return [
  [
    'stars' => 5,
    'name' => 'Sander',
    'message' => 'eSIM werkte perfect in Albanië, snel en betrouwbaar.',
  ],
  [
    'stars' => 5,
    'name' => 'Niels',
    'message' => 'Met GoSim videocalls in het buitenland zonder problemen.',
  ],
  [
    'stars' => 4,
    'name' => 'Leticia',
    'message' => 'Goede prijs voor 10GB in Turkije, 42 dagen geldig.',
  ],
  [
    'stars' => 5,
    'name' => 'Jacques',
    'message' => 'Super handig, geen gedoe met meerdere simkaarten in de Balkan.',
  ],
  [
    'stars' => 4,
    'name' => 'Marij',
    'message' => 'Eerste keer een probleem, maar klantenservice loste het snel op.',
  ],
  [
    'stars' => 5,
    'name' => 'Kaar',
    'message' => 'Gemakkelijk te installeren eSIM, werkte perfect tijdens mijn reis.',
  ],
  [
    'stars' => 4,
    'name' => 'Yvonne',
    'message' => 'Belminuten en internetdata waren goed, maar geen resultaat.',
  ],
  [
    'stars' => 5,
    'name' => 'Ruud',
    'message' => 'Geweldig, het werkte zoals beloofd!',
  ],
  [
    'stars' => 5,
    'name' => 'Frank',
    'message' => 'Tevreden over GoSim, goede support en internet werkte goed.',
  ],
  [
    'stars' => 5,
    'name' => 'Janette',
    'message' => 'Uitstekende service, probleem snel opgelost met nieuwe sim.',
  ],
  [
    'stars' => 4,
    'name' => 'Jeffrey',
    'message' => 'Bij aankomst in Maleisië werkte de eSIM meteen.',
  ],
  [
    'stars' => 5,
    'name' => 'Willy',
    'message' => 'Super contact en service, ik gebruik Gosim opnieuw!',
  ],
  [
    'stars' => 4,
    'name' => 'Noelle',
    'message' => 'Prima ervaring, handig voor backpackers in verschillende landen.',
  ],
  [
    'stars' => 5,
    'name' => 'Emma',
    'message' => 'Eerste keer eSIM, werkte perfect voor Google Maps!',
  ],
  [
    'stars' => 5,
    'name' => 'Ingrid',
    'message' => 'GoSim hielp ons de sim werkend te krijgen in Zuid-Afrika.',
  ],
  [
    'stars' => 4,
    'name' => 'Leo',
    'message' => 'Canada sim werkte niet direct, maar goede helpdesk.',
  ],
  [
    'stars' => 5,
    'name' => 'Wil',
    'message' => 'Kortdurend abonnement werkte prima, goede verbinding gehad.',
  ],
  [
    'stars' => 5,
    'name' => 'Wilma',
    'message' => 'Eenvoudig te installeren, goed bereik tijdens reizen naar Turkije!',
  ],
  [
    'stars' => 5,
    'name' => 'Goedele',
    'message' => 'E-sim downloaden, eenvoudig en snel geregeld!',
  ],
  [
    'stars' => 5,
    'name' => 'M. Jansen',
    'message' => 'Eenvoudig, goede service, volgende keer weer!',
  ],
];
