<?php

//This file is automatically generated. Do not modify.

return [
  'days' => 'dagen',
  'buy_plan' => 'Koop nu!',
  'perks' => [
    'instant' => 'Directe levering',
    'advanced_self_service' => 'Geavanceerd self-serviceportaal',
    '247_support' => '24/7 live chat ondersteuning',
    'prepaid' => 'Prepaid, geen voorwaarden verbonden',
    'no_roaming' => 'Geen roamingkosten',
  ],
  'local_for' => 'Lokale eSIM\'s voor :countryName',
  'not_available_yet' => 'We bieden momenteel geen eSIMs voor dit land aan.',
  'not_available_yet_contact_us' => 'We werken hard om onze wereldwijde dekking uit te breiden. Als je in de tussentijd geïnteresseerd bent in eSIMs voor dit land, neem dan contact met ons op.',
  'top_plan' => 'Meest populair',
  'all_features' => 'Alle functies',
  'features' => [
    'feature_one' => 'Hotspot mogelijk',
    'feature_two' => 'Dekking over alle nationale netwerken',
    'feature_three' => 'Eenvoudige opwaardering in uw persoonlijke portal',
  ],
  'buy_now' => 'Koop nu',
  'starting_from' => 'Beginnen vanaf',
  'choose_destination' => 'Vind een bestemming',
  'how_esim_works' => [
    'title' => 'Hoe eSIM werkt',
    'subtitle' => 'Aan de slag met eSIM is eenvoudig! Volg deze eenvoudige stappen om verbonden te blijven.',
    'steps' => [
      [
        'title' => 'Koop uw eSIM',
        'description' => 'Kies je bestemming, kies een bundel die aan je databehoeften voldoet, en voltooi je aankoop.',
        'image' => '/images/howesimworks/1.png',
      ],
      [
        'title' => 'Ontvang uw eSIM',
        'description' => 'Ontvang direct uw eSIM QR-code in uw e-mail. Klaar voor gebruik meteen.',
        'image' => '/images/howesimworks/2.png',
      ],
      [
        'title' => 'Activeer en Verbind',
        'description' => 'Scan de QR-code, activeer je eSIM en geniet van snelle, betrouwbare data waar je ook reist.',
        'image' => '/images/howesimworks/3.png',
      ],
    ],
  ],
  'sub_description' => 'Kies je bundel hieronder en geniet van naadloze connectiviteit in :countryName op de beste netwerken tegen de beste prijs.',
];
