<?php

//This file is automatically generated. Do not modify.

return [
  'days' => 'dagen',
  'buy_plan' => 'Koop nu!',
  'perks' => [
    'instant' => 'Onmiddellijke levering',
    'advanced_self_service' => 'Geavanceerd selfservic portaal',
    '247_support' => '24/7 live chat ondersteuning',
    'prepaid' => 'Prepaid, geen verplichtingen',
    'no_roaming' => 'Geen roamingkosten',
  ],
  'local_for' => 'Lokale eSIMs voor :countryName',
  'not_available_yet' => 'We bieden momenteel geen eSIMs voor dit land aan.',
  'not_available_yet_contact_us' => 'We werken hard om onze wereldwijde dekking uit te breiden. Als je in de tussentijd geïnteresseerd bent in eSIMs voor dit land, neem dan contact met ons op.',
];
