<?php

//This file is automatically generated. Do not modify.

return [
  'title' => 'eSIM-service - Prepaid virtuele SIM-kaarten voor reizigers - :site_name',
  'description' => 'eSIM-service ⏩ Prepaid digitale SIM-kaarten voor toerisme en zaken ⏩ Standaard en onbeperkte, lokale en wereldwijde mobiele dataplannen ⏩ Geen contracten ✅ Geen verborgen roamingkosten en -vergoedingen ✅ - :site_name',
  'keywords' => 'eSIM, eSIM-service, eSIM-kaart, eSIM-gegevens, eSIM-gegevensplan, eSIM-gegevensplannen, eSIM-gegevensplan voor reizigers, eSIM-gegevensplan voor toeristen, eSIM-gegevensplan voor bedrijven, eSIM-gegevensplan voor reizen, eSIM-gegevensplan voor Europa, eSIM-gegevensplan voor de VS, eSIM-gegevensplan voor Azië, eSIM-gegevensplan voor Afrika, eSIM-gegevensplan voor Australië, eSIM-gegevensplan voor Zuid-Amerika, eSIM-gegevensplan voor Noord-Amerika, eSIM-gegevensplan voor het Midden-Oosten, eSIM-gegevensplan voor Rusland, eSIM-gegevensplan voor China, eSIM-gegevensplan voor India, eSIM-gegevensplan voor Japan',
  'routes' => [
    'home' => [
      'title' => 'eSIM-service - Prepaid virtuele SIM-kaarten voor reizigers - :site_name',
      'description' => 'eSIM-service ⏩ Prepaid digitale SIM-kaarten voor toerisme en zaken ⏩ Standaard en onbeperkte, lokale en wereldwijde mobiele dataplannen ⏩ Geen contracten ✅ Geen verborgen roamingkosten en -vergoedingen ✅ - :site_name',
    ],
    'about' => [
      'title' => 'Over ons - :site_name',
      'description' => 'Over ons ⏩ Prepaid digitale SIM-kaarten voor toerisme en zaken ⏩ Standaard en onbeperkte, lokale en wereldwijde mobiele dataplannen ⏩ Geen contracten ✅ Geen verborgen roamingkosten en -vergoedingen ✅ - :site_name',
    ],
    'supported-devices' => [
      'title' => 'Ondersteunde Apparaten - :site_name',
      'description' => 'Ondersteunde Apparaten ⏩ Prepaid digitale SIM-kaarten voor toerisme en zaken ⏩ Standaard en onbeperkte, lokale en wereldwijde mobiele dataplannen ⏩ Geen contracten ✅ Geen verborgen roamingkosten en -vergoedingen ✅ - :site_name',
    ],
    'esim-bundle-per-country' => [
      'title' => 'eSIM :countryName - :site_name',
      'description' => 'eSIM :countryName ⏩ Prepaid digitale SIM-kaarten voor toerisme en zaken ⏩ Standaard en onbeperkte, lokale en wereldwijde mobiele dataplannen ⏩ Geen contracten ✅ Geen verborgen roamingkosten en -vergoedingen ✅ - :site_name',
    ],
  ],
];
