<?php

//This file is automatically generated. Do not modify.

return [
  'title' => 'Meist meist',
  'subtitle' => 'Navigeeri maailmas ilma piirideta koos meiega. Me oleme sinu lõplik partner, kes hoiab sind ühenduses, olenemata sellest, kuhu su kirg sind viib.',
  'our_team' => 'Meie meeskond',
  'our_team_subtitle' => 'Usume, et anname reisijatele võimekuse usaldusväärse ja taskukohase globaalsete andmeühenduste kaudu. Meie mitmekesine meeskond on ühtne, et luua kõigile liikuvatele inimestele rohkem ühendatud ja ligipääsetav maailm.',
  'why_us' => 'Miks valida meid',
  'why_us_subtitle' => 'Me oleme uhked oma usaldusväärse teenuse, konkurentsivõimeliste hindade ja kliendikeskse lähenemise üle. Teie rahulolu on meie kõrgeim prioriteet.',
  'why_us_reasons' => [
    [
      'title' => 'Paindlikud plaanid, mis on loodud teie reisivajaduste jaoks',
      'subtitle' => 'Valige erinevate riikide ja piirkondade jaoks kohandatud taskukohaste pakettide hulgast. Anname teile paindlikkuse valida ideaalne andmepakett, nii et maksate ainult selle eest, mida vajate, ilma peidetud kuludeta.',
      'image' => '/images/whyus/nlo2.png',
    ],
    [
      'title' => 'Otsene aktiveerimine, füüsilisi SIM-kaarte ei vajata',
      'subtitle' => 'Füüsiliste SIM-kaartide vahetamise päevad on möödas. Meie juures saad eSIM-i otse e-posti teel ja see saab aktiveeritud mõne minutiga. Lihtsalt skaneeri QR-kood ja oled valmis ühenduma.',
      'image' => '/images/whyus/nlo3.png',
    ],
  ],
  'contact' => 'Võta meiega ühendust',
  'contact_subtitle' => 'Me oleme siin, et teid aidata. Kui teil on küsimusi või vajate abi, palun võtke meiega ühendust.',
];
