<?php

//This file is automatically generated. Do not modify.

return [
  'title' => 'Kõik meie sihtkohad',
  'subtitle' => 'Kuhu iganes te lähete, meil on teie jaoks olemas eSIM-id iga sihtkoha jaoks. Valige oma sihtkoht allpool, et alustada.',
];
