<?php

//This file is automatically generated. Do not modify.

return [
  'title' => 'Toetatud seadmed',
  'subtitle' => 'Toetame laia valikut seadmeid. Kontrollige, kas teie seade on alloleval loetelul. Seadmed on korraldatud tootja järgi.',
  'models_below' => 'Toetatud mudelid on loetletud allpool.',
];
