<?php

//This file is automatically generated. Do not modify.

return [
  [
    'question' => 'Mis on eSIM ja kuidas ma saan kasutada :organisationName?',
    'answer' => 'eSIM, või sisseehitatud SIM, on digitaalne SIM-kaart, mis võimaldab kasutajatel aktiveerida ja hallata mitmeid mobiiliplane ühel seadmel ilma füüsilise SIM-kaardita. eSIM-i abil saate hõlpsasti vahetada mobiilioperaatoreid ja nautida selliseid funktsioone nagu lisaliini lisamine rahvusvaheliseks reisiks või eraldi andmepakettide säilitamine isiklikuks ja äriliseks kasutamiseks.',
  ],
  [
    'question' => 'Kuidas aktiveerida eSIM mobiilset internetti :organisationName\'iga?',
    'answer' => 'Internetiühenduse loomiseks :organisationName eSIM-i abil järgige neid samme: 1. Minge oma mobiilse andmeside seadistustesse. 2. Lülitage sisse :organisationName mobiilne liin. 3. Aktiveerige andmevahetus. 4. Valige :organisationName Interneti liin oma peamiseks ühenduseks. *Vältige valiku "Kustuta andmepakett" valimist, kuna see kustutab teie eSIM profiili.*',
  ],
  [
    'question' => 'Kas ma saan teha telefonikõnesid või saata tekstisõnumeid?',
    'answer' => ':organisationName\'i ettemakstud eSIM plaanid on mõeldud ainult andmete kasutamiseks ja ei sisalda traditsiooniliste kõnede või SMS-sõnumite jaoks mobiiltelefoni numbrit. Soovitame kasutada VoIP rakendusi nagu Facebook Messenger, WhatsApp, Viber, Telegram või Skype, et olla ülemaailmselt ühenduses ilma tavalise rahvusvahelise SIM-kaardi vajaduseta.',
  ],
  [
    'question' => 'Kas eSIM-kaarti saab uuesti kasutada?',
    'answer' => 'Iga eSIM-i QR-kood on ainulaadne ja seda saab kasutada ainult ühel seadmel. Kui eSIM-i profiil on kustutatud, ei saa QR-koodi sama või teise seadme peal uuesti kasutada, tagades turvalisuse ja eksklusiivsuse.',
  ],
  [
    'question' => 'Millal algab eSIM mobiilsete andmepakettide kestus?',
    'answer' => 'Teie eSIM andmeside plaani kestus algab kohe pärast seda, kui teie seade esmakordselt ühendub mobiilsidevõrguga, kus on eSIM.',
  ],
  [
    'question' => 'Kas ma saan pikendada oma praeguse eSIM mobiilse andmeplaani aegumiskuupäeva?',
    'answer' => 'Loomulikult! Sa saad mitu push-teadet, kui oled oma paketist peaaegu välja saanud. Sa saad oma isikliku portaali kaudu hõlpsasti lisada.',
  ],
  [
    'question' => 'Kas ma saan kasutada tetheringut või Isiklikku Hotspoti :organisationName\'iga?',
    'answer' => 'Jah, saate jagada oma mobiilset andmesidet teiste seadmetega oma :organisationName-eSIM-i kaudu. Lihtsalt installige :organisationName-eSIM oma seadmesse ja aktiveerige isiklik hotspot oma seadete kaudu. See funktsioon on kaasatud lisakuludeta, kuid palun pange tähele, et ühendatud andmete kasutamine arvatakse teie plaanist maha.',
  ],
  [
    'question' => 'Kas ma saan hoida oma isikliku sõnumirakenduse numbreid, kasutades :organisationName eSIM-i?',
    'answer' => 'Jah, saate jätkata oma WhatsAppi, Snapchati, Telegrami ja teiste sõnumirakenduste kasutamist koos oma :organisationName eeltasu eSIM-iga ilma probleemideta.',
  ],
  [
    'question' => 'Kuidas ma saan oma eSIM-i uuele telefonile üle kanda?',
    'answer' => 'Enne ülekande tegemist veenduge, et teie uus nutitelefon toetab eSIM-tehnoloogiat. Võtke ühendust meie tugimeeskonnaga, et luua uus eSIM-profiil, seejärel logige sisse oma :organisationName kontole uuel seadmel, et installida QR-kood. Veenduge, et kinnitate, et kasutate täpsete seadistuste värskendamiseks erinevat seadet.',
  ],
  [
    'question' => 'Kas on lepingud nagu traditsiooniliste eSIM-teenusepakkujate omad?',
    'answer' => 'Ei, :organisationName ei nõua, et te allkirjastaksite lepingud. Saate oma eSIM-kaardi aktiveerida või deaktiveerida vastavalt oma plaanidele. Meil on hea meel teid aidata.',
  ],
  [
    'question' => 'Milline on erinevus :organisationName eSIM-i ja füüsiliste mobiilioperaatorite tavaliste rändeteenuste andmepakettide vahel?',
    'answer' => ':organisationName pakub lepinguvabasid andmepakette ilma varjatud rändlustasudeta. Sa maksad ainult kasutatud andmete eest, sõltuvalt valitud paketist, muutes selle sageli majanduslikumaks valikuks.',
  ],
  [
    'question' => 'Miks on minu andmeedastuskiirus aeglane?',
    'answer' => 'Andmeside kiirus võib olla mõjutatud erinevatest teguritest, sealhulgas teie nutitelefoni tüübist, võrgu tehnoloogiast, kasutatavatest veebisaitidest või rakendustest ning päevaajast. Lisaks võivad kiirused varieeruda sõltuvalt riigi võrgu infrastruktuurist. Kui te kogete aeglaseid kiirusid, proovige oma telefoni taaskäivitada ja jagage meiega kõiki kiirusetulemusi, eriti võrreldes :LTE režiimi lubamisega ja ilma.',
  ],
  [
    'question' => 'Kuidas ma saan oma pakette vaadata?',
    'answer' => 'Saate jälgida oma allesjäänud andmeid ja piire meie kliendipaneelis.',
  ],
  [
    'question' => 'Mis teeb :organisationName erinevaks teistest eSIM teenustest?',
    'answer' => ':organisationName paistab silma kohalike operaatoritega koostööd tehes enam kui 200 riigis, pakkudes kulutõhusaid andmepakette ilma vahendajateta. Me pakume tugevat katvust ja lihtsat aktiveerimisprotsessi. :organisationName on ideaalne reisijatele, kes otsivad mobiilse interneti lahendusi.',
  ],
];
