<?php

//This file is automatically generated. Do not modify.

return [
  'title' => 'Püsi veebis ühenduses :countryName',
  'subtitle' => 'Reisimine :countryName? Püsige ühenduses meie eSIM-iga, tagades, et teil on koheselt internetiühendus saabumisel.',
  'features' => [
    [
      'title' => 'Usaldusväärselt ja kiiresti veebis :countryName\'s',
      'subtitle' => ':countryName on kaunis sihtkoht, millel on elavad moodsad linnad ja hingematvad loodusmaastikud. Parandage oma reisikogemust meie eSIM-iga, tagades, et olete kohale jõudes kohe ühendatud. 
        Ütlege hüvasti kohaliku SIM-kaardi otsimise või kulukate andmeside rändlusteenustega. Meie eSIM-iga naudite sujuvat juurdepääsu 4G/5G võrkudele riigi parimatelt teenusepakkujatelt, hoides teid internetis olenemata sellest, kuhu teie reis viib.',
      'image' => 'images/features/feature1.jpg',
    ],
    [
      'title' => 'Püsi ühenduses lähedastega',
      'subtitle' => 'Meie eSIM on loodud sujuvaks internetiühenduseks, hoides teid ühenduses kõigi teie veebitegevustega ilma uue telefoninumbri vajaduseta. Looge hõlpsasti hotspot, et jagada oma ühendust kaasreisijate või perega, funktsioon, mida teised teenusepakkujad sageli blokeerivad, kuid mida meie täielikult toetame. Nautige eSIM-ühilduvate seadmete kohest ühenduvust, tagades, et teie ja teie lähedased püsivad veebis igal ajal ja igas kohas. Palun kinnitage, kas teie seade toetab eSIM-i, et tagada, et olete meie internetipakkumiste jaoks valmis. Palun pange tähele, et kõned ja sõnumid ei ole meie eSIM-i puhul toetatud.',
      'image' => 'images/features/feature2.jpg',
    ],
  ],
];
