<?php

//This file is automatically generated. Do not modify.

return [
  'all_rights_reserved' => 'Kõik õigused kaitstud.',
  'foreign_currencies_for_reference_only' => 'Välismaised valuutad on ainult viitamiseks. Arveldamine toimub eurodes.',
];
