<?php

//This file is automatically generated. Do not modify.

return [
  'from' => ':price/GB',
  'title' => 'Ühenda globaalselt meie eSIMidega',
  'subtitle' => 'Uurige meie eSIM pakette ja püsige ühenduses, kus iganes te olete!',
  'search_destination' => 'Leia sihtkohta',
  'show_all_esim' => 'Kuva kõik eSIM plaanid',
  'how_it_works' => 'Kuidas see töötab?',
  'steps' => [
    [
      'title' => 'Samm 1',
      'description' => 'Kontrollige, kas teie seade on meie ühilduvuse loendis eSIM-iga ühilduv.',
    ],
    [
      'title' => 'Samm 2',
      'description' => 'Vali oma sihtkoht ja soovitud eSIM andmepakett',
    ],
    [
      'title' => 'Samm 3',
      'description' => 'Osta eSIM kaart, mis sobib kõige paremini teie vajadustega',
    ],
    [
      'title' => 'Samm 4',
      'description' => 'Teie eSIM saadetakse automaatselt. Järgige oma e-kirjas olevaid juhiseid.',
    ],
    [
      'title' => 'Samm 5',
      'description' => 'Installige oma eSIM profiil ja nautige oma reisi!',
    ],
  ],
  'supported_networks' => 'Toetatud võrgu pakkujad',
  'supported_networks_description' => 'Me töötame tihedalt koos usaldusväärsete turuliidrite ühenduvuse, meedia ja tehnoloogia brändidega üle kogu maailma.',
  'and_many_more' => 'ja palju muud...',
  'user_reviews' => 'Mida meie rahulolevad kasutajad ütlevad',
  'user_reviews_subtitle' => 'Vaata, miks reisijad üle kogu maailma usaldavad meie eSIM-i sujuvaks ja usaldusväärseks ühenduseks liikvel olles.',
  'faq' => 'Korduma kippuvad küsimused',
  'popular_destinations' => 'Populaarsed sihtkohad',
  'popular_destinations_description' => 'Avasta meie populaarseimad eSIM sihtkohad ja jää ühendatuks, olenemata sellest, kuhu lähed!',
  'see_all_destinations' => 'Vaata kõiki sihtkohti',
];
