<?php

//This file is automatically generated. Do not modify.

return [
  'home' => 'Kodu',
  'supported-devices' => 'Toetatud seadmed',
  'destinations' => 'Kõik sihtkohad',
  'about' => 'Teave',
  'contact' => 'Kontakt',
  'portal_link' => 'Minu Portaal',
];
