<?php

//This file is automatically generated. Do not modify.

return [
  'days' => 'päevad',
  'buy_plan' => 'Osta nüüd!',
  'perks' => [
    'instant' => 'Otsene kohaletoimetamine',
    'advanced_self_service' => 'Kasutajateeninduse arenenud portaal',
    '247_support' => '24/7 reaalajas vestluse tugi',
    'prepaid' => 'Eelnevalt makstud, ilma tingimusteta',
    'no_roaming' => 'Ei rändlustasusid',
  ],
  'local_for' => 'Kohalikud eSIM-id :countryName jaoks',
  'not_available_yet' => 'Me ei paku praegu eSIM-e selle riigi jaoks.',
  'not_available_yet_contact_us' => 'Me töötame kõvasti, et laiendada meie globaalset katvust. Kui te olete selle riigi eSIMide vastu huvitatud, võtke meiega palun ühendust.',
  'top_plan' => 'Kõige populaarsem',
  'all_features' => 'Kõik funktsioonid',
  'features' => [
    'feature_one' => 'Võimalik kuum koht',
    'feature_two' => 'Kattevõrkude katvus kõikides riikides',
    'feature_three' => 'Lihtne uuendus teie isiklikus portaalis',
  ],
  'buy_now' => 'Osta nüüd',
  'starting_from' => 'Alustades',
  'choose_destination' => 'Leia sihtkoht',
  'how_esim_works' => [
    'title' => 'Kuidas eSIM töötab',
    'subtitle' => 'eSIM-iga alustamine on lihtne! Järgige neid lihtsaid samme, et olla ühenduses.',
    'steps' => [
      [
        'title' => 'Osta oma eSIM',
        'description' => 'Vali oma sihtkoht, vali pakett, mis vastab sinu andmevajadustele, ja lõpeta oma ost.',
        'image' => '/images/howesimworks/1.png',
      ],
      [
        'title' => 'Saada oma eSIM',
        'description' => 'Saate oma eSIM QR-koodi otse oma e-posti. Valmis koheseks kasutamiseks.',
        'image' => '/images/howesimworks/2.png',
      ],
      [
        'title' => 'Aktiveeri ja Ühenda',
        'description' => 'Skaneeri QR-kood, aktiveeri oma eSIM ja naudi kiiret, usaldusväärset andmesideühendust igal pool, kuhu reisid.',
        'image' => '/images/howesimworks/3.png',
      ],
    ],
  ],
  'sub_description' => 'Vali oma pakett allpool ja naudi sujuvat ühendust :countryName parimates võrkudes parima hinnaga.',
];
