<?php

//This file is automatically generated. Do not modify.

return [
  'title' => 'eSIM teenus - Eelmakstud virtuaalsed SIM-kaardid reisijatele - :site_name',
  'description' => 'eSIM teenus ⏩ Eelmakstud digitaalsed SIM-kaardid turismi ja äri jaoks ⏩ Standard- ja piiramatud, kohalikud ja globaalsete mobiilside andmeside plaanid ⏩ Ei mingeid lepinguid ✅ Ei varjatud rändlustasud ja -kulud ✅ - :site_name',
  'keywords' => 'eSIM, eSIM teenus, eSIM kaart, eSIM andmed, eSIM andmeplaan, eSIM andmeplaanid, eSIM andmeplaan reisijatele, eSIM andmeplaan turistidele, eSIM andmeplaan äri jaoks, eSIM andmeplaan reisimiseks, eSIM andmeplaan Euroopas, eSIM andmeplaan Ameerikas, eSIM andmeplaan Aasias, eSIM andmeplaan Aafrikas, eSIM andmeplaan Austraalias, eSIM andmeplaan Lõuna-Ameerikas, eSIM andmeplaan Põhja-Ameerikas, eSIM andmeplaan Lähis-Idas, eSIM andmeplaan Venemaal, eSIM andmeplaan Hiinas, eSIM andmeplaan Indias, eSIM andmeplaan Jaapanis',
  'routes' => [
    'home' => [
      'title' => 'eSIM teenus - Eelmakstud virtuaalsed SIM-kaardid reisijatele - :site_name',
      'description' => 'eSIM teenus ⏩ Eelmakstud digitaalsed SIM-kaardid turismi ja äri jaoks ⏩ Standard- ja piiramatu, kohalike ja globaalsete mobiiltelefoni andmepaketid ⏩ Ilma lepinguteta ✅ Pole varjatud rändlustasusid ja -makse ✅ - :site_name',
    ],
    'about' => [
      'title' => 'Meist meist - :site_name',
      'description' => 'Meist ⏩ Eelnevalt makstud digitaalsed SIM-kaardid turismi ja äri jaoks ⏩ Standard- ja piiramatud, kohalikud ja globaalsete mobiiltelefoni andmeside plaanid ⏩ Ilma lepinguteta ✅ Ei mingeid varjatud rändlustasusid ja -tasusid ✅ - :site_name',
    ],
    'supported-devices' => [
      'title' => 'Toetatud seadmed - :site_name',
      'description' => 'Toetatud seadmed ⏩ Eelmakstud digitaalsed SIM-kaardid turismi ja äri jaoks ⏩ Standard- ja piiramatu, kohalike ja globaalsete mobiiltelefoni andmepaketid ⏩ Ei mingeid lepinguid ✅ Ei mingeid varjatud rändlustasusid ja tasusid ✅ - :site_name',
    ],
    'esim-bundle-per-country' => [
      'title' => 'Taskukohased kohalikud eSIM pakkumised :countryName - :site_name',
      'description' => 'Taskukohased kohalikud eSIM pakkumised :countryName ⏩ Eelmakstud digitaalsed SIM-kaardid turismi ja äri jaoks ⏩ Standard- ja piiramatu, kohalikud ja globaalsete mobiilsete andmepaketid ⏩ Ilma lepinguteta ✅ Ilma varjatud rändlustasude ja tasudeta ✅ - :site_name',
    ],
  ],
];
