<?php

//This file is automatically generated. Do not modify.

return [
  'title' => 'eSIM-teenus - Eelmakstud virtuaalsed SIM-kaardid reisijatele - :site_name',
  'description' => 'eSIM-teenus ⏩ Eelmaksetavad digitaalsed SIM-kaardid turismi ja äri jaoks ⏩ Standard- ja piiramatu, kohalike ja globaalsete mobiilsete andmeplaanide ⏩ Ilma lepinguteta ✅ Ilma varjatud rändlustasudeta ja -tasudeta ✅ - :site_name',
  'keywords' => 'eSIM, eSIM-teenus, eSIM-kaart, eSIM-andmed, eSIM-andmeplaan, eSIM-andmeplaanid, eSIM-andmeplaan reisijatele, eSIM-andmeplaan turistidele, eSIM-andmeplaan ettevõtetele, eSIM-andmeplaan reisimiseks, eSIM-andmeplaan Euroopas, eSIM-andmeplaan Ameerikas, eSIM-andmeplaan Aasias, eSIM-andmeplaan Aafrikas, eSIM-andmeplaan Austraalias, eSIM-andmeplaan Lõuna-Ameerikas, eSIM-andmeplaan Põhja-Ameerikas, eSIM-andmeplaan Lähis-Idas, eSIM-andmeplaan Venemaal, eSIM-andmeplaan Hiinas, eSIM-andmeplaan Indias, eSIM-andmeplaan Jaapanis',
  'routes' => [
    'home' => [
      'title' => 'eSIM-teenus - Eelmakstud virtuaalsed SIM-kaardid reisijatele - :site_name',
      'description' => 'eSIM-teenus ⏩ Eelmakset digitaal SIM-kaardid turismi ja äri jaoks ⏩ Standard ja piiramatud, kohalikke ja globaalseid mobiilseid andmepakette ⏩ Ei lepinguid ✅ Ei varjatud rändlustasud ja -tasud ✅ - :site_name',
    ],
    'about' => [
      'title' => 'Meist - :site_name',
      'description' => 'Meist ⏩ Eelne prepaid digitaal SIM-kaardid turismi ja äri jaoks ⏩ Standard ja piiramatu, kohalikke ja globaalne mobiilse andmeside plaanid ⏩ Ei lepingud ✅ Ei varjatud rändlustasud ja -tasud ✅ - :site_name',
    ],
    'supported-devices' => [
      'title' => 'Toetatud seadmed - :site_name',
      'description' => 'Toetatud seadmed ⏩ Eelmakstud digitaalsed SIM-kaardid turismi ja äri jaoks ⏩ Standard- ja piiramatu, kohalike ja globaalsete mobiilsete andmeplaanide ⏩ Ei mingeid lepinguid ✅ Ei mingeid varjatud rändlustasusid ja -tasusid ✅ - :site_name',
    ],
    'esim-bundle-per-country' => [
      'title' => 'eSIM :countryName - :site_name',
      'description' => 'eSIM :countryName ⏩ Eelkaardid digitaalne SIM-kaardid turismi ja äri jaoks ⏩ Standard ja piiramatu, kohalikke ja globaalseid mobiilseid andmepakette ⏩ Ei lepingud ✅ Ei varjatud rändlustasud ja -tasud ✅ - :site_name',
    ],
  ],
];
