<?php

//This file is automatically generated. Do not modify.

return [
  'Rens' => [
    'role' => 'Kaasutaja',
    'image' => '/images/team/rens.png',
  ],
  'Luuk' => [
    'role' => 'Kaasutaja',
    'image' => '/images/team/luuk.png',
  ],
  'Fleur' => [
    'role' => 'Klienditugi',
    'image' => '/images/team/fleur.png',
  ],
  'Patrick' => [
    'role' => 'Arendaja',
    'image' => '/images/team/patrick.png',
  ],
];
