<?php

//This file is automatically generated. Do not modify.

return [
  'title' => '关于我们',
  'subtitle' => '与我们一起无国界地探索世界。我们是您终极的合作伙伴，让您无论身在何处都能保持连接，随心所欲。',
  'our_team' => '我们的团队',
  'our_team_subtitle' => '我们相信赋予旅行者可靠且实惠的全球数据连接能力。我们多元化的团队团结一致，致力于为每一个出行的人创造一个更加互联和可及的世界。',
  'why_us' => '为什么选择我们',
  'why_us_subtitle' => '我们为我们可靠的服务、具有竞争力的价格和以客户为导向的方法感到自豪。您的满意是我们的最高优先事项。',
  'why_us_reasons' => [
    [
      'title' => '为您的旅行需求设计的灵活计划',
      'subtitle' => '从适合不同国家和地区的一系列实惠套餐中进行选择。我们为您提供灵活性，以选择完美的数据计划，因此您只需为所需的内容付费，没有隐藏费用。',
      'image' => '/images/whyus/nlo2.png',
    ],
    [
      'title' => '直接激活，无需物理SIM卡',
      'subtitle' => '更换实体SIM卡的日子已经结束。通过我们，您的eSIM将直接通过电子邮件发送，并且可以在几分钟内激活。只需扫描二维码，您就可以连接。',
      'image' => '/images/whyus/nlo3.png',
    ],
  ],
  'contact' => '联系我们',
  'contact_subtitle' => '我们在这里帮助您。如果您有任何问题或需要帮助，请联系我们。',
];
