<?php

//This file is automatically generated. Do not modify.

return [
  [
    'question' => '什么是eSIM，我该如何使用:organisationName？',
    'answer' => 'eSIM（嵌入式SIM）是一种数字SIM卡，允许用户在一台设备上激活和管理多个移动计划，而无需物理SIM卡。使用eSIM，您可以轻松切换移动服务提供商，并享受诸如为国际旅行添加额外线路或为个人和商务使用维护独立数据计划等功能。',
  ],
  [
    'question' => '如何使用:organisationName激活eSIM移动互联网？',
    'answer' => '要使用 :organisationName eSIM 连接互联网，请按照以下步骤操作：1. 转到您的移动数据设置。2. 打开 :organisationName 移动线路。3. 激活数据漫游。4. 将 :organisationName Internet 线路选择为您的主要连接。*避免选择“移除数据计划”选项，因为这将删除您的 eSIM 配置文件。*',
  ],
  [
    'question' => '我可以拨打电话或发送短信吗？',
    'answer' => ':organisationName的预付费eSIM计划旨在仅用于数据，不包括用于传统电话或短信的手机号码。我们建议使用VoIP应用程序，如Facebook Messenger、WhatsApp、Viber、Telegram或Skype，以便在全球范围内保持联系，而无需标准国际SIM卡。',
  ],
  [
    'question' => 'eSIM卡可以重复使用吗？',
    'answer' => '每个 eSIM 的 QR 码都是唯一的，只能在一个设备上使用。一旦 eSIM 配置文件被删除，QR 码就无法在同一设备或其他设备上重复使用，从而确保安全性和独占性。',
  ],
  [
    'question' => 'eSIM移动数据计划的有效期从什么时候开始？',
    'answer' => '您的eSIM数据计划的有效期在您的设备首次连接到具有eSIM的移动网络后立即开始。',
  ],
  [
    'question' => '我可以延长我当前的eSIM移动数据计划的到期日期吗？',
    'answer' => '当然！当您快用完套餐时，您将收到多条推送通知。您可以通过您的个人门户轻松充值。',
  ],
  [
    'question' => '我可以使用共享网络或个人热点与 :organisationName 吗？',
    'answer' => '是的，您可以通过您的 :organisationName-eSIM 与其他设备共享移动数据。只需在您的设备上安装 :organisationName-eSIM 并在设置中启用个人热点。此功能无需额外费用，但请注意，使用共享数据将从您的计划中扣除。',
  ],
  [
    'question' => '我可以在使用来自:organisationName的eSIM时保留我的个人消息应用程序号码吗？',
    'answer' => '是的，您可以继续使用您的WhatsApp、Snapchat、Telegram和其他消息应用程序，与您的:organisationName 预付费eSIM一起使用，没有任何问题。',
  ],
  [
    'question' => '我如何将我的eSIM转移到新手机？',
    'answer' => '在转移之前，请确保您的新智能手机支持eSIM技术。联系我们的支持团队以创建新的eSIM配置文件，然后在新设备上登录您的:organisationName帐户以安装二维码。请确保您确认您正在使用不同的设备以便进行准确的设置更新。',
  ],
  [
    'question' => '是否有类似于传统eSIM提供商的合同？',
    'answer' => '不，:organisationName 不需要您签署合同。您可以根据自己的计划随时激活或停用您的 eSIM 卡。我们很高兴为您提供帮助。',
  ],
  [
    'question' => ':organisationName的eSIM与实体移动运营商的标准漫游数据计划有什么区别？',
    'answer' => ':organisationName 提供无合同的数据计划，没有隐藏的漫游费用。您只需为所使用的数据付费，具体取决于您选择的套餐，这通常是一个更经济的选择。',
  ],
  [
    'question' => '为什么我的数据速度慢？',
    'answer' => '数据速度可能会受到各种因素的影响，包括您拥有的智能手机类型、网络技术、您使用的网站或应用程序以及一天中的时间。此外，速度可能会根据国家的网络基础设施而有所不同。如果您遇到速度缓慢的问题，请尝试重启您的手机，并与我们分享任何速度结果，特别是启用和未启用 LTE 模式的比较。',
  ],
  [
    'question' => '我如何查看我的捆绑包？',
    'answer' => '您可以在我们的客户面板中跟踪您剩余的数据和限制。',
  ],
  [
    'question' => ':organisationName与其他eSIM服务有什么不同？',
    'answer' => ':organisationName通过与200多个国家的本地运营商合作脱颖而出，提供无中介的高性价比数据套餐。我们提供强大的覆盖范围和简单的激活流程。:organisationName非常适合寻找移动互联网解决方案的旅行者。',
  ],
];
