<?php

//This file is automatically generated. Do not modify.

return [
  'title' => '在:countryName在线保持连接',
  'subtitle' => '前往:countryName？使用我们的eSIM保持连接，确保您在抵达时即可获得即时互联网访问。',
  'features' => [
    [
      'title' => '在:countryName中可靠且快速在线',
      'subtitle' => ':countryName 是一个美丽的目的地，拥有充满活力的现代城市和令人叹为观止的自然风光。使用我们的 eSIM 来提升您的旅行体验，确保您在抵达时立即保持连接。
        告别寻找当地 SIM 卡或处理昂贵数据漫游的麻烦。使用我们的 eSIM，您将享受来自该国顶级服务提供商的无缝 4G/5G 网络访问，让您在旅途中随时在线。',
      'image' => 'images/features/feature1.jpg',
    ],
    [
      'title' => '与亲人保持联系',
      'subtitle' => '我们的eSIM旨在提供无缝的互联网连接，让您在所有在线活动中保持连接，无需新的电话号码。轻松创建热点，与其他旅行者或家人分享您的连接，这一功能通常被其他服务提供商阻止，但我们完全支持。享受在eSIM兼容设备上即时连接的便利，确保您和您的亲人随时随地在线。请确认您的设备是否支持eSIM，以确保您准备好使用我们的互联网服务。请注意，使用我们的eSIM不支持拨打电话和发送短信。',
      'image' => 'images/features/feature2.jpg',
    ],
  ],
];
