<?php

//This file is automatically generated. Do not modify.

return [
  'from' => ':price/GB',
  'title' => '通过我们的eSIM全球连接',
  'subtitle' => '探索我们的eSIM套餐，无论您身在何处，都能保持连接！',
  'search_destination' => '找到一个目的地',
  'show_all_esim' => '显示所有eSIM计划',
  'how_it_works' => '它是如何工作的？',
  'steps' => [
    [
      'title' => '第一步',
      'description' => '在我们的兼容性列表中检查您的设备是否支持eSIM。',
    ],
    [
      'title' => '步骤 2',
      'description' => '选择您的目的地和所需的eSIM数据计划',
    ],
    [
      'title' => '步骤 3',
      'description' => '购买最适合您需求的eSIM卡',
    ],
    [
      'title' => '步骤 4',
      'description' => '您的 eSIM 将自动交付。请按照您电子邮件中的说明操作。',
    ],
    [
      'title' => '步骤 5',
      'description' => '安装您的eSIM配置文件，享受您的旅行！',
    ],
  ],
  'supported_networks' => '支持的网络提供商',
  'supported_networks_description' => '我们与全球值得信赖的市场领先连接、媒体和技术品牌紧密合作。',
  'and_many_more' => '和更多...',
  'user_reviews' => '我们满意的用户说',
  'user_reviews_subtitle' => '了解世界各地的旅行者为何依赖我们的eSIM，以便在旅途中实现无缝、可靠的连接。',
  'faq' => '常见问题解答',
  'popular_destinations' => '热门目的地',
  'popular_destinations_description' => '发现我们最受欢迎的eSIM目的地，无论你去哪里都能保持连接！',
  'see_all_destinations' => '查看所有目的地',
];
