<?php

//This file is automatically generated. Do not modify.

return [
  'home' => '家',
  'supported-devices' => '支持的设备',
  'destinations' => '所有目的地',
  'about' => '关于',
  'contact' => '联系',
  'portal_link' => '我的门户',
];
