<?php

//This file is automatically generated. Do not modify.

return [
  'days' => '天数',
  'buy_plan' => '立即购买！',
  'perks' => [
    'instant' => '直接交付',
    'advanced_self_service' => '高级自助服务门户',
    '247_support' => '24/7 在线聊天支持',
    'prepaid' => '预付，无附加条件',
    'no_roaming' => '无漫游费用',
  ],
  'local_for' => ':countryName 的本地 eSIMs',
  'not_available_yet' => '我们目前不为该国家提供eSIM。',
  'not_available_yet_contact_us' => '我们正在努力扩大我们的全球覆盖。如果您对这个国家的eSIM感兴趣，请与我们联系。',
  'top_plan' => '最受欢迎',
  'all_features' => '所有功能',
  'features' => [
    'feature_one' => '可能的热点',
    'feature_two' => '覆盖所有国家网络',
    'feature_three' => '在您的个人门户中简单升级',
  ],
  'buy_now' => '立即购买',
  'starting_from' => '开始于',
  'choose_destination' => '寻找一个目的地',
  'how_esim_works' => [
    'title' => 'eSIM是如何工作的',
    'subtitle' => '开始使用eSIM很简单！按照以下简单步骤保持连接。',
    'steps' => [
      [
        'title' => '购买您的 eSIM',
        'description' => '选择您的目的地，选择一个满足您数据需求的套餐，然后完成您的购买。',
        'image' => '/images/howesimworks/1.png',
      ],
      [
        'title' => '接收您的eSIM',
        'description' => '直接在您的电子邮件中接收您的eSIM QR码。可以立即使用。',
        'image' => '/images/howesimworks/2.png',
      ],
      [
        'title' => '激活并连接',
        'description' => '扫描二维码，激活您的eSIM，享受快速、可靠的数据，无论您去哪里旅行。',
        'image' => '/images/howesimworks/3.png',
      ],
    ],
  ],
  'sub_description' => '在 :countryName 选择您的套餐，享受最佳网络和最佳价格的无缝连接。',
];
