<?php

//This file is automatically generated. Do not modify.

return [
  'title' => 'eSIM服务 - 旅行者的预付费虚拟SIM卡 - :site_name',
  'description' => 'eSIM服务 ⏩ 旅游和商务的预付费数字SIM卡 ⏩ 标准和无限制的本地和全球移动数据计划 ⏩ 无合同 ✅ 无隐藏的漫游费用和补偿 ✅ - :site_name',
  'keywords' => 'eSIM, eSIM服务, eSIM卡, eSIM数据, eSIM数据计划, eSIM数据计划, 旅行者的eSIM数据计划, 游客的eSIM数据计划, 企业的eSIM数据计划, 旅行的eSIM数据计划, 欧洲的eSIM数据计划, 美国的eSIM数据计划, 亚洲的eSIM数据计划, 非洲的eSIM数据计划, 澳大利亚的eSIM数据计划, 南美的eSIM数据计划, 北美的eSIM数据计划, 中东的eSIM数据计划, 俄罗斯的eSIM数据计划, 中国的eSIM数据计划, 印度的eSIM数据计划, 日本的eSIM数据计划',
  'routes' => [
    'home' => [
      'title' => 'eSIM服务 - 旅行者的预付费虚拟SIM卡 - :site_name',
      'description' => 'eSIM服务 ⏩ 旅游和商务的预付费数字SIM卡 ⏩ 标准和无限制的本地和全球移动数据计划 ⏩ 无合同 ✅ 无隐藏的漫游费用和补偿 ✅ - :site_name',
    ],
    'about' => [
      'title' => '关于我们 - :site_name',
      'description' => '关于我们 ⏩ 旅游和商务的预付费数字SIM卡 ⏩ 标准和无限制的本地和全球移动数据计划 ⏩ 无合同 ✅ 无隐藏的漫游费用和补偿 ✅ - :site_name',
    ],
    'supported-devices' => [
      'title' => '支持的设备 - :site_name',
      'description' => '支持的设备 ⏩ 旅游和商务的预付费数字SIM卡 ⏩ 标准和无限制的本地和全球移动数据计划 ⏩ 无合同 ✅ 无隐藏的漫游费用和补偿 ✅ - :site_name',
    ],
    'esim-bundle-per-country' => [
      'title' => 'eSIM :countryName - :site_name',
      'description' => 'eSIM :countryName ⏩ 旅游和商务的预付费数字SIM卡 ⏩ 标准和无限制的本地和全球移动数据计划 ⏩ 无合同 ✅ 无隐藏的漫游费用和补偿 ✅ - :site_name',
    ],
  ],
];
