<?php

//This file is automatically generated. Do not modify.

return [
  'Rens' => [
    'role' => '联合创始人',
    'image' => '/images/team/rens.png',
  ],
  'Luuk' => [
    'role' => '联合创始人',
    'image' => '/images/team/luuk.png',
  ],
  'Fleur' => [
    'role' => '客户支持',
    'image' => '/images/team/fleur.png',
  ],
  'Patrick' => [
    'role' => '开发者',
    'image' => '/images/team/patrick.png',
  ],
];
