<?php

//This file is automatically generated. Do not modify.

return [
  'title' => 'Chi siamo',
  'subtitle' => 'Naviga il mondo senza confini con noi. Siamo il tuo partner ideale che ti tiene connesso ovunque la tua passione ti porti.',
  'our_team' => 'Il nostro team',
  'our_team_subtitle' => 'Crediamo nel dare potere ai viaggiatori con una connettività dati globale affidabile e accessibile. Il nostro team diversificato è unito nel creare un mondo più connesso e accessibile per tutti coloro che sono in movimento.',
  'why_us' => 'Perché scegliere noi',
  'why_us_subtitle' => 'Siamo orgogliosi del nostro servizio affidabile, dei prezzi competitivi e dell\'approccio orientato al cliente. La tua soddisfazione è la nostra massima priorità.',
  'why_us_reasons' => [
    [
      'title' => 'Piani Flessibili Progettati per le Tue Esigenze di Viaggio',
      'subtitle' => 'Scegli tra una gamma di pacchetti convenienti adattati a diversi paesi e regioni. Ti offriamo la flessibilità di selezionare il piano dati perfetto, così paghi solo per ciò di cui hai bisogno, senza costi nascosti.',
      'image' => '/images/whyus/nlo2.png',
    ],
    [
      'title' => 'Attivazione diretta, nessuna scheda SIM fisica necessaria',
      'subtitle' => 'I giorni in cui si scambiavano le schede SIM fisiche sono finiti. Con noi, la tua eSIM viene consegnata direttamente via email e può essere attivata in pochi minuti. Basta scansionare il codice QR e sei pronto a connetterti.',
      'image' => '/images/whyus/nlo3.png',
    ],
  ],
  'contact' => 'Contattaci',
  'contact_subtitle' => 'Siamo qui per aiutarti. Se hai domande o hai bisogno di assistenza, ti preghiamo di contattarci.',
];
