<?php

//This file is automatically generated. Do not modify.

return [
  'title' => 'Tutte le nostre destinazioni',
  'subtitle' => 'Ovunque tu vada, ti copriamo con eSIM per ogni destinazione. Scegli la tua destinazione qui sotto per iniziare.',
];
