<?php

//This file is automatically generated. Do not modify.

return [
  'title' => 'Dispositivi supportati',
  'subtitle' => 'Supportiamo un\'ampia gamma di dispositivi. Controlla se il tuo dispositivo è nell\'elenco qui sotto. I dispositivi sono organizzati per produttore.',
  'models_below' => 'I modelli supportati sono elencati di seguito.',
];
