<?php

//This file is automatically generated. Do not modify.

return [
  [
    'question' => 'Cos\'è un eSIM e come posso utilizzare :organisationName?',
    'answer' => 'Una eSIM, o SIM incorporata, è una scheda SIM digitale che consente agli utenti di attivare e gestire più piani mobili su un unico dispositivo senza la necessità di una scheda SIM fisica. Con un\'eSIM, puoi facilmente passare da un fornitore di servizi mobili all\'altro e godere di funzionalità come l\'aggiunta di una linea extra per viaggi internazionali o il mantenimento di piani dati separati per uso personale e aziendale.',
  ],
  [
    'question' => 'Come attivo Internet mobile eSIM con :organisationName?',
    'answer' => 'Per connetterti a Internet utilizzando la eSIM :organisationName, segui questi passaggi: 1. Vai alle impostazioni dei Dati Mobili. 2. Attiva la linea mobile :organisationName. 3. Attiva il roaming dati. 4. Seleziona la linea Internet :organisationName come connessione primaria. *Evita di selezionare l\'opzione "Rimuovi piano dati", poiché questo eliminerà il tuo profilo eSIM.*',
  ],
  [
    'question' => 'Posso fare telefonate o inviare messaggi di testo?',
    'answer' => 'I piani eSIM prepagati di :organisationName sono progettati per un uso esclusivamente dati e non includono un numero di telefono mobile per chiamate tradizionali o messaggi SMS. Raccomandiamo di utilizzare applicazioni VoIP come Facebook Messenger, WhatsApp, Viber, Telegram o Skype per rimanere connessi in tutto il mondo senza la necessità di una scheda SIM internazionale standard.',
  ],
  [
    'question' => 'Un eSIM può essere riutilizzato?',
    'answer' => 'Ogni codice QR per un eSIM è unico e può essere utilizzato solo su un dispositivo. Una volta che il profilo eSIM è stato eliminato, il codice QR non può essere riutilizzato sullo stesso dispositivo o su un altro, garantendo sicurezza ed esclusività.',
  ],
  [
    'question' => 'Quando inizia la durata dei piani dati mobili eSIM?',
    'answer' => 'La durata del tuo piano dati eSIM inizia immediatamente dopo che il tuo dispositivo si connette per la prima volta a una rete mobile con l\'eSIM.',
  ],
  [
    'question' => 'Posso estendere la data di scadenza del mio attuale piano dati mobile eSIM?',
    'answer' => 'Certo! Riceverai più notifiche push quando sei quasi fuori dal tuo pacchetto. Puoi facilmente ricaricare tramite il tuo portale personale.',
  ],
  [
    'question' => 'Posso usare il tethering o il Personal Hotspot con :organisationName?',
    'answer' => 'Sì, puoi condividere i tuoi dati mobili con altri dispositivi tramite il tuo :organisationName-eSIM. Basta installare il :organisationName-eSIM sul tuo dispositivo e attivare l\'Hotspot personale nelle impostazioni. Questa funzione è inclusa senza costi aggiuntivi, ma tieni presente che l\'uso dei dati tethered verrà detrattato dal tuo piano.',
  ],
  [
    'question' => 'Posso mantenere i numeri della mia app di messaggistica personale mentre utilizzo l\'eSIM di :organisationName?',
    'answer' => 'Sì, puoi continuare a utilizzare il tuo WhatsApp, Snapchat, Telegram e altre app di messaggistica insieme al tuo eSIM prepagato :organisationName senza alcun problema.',
  ],
  [
    'question' => 'Come posso trasferire il mio eSIM su un nuovo telefono?',
    'answer' => 'Prima di trasferire, assicurati che il tuo nuovo smartphone supporti la tecnologia eSIM. Contatta il nostro team di supporto per creare un nuovo profilo eSIM, quindi accedi al tuo account :organisationName sul nuovo dispositivo per installare il codice QR. Assicurati di confermare che stai utilizzando un dispositivo diverso per aggiornamenti accurati delle impostazioni.',
  ],
  [
    'question' => 'Ci sono contratti simili a quelli dei fornitori tradizionali di eSIM?',
    'answer' => 'No, :organisationName non richiede di firmare contratti. Puoi attivare o disattivare la tua eSIM come desideri, a seconda dei tuoi piani. Siamo felici di aiutarti.',
  ],
  [
    'question' => 'Qual è la differenza tra l\'eSIM di :organisationName e i piani dati di roaming standard degli operatori mobili fisici?',
    'answer' => ':organisationName offre piani dati senza contratto e senza costi di roaming nascosti. Paghi solo per i dati che utilizzi, a seconda del pacchetto che scegli, rendendolo spesso un\'opzione più economica.',
  ],
  [
    'question' => 'Perché la mia velocità di dati è lenta?',
    'answer' => 'La velocità dei dati può essere influenzata da vari fattori, tra cui il tipo di smartphone che possiedi, la tecnologia di rete, i siti web o le app che utilizzi e l\'ora del giorno. Inoltre, le velocità possono variare a seconda dell\'infrastruttura di rete del paese. Se stai riscontrando velocità lente, prova a riavviare il tuo telefono e condividi con noi eventuali risultati di velocità, in particolare confronti con e senza LTE mode abilitato.',
  ],
  [
    'question' => 'Come posso visualizzare i miei bundles?',
    'answer' => 'Puoi tenere traccia dei tuoi dati rimanenti e dei limiti nel nostro pannello clienti.',
  ],
  [
    'question' => 'Cosa rende :organisationName diversa dagli altri servizi eSIM?',
    'answer' => ':organisationName si distingue collaborando con operatori locali in oltre 200 paesi, offrendo pacchetti dati economici senza intermediari. Forniamo una copertura robusta e un processo di attivazione semplice. :organisationName è perfetto per i viaggiatori in cerca di soluzioni per internet mobile.',
  ],
];
