<?php

//This file is automatically generated. Do not modify.

return [
  'title' => 'Rimani connesso online in :countryName',
  'subtitle' => 'Viaggiando verso :countryName? Rimani connesso con la nostra eSIM, assicurandoti di avere accesso a Internet istantaneo all\'arrivo.',
  'features' => [
    [
      'title' => 'Affidabile e veloce online in :countryName',
      'subtitle' => ':countryName è una bellissima destinazione, che vanta città moderne vivaci e paesaggi naturali mozzafiato. Migliora la tua esperienza di viaggio con la nostra eSIM, assicurandoti di rimanere connesso istantaneamente all\'arrivo.  
        Dì addio al fastidio di cercare una scheda SIM locale o di affrontare costosi costi di roaming dati. Con la nostra eSIM, godrai di un accesso senza soluzione di continuità alle reti 4G/5G dei migliori fornitori del paese, rimanendo online ovunque ti porti il tuo viaggio.',
      'image' => 'images/features/feature1.jpg',
    ],
    [
      'title' => 'Rimani connesso con i tuoi cari',
      'subtitle' => 'La nostra eSIM è progettata per un accesso a Internet senza interruzioni, mantenendoti connesso per tutte le tue attività online senza la necessità di un nuovo numero di telefono. Crea facilmente un hotspot per condividere la tua connessione con altri viaggiatori o familiari, una funzione spesso bloccata da altri fornitori ma completamente supportata da noi. Goditi la comodità di una connettività istantanea su dispositivi compatibili con eSIM, assicurando che tu e i tuoi cari rimaniate online in qualsiasi momento e ovunque. Ti preghiamo di confermare se il tuo dispositivo supporta eSIM per assicurarti di essere pronto per le nostre offerte internet. Si prega di notare che le chiamate e gli SMS non sono supportati con la nostra eSIM.',
      'image' => 'images/features/feature2.jpg',
    ],
  ],
];
