<?php

//This file is automatically generated. Do not modify.

return [
  'all_rights_reserved' => 'Tutti i diritti riservati.',
  'foreign_currencies_for_reference_only' => 'Le valute estere sono solo a scopo di riferimento. La fatturazione sarà in Euro.',
];
