<?php

//This file is automatically generated. Do not modify.

return [
  'from' => ':price/GB',
  'title' => 'Collegati globalmente con le nostre eSIM.',
  'subtitle' => 'Esplora i nostri pacchetti eSIM e rimani connesso, ovunque tu sia!',
  'search_destination' => 'Trova una destinazione',
  'show_all_esim' => 'Mostra tutti i piani eSIM',
  'how_it_works' => 'Come funziona?',
  'steps' => [
    [
      'title' => 'Passo 1',
      'description' => 'Controlla se il tuo dispositivo è compatibile con eSIM nella nostra lista di compatibilità.',
    ],
    [
      'title' => 'Passo 2',
      'description' => 'Scegli la tua destinazione e il piano dati eSIM desiderato',
    ],
    [
      'title' => 'Passo 3',
      'description' => 'Acquista la scheda eSIM che meglio si adatta alle tue esigenze',
    ],
    [
      'title' => 'Passo 4',
      'description' => 'La tua eSIM verrà consegnata automaticamente. Segui le istruzioni nella tua email.',
    ],
    [
      'title' => 'Passo 5',
      'description' => 'Installa il tuo profilo eSIM e goditi il tuo viaggio!',
    ],
  ],
  'supported_networks' => 'Fornitori di rete supportati',
  'supported_networks_description' => 'Lavoriamo a stretto contatto con marchi di connettività, media e tecnologia leader di mercato fidati in tutto il mondo.',
  'and_many_more' => 'e molto di più...',
  'user_reviews' => 'Cosa dicono i nostri utenti soddisfatti',
  'user_reviews_subtitle' => 'Scopri perché i viaggiatori di tutto il mondo si affidano alla nostra eSIM per una connettività senza interruzioni e affidabile in movimento.',
  'faq' => 'Domande Frequenti',
  'popular_destinations' => 'Destinazioni Popolari',
  'popular_destinations_description' => 'Scopri le nostre destinazioni eSIM più popolari e rimani connesso, ovunque tu vada!',
  'see_all_destinations' => 'Visualizza tutte le destinazioni',
];
