<?php

//This file is automatically generated. Do not modify.

return [
  'home' => 'Casa',
  'supported-devices' => 'Dispositivi supportati',
  'destinations' => 'Tutte le destinazioni',
  'about' => 'Informazioni',
  'contact' => 'Contatto',
  'portal_link' => 'Il mio Portal',
];
