<?php

//This file is automatically generated. Do not modify.

return [
  'days' => 'giorni',
  'buy_plan' => 'Compra ora!',
  'perks' => [
    'instant' => 'Consegna diretta',
    'advanced_self_service' => 'Portale di self-service avanzato',
    '247_support' => 'supporto chat live 24/7',
    'prepaid' => 'Prepagato, senza condizioni attaccate',
    'no_roaming' => 'Nessun costo di roaming',
  ],
  'local_for' => 'eSIM locali per :countryName',
  'not_available_yet' => 'Attualmente non offriamo eSIM per questo paese.',
  'not_available_yet_contact_us' => 'Stiamo lavorando duramente per espandere la nostra copertura globale. Se sei interessato a eSIM per questo paese nel frattempo, ti preghiamo di contattarci.',
  'top_plan' => 'Più popolare',
  'all_features' => 'Tutte le funzioni',
  'features' => [
    'feature_one' => 'Possibile hotspot',
    'feature_two' => 'Copertura su tutte le reti nazionali',
    'feature_three' => 'Aggiornamento semplice nel tuo portale personale',
  ],
  'buy_now' => 'Acquista ora',
  'starting_from' => 'Iniziando da',
  'choose_destination' => 'Trova una destinazione',
  'how_esim_works' => [
    'title' => 'Come funziona l\'eSIM',
    'subtitle' => 'Iniziare con l\'eSIM è facile! Segui questi semplici passaggi per rimanere connesso.',
    'steps' => [
      [
        'title' => 'Acquista la tua eSIM',
        'description' => 'Scegli la tua destinazione, seleziona un pacchetto che soddisfi le tue esigenze di dati e completa il tuo acquisto.',
        'image' => '/images/howesimworks/1.png',
      ],
      [
        'title' => 'Ricevi la tua eSIM',
        'description' => 'Ricevi il tuo codice QR eSIM direttamente nella tua email. Pronto per essere utilizzato immediatamente.',
        'image' => '/images/howesimworks/2.png',
      ],
      [
        'title' => 'Attiva e Connetti',
        'description' => 'Scansiona il codice QR, attiva la tua eSIM e goditi dati veloci e affidabili ovunque tu vada.',
        'image' => '/images/howesimworks/3.png',
      ],
    ],
  ],
  'sub_description' => 'Scegli il tuo pacchetto qui sotto e goditi una connettività senza interruzioni in :countryName sulle migliori reti al miglior prezzo.',
];
