<?php

//This file is automatically generated. Do not modify.

return [
  'title' => 'Servizio eSIM - Schede SIM virtuali prepagate per viaggiatori - :site_name',
  'description' => 'Servizio eSIM ⏩ Schede SIM digitali prepagate per turismo e affari ⏩ Piani dati per cellulari standard e illimitati, locali e globali ⏩ Nessun contratto ✅ Nessun costo e commissioni di roaming nascosti ✅ - :site_name',
  'keywords' => 'eSIM, servizio eSIM, scheda eSIM, dati eSIM, piano dati eSIM, piani dati eSIM, piano dati eSIM per viaggiatori, piano dati eSIM per turisti, piano dati eSIM per affari, piano dati eSIM per viaggi, piano dati eSIM per l\'Europa, piano dati eSIM per gli USA, piano dati eSIM per l\'Asia, piano dati eSIM per l\'Africa, piano dati eSIM per l\'Australia, piano dati eSIM per il Sud America, piano dati eSIM per il Nord America, piano dati eSIM per il Medio Oriente, piano dati eSIM per la Russia, piano dati eSIM per la Cina, piano dati eSIM per l\'India, piano dati eSIM per il Giappone',
  'routes' => [
    'home' => [
      'title' => 'Servizio eSIM - Schede SIM virtuali prepagate per viaggiatori - :site_name',
      'description' => 'servizio eSIM ⏩ Schede SIM digitali prepagate per turismo e affari ⏩ Piani dati per telefoni cellulari standard e illimitati, locali e globali ⏩ Nessun contratto ✅ Nessun costo e tassa di roaming nascosti ✅ - :site_name',
    ],
    'about' => [
      'title' => 'Chi Siamo - :site_name',
      'description' => 'Chi Siamo ⏩ Schede SIM digitali prepagate per turismo e affari ⏩ Piani tariffari per dati mobili standard e illimitati, locali e globali ⏩ Nessun contratto ✅ Nessun costo e tassa di roaming nascosti ✅ - :site_name',
    ],
    'supported-devices' => [
      'title' => 'Dispositivi supportati - :site_name',
      'description' => 'Dispositivi supportati ⏩ SIM card digitali prepagate per turismo e affari ⏩ Piani tariffari per dati cellulari standard e illimitati, locali e globali ⏩ Nessun contratto ✅ Nessun costo e tassa di roaming nascosti ✅ - :site_name',
    ],
    'esim-bundle-per-country' => [
      'title' => 'Offerte eSIM locali convenienti per :countryName - :site_name',
      'description' => 'Offerte eSIM locali convenienti per :countryName ⏩ Schede SIM digitali prepagate per il turismo e gli affari ⏩ Piani dati per telefoni cellulari standard e illimitati, locali e globali ⏩ Nessun contratto ✅ Nessun costo e tassa di roaming nascosti ✅ - :site_name',
    ],
  ],
];
