<?php

//This file is automatically generated. Do not modify.

return [
  'title' => 'eSIM-service - Schede SIM virtuali prepagate per viaggiatori - :site_name',
  'description' => 'eSIM-service ⏩ Schede SIM digitali prepagate per il turismo e gli affari ⏩ Piani di dati mobili standard e illimitati, locali e globali ⏩ Nessun contratto ✅ Nessun costo di roaming nascosto e commissioni ✅ - :site_name',
  'keywords' => 'eSIM, servizio eSIM, scheda eSIM, dati eSIM, piano dati eSIM, piani dati eSIM, piano dati eSIM per viaggiatori, piano dati eSIM per turisti, piano dati eSIM per aziende, piano dati eSIM per viaggi, piano dati eSIM per l\'Europa, piano dati eSIM per gli Stati Uniti, piano dati eSIM per l\'Asia, piano dati eSIM per l\'Africa, piano dati eSIM per l\'Australia, piano dati eSIM per il Sud America, piano dati eSIM per il Nord America, piano dati eSIM per il Medio Oriente, piano dati eSIM per la Russia, piano dati eSIM per la Cina, piano dati eSIM per l\'India, piano dati eSIM per il Giappone',
  'routes' => [
    'home' => [
      'title' => 'eSIM-service - Schede SIM virtuali prepagate per viaggiatori - :site_name',
      'description' => 'eSIM-service ⏩ Schede SIM digitali prepagate per turismo e affari ⏩ Piani dati mobili standard e illimitati, locali e globali ⏩ Nessun contratto ✅ Nessun costo di roaming nascosto e commissioni ✅ - :site_name',
    ],
    'about' => [
      'title' => 'Chi siamo - :site_name',
      'description' => 'Chi siamo ⏩ Schede SIM digitali prepagate per turismo e affari ⏩ Piani dati mobili standard e illimitati, locali e globali ⏩ Nessun contratto ✅ Nessun costo di roaming nascosto e commissioni ✅ - :site_name',
    ],
    'supported-devices' => [
      'title' => 'Dispositivi supportati - :site_name',
      'description' => 'Dispositivi supportati ⏩ SIM card digitali prepagate per turismo e affari ⏩ Piani dati mobili standard e illimitati, locali e globali ⏩ Nessun contratto ✅ Nessun costo di roaming nascosto e commissioni ✅ - :site_name',
    ],
    'esim-bundle-per-country' => [
      'title' => 'eSIM :countryName - :site_name',
      'description' => 'eSIM :countryName ⏩ Schede SIM digitali prepagate per turismo e affari ⏩ Piani dati mobili standard e illimitati, locali e globali ⏩ Nessun contratto ✅ Nessun costo di roaming nascosto e commissioni ✅ - :site_name',
    ],
  ],
];
