<?php

//This file is automatically generated. Do not modify.

return [
  'Rens' => [
    'role' => 'Co-Fondatore',
    'image' => '/images/team/rens.png',
  ],
  'Luuk' => [
    'role' => 'Co-Fondatore',
    'image' => '/images/team/luuk.png',
  ],
  'Fleur' => [
    'role' => 'Supporto Clienti',
    'image' => '/images/team/fleur.png',
  ],
  'Patrick' => [
    'role' => 'Sviluppatore',
    'image' => '/images/team/patrick.png',
  ],
];
