<?php

//This file is automatically generated. Do not modify.

return [
  'title' => 'Sobre nós',
  'subtitle' => 'Navegue pelo mundo sem fronteiras conosco. Somos seu parceiro definitivo que mantém você conectado onde quer que sua paixão o leve.',
  'our_team' => 'Nossa Equipe',
  'our_team_subtitle' => 'Acreditamos em capacitar os viajantes com conectividade de dados global confiável e acessível. Nossa equipe diversificada está unida na criação de um mundo mais conectado e acessível para todos que estão em movimento.',
  'why_us' => 'Por que nos escolher',
  'why_us_subtitle' => 'Estamos orgulhosos do nosso serviço confiável, preços competitivos e abordagem voltada para o cliente. Sua satisfação é nossa maior prioridade.',
  'why_us_reasons' => [
    [
      'title' => 'Planos Flexíveis Projetados para Suas Necessidades de Viagem',
      'subtitle' => 'Escolha entre uma variedade de pacotes acessíveis adaptados a diferentes países e regiões. Oferecemos a flexibilidade de selecionar o plano de dados perfeito, para que você pague apenas pelo que precisa, sem custos ocultos.',
      'image' => '/images/whyus/nlo2.png',
    ],
    [
      'title' => 'Ativação direta, sem necessidade de cartões SIM físicos',
      'subtitle' => 'Os dias de trocar cartões SIM físicos acabaram. Com a gente, seu eSIM é entregue diretamente por e-mail e pode ser ativado em minutos. Basta escanear o código QR e você está pronto para se conectar.',
      'image' => '/images/whyus/nlo3.png',
    ],
  ],
  'contact' => 'Entre em contato conosco',
  'contact_subtitle' => 'Estamos aqui para ajudar você. Se você tiver alguma dúvida ou precisar de assistência, entre em contato conosco.',
];
