<?php

//This file is automatically generated. Do not modify.

return [
  'title' => 'Dispositivos suportados',
  'subtitle' => 'Nós suportamos uma ampla gama de dispositivos. Verifique se o seu dispositivo está na lista abaixo. Os dispositivos estão organizados por fabricante.',
  'models_below' => 'Os modelos suportados estão listados abaixo.',
];
