<?php

//This file is automatically generated. Do not modify.

return [
  'faq' => 'FAQ',
  'subtitle' => 'Você tem perguntas? Nós temos respostas. Encontre tudo o que você precisa saber sobre nossos eSIMs.',
];
