<?php

//This file is automatically generated. Do not modify.

return [
  [
    'question' => 'O que é um eSIM e como posso usar :organisationName?',
    'answer' => 'Um eSIM, ou SIM embutido, é um cartão SIM digital que permite aos usuários ativar e gerenciar vários planos móveis em um único dispositivo sem precisar de um cartão SIM físico. Com um eSIM, você pode facilmente alternar entre provedores móveis e aproveitar recursos como adicionar uma linha extra para viagens internacionais ou manter planos de dados separados para uso pessoal e empresarial.',
  ],
  [
    'question' => 'Como ativo a internet móvel eSIM com :organisationName?',
    'answer' => 'Para se conectar à internet usando o :organisationName eSIM, siga estas etapas: 1. Vá para as configurações de Dados Móveis. 2. Ative a linha móvel :organisationName. 3. Ative o Roaming de Dados. 4. Selecione a linha de Internet :organisationName como sua conexão principal. *Evite selecionar a opção "Remover plano de dados", pois isso excluirá seu perfil eSIM.*',
  ],
  [
    'question' => 'Posso fazer chamadas telefônicas ou enviar mensagens de texto?',
    'answer' => 'Os planos de eSIM pré-pagos da :organisationName são projetados para uso somente de dados e não incluem um número de telefone móvel para chamadas tradicionais ou mensagens SMS. Recomendamos o uso de aplicativos VoIP, como Facebook Messenger, WhatsApp, Viber, Telegram ou Skype, para se manter conectado em todo o mundo sem a necessidade de um cartão SIM internacional padrão.',
  ],
  [
    'question' => 'Um cartão eSIM pode ser reutilizado?',
    'answer' => 'Cada código QR para um eSIM é único e pode ser usado apenas em um dispositivo. Uma vez que o perfil eSIM é excluído, o código QR não pode ser reutilizado no mesmo dispositivo ou em outro, garantindo segurança e exclusividade.',
  ],
  [
    'question' => 'Quando começa a duração dos planos de dados móveis eSIM?',
    'answer' => 'A duração do seu plano de dados eSIM começa imediatamente após o seu dispositivo se conectar pela primeira vez a uma rede móvel com o eSIM.',
  ],
  [
    'question' => 'Posso estender a data de expiração do meu plano de dados móveis eSIM atual?',
    'answer' => 'Claro! Você receberá várias notificações push quando estiver quase sem seu pacote. Você pode facilmente recarregar através do seu portal pessoal.',
  ],
  [
    'question' => 'Posso usar tethering ou Hotspot Pessoal com :organisationName?',
    'answer' => 'Sim, você pode compartilhar seus dados móveis com outros dispositivos através do seu :organisationName-eSIM. Basta instalar o :organisationName-eSIM no seu dispositivo e ativar o Hotspot Pessoal nas suas configurações. Este recurso está incluído sem custo adicional, mas observe que o uso de dados compartilhados será descontado do seu plano.',
  ],
  [
    'question' => 'Posso manter meus números do aplicativo de mensagens pessoais enquanto uso o eSIM da :organisationName?',
    'answer' => 'Sim, você pode continuar a usar seu WhatsApp, Snapchat, Telegram e outros aplicativos de mensagens junto com seu :organisationName eSIM pré-pago sem nenhum problema.',
  ],
  [
    'question' => 'Como posso transferir meu eSIM para um novo telefone?',
    'answer' => 'Antes de transferir, certifique-se de que seu novo smartphone suporta a tecnologia eSIM. Entre em contato com nossa equipe de suporte para criar um novo perfil eSIM, em seguida, faça login na sua conta :organisationName no novo dispositivo para instalar o código QR. Certifique-se de confirmar que você está usando um dispositivo diferente para atualizações de configurações precisas.',
  ],
  [
    'question' => 'Existem contratos como os dos provedores tradicionais de eSIM?',
    'answer' => 'Não, :organisationName não exige que você assine contratos. Você pode ativar ou desativar seu cartão eSIM como desejar, dependendo de seus planos. Estamos felizes em ajudar você.',
  ],
  [
    'question' => 'Qual é a diferença entre o eSIM da :organisationName e os planos de dados de roaming padrão dos operadores móveis físicos?',
    'answer' => ':organisationName oferece planos de dados sem contrato e sem custos ocultos de roaming. Você paga apenas pelos dados que usa, dependendo do pacote que escolher, tornando-se muitas vezes uma opção mais econômica.',
  ],
  [
    'question' => 'Por que a velocidade dos meus dados está lenta?',
    'answer' => 'A velocidade dos dados pode ser afetada por vários fatores, incluindo o tipo de smartphone que você possui, a tecnologia de rede, os sites ou aplicativos que você usa e a hora do dia. Além disso, as velocidades podem variar dependendo da infraestrutura de rede do país. Se você estiver enfrentando velocidades lentas, tente reiniciar seu telefone e compartilhe quaisquer resultados de velocidade conosco, especialmente comparações com e sem LTE mode habilitado.',
  ],
  [
    'question' => 'Como posso ver meus bundles?',
    'answer' => 'Você pode acompanhar seus dados restantes e limites em nosso painel de clientes.',
  ],
  [
    'question' => 'O que torna :organisationName diferente de outros serviços eSIM?',
    'answer' => ':organisationName se destaca ao colaborar com operadores locais em mais de 200 países, oferecendo pacotes de dados econômicos sem intermediários. Nós fornecemos cobertura robusta e um processo de ativação simples. :organisationName é perfeito para viajantes que buscam soluções de internet móvel.',
  ],
];
