<?php

//This file is automatically generated. Do not modify.

return [
  'all_rights_reserved' => 'Todos os direitos reservados.',
  'foreign_currencies_for_reference_only' => 'Moedas estrangeiras são apenas para referência. A faturação será em Euros.',
];
