<?php

//This file is automatically generated. Do not modify.

return [
  'home' => 'Início',
  'supported-devices' => 'Dispositivos suportados',
  'destinations' => 'Todos os destinos',
  'about' => 'Sobre',
  'contact' => 'Contato',
  'portal_link' => 'Meu Portal',
];
