<?php

//This file is automatically generated. Do not modify.

return [
  'title' => 'eSIM-service - Cartões SIM virtuais pré-pagos para viajantes - :site_name',
  'description' => 'eSIM-service ⏩ Cartões SIM digitais pré-pagos para turismo e negócios ⏩ Planos de dados móveis padrão e ilimitados, locais e globais ⏩ Sem contratos ✅ Sem custos e taxas de roaming ocultos ✅ - :site_name',
  'keywords' => 'eSIM, eSIM-serviço, eSIM-cartão, eSIM-dados, eSIM-plano de dados, eSIM-planos de dados, eSIM-plano de dados para viajantes, eSIM-plano de dados para turistas, eSIM-plano de dados para empresas, eSIM-plano de dados para viagens, eSIM-plano de dados para a Europa, eSIM-plano de dados para os EUA, eSIM-plano de dados para a Ásia, eSIM-plano de dados para a África, eSIM-plano de dados para a Austrália, eSIM-plano de dados para a América do Sul, eSIM-plano de dados para a América do Norte, eSIM-plano de dados para o Oriente Médio, eSIM-plano de dados para a Rússia, eSIM-plano de dados para a China, eSIM-plano de dados para a Índia, eSIM-plano de dados para o Japão',
  'routes' => [
    'home' => [
      'title' => 'eSIM-service - Cartões SIM virtuais pré-pagos para viajantes - :site_name',
      'description' => 'eSIM-service ⏩ Cartões SIM digitais pré-pagos para turismo e negócios ⏩ Planos de dados móveis padrão e ilimitados, locais e globais ⏩ Sem contratos ✅ Sem taxas e cobranças ocultas de roaming ✅ - :site_name',
    ],
    'about' => [
      'title' => 'Sobre nós - :site_name',
      'description' => 'Sobre nós ⏩ Cartões SIM digitais pré-pagos para turismo e negócios ⏩ Planos de dados móveis locais e globais, padrão e ilimitados ⏩ Sem contratos ✅ Sem taxas de roaming ocultas e reembolsos ✅ - :site_name',
    ],
    'supported-devices' => [
      'title' => 'Dispositivos Suportados - :site_name',
      'description' => 'Dispositivos Suportados ⏩ Cartões SIM digitais pré-pagos para turismo e negócios ⏩ Planos de dados móveis locais e globais padrão e ilimitados ⏩ Sem contratos ✅ Sem taxas e encargos ocultos de roaming ✅ - :site_name',
    ],
    'esim-bundle-per-country' => [
      'title' => 'eSIM :countryName - :site_name',
      'description' => 'eSIM :countryName ⏩ Cartões SIM digitais pré-pagos para turismo e negócios ⏩ Planos de dados móveis locais e globais, padrão e ilimitados ⏩ Sem contratos ✅ Sem taxas e encargos ocultos de roaming ✅ - :site_name',
    ],
  ],
];
