<?php

//This file is automatically generated. Do not modify.

return [
  'title' => 'Όλοι οι προορισμοί μας',
  'subtitle' => 'Οπουδήποτε κι αν πάτε, σας έχουμε καλύψει με eSIMs για κάθε προορισμό. Επιλέξτε τον προορισμό σας παρακάτω για να ξεκινήσετε.',
];
