<?php

//This file is automatically generated. Do not modify.

return [
  'faq' => 'Συχνές Ερωτήσεις',
  'subtitle' => 'Έχετε ερωτήσεις; Έχουμε απαντήσεις. Βρείτε τα πάντα που χρειάζεστε να ξέρετε για τα eSIMs μας.',
];
