<?php

//This file is automatically generated. Do not modify.

return [
  'all_rights_reserved' => 'Όλα τα δικαιώματα διατηρούνται.',
  'foreign_currencies_for_reference_only' => 'Οι ξένες νομίσματα είναι μόνο για αναφορά. Η τιμολόγηση θα είναι σε Ευρώ.',
];
