<?php

//This file is automatically generated. Do not modify.

return [
  'home' => 'Σπίτι',
  'supported-devices' => 'Υποστηριζόμενες συσκευές',
  'destinations' => 'Όλοι οι προορισμοί',
  'about' => 'Σχετικά',
  'contact' => 'Επικοινωνία',
  'portal_link' => 'Η Πύλη μου',
];
