<?php

//This file is automatically generated. Do not modify.

return [
  'title' => 'eSIM-service - Προπληρωμένες εικονικές κάρτες SIM για ταξιδιώτες - :site_name',
  'description' => 'eSIM-service ⏩ Προπληρωμένες ψηφιακές SIM κάρτες για τουρισμό και επιχειρήσεις ⏩ Πρότυπα και απεριόριστα, τοπικά και παγκόσμια σχέδια κινητής δεδομένων ⏩ Χωρίς συμβόλαια ✅ Χωρίς κρυφές χρεώσεις και αποζημιώσεις περιαγωγής ✅ - :site_name',
  'keywords' => 'eSIM, eSIM-service, eSIM-kaart, eSIM-gegevens, eSIM-gegevensplan, eSIM-gegevensπλάνα, eSIM-gegevensplan για ταξιδιώτες, eSIM-gegevensplan για τουρίστες, eSIM-gegevensplan για επιχειρήσεις, eSIM-gegevensplan για ταξίδια, eSIM-gegevensplan για την Ευρώπη, eSIM-gegevensplan για τις ΗΠΑ, eSIM-gegevensplan για την Ασία, eSIM-gegevensplan για την Αφρική, eSIM-gegevensplan για την Αυστραλία, eSIM-gegevensplan για τη Νότια Αμερική, eSIM-gegevensplan για τη Βόρεια Αμερική, eSIM-gegevensplan για τη Μέση Ανατολή, eSIM-gegevensplan για τη Ρωσία, eSIM-gegevensplan για την Κίνα, eSIM-gegevensplan για την Ινδία, eSIM-gegevensplan για την Ιαπωνία',
  'routes' => [
    'home' => [
      'title' => 'eSIM-service - Προπληρωμένες εικονικές κάρτες SIM για ταξιδιώτες - :site_name',
      'description' => 'eSIM-service ⏩ Προπληρωμένες ψηφιακές SIM κάρτες για τουρισμό και επιχειρήσεις ⏩ Πρότυπα και απεριόριστα, τοπικά και παγκόσμια προγράμματα κινητής δεδομένων ⏩ Χωρίς συμβόλαια ✅ Χωρίς κρυφές χρεώσεις και αποζημιώσεις περιαγωγής ✅ - :site_name',
    ],
    'about' => [
      'title' => 'Σχετικά με εμάς - :site_name',
      'description' => 'Για εμάς ⏩ Προπληρωμένες ψηφιακές κάρτες SIM για τουρισμό και επιχειρήσεις ⏩ Κανονικά και απεριόριστα, τοπικά και παγκόσμια σχέδια κινητής δεδομένων ⏩ Χωρίς συμβόλαια ✅ Χωρίς κρυφές χρεώσεις και αποζημιώσεις περιαγωγής ✅ - :site_name',
    ],
    'supported-devices' => [
      'title' => 'Υποστηριζόμενες Συσκευές - :site_name',
      'description' => 'Υποστηριζόμενες Συσκευές ⏩ Προπληρωμένες ψηφιακές SIM κάρτες για τουρισμό και επιχειρήσεις ⏩ Πρότυπα και απεριόριστα, τοπικά και παγκόσμια σχέδια κινητής δεδομένων ⏩ Χωρίς συμβόλαια ✅ Χωρίς κρυφές χρεώσεις και αποζημιώσεις περιαγωγής ✅ - :site_name',
    ],
    'esim-bundle-per-country' => [
      'title' => 'eSIM :countryName - :site_name',
      'description' => 'eSIM :countryName ⏩ Προπληρωμένες ψηφιακές SIM κάρτες για τουρισμό και επιχειρήσεις ⏩ Τυπικά και απεριόριστα, τοπικά και παγκόσμια προγράμματα κινητής δεδομένων ⏩ Χωρίς συμβόλαια ✅ Χωρίς κρυφές χρεώσεις και αποζημιώσεις περιαγωγής ✅ - :site_name',
    ],
  ],
];
