<?php

//This file is automatically generated. Do not modify.

return [
  'title' => 'Acerca de nosotros',
  'subtitle' => 'Navega por el mundo sin fronteras con nosotros. Somos tu socio definitivo que te mantiene conectado dondequiera que tu pasión te lleve.',
  'our_team' => 'Nuestro Equipo',
  'our_team_subtitle' => 'Creemos en empoderar a los viajeros con conectividad de datos global confiable y asequible. Nuestro equipo diverso está unido en la creación de un mundo más conectado y accesible para todos los que están en movimiento.',
  'why_us' => 'Por qué elegirnos',
  'why_us_subtitle' => 'Estamos orgullosos de nuestro servicio confiable, precios competitivos y enfoque orientado al cliente. Su satisfacción es nuestra máxima prioridad.',
  'why_us_reasons' => [
    [
      'title' => 'Planes flexibles diseñados para tus necesidades de viaje',
      'subtitle' => 'Elige entre una variedad de paquetes asequibles adaptados a diferentes países y regiones. Te damos la flexibilidad de seleccionar el plan de datos perfecto, para que solo pagues por lo que necesitas, sin costos ocultos.',
      'image' => '/images/whyus/nlo2.png',
    ],
    [
      'title' => 'Activación directa, no se necesitan tarjetas SIM físicas',
      'subtitle' => 'Los días de cambiar tarjetas SIM físicas han terminado. Con nosotros, tu eSIM se entrega directamente por correo electrónico y puede ser activada en minutos. Solo escanea el código QR y estarás listo para conectarte.',
      'image' => '/images/whyus/nlo3.png',
    ],
  ],
  'contact' => 'Contáctanos',
  'contact_subtitle' => 'Estamos aquí para ayudarte. Si tienes alguna pregunta o necesitas asistencia, por favor contáctanos.',
];
