<?php

//This file is automatically generated. Do not modify.

return [
  'title' => 'Todos nuestros destinos',
  'subtitle' => 'Dondequiera que vayas, te tenemos cubierto con eSIMs para cada destino. Elige tu destino a continuación para comenzar.',
];
