<?php

//This file is automatically generated. Do not modify.

return [
  'faq' => 'FAQ',
  'subtitle' => '¿Tienes preguntas? Tenemos respuestas. Encuentra todo lo que necesitas saber sobre nuestras eSIMs.',
];
