<?php

//This file is automatically generated. Do not modify.

return [
  [
    'question' => '¿Qué es un eSIM y cómo puedo usar :organisationName?',
    'answer' => 'Una eSIM, o SIM embebida, es una tarjeta SIM digital que permite a los usuarios activar y gestionar múltiples planes móviles en un solo dispositivo sin necesidad de una tarjeta SIM física. Con una eSIM, puedes cambiar fácilmente entre proveedores móviles y disfrutar de características como agregar una línea adicional para viajes internacionales o mantener planes de datos separados para uso personal y empresarial.',
  ],
  [
    'question' => '¿Cómo activo el internet móvil eSIM con :organisationName?',
    'answer' => 'Para conectarte a internet usando la eSIM de :organisationName, sigue estos pasos: 1. Ve a la configuración de Datos Móviles. 2. Activa la línea móvil de :organisationName. 3. Activa el Roaming de Datos. 4. Selecciona la línea de Internet de :organisationName como tu conexión principal. *Evita seleccionar la opción "Eliminar plan de datos", ya que esto eliminará tu perfil de eSIM.*',
  ],
  [
    'question' => '¿Puedo hacer llamadas telefónicas o enviar mensajes de texto?',
    'answer' => 'Los planes de eSIM prepago de :organisationName están diseñados para uso solo de datos y no incluyen un número de teléfono móvil para llamadas tradicionales o mensajes SMS. Recomendamos utilizar aplicaciones de VoIP como Facebook Messenger, WhatsApp, Viber, Telegram o Skype para mantenerse conectado en todo el mundo sin la necesidad de una tarjeta SIM internacional estándar.',
  ],
  [
    'question' => '¿Se puede reutilizar una tarjeta eSIM?',
    'answer' => 'Cada código QR para un eSIM es único y solo se puede usar en un dispositivo. Una vez que se elimina el perfil de eSIM, el código QR no se puede reutilizar en el mismo dispositivo o en otro, asegurando seguridad y exclusividad.',
  ],
  [
    'question' => '¿Cuándo comienza la duración de los planes de datos móviles eSIM?',
    'answer' => 'La duración de tu plan de datos eSIM comienza inmediatamente después de que tu dispositivo se conecte por primera vez a una red móvil con la eSIM.',
  ],
  [
    'question' => '¿Puedo extender la fecha de expiración de mi actual plan de datos móviles eSIM?',
    'answer' => '¡Claro! Recibirás múltiples notificaciones push cuando estés casi fuera de tu bundle. Puedes recargar fácilmente a través de tu portal personal.',
  ],
  [
    'question' => '¿Puedo usar el anclaje o el Hotspot Personal con :organisationName?',
    'answer' => 'Sí, puedes compartir tus datos móviles con otros dispositivos a través de tu :organisationName-eSIM. Simplemente instala la :organisationName-eSIM en tu dispositivo y activa el Punto de Acceso Personal en tu configuración. Esta función está incluida sin costo adicional, pero ten en cuenta que el uso de datos compartidos se deducirá de tu plan.',
  ],
  [
    'question' => '¿Puedo mantener mis números de la aplicación de mensajería personal mientras uso el eSIM de :organisationName?',
    'answer' => 'Sí, puedes seguir utilizando tu WhatsApp, Snapchat, Telegram y otras aplicaciones de mensajería junto con tu :organisationName eSIM prepago sin ningún problema.',
  ],
  [
    'question' => '¿Cómo puedo transferir mi eSIM a un nuevo teléfono?',
    'answer' => 'Antes de transferir, asegúrate de que tu nuevo smartphone sea compatible con la tecnología eSIM. Contacta a nuestro equipo de soporte para crear un nuevo perfil eSIM, luego inicia sesión en tu cuenta de :organisationName en el nuevo dispositivo para instalar el código QR. Asegúrate de confirmar que estás utilizando un dispositivo diferente para actualizaciones precisas de configuración.',
  ],
  [
    'question' => '¿Existen contratos como los de los proveedores tradicionales de eSIM?',
    'answer' => 'No, :organisationName no requiere que firmes contratos. Puedes activar o desactivar tu tarjeta eSIM como desees, dependiendo de tus planes. Estamos felices de ayudarte.',
  ],
  [
    'question' => '¿Cuál es la diferencia entre el eSIM de :organisationName y los planes de datos de roaming estándar de los operadores móviles físicos?',
    'answer' => ':organisationName ofrece planes de datos sin contrato y sin costos ocultos de roaming. Solo pagas por los datos que usas, dependiendo del paquete que elijas, lo que a menudo lo convierte en una opción más económica.',
  ],
  [
    'question' => '¿Por qué es lenta la velocidad de mis datos?',
    'answer' => 'La velocidad de los datos puede verse afectada por varios factores, incluyendo el tipo de smartphone que tienes, la tecnología de red, los sitios web o aplicaciones que usas, y la hora del día. Además, las velocidades pueden variar dependiendo de la infraestructura de red del país. Si estás experimentando velocidades lentas, intenta reiniciar tu teléfono y comparte con nosotros cualquier resultado de velocidad, especialmente comparaciones con y sin LTE mode habilitado.',
  ],
  [
    'question' => '¿Cómo puedo ver mis bundles?',
    'answer' => 'Puedes rastrear tus datos restantes y límites en nuestro panel de clientes.',
  ],
  [
    'question' => '¿Qué hace que :organisationName sea diferente de otros servicios de eSIM?',
    'answer' => ':organisationName se destaca al colaborar con operadores locales en más de 200 países, ofreciendo paquetes de datos rentables sin intermediarios. Proporcionamos una cobertura sólida y un proceso de activación simple. :organisationName es perfecto para los viajeros que buscan soluciones de internet móvil.',
  ],
];
