<?php

//This file is automatically generated. Do not modify.

return [
  'all_rights_reserved' => 'Todos los derechos reservados.',
  'foreign_currencies_for_reference_only' => 'Las divisas extranjeras son solo para referencia. La facturación será en Euros.',
];
