<?php

//This file is automatically generated. Do not modify.

return [
  'from' => ':price/GB',
  'title' => 'Conéctate globalmente con nuestras eSIMs',
  'subtitle' => '¡Explora nuestros paquetes de eSIM y mantente conectado, dondequiera que estés!',
  'search_destination' => 'Encuentra un destino',
  'show_all_esim' => 'Mostrar todos los planes de eSIM',
  'how_it_works' => '¿Cómo funciona?',
  'steps' => [
    [
      'title' => 'Paso 1',
      'description' => 'Verifica si tu dispositivo es compatible con eSIM en nuestra lista de compatibilidad.',
    ],
    [
      'title' => 'Paso 2',
      'description' => 'Elige tu destino y el plan de datos eSIM deseado.',
    ],
    [
      'title' => 'Paso 3',
      'description' => 'Compra la tarjeta eSIM que mejor se adapte a tus necesidades.',
    ],
    [
      'title' => 'Paso 4',
      'description' => 'Tu eSIM se entregará automáticamente. Sigue las instrucciones en tu correo electrónico.',
    ],
    [
      'title' => 'Paso 5',
      'description' => '¡Instala tu perfil de eSIM y disfruta de tu viaje!',
    ],
  ],
  'supported_networks' => 'Proveedores de red compatibles',
  'supported_networks_description' => 'Trabajamos en estrecha colaboración con marcas de conectividad, medios y tecnología líderes en el mercado y de confianza en todo el mundo.',
  'and_many_more' => 'y mucho más...',
  'user_reviews' => 'Lo que dicen nuestros usuarios satisfechos',
  'user_reviews_subtitle' => 'Vea por qué los viajeros de todo el mundo confían en nuestra eSIM para una conectividad fluida y confiable en movimiento.',
  'faq' => 'Preguntas Frecuentes',
  'popular_destinations' => 'Destinos Populares',
  'popular_destinations_description' => 'Descubre nuestros destinos de eSIM más populares y mantente conectado, ¡sin importar a dónde vayas!',
  'see_all_destinations' => 'Ver todos los destinos',
];
