<?php

//This file is automatically generated. Do not modify.

return [
  'home' => 'Inicio',
  'supported-devices' => 'Dispositivos compatibles',
  'destinations' => 'Todos los destinos',
  'about' => 'Acerca de',
  'contact' => 'Contacto',
  'portal_link' => 'Mi Portal',
];
