<?php

//This file is automatically generated. Do not modify.

return [
  'days' => 'días',
  'buy_plan' => '¡Compra ahora!',
  'perks' => [
    'instant' => 'Entrega directa',
    'advanced_self_service' => 'Portal de autoservicio avanzado',
    '247_support' => 'soporte de chat en vivo 24/7',
    'prepaid' => 'Prepagado, sin condiciones adjuntas',
    'no_roaming' => 'Sin cargos por roaming',
  ],
  'local_for' => 'eSIMs locales para :countryName',
  'not_available_yet' => 'Actualmente no ofrecemos eSIMs para este país.',
  'not_available_yet_contact_us' => 'Estamos trabajando arduamente para expandir nuestra cobertura global. Si estás interesado en eSIMs para este país mientras tanto, por favor contáctanos.',
  'top_plan' => 'Más popular',
  'all_features' => 'Todas las funciones',
  'features' => [
    'feature_one' => 'Posible punto caliente',
    'feature_two' => 'Cobertura en todas las redes nacionales',
    'feature_three' => 'Actualización simple en tu portal personal',
  ],
  'buy_now' => 'Compra ahora',
  'starting_from' => 'Comenzando desde',
  'choose_destination' => 'Encuentra un destino',
  'how_esim_works' => [
    'title' => 'Cómo funciona eSIM',
    'subtitle' => '¡Comenzar con eSIM es fácil! Sigue estos simples pasos para mantenerte conectado.',
    'steps' => [
      [
        'title' => 'Compra tu eSIM',
        'description' => 'Elige tu destino, selecciona un paquete que satisfaga tus necesidades de datos y completa tu compra.',
        'image' => '/images/howesimworks/1.png',
      ],
      [
        'title' => 'Recibe tu eSIM',
        'description' => 'Recibe tu código QR de eSIM directamente en tu correo electrónico. Listo para usar de inmediato.',
        'image' => '/images/howesimworks/2.png',
      ],
      [
        'title' => 'Activar y Conectar',
        'description' => 'Escanea el código QR, activa tu eSIM y disfruta de datos rápidos y confiables dondequiera que viajes.',
        'image' => '/images/howesimworks/3.png',
      ],
    ],
  ],
  'sub_description' => 'Elige tu paquete a continuación y disfruta de una conectividad sin interrupciones en :countryName en las mejores redes al mejor precio.',
];
