<?php

//This file is automatically generated. Do not modify.

return [
  'title' => 'eSIM-service - Tarjetas SIM virtuales prepago para viajeros - :site_name',
  'description' => 'eSIM-service ⏩ Tarjetas SIM digitales prepago para turismo y negocios ⏩ Planes de datos móviles estándar y ilimitados, locales y globales ⏩ Sin contratos ✅ Sin costos ni cargos ocultos por roaming ✅ - :site_name',
  'keywords' => 'eSIM, servicio eSIM, tarjeta eSIM, datos eSIM, plan de datos eSIM, planes de datos eSIM, plan de datos eSIM para viajeros, plan de datos eSIM para turistas, plan de datos eSIM para empresas, plan de datos eSIM para viajes, plan de datos eSIM para Europa, plan de datos eSIM para EE. UU., plan de datos eSIM para Asia, plan de datos eSIM para África, plan de datos eSIM para Australia, plan de datos eSIM para América del Sur, plan de datos eSIM para América del Norte, plan de datos eSIM para Oriente Medio, plan de datos eSIM para Rusia, plan de datos eSIM para China, plan de datos eSIM para India, plan de datos eSIM para Japón',
  'routes' => [
    'home' => [
      'title' => 'eSIM-servicio - Tarjetas SIM virtuales prepago para viajeros - :site_name',
      'description' => 'eSIM-service ⏩ Tarjetas SIM digitales prepago para turismo y negocios ⏩ Planes de datos móviles estándar y ilimitados, locales y globales ⏩ Sin contratos ✅ Sin costos ocultos de roaming y tarifas de reembolso ✅ - :site_name',
    ],
    'about' => [
      'title' => 'Sobre nosotros - :site_name',
      'description' => 'Sobre nosotros ⏩ Tarjetas SIM digitales prepago para turismo y negocios ⏩ Planes de datos móviles estándar y ilimitados, locales y globales ⏩ Sin contratos ✅ Sin costos ocultos de roaming ni tarifas ✅ - :site_name',
    ],
    'supported-devices' => [
      'title' => 'Dispositivos compatibles - :site_name',
      'description' => 'Dispositivos compatibles ⏩ Tarjetas SIM digitales prepagas para turismo y negocios ⏩ Planes de datos móviles locales y globales, estándar y sin límites ⏩ Sin contratos ✅ Sin costos ocultos de roaming ni tarifas ✅ - :site_name',
    ],
    'esim-bundle-per-country' => [
      'title' => 'eSIM :countryName - :site_name',
      'description' => 'eSIM :countryName ⏩ Tarjetas SIM digitales prepago para turismo y negocios ⏩ Planes de datos móviles estándar y ilimitados, locales y globales ⏩ Sin contratos ✅ Sin costos y cargos ocultos de roaming ✅ - :site_name',
    ],
  ],
];
