<?php

//This file is automatically generated. Do not modify.

return [
  'title' => 'Servicio eSIM - Tarjetas SIM Virtuales Prepagadas para Viajeros - :site_name',
  'description' => 'Servicio eSIM ⏩ Tarjetas SIM digitales prepagas para turismo y negocios ⏩ Planes de datos móviles locales y globales, estándar y ilimitados ⏩ Sin contratos ✅ Sin cargos y tarifas ocultas de roaming ✅ - :site_name',
  'keywords' => 'eSIM, servicio eSIM, tarjeta eSIM, datos eSIM, plan de datos eSIM, planes de datos eSIM, plan de datos eSIM para viajeros, plan de datos eSIM para turistas, plan de datos eSIM para negocios, plan de datos eSIM para viajes, plan de datos eSIM para Europa, plan de datos eSIM para EE. UU., plan de datos eSIM para Asia, plan de datos eSIM para África, plan de datos eSIM para Australia, plan de datos eSIM para América del Sur, plan de datos eSIM para América del Norte, plan de datos eSIM para Oriente Medio, plan de datos eSIM para Rusia, plan de datos eSIM para China, plan de datos eSIM para India, plan de datos eSIM para Japón',
  'routes' => [
    'home' => [
      'title' => 'Servicio eSIM - Tarjetas SIM Virtuales Prepagadas para Viajeros - :site_name',
      'description' => 'Servicio eSIM ⏩ Tarjetas SIM digitales prepago para turismo y negocios ⏩ Planes de datos móviles locales y globales, estándar y ilimitados ⏩ Sin contratos ✅ Sin cargos y tarifas ocultos de roaming ✅ - :site_name',
    ],
    'about' => [
      'title' => 'Acerca de nosotros - :site_name',
      'description' => 'Sobre nosotros ⏩ Tarjetas SIM digitales prepagas para turismo y negocios ⏩ Planes de datos móviles estándar y ilimitados, locales y globales ⏩ Sin contratos ✅ Sin cargos y tarifas ocultas de roaming ✅ - :site_name',
    ],
    'supported-devices' => [
      'title' => 'Dispositivos compatibles - :site_name',
      'description' => 'Dispositivos compatibles ⏩ Tarjetas SIM digitales prepagas para turismo y negocios ⏩ Planes de datos móviles estándar y ilimitados, locales y globales ⏩ Sin contratos ✅ Sin cargos ni tarifas ocultas de roaming ✅ - :site_name',
    ],
    'esim-bundle-per-country' => [
      'title' => 'Ofertas de eSIM locales asequibles para :countryName - :site_name',
      'description' => 'Ofertas de eSIM locales asequibles para :countryName ⏩ Tarjetas SIM digitales prepagas para turismo y negocios ⏩ Planes de datos móviles locales y globales estándar y ilimitados ⏩ Sin contratos ✅ Sin cargos ni tarifas ocultas de roaming ✅ - :site_name',
    ],
  ],
];
