<?php

//This file is automatically generated. Do not modify.

return [
  'Rens' => [
    'role' => 'Co-Fundador',
    'image' => '/images/team/rens.png',
  ],
  'Luuk' => [
    'role' => 'Co-Fundador',
    'image' => '/images/team/luuk.png',
  ],
  'Fleur' => [
    'role' => 'Soporte al Cliente',
    'image' => '/images/team/fleur.png',
  ],
  'Patrick' => [
    'role' => 'Desarrollador',
    'image' => '/images/team/patrick.png',
  ],
];
