<?php

//This file is automatically generated. Do not modify.

return [
  'title' => 'Meistä',
  'subtitle' => 'Navigoi maailmaa ilman rajoja kanssamme. Olemme lopullinen kumppanisi, joka pitää sinut yhteydessä, minne tahansa intohimosi viekään.',
  'our_team' => 'Meidän tiimimme',
  'our_team_subtitle' => 'Uskomme matkustajien voimaannuttamiseen luotettavalla ja edullisella globaalilla datayhteydellä. Monimuotoinen tiimimme on yhtenäinen luodessaan enemmän yhteydessä olevaa ja saavutettavaa maailmaa kaikille liikkeellä oleville.',
  'why_us' => 'Miksi valita meidät',
  'why_us_subtitle' => 'Olemme ylpeitä luotettavasta palvelustamme, kilpailukykyisistä hinnoistamme ja asiakaslähtöisestä lähestymistavastamme. Tyydytyksesi on meille tärkein prioriteetti.',
  'why_us_reasons' => [
    [
      'title' => 'Joustavat suunnitelmat, jotka on suunniteltu matkatarpeisiisi',
      'subtitle' => 'Valitse erilaisista edullisista paketeista, jotka on räätälöity eri maihin ja alueisiin. Annamme sinulle joustavuutta valita täydellinen datasuunnitelma, joten maksat vain siitä, mitä tarvitset, ilman piilokuluja.',
      'image' => '/images/whyus/nlo2.png',
    ],
    [
      'title' => 'Suora aktivointi, ei tarvitse fyysisiä SIM-kortteja',
      'subtitle' => 'Fyysisten SIM-korttien vaihtamisen päivät ovat ohi. Meillä eSIM toimitetaan suoraan sähköpostitse ja se voidaan aktivoida muutamassa minuutissa. Skannaa vain QR-koodi ja olet valmis liittymään.',
      'image' => '/images/whyus/nlo3.png',
    ],
  ],
  'contact' => 'Ota meihin yhteyttä',
  'contact_subtitle' => 'Olemme täällä auttamassa sinua. Jos sinulla on kysymyksiä tai tarvitset apua, ota meihin yhteyttä.',
];
