<?php

//This file is automatically generated. Do not modify.

return [
  'title' => 'Kaikki kohteemme',
  'subtitle' => 'Missä ikinä menetkin, meillä on sinut katettu eSIMillä jokaiseen kohteeseen. Valitse kohteesi alla aloittaaksesi.',
];
