<?php

//This file is automatically generated. Do not modify.

return [
  'title' => 'Tuetut laitteet',
  'subtitle' => 'Tuemme laajaa valikoimaa laitteita. Tarkista, onko laitteesi alla olevassa luettelossa. Laitteet on järjestetty valmistajan mukaan.',
  'models_below' => 'Tuetut mallit on lueteltu alla.',
];
