<?php

//This file is automatically generated. Do not modify.

return [
  'faq' => 'UKK',
  'subtitle' => 'Onko sinulla kysymyksiä? Meillä on vastauksia. Löydä kaikki tarvitsemasi tiedot eSIMeistämme.',
];
