<?php

//This file is automatically generated. Do not modify.

return [
  [
    'question' => 'Mikä on eSIM ja miten voin käyttää :organisationName?',
    'answer' => 'eSIM, eli upotettu SIM, on digitaalinen SIM-kortti, joka mahdollistaa käyttäjien aktivoida ja hallita useita mobiilisuunnitelmia yhdellä laitteella ilman fyysistä SIM-korttia. eSIMn avulla voit helposti vaihtaa mobiilipalveluntarjoajien välillä ja nauttia ominaisuuksista, kuten ylimääräisen linjan lisäämisestä kansainväliselle matkalle tai erillisten datasuunnitelmien ylläpitämisestä henkilökohtaiseen ja liiketoimintaan.',
  ],
  [
    'question' => 'How do I activate eSIM mobile internet with :organisationName?',
    'answer' => 'Yhdistäksesi internetiin käyttäen :organisationName eSIMiä, seuraa näitä vaiheita: 1. Siirry mobiilidatayhteyden asetuksiin. 2. Ota käyttöön :organisationName mobiililinja. 3. Aktivoi dataroaming. 4. Valitse :organisationName Internet-linja ensisijaiseksi yhteydeksi. *Vältä valitsemasta vaihtoehtoa "Poista datasuunnitelma", sillä tämä poistaa eSIM-profiilisi.*',
  ],
  [
    'question' => 'Voinko soittaa puheluita tai lähettää tekstiviestejä?',
    'answer' => ':organisationName\'n ennakkomaksulliset eSIM-suunnitelmat on suunniteltu vain datakäyttöön, eikä niihin sisälly matkapuhelinnumeroa perinteisiä puheluja tai SMS-viestejä varten. Suosittelemme käyttämään VoIP-sovelluksia, kuten Facebook Messenger, WhatsApp, Viber, Telegram tai Skype, pysyäksesi yhteydessä maailmanlaajuisesti ilman tarvetta tavalliselle kansainväliselle SIM-kortille.',
  ],
  [
    'question' => 'Voiko eSIM-korttia käyttää uudelleen?',
    'answer' => 'Jokainen eSIMille tarkoitettu QR-koodi on ainutlaatuinen ja sitä voidaan käyttää vain yhdellä laitteella. Kun eSIM-profiili on poistettu, QR-koodia ei voi käyttää uudelleen samalla tai toisella laitteella, mikä varmistaa turvallisuuden ja yksinoikeuden.',
  ],
  [
    'question' => 'Milloin eSIM-mobiilidatapakettien kesto alkaa?',
    'answer' => 'eSIM-datapaketin kesto alkaa heti, kun laitteesi ensimmäisen kerran yhdistää mobiiliverkkoon eSIMin kanssa.',
  ],
  [
    'question' => 'Voinko pidentää nykyisen eSIM-mobiilidatapaketin voimassaoloa?',
    'answer' => 'Varmasti! Saat useita push-ilmoituksia, kun olet melkein loppumassa pakettisi. Voit helposti ladata lisää henkilökohtaisen portaalisi kautta.',
  ],
  [
    'question' => 'Can I use tethering or Personal Hotspot with :organisationName?',
    'answer' => 'Kyllä, voit jakaa mobiilidatasi muille laitteille :organisationName-eSIMsi kautta. Asenna vain :organisationName-eSIM laitteeseesi ja aktivoi Henkilökohtainen hotspot asetuksissasi. Tämä ominaisuus sisältyy ilman lisäkustannuksia, mutta huomioithan, että jaetun datan käyttö vähennetään suunnitelmastasi.',
  ],
  [
    'question' => 'Can I keep my personal messaging app numbers while using the eSIM from :organisationName?',
    'answer' => 'Kyllä, voit jatkaa WhatsAppin, Snapchatin, Telegramin ja muiden viestisovellusten käyttöä yhdessä :organisationName ennakkomaksullisen eSIMin kanssa ilman ongelmia.',
  ],
  [
    'question' => 'Miten voin siirtää eSIMni uuteen puhelimeen?',
    'answer' => 'Ennen siirtoa varmista, että uusi älypuhelimesi tukee eSIM-teknologiaa. Ota yhteyttä tukitiimiimme luodaksesi uuden eSIM-profiilin, ja kirjaudu sitten :organisationName-tilillesi uudella laitteella asentaaksesi QR-koodin. Varmista, että vahvistat käyttäväsi eri laitetta tarkkojen asetuspäivitysten saamiseksi.',
  ],
  [
    'question' => 'Onko olemassa sopimuksia, kuten perinteisten eSIM-palveluntarjoajien?',
    'answer' => 'Ei, :organisationName ei vaadi sinua allekirjoittamaan sopimuksia. Voit aktivoida tai deaktivoida eSIM-korttisi haluamallasi tavalla suunnitelmiesi mukaan. Olemme iloisia voidessamme auttaa sinua.',
  ],
  [
    'question' => 'What is the difference between :organisationName\'s eSIM and standard roaming data plans from physical mobile operators?',
    'answer' => ':organisationName tarjoaa sopimuksettomia datasuunnitelmia ilman piilotettuja roaming-kustannuksia. Maksat vain käyttämästäsi datasta, riippuen valitsemastasi paketista, mikä tekee siitä usein taloudellisemman vaihtoehdon.',
  ],
  [
    'question' => 'Miksi tietoni nopeus on hidas?',
    'answer' => 'Tietojen nopeuteen voivat vaikuttaa erilaiset tekijät, mukaan lukien älypuhelimesi tyyppi, verkko- ja teknologia, käyttämäsi verkkosivustot tai sovellukset sekä vuorokauden aika. Lisäksi nopeudet voivat vaihdella maan verkoinfrastruktuurin mukaan. Jos koet hitaita nopeuksia, yritä käynnistää puhelimesi uudelleen ja jaa kanssamme kaikki nopeustulokset, erityisesti vertailut :LTE-tilan ollessa päällä ja pois päältä.',
  ],
  [
    'question' => 'Kuinka voin tarkastella pakettejani?',
    'answer' => 'Voit seurata jäljellä olevaa dataasi ja rajoituksiasi asiakaspaneelissamme.',
  ],
  [
    'question' => 'What makes :organisationName different from other eSIM services?',
    'answer' => ':organisationName erottuu yhteistyöllään paikallisten operaattoreiden kanssa yli 200 maassa, tarjoten kustannustehokkaita datapaketteja ilman välikäsiä. Tarjoamme vahvan kattavuuden ja yksinkertaisen aktivointiprosessin. :organisationName on täydellinen matkailijoille, jotka etsivät mobiili-internetratkaisuja.',
  ],
];
