<?php

//This file is automatically generated. Do not modify.

return [
  'title' => 'Stay connected online in :countryName',
  'subtitle' => 'Traveling to :countryName? Stay connected with our eSIM, ensuring you have instant internet access upon arrival.',
  'features' => [
    [
      'title' => 'Luotettavasti ja nopeasti verkossa :countryName',
      'subtitle' => ':countryName on kaunis matkakohde, jossa on eloisia moderneja kaupunkeja ja henkeäsalpaavia luonnonmaisemia. Paranna matkakokemustasi eSIMllämme, joka varmistaa, että pysyt yhteydessä heti saapuessasi.
        Sano hyvästit paikallisen SIM-kortin etsimisen vaivannäölle tai kalliille dataroamingille. eSIMllämme nautit saumattomasta pääsystä 4G/5G-verkkoihin maan parhaiden tarjoajien kautta, pitäen sinut online missä tahansa matkasi viekään.',
      'image' => 'images/features/feature1.jpg',
    ],
    [
      'title' => 'Pysy yhteydessä rakkaisiin.',
      'subtitle' => 'eSIMimme on suunniteltu saumattomaan internet-yhteyteen, pitäen sinut yhteydessä kaikkiin verkkotoimintoihisi ilman tarvetta uudelle puhelinnumerolle. Luo helposti hotspot jakaaksesi yhteytesi muiden matkustajien tai perheen kanssa, ominaisuus, jota muut palveluntarjoajat usein estävät, mutta jota me tuemme täysin. Nauti eSIM-yhteensopivien laitteiden välittömästä yhteydestä, varmistaen, että sinä ja rakkaasi pysytte verkossa milloin tahansa, missä tahansa. Vahvista, tukevatko laitteesi eSIM:ää varmistaaksesi, että olet valmis internet-tarjouksiimme. Huomaa, että puhelut ja tekstiviestit eivät ole tuettuja eSIMllämme.',
      'image' => 'images/features/feature2.jpg',
    ],
  ],
];
