<?php

//This file is automatically generated. Do not modify.

return [
  'all_rights_reserved' => 'Kaikki oikeudet pidätetään.',
  'foreign_currencies_for_reference_only' => 'Ulkomaiset valuutat ovat vain viitteellisiä. Laskutus tapahtuu euroissa.',
];
