<?php

//This file is automatically generated. Do not modify.

return [
  'from' => ':price/GB',
  'title' => 'Yhdistä globaalisti eSIMiemme avulla',
  'subtitle' => 'Tutustu eSIM-paketteihimme ja pysy yhteydessä, missä ikinä oletkin!',
  'search_destination' => 'Löydä kohde',
  'show_all_esim' => 'Näytä kaikki eSIM-suunnitelmat',
  'how_it_works' => 'Miten se toimii?',
  'steps' => [
    [
      'title' => 'Vaihe 1',
      'description' => 'Tarkista, onko laitteesi eSIM-yhteensopiva yhteensopivuuslistaltamme.',
    ],
    [
      'title' => 'Vaihe 2',
      'description' => 'Valitse kohteesi ja haluamasi eSIM-tietosuunnitelma',
    ],
    [
      'title' => 'Vaihe 3',
      'description' => 'Osta eSIM-kortti, joka parhaiten vastaa tarpeitasi',
    ],
    [
      'title' => 'Vaihe 4',
      'description' => 'eSIM: toimitetaan automaattisesti. Seuraa ohjeita sähköpostissasi.',
    ],
    [
      'title' => 'Vaihe 5',
      'description' => 'Asenna eSIM-profiilisi ja nauti matkasta!',
    ],
  ],
  'supported_networks' => 'Tuetut verkkopalveluntarjoajat',
  'supported_networks_description' => 'Teemme tiivistä yhteistyötä luotettavien markkinajohtajien, kuten connectivity, media ja technology brändien kanssa ympäri maailmaa.',
  'and_many_more' => 'ja paljon muuta...',
  'user_reviews' => 'Mitä tyytyväiset käyttäjämme sanovat',
  'user_reviews_subtitle' => 'Näe, miksi matkustajat ympäri maailmaa luottavat eSIMimme saumattomaan ja luotettavaan yhteyteen liikkeellä ollessaan.',
  'faq' => 'Usein kysytyt kysymykset',
  'popular_destinations' => 'Suositut kohteet',
  'popular_destinations_description' => 'Tutustu suosituimpiin eSIM-kohteisiimme ja pysy yhteydessä, missä tahansa oletkin!',
  'see_all_destinations' => 'Näytä kaikki kohteet',
];
