<?php

//This file is automatically generated. Do not modify.

return [
  'home' => 'Koti',
  'supported-devices' => 'Tuetut laitteet',
  'destinations' => 'Kaikki kohteet',
  'about' => 'Tietoja',
  'contact' => 'Yhteystiedot',
  'portal_link' => 'Oma Portaalini',
];
