<?php

//This file is automatically generated. Do not modify.

return [
  'days' => 'päivät',
  'buy_plan' => 'Osta nyt!',
  'perks' => [
    'instant' => 'Suora toimitus',
    'advanced_self_service' => 'Edistynyt itsepalveluportaalin',
    '247_support' => '24/7 live chat -tuki',
    'prepaid' => 'Ennakkomaksu, ei ehtoja liitettynä',
    'no_roaming' => 'Ei roaming-maksuja',
  ],
  'local_for' => 'Paikalliset eSIMit :countryName varten',
  'not_available_yet' => 'Emme tällä hetkellä tarjoa eSIM-kortteja tälle maalle.',
  'not_available_yet_contact_us' => 'Teemme kovasti töitä laajentaaksemme globaalia kattavuuttamme. Jos olet kiinnostunut eSIM: -ratkaisuista tässä maassa, ota meihin yhteyttä.',
  'top_plan' => 'Suosituin',
  'all_features' => 'Kaikki toiminnot',
  'features' => [
    'feature_one' => 'Mahdollinen kuuma kohta',
    'feature_two' => 'Peitto kaikilla kansallisilla verkoilla',
    'feature_three' => 'Yksinkertainen päivitys henkilökohtaisessa portaalissasi',
  ],
  'buy_now' => 'Osta nyt',
  'starting_from' => 'Aloittaen kohdasta',
  'choose_destination' => 'Löydä kohde',
  'how_esim_works' => [
    'title' => 'Kuinka eSIM toimii',
    'subtitle' => 'eSIMin käyttöönotto on helppoa! Seuraa näitä yksinkertaisia vaiheita pysyäksesi yhteydessä.',
    'steps' => [
      [
        'title' => 'Osta eSIMsi',
        'description' => 'Valitse määränpääsi, valitse paketti, joka täyttää tietotarpeesi, ja viimeistele ostoksesi.',
        'image' => '/images/howesimworks/1.png',
      ],
      [
        'title' => 'Vastaanota eSIMisi',
        'description' => 'Saat eSIM QR-koodisi suoraan sähköpostiisi. Valmis käytettäväksi heti.',
        'image' => '/images/howesimworks/2.png',
      ],
      [
        'title' => 'Aktivoi ja Yhdistä',
        'description' => 'Skannaa QR-koodi, aktivoi eSIM ja nauti nopeasta, luotettavasta datasta missä tahansa matkustat.',
        'image' => '/images/howesimworks/3.png',
      ],
    ],
  ],
  'sub_description' => 'Valitse alla oleva paketti ja nauti saumattomasta yhteydestä :countryName parhailla verkoilla parhaaseen hintaan.',
];
