<?php

//This file is automatically generated. Do not modify.

return [
  'title' => 'eSIM-palvelu - Ennakkomaksulliset virtuaaliset SIM-kortit matkailijoille - :site_name',
  'description' => 'eSIM-palvelu ⏩ Esimaksulliset digitaaliset SIM-kortit matkailua ja liiketoimintaa varten ⏩ Standardi- ja rajattomat, paikalliset ja globaalit matkapuhelindatapalvelut ⏩ Ei sopimuksia ✅ Ei piilotettuja roaming-maksuja ja -kuluja ✅ - :site_name',
  'keywords' => 'eSIM, eSIM-palvelu, eSIM-kortti, eSIM-data, eSIM-datapaketti, eSIM-datapaketteja, eSIM-datapaketti matkailijoille, eSIM-datapaketti turisteille, eSIM-datapaketti yrityksille, eSIM-datapaketti matkustamiseen, eSIM-datapaketti Eurooppaan, eSIM-datapaketti Yhdysvaltoihin, eSIM-datapaketti Aasiaan, eSIM-datapaketti Afrikkaan, eSIM-datapaketti Australiaan, eSIM-datapaketti Etelä-Amerikkaan, eSIM-datapaketti Pohjois-Amerikkaan, eSIM-datapaketti Lähi-itään, eSIM-datapaketti Venäjälle, eSIM-datapaketti Kiinaan, eSIM-datapaketti Intiaan, eSIM-datapaketti Japaniin',
  'routes' => [
    'home' => [
      'title' => 'eSIM-palvelu - Ennakkomaksulliset virtuaaliset SIM-kortit matkailijoille - :site_name',
      'description' => 'eSIM-palvelu ⏩ Ennakkomaksulliset digitaaliset SIM-kortit matkailua ja liiketoimintaa varten ⏩ Standardi- ja rajattomat, paikalliset ja globaalit matkapuhelindatapalvelut ⏩ Ei sopimuksia ✅ Ei piilotettuja roaming-maksuja ja -kuluja ✅ - :site_name',
    ],
    'about' => [
      'title' => 'Tietoa meistä - :site_name',
      'description' => 'Meistä ⏩ Ennakkomaksulliset digitaaliset SIM-kortit matkailua ja liiketoimintaa varten ⏩ Standardi- ja rajattomat, paikalliset ja globaalit matkapuhelindatapalvelut ⏩ Ei sopimuksia ✅ Ei piilotettuja roaming-maksuja ja -kuluja ✅ - :site_name',
    ],
    'supported-devices' => [
      'title' => 'Tuetut laitteet - :site_name',
      'description' => 'Tuetut laitteet ⏩ Ennakkomaksulliset digitaaliset SIM-kortit matkailua ja liiketoimintaa varten ⏩ Standardi- ja rajattomat, paikalliset ja globaalit matkapuhelindatapaketit ⏩ Ei sopimuksia ✅ Ei piilotettuja roaming-maksuja ja -kuluja ✅ - :site_name',
    ],
    'esim-bundle-per-country' => [
      'title' => 'Edulliset paikalliset eSIM-tarjoukset :countryName - :site_name',
      'description' => 'Edulliset paikalliset eSIM-tarjoukset :countryName ⏩ Ennakkomaksulliset digitaaliset SIM-kortit matkailua ja liiketoimintaa varten ⏩ Standardi- ja rajattomat, paikalliset ja globaalit matkapuhelindatapalvelut ⏩ Ei sopimuksia ✅ Ei piilossa olevia roaming-maksuja ja -kuluja ✅ - :site_name',
    ],
  ],
];
