<?php

//This file is automatically generated. Do not modify.

return [
  'title' => 'eSIM-palvelu - Ennakkomaksulliset virtuaaliset SIM-kortit matkailijoille - :site_name',
  'description' => 'eSIM-palvelu ⏩ Ennakkomaksulliset digitaaliset SIM-kortit matkailua ja liiketoimintaa varten ⏩ Standardi ja rajattomat, paikalliset ja globaalit mobiilidatapaketit ⏩ Ei sopimuksia ✅ Ei piilokuluja ja -korvauksia ✅ - :site_name',
  'keywords' => 'eSIM, eSIM-palvelu, eSIM-kortti, eSIM-tiedot, eSIM-tietosuunnitelma, eSIM-tietosuunnitelmat, eSIM-tietosuunnitelma matkustajille, eSIM-tietosuunnitelma turisteille, eSIM-tietosuunnitelma yrityksille, eSIM-tietosuunnitelma matkustamiseen, eSIM-tietosuunnitelma Eurooppaan, eSIM-tietosuunnitelma Yhdysvaltoihin, eSIM-tietosuunnitelma Aasiaan, eSIM-tietosuunnitelma Afrikkaan, eSIM-tietosuunnitelma Australiaan, eSIM-tietosuunnitelma Etelä-Amerikkaan, eSIM-tietosuunnitelma Pohjois-Amerikkaan, eSIM-tietosuunnitelma Lähi-itään, eSIM-tietosuunnitelma Venäjälle, eSIM-tietosuunnitelma Kiinaan, eSIM-tietosuunnitelma Intiaan, eSIM-tietosuunnitelma Japaniin',
  'routes' => [
    'home' => [
      'title' => 'eSIM-palvelu - Esimaksulliset virtuaaliset SIM-kortit matkailijoille - :site_name',
      'description' => 'eSIM-palvelu ⏩ Ennakkomaksulliset digitaaliset SIM-kortit matkailua ja liiketoimintaa varten ⏩ Standardi- ja rajoittamattomat, paikalliset ja maailmanlaajuiset mobiilidatapaketit ⏩ Ei sopimuksia ✅ Ei piilossa olevia roaming-kustannuksia ja -korvauksia ✅ - :site_name',
    ],
    'about' => [
      'title' => 'Meistä - :site_name',
      'description' => 'Meistä ⏩ Ennakkoon maksetut digitaaliset SIM-kortit matkailua ja liiketoimintaa varten ⏩ Vakiot ja rajattomat, paikalliset ja globaalit mobiilidatapaketit ⏩ Ei sopimuksia ✅ Ei piilokuluja tai -maksuja ✅ - :site_name',
    ],
    'supported-devices' => [
      'title' => 'Tuetut laitteet - :site_name',
      'description' => 'Tuetut laitteet ⏩ Ennakkomaksulliset digitaaliset SIM-kortit matkailua ja liiketoimintaa varten ⏩ Standardi ja rajoittamaton, paikallinen ja maailmanlaajuinen mobiilidatapaketit ⏩ Ei sopimuksia ✅ Ei piilokuluja tai -korvauksia ✅ - :site_name',
    ],
    'esim-bundle-per-country' => [
      'title' => 'eSIM :countryName - :site_name',
      'description' => 'eSIM :countryName ⏩ Esim-kortit matkailuun ja liiketoimintaan ⏩ Standardi- ja rajattomat, paikalliset ja globaalit mobiilidatayhteydet ⏩ Ei sopimuksia ✅ Ei piilossa olevia roamingmaksuja tai -korvauksia ✅ - :site_name',
    ],
  ],
];
