<?php

//This file is automatically generated. Do not modify.

return [
  'Rens' => [
    'role' => 'Toimitusjohtaja',
    'image' => '/images/team/rens.png',
  ],
  'Luuk' => [
    'role' => 'Co-Founder',
    'image' => '/images/team/luuk.png',
  ],
  'Fleur' => [
    'role' => 'Asiakastuki',
    'image' => '/images/team/fleur.png',
  ],
  'Patrick' => [
    'role' => 'Kehittäjä',
    'image' => '/images/team/patrick.png',
  ],
];
