<?php

//This file is automatically generated. Do not modify.

return [
  'title' => 'Todos os nossos destinos',
  'subtitle' => 'Onde quer que você vá, temos tudo coberto com eSIMs para cada destino. Escolha seu destino abaixo para começar.',
];
