<?php

//This file is automatically generated. Do not modify.

return [
  'title' => 'Fique conectado online em :countryName',
  'subtitle' => 'Viajando para :countryName? Fique conectado com nosso eSIM, garantindo que você tenha acesso instantâneo à internet ao chegar.',
  'features' => [
    [
      'title' => 'Confiável e rápido online em :countryName',
      'subtitle' => ':countryName é um destino lindo, com cidades modernas vibrantes e paisagens naturais deslumbrantes. Melhore sua experiência de viagem com nosso eSIM, garantindo que você permaneça conectado instantaneamente ao chegar.
        Diga adeus à dificuldade de procurar um cartão SIM local ou lidar com tarifas de roaming de dados caras. Com nosso eSIM, você desfrutará de acesso contínuo às redes 4G/5G dos principais provedores do país, mantendo você online onde quer que sua jornada o leve.',
      'image' => 'images/features/feature1.jpg',
    ],
    [
      'title' => 'Fique conectado com entes queridos',
      'subtitle' => 'Nossa eSIM é projetada para acesso à internet sem interrupções, mantendo você conectado para todas as suas atividades online sem a necessidade de um novo número de telefone. Crie facilmente um hotspot para compartilhar sua conexão com outros viajantes ou familiares, um recurso frequentemente bloqueado por outros provedores, mas totalmente suportado por nós. Aproveite a conveniência da conectividade instantânea em dispositivos compatíveis com eSIM, garantindo que você e seus entes queridos permaneçam online a qualquer hora, em qualquer lugar. Por favor, confirme se seu dispositivo suporta eSIM para garantir que você esteja pronto para nossas ofertas de internet. Observe que chamadas e mensagens de texto não são suportadas com nossa eSIM.',
      'image' => 'images/features/feature2.jpg',
    ],
  ],
];
