<?php

//This file is automatically generated. Do not modify.

return [
  'from' => ':price/GB',
  'title' => 'Conecte-se globalmente com nossos eSIMs',
  'subtitle' => 'Explore nossos pacotes de eSIM e fique conectado, onde quer que você esteja!',
  'search_destination' => 'Encontre um destino',
  'show_all_esim' => 'Mostre todos os planos de eSIM',
  'how_it_works' => 'Como funciona?',
  'steps' => [
    [
      'title' => 'Passo 1',
      'description' => 'Verifique se o seu dispositivo é compatível com eSIM na nossa lista de compatibilidade.',
    ],
    [
      'title' => 'Passo 2',
      'description' => 'Escolha seu destino e o plano de dados eSIM desejado',
    ],
    [
      'title' => 'Passo 3',
      'description' => 'Compre o cartão eSIM que melhor se adapta às suas necessidades',
    ],
    [
      'title' => 'Passo 4',
      'description' => 'Seu eSIM será entregue automaticamente. Siga as instruções no seu e-mail.',
    ],
    [
      'title' => 'Passo 5',
      'description' => 'Instale seu perfil eSIM e aproveite sua viagem!',
    ],
  ],
  'supported_networks' => 'Provedores de rede suportados',
  'supported_networks_description' => 'Trabalhamos em estreita colaboração com marcas de conectividade, mídia e tecnologia líderes de mercado e confiáveis em todo o mundo.',
  'and_many_more' => 'e muito mais...',
  'user_reviews' => 'O que nossos usuários satisfeitos dizem',
  'user_reviews_subtitle' => 'Veja por que viajantes de todo o mundo confiam em nosso eSIM para conectividade contínua e confiável em movimento.',
  'faq' => 'Perguntas Frequentes',
  'popular_destinations' => 'Destinos Populares',
  'popular_destinations_description' => 'Descubra nossos destinos de eSIM mais populares e mantenha-se conectado, não importa onde você vá!',
  'see_all_destinations' => 'Ver todos os destinos',
];
