<?php

//This file is automatically generated. Do not modify.

return [
  'days' => 'dias',
  'buy_plan' => 'Compre agora!',
  'perks' => [
    'instant' => 'Entrega direta',
    'advanced_self_service' => 'Portal de autoatendimento avançado',
    '247_support' => 'suporte de chat ao vivo 24/7',
    'prepaid' => 'Pré-pago, sem condições anexas',
    'no_roaming' => 'Sem taxas de roaming',
  ],
  'local_for' => 'eSIMs locais para :countryName',
  'not_available_yet' => 'Atualmente, não oferecemos eSIMs para este país.',
  'not_available_yet_contact_us' => 'Estamos trabalhando arduamente para expandir nossa cobertura global. Se você estiver interessado em eSIMs para este país enquanto isso, entre em contato conosco.',
  'top_plan' => 'Mais popular',
  'all_features' => 'Todas as funções',
  'features' => [
    'feature_one' => 'Possível ponto quente',
    'feature_two' => 'Cobertura em todas as redes nacionais',
    'feature_three' => 'Atualização simples no seu portal pessoal',
  ],
  'buy_now' => 'Compre agora',
  'starting_from' => 'Começando a partir de',
  'choose_destination' => 'Encontre um destino',
  'how_esim_works' => [
    'title' => 'Como funciona o eSIM',
    'subtitle' => 'Começar com eSIM é fácil! Siga estas etapas simples para se manter conectado.',
    'steps' => [
      [
        'title' => 'Compre seu eSIM',
        'description' => 'Escolha seu destino, selecione um pacote que atenda às suas necessidades de dados e complete sua compra.',
        'image' => '/images/howesimworks/1.png',
      ],
      [
        'title' => 'Receba seu eSIM',
        'description' => 'Receba seu código QR de eSIM diretamente no seu e-mail. Pronto para uso imediato.',
        'image' => '/images/howesimworks/2.png',
      ],
      [
        'title' => 'Ativar e Conectar',
        'description' => 'Escaneie o código QR, ative seu eSIM e aproveite dados rápidos e confiáveis onde quer que você viaje.',
        'image' => '/images/howesimworks/3.png',
      ],
    ],
  ],
  'sub_description' => 'Escolha seu pacote abaixo e desfrute de conectividade sem interrupções em :countryName nas melhores redes pelo melhor preço.',
];
