<?php

//This file is automatically generated. Do not modify.

return [
  'title' => 'Serviço eSIM - Cartões SIM Virtuais Pré-pagos para Viajantes - :site_name',
  'description' => 'Serviço eSIM ⏩ Cartões SIM digitais pré-pagos para turismo e negócios ⏩ Planos de dados móveis padrão e ilimitados, locais e globais ⏩ Sem contratos ✅ Sem taxas e encargos de roaming ocultos ✅ - :site_name',
  'keywords' => 'eSIM, serviço eSIM, cartão eSIM, dados eSIM, plano de dados eSIM, planos de dados eSIM, plano de dados eSIM para viajantes, plano de dados eSIM para turistas, plano de dados eSIM para negócios, plano de dados eSIM para viagens, plano de dados eSIM para a Europa, plano de dados eSIM para os EUA, plano de dados eSIM para a Ásia, plano de dados eSIM para a África, plano de dados eSIM para a Austrália, plano de dados eSIM para a América do Sul, plano de dados eSIM para a América do Norte, plano de dados eSIM para o Oriente Médio, plano de dados eSIM para a Rússia, plano de dados eSIM para a China, plano de dados eSIM para a Índia, plano de dados eSIM para o Japão',
  'routes' => [
    'home' => [
      'title' => 'Serviço eSIM - Cartões SIM Virtuais Pré-Pagos para Viajantes - :site_name',
      'description' => 'serviço eSIM ⏩ Cartões SIM digitais pré-pagos para turismo e negócios ⏩ Planos de dados para celular padrão e ilimitados, locais e globais ⏩ Sem contratos ✅ Sem taxas e encargos de roaming ocultos ✅ - :site_name',
    ],
    'about' => [
      'title' => 'Sobre Nós - :site_name',
      'description' => 'Sobre Nós ⏩ Cartões SIM digitais pré-pagos para turismo e negócios ⏩ Planos de dados para celular padrão e ilimitados, locais e globais ⏩ Sem contratos ✅ Sem taxas e encargos de roaming ocultos ✅ - :site_name',
    ],
    'supported-devices' => [
      'title' => 'Dispositivos Suportados - :site_name',
      'description' => 'Dispositivos Suportados ⏩ Cartões SIM digitais pré-pagos para turismo e negócios ⏩ Planos de dados para celular padrão e ilimitados, locais e globais ⏩ Sem contratos ✅ Sem taxas e encargos de roaming ocultos ✅ - :site_name',
    ],
    'esim-bundle-per-country' => [
      'title' => 'Ofertas de eSIM locais acessíveis para :countryName - :site_name',
      'description' => 'Ofertas de eSIM locais acessíveis para :countryName ⏩ Cartões SIM digitais pré-pagos para turismo e negócios ⏩ Planos de dados para celular locais e globais, padrão e ilimitados ⏩ Sem contratos ✅ Sem taxas e encargos de roaming ocultos ✅ - :site_name',
    ],
  ],
];
