<?php

//This file is automatically generated. Do not modify.

return [
  'first' => 'مُصنَّف 4.5/5 على Trustpilot',
  'second' => 'دعم على مدار الساعة طوال الأسبوع',
  'third' => 'فقط أفضل الشبكات',
];
