<?php

//This file is automatically generated. Do not modify.

return [
  'title' => 'الأجهزة المدعومة',
  'subtitle' => 'نحن ندعم مجموعة واسعة من الأجهزة. تحقق مما إذا كان جهازك موجودًا في القائمة أدناه. يتم تنظيم الأجهزة حسب الشركة المصنعة.',
  'models_below' => 'النماذج المدعومة مدرجة أدناه.',
];
