<?php

//This file is automatically generated. Do not modify.

return [
  'all_rights_reserved' => 'جميع الحقوق محفوظة.',
  'foreign_currencies_for_reference_only' => 'العملات الأجنبية هي للرجوع فقط. ستتم الفوترة باليورو.',
];
