<?php

//This file is automatically generated. Do not modify.

return [
  'from' => ':price/GB',
  'title' => 'تواصل عالميًا مع eSIMs لدينا',
  'subtitle' => 'استكشف باقات eSIM الخاصة بنا وابق على اتصال، أينما كنت!',
  'search_destination' => 'ابحث عن وجهة',
  'show_all_esim' => 'عرض جميع خطط eSIM',
  'how_it_works' => 'كيف تعمل؟',
  'steps' => [
    [
      'title' => 'الخطوة 1',
      'description' => 'تحقق مما إذا كان جهازك متوافقًا مع eSIM في قائمة التوافق لدينا.',
    ],
    [
      'title' => 'الخطوة 2',
      'description' => 'اختر وجهتك وخطة بيانات eSIM المرغوبة',
    ],
    [
      'title' => 'الخطوة 3',
      'description' => 'اشترِ بطاقة eSIM التي تناسب احتياجاتك أفضل',
    ],
    [
      'title' => 'الخطوة 4',
      'description' => 'سيتم تسليم eSIM الخاصة بك تلقائيًا. اتبع التعليمات في بريدك الإلكتروني.',
    ],
    [
      'title' => 'الخطوة 5',
      'description' => 'قم بتثبيت ملف eSIM الخاص بك واستمتع برحلتك!',
    ],
  ],
  'supported_networks' => 'موفرو الشبكة المدعومين',
  'supported_networks_description' => 'نحن نعمل عن كثب مع علامات تجارية موثوقة رائدة في السوق في مجالات الاتصال والإعلام والتكنولوجيا حول العالم.',
  'and_many_more' => 'والمزيد...',
  'user_reviews' => 'ماذا يقول مستخدمونا الراضون',
  'user_reviews_subtitle' => 'اكتشف لماذا يعتمد المسافرون حول العالم على eSIM الخاصة بنا لتوفير اتصال سلس وموثوق أثناء التنقل.',
  'faq' => 'الأسئلة المتكررة',
  'popular_destinations' => 'وجهات شعبية',
  'popular_destinations_description' => 'اكتشف وجهات eSIM الأكثر شعبية لدينا وابق متصلاً، بغض النظر عن المكان الذي تذهب إليه!',
  'see_all_destinations' => 'عرض جميع الوجهات',
];
