<?php

//This file is automatically generated. Do not modify.

return [
  'home' => 'الصفحة الرئيسية',
  'supported-devices' => 'الأجهزة المدعومة',
  'destinations' => 'جميع الوجهات',
  'about' => 'حول',
  'contact' => 'اتصل',
  'portal_link' => 'بوابتي',
];
