<?php

//This file is automatically generated. Do not modify.

return [
  'days' => 'أيام',
  'buy_plan' => 'اشترِ الآن!',
  'perks' => [
    'instant' => 'توصيل مباشر',
    'advanced_self_service' => 'بوابة الخدمة الذاتية المتقدمة',
    '247_support' => 'دعم الدردشة المباشرة على مدار الساعة طوال الأسبوع',
    'prepaid' => 'مدفوع مسبقاً، دون شروط attached',
    'no_roaming' => 'لا رسوم تجوال',
  ],
  'local_for' => 'eSIMs محلية لـ :countryName',
  'not_available_yet' => 'نحن حاليًا لا نقدم eSIMs لهذا البلد.',
  'not_available_yet_contact_us' => 'نحن نعمل بجد لتوسيع تغطيتنا العالمية. إذا كنت مهتمًا بـ eSIMs لهذا البلد في هذه الأثناء، يرجى الاتصال بنا.',
  'top_plan' => 'الأكثر شعبية',
  'all_features' => 'جميع الوظائف',
  'features' => [
    'feature_one' => 'نقطة ساخنة محتملة',
    'feature_two' => 'التغطية عبر جميع الشبكات الوطنية',
    'feature_three' => 'ترقية بسيطة في بوابتك الشخصية',
  ],
  'buy_now' => 'اشترِ الآن',
  'starting_from' => 'بدءًا من',
  'choose_destination' => 'ابحث عن وجهة',
  'how_esim_works' => [
    'title' => 'كيف تعمل eSIM',
    'subtitle' => 'البدء مع eSIM سهل! اتبع هذه الخطوات البسيطة للبقاء متصلاً.',
    'steps' => [
      [
        'title' => 'اشترِ eSIM الخاصة بك',
        'description' => 'اختر وجهتك، اختر حزمة تناسب احتياجات بياناتك، وأكمل عملية الشراء.',
        'image' => '/images/howesimworks/1.png',
      ],
      [
        'title' => 'استلم eSIM الخاص بك',
        'description' => 'استلم رمز الاستجابة السريعة eSIM الخاص بك مباشرة في بريدك الإلكتروني. جاهز للاستخدام على الفور.',
        'image' => '/images/howesimworks/2.png',
      ],
      [
        'title' => 'تفعيل و الاتصال',
        'description' => 'امسح رمز الاستجابة السريعة، قم بتفعيل eSIM الخاصة بك، واستمتع ببيانات سريعة وموثوقة أينما سافرت.',
        'image' => '/images/howesimworks/3.png',
      ],
    ],
  ],
  'sub_description' => 'اختر حزمة من الأسفل واستمتع باتصال سلس في :countryName على أفضل الشبكات بأفضل الأسعار.',
];
