<?php

//This file is automatically generated. Do not modify.

return [
  'title' => 'خدمة eSIM - بطاقات SIM افتراضية مسبقة الدفع للمسافرين - :site_name',
  'description' => 'eSIM-service ⏩ بطاقات SIM رقمية مسبقة الدفع للسياحة والأعمال ⏩ خطط بيانات محلية وعالمية قياسية وغير محدودة ⏩ لا عقود ✅ لا رسوم تجوال مخفية أو تعويضات ✅ - :site_name',
  'keywords' => 'eSIM، eSIM-service، eSIM-kaart، eSIM-gegevens، eSIM-gegevensplan، eSIM-gegevensplannen، eSIM-gegevensplan voor reizigers، eSIM-gegevensplan voor toeristen، eSIM-gegevensplan voor bedrijven، eSIM-gegevensplan voor reizen، eSIM-gegevensplan voor Europa، eSIM-gegevensplan voor de VS، eSIM-gegevensplan voor Azië، eSIM-gegevensplan voor Afrika، eSIM-gegevensplan voor Australië، eSIM-gegevensplan voor Zuid-Amerika، eSIM-gegevensplan voor Noord-Amerika، eSIM-gegevensplan voor het Midden-Oosten، eSIM-gegevensplan voor Rusland، eSIM-gegevensplan voor China، eSIM-gegevensplan voor India، eSIM-gegevensplan voor Japan',
  'routes' => [
    'home' => [
      'title' => 'خدمة eSIM - بطاقات SIM افتراضية مدفوعة مسبقًا للمسافرين - :site_name',
      'description' => 'خدمة eSIM ⏩ بطاقات SIM رقمية مسبقة الدفع للسياحة والأعمال ⏩ خطط بيانات محلية وعالمية قياسية وغير محدودة ⏩ لا عقود ✅ لا رسوم تجوال مخفية أو تعويضات ✅ - :site_name',
    ],
    'about' => [
      'title' => 'حولنا - :site_name',
      'description' => 'عنّا ⏩ بطاقات SIM الرقمية المدفوعة مسبقًا للسياحة والأعمال ⏩ خطط بيانات محلية وعالمية قياسية وغير محدودة ⏩ لا عقود ✅ لا رسوم أو تكاليف تجوال مخفية ✅ - :site_name',
    ],
    'supported-devices' => [
      'title' => 'الأجهزة المدعومة - :site_name',
      'description' => 'أجهزة مدعومة ⏩ بطاقات SIM رقمية مسبقة الدفع للسياحة والأعمال ⏩ خطط بيانات محلية وعالمية قياسية وغير محدودة ⏩ لا عقود ✅ لا تكاليف أو رسوم تجوال مخفية ✅ - :site_name',
    ],
    'esim-bundle-per-country' => [
      'title' => 'eSIM :countryName - :site_name',
      'description' => 'eSIM :countryName ⏩ بطاقات SIM رقمية مسبقة الدفع للسياحة والأعمال ⏩ خطط بيانات محلية وعالمية قياسية وغير محدودة ⏩ لا عقود ✅ لا توجد رسوم تجوال مخفية أو تعويضات ✅ - :site_name',
    ],
  ],
];
