<?php

//This file is automatically generated. Do not modify.

return [
  'Rens' => [
    'role' => 'مؤسس مشارك',
    'image' => '/images/team/rens.png',
  ],
  'Luuk' => [
    'role' => 'المؤسس المشارك',
    'image' => '/images/team/luuk.png',
  ],
  'Fleur' => [
    'role' => 'دعم العملاء',
    'image' => '/صور/فريق/فليور.png',
  ],
  'Patrick' => [
    'role' => 'مطور',
    'image' => '/images/team/patrick.png',
  ],
];
