<?php

//This file is automatically generated. Do not modify.

return [
  'title' => 'Rólunk',
  'subtitle' => 'Navigálj a határok nélküli világban velünk. Mi vagyunk a végső partnered, amely folyamatosan kapcsolatban tart, bárhová is visz a szenvedélyed.',
  'our_team' => 'Csapatunk',
  'our_team_subtitle' => 'Hiszünk abban, hogy a traveler-eket megbízható és megfizethető globális adatkapcsolattal ruházzuk fel. Sokszínű csapatunk egyesült abban, hogy egy még összekapcsoltabb és mindenki számára elérhetőbb világot teremtsen az úton lévők számára.',
  'why_us' => 'Miért válasszon minket',
  'why_us_subtitle' => 'Büszkék vagyunk megbízható szolgáltatásunkra, versenyképes árainkra és ügyfélközpontú megközelítésünkre. Az Ön elégedettsége a legfontosabb számunkra.',
  'why_us_reasons' => [
    [
      'title' => 'Rugalmas tervek az utazási igényeidhez tervezve',
      'subtitle' => 'Válasszon egy sor megfizethető csomagból, amely különböző országokhoz és régiókhoz van igazítva. Rugalmasan választhatja ki a tökéletes adatcsomagot, így csak azért fizet, amire szüksége van, rejtett költségek nélkül.',
      'image' => '/images/whyus/nlo2.png',
    ],
    [
      'title' => 'Közvetlen aktiválás, nincs szükség fizikai SIM-kártyákra',
      'subtitle' => 'A fizikai SIM-kártyák cseréjének napjai véget értek. Nálunk az eSIM közvetlenül e-mailben érkezik, és néhány percen belül aktiválható. Csak olvasd be a QR-kódot, és máris készen állsz a csatlakozásra.',
      'image' => '/images/whyus/nlo3.png',
    ],
  ],
  'contact' => 'Lépjen velünk kapcsolatba',
  'contact_subtitle' => 'Itt vagyunk, hogy segítsünk neked. Ha bármilyen kérdésed van, vagy segítségre van szükséged, kérlek, vedd fel velünk a kapcsolatot.',
];
