<?php

//This file is automatically generated. Do not modify.

return [
  'first' => '4.5/5-re értékelték a Trustpilot-on',
  'second' => '24/7 Támogatás',
  'third' => 'Csak a legjobb hálózatok',
];
