<?php

//This file is automatically generated. Do not modify.

return [
  'title' => 'Minden úti célunk',
  'subtitle' => 'Bárhova is mész, mi fedezünk téged az eSIM-ekkel minden úti célhoz. Válaszd ki az úti célodat az alábbiakban, hogy elkezdhessd.',
];
