<?php

//This file is automatically generated. Do not modify.

return [
  'title' => 'Támogatott eszközök',
  'subtitle' => 'Széles eszközkínálatot támogatunk. Ellenőrizze, hogy az Ön eszköze szerepel-e az alábbi listán. Az eszközök gyártó szerint vannak rendezve.',
  'models_below' => 'A támogatott modellek az alábbiakban találhatók.',
];
