<?php

//This file is automatically generated. Do not modify.

return [
  'faq' => 'GYIK',
  'subtitle' => 'Van kérdése? Nekünk vannak válaszaink. Minden információt megtalál, amire szüksége van az eSIM-jeinkkel kapcsolatban.',
];
