<?php

//This file is automatically generated. Do not modify.

return [
  [
    'question' => 'Mi az eSIM és hogyan használhatom a :organisationName-t?',
    'answer' => 'Az eSIM, vagy beágyazott SIM, egy digitális SIM-kártya, amely lehetővé teszi a felhasználók számára, hogy aktiváljanak és kezeljenek több mobil előfizetést egy eszközön anélkül, hogy fizikai SIM-kártyára lenne szükség. Az eSIM segítségével könnyedén válthat a mobil szolgáltatók között, és élvezheti az olyan funkciókat, mint például egy extra vonal hozzáadása nemzetközi utazás során, vagy külön adatcsomagok fenntartása személyes és üzleti használatra.',
  ],
  [
    'question' => 'Hogyan aktiválom az eSIM mobilinternetet a :organisationName segítségével?',
    'answer' => 'Az internethez való csatlakozáshoz a :organisationName eSIM használatával kövesse az alábbi lépéseket: 1. Menjen a Mobil adatbeállításokhoz. 2. Kapcsolja be a :organisationName mobilvonalat. 3. Aktiválja az Adat roamingot. 4. Válassza a :organisationName Internet vonalat elsődleges kapcsolataként. *Kerülje el az "Adatcsomag eltávolítása" lehetőség kiválasztását, mivel ez törli az eSIM profilját.*',
  ],
  [
    'question' => 'Hívásokat indíthatok vagy üzeneteket küldhetek?',
    'answer' => ':organisationName előre fizetett eSIM csomagjai adatforgalomra lettek tervezve, és nem tartalmaznak mobiltelefonszámot hagyományos hívásokhoz vagy SMS üzenetekhez. Javasoljuk, hogy VoIP alkalmazásokat használjon, mint például a Facebook Messenger, WhatsApp, Viber, Telegram vagy Skype, hogy világszerte kapcsolatban maradhasson anélkül, hogy standard nemzetközi SIM kártyára lenne szüksége.',
  ],
  [
    'question' => 'Újrahasználható egy eSIM kártya?',
    'answer' => 'Minden QR-kód egy eSIM-hez egyedi, és csak egy eszközön használható. Miután az eSIM profil törlésre került, a QR-kód nem használható újra ugyanazon vagy másik eszközön, biztosítva ezzel a biztonságot és az exkluzivitást.',
  ],
  [
    'question' => 'Mikor kezdődik az eSIM mobil adatcsomagok időtartama?',
    'answer' => 'Az eSIM adatcsomagod időtartama azonnal kezdődik, miután az eszközöd először csatlakozik egy mobilhálózathoz az eSIM segítségével.',
  ],
  [
    'question' => 'Meg tudom hosszabbítani a jelenlegi eSIM mobil adatcsomagom lejárati idejét?',
    'answer' => 'Biztosan! Több értesítést fogsz kapni, amikor már majdnem kifogytál a csomagodból. Könnyedén feltöltheted a személyes portálodon keresztül.',
  ],
  [
    'question' => 'Használhatom a tetheringet vagy a Személyes Hotspotot a :organisationName használatával?',
    'answer' => 'Igen, megoszthatja mobil adatát más eszközökkel a :organisationName-eSIM-en keresztül. Egyszerűen telepítse a :organisationName-eSIM-et az eszközére, és aktiválja a Személyes Hotspotot a beállításokban. Ez a funkció extra költség nélkül elérhető, de kérjük, vegye figyelembe, hogy a megosztott adat használata levonásra kerül a csomagjából.',
  ],
  [
    'question' => 'Megőrizhetem a személyes üzenetküldő alkalmazásom számát, miközben a :organisationName eSIM-et használom?',
    'answer' => 'Igen, továbbra is használhatja a WhatsApp, Snapchat, Telegram és egyéb üzenetküldő alkalmazásait a :organisationName előre fizetett eSIM mellett, problémák nélkül.',
  ],
  [
    'question' => 'Hogyan tudom átkonvertálni az eSIM-emet egy új telefonra?',
    'answer' => 'Mielőtt átkapcsolna, győződjön meg arról, hogy az új okostelefonja támogatja az eSIM technológiát. Lépjen kapcsolatba a támogatói csapatunkkal egy új eSIM profil létrehozásához, majd jelentkezzen be a :organisationName fiókjába az új eszközön a QR-kód telepítéséhez. Győződjön meg arról, hogy megerősíti, hogy másik eszközt használ a pontos beállítási frissítésekhez.',
  ],
  [
    'question' => 'Vannak olyan szerződések, mint a hagyományos eSIM szolgáltatók esetében?',
    'answer' => 'Nem, a :organisationName nem követeli meg, hogy szerződéseket írj alá. Az eSIM kártyádat aktiválhatod vagy deaktiválhatod, ahogy szeretnéd, a terveid függvényében. Örömmel segítünk neked.',
  ],
  [
    'question' => 'Mi a különbség a :organisationName eSIM-je és a fizikai mobilszolgáltatók standard roaming adatcsomagjai között?',
    'answer' => ':organisationName szerződésmentes adatcsomagokat kínál, rejtett roaming költségek nélkül. Csak az általad használt adatért fizetsz, a választott csomagtól függően, ami gyakran gazdaságosabb lehetőség.',
  ],
  [
    'question' => 'Miért lassú az adatsebességem?',
    'answer' => 'Az adatsebességet különböző tényezők befolyásolhatják, beleértve a használt okostelefon típusát, a hálózati technológiát, a weboldalakat vagy alkalmazásokat, amelyeket használ, és a napszakot. Ezenkívül a sebességek változhatnak az ország hálózati infrastruktúrájától függően. Ha lassú sebességet tapasztalsz, próbáld meg újraindítani a telefonodat, és oszd meg velünk a sebességi eredményeket, különösen a LTE mód engedélyezett és nem engedélyezett összehasonlításait.',
  ],
  [
    'question' => 'Hogyan nézhetem meg a csomagjaimat?',
    'answer' => 'Nyomon követheti a fennmaradó adatokat és a korlátokat az ügyfélpanelünkben.',
  ],
  [
    'question' => 'Mi teszi a :organisationName-t különbözővé más eSIM szolgáltatásoktól?',
    'answer' => ':organisationName kiemelkedik azáltal, hogy helyi szolgáltatókkal működik együtt több mint 200 országban, költséghatékony adatcsomagokat kínálva közvetítők nélkül. Erős lefedettséget és egyszerű aktiválási folyamatot biztosítunk. :organisationName tökéletes utazók számára, akik mobilinternet megoldásokat keresnek.',
  ],
];
