<?php

//This file is automatically generated. Do not modify.

return [
  'title' => 'Maradj kapcsolatban online :countryName-ban.',
  'subtitle' => 'Utazik :countryName-ba? Maradjon kapcsolatban eSIM-ünkkel, biztosítva, hogy azonnali internet-hozzáférése legyen érkezéskor.',
  'features' => [
    [
      'title' => 'Megbízhatóan és gyorsan online :countryName-ban.',
      'subtitle' => ':countryName egy gyönyörű úti cél, amely élénk modern városokkal és lélegzetelállító természeti tájakkal büszkélkedik. Fokozza utazási élményét eSIM-ünkkel, biztosítva, hogy azonnal kapcsolódhasson érkezéskor.  
        Mondjon búcsút a helyi SIM-kártya keresésének vagy a költséges adat roaminggal való bajlódásnak. E- SIM-ünkkel zökkenőmentes hozzáférést élvezhet az ország legjobb szolgáltatóinak 4G/5G hálózataihoz, így mindig online maradhat, bármerre is vezessen az útja.',
      'image' => 'images/features/feature1.jpg',
    ],
    [
      'title' => 'Maradj kapcsolatban a szeretteiddel',
      'subtitle' => 'Az eSIM-ünk zökkenőmentes internet-hozzáférésre lett tervezve, lehetővé téve, hogy minden online tevékenységed során folyamatosan kapcsolatban maradj anélkül, hogy új telefonszámra lenne szükséged. Könnyedén létrehozhatsz egy hotspotot, hogy megoszd a kapcsolatodat más utazókkal vagy családtagokkal, egy olyan funkció, amelyet más szolgáltatók gyakran blokkolnak, de nálunk teljes mértékben támogatott. Élvezd az azonnali csatlakozás kényelmét eSIM-kompatibilis eszközökön, biztosítva, hogy te és szeretteid bármikor, bárhol online maradhassatok. Kérjük, erősítsd meg, hogy az eszközöd támogatja-e az eSIM-et, hogy biztos lehess abban, hogy készen állsz internetes ajánlatainkra. Kérjük, vedd figyelembe, hogy a hívások és az üzenetek nem támogatottak az eSIM-ünkkel.',
      'image' => 'images/features/feature2.jpg',
    ],
  ],
];
