<?php

//This file is automatically generated. Do not modify.

return [
  'all_rights_reserved' => 'Minden jog fenntartva.',
  'foreign_currencies_for_reference_only' => 'A külföldi valuták csak tájékoztató jellegűek. A számlázás euróban történik.',
];
