<?php

//This file is automatically generated. Do not modify.

return [
  'from' => ':price/GB',
  'title' => 'Csatlakozz globálisan eSIM-jeinkkel',
  'subtitle' => 'Fedezd fel eSIM csomagjainkat, és maradj kapcsolatban, bárhol is vagy!',
  'search_destination' => 'Keress egy úti célt',
  'show_all_esim' => 'Mutasd az összes eSIM tervet',
  'how_it_works' => 'Hogyan működik?',
  'steps' => [
    [
      'title' => '1. lépés',
      'description' => 'Ellenőrizze, hogy az eszköze eSIM-kompatibilis-e a kompatibilitási listánkon.',
    ],
    [
      'title' => '2. lépés',
      'description' => 'Válaszd ki a célállomást és a kívánt eSIM adatcsomagot',
    ],
    [
      'title' => '3. lépés',
      'description' => 'Vásárolja meg a legjobban megfelelő eSIM kártyát az igényeihez.',
    ],
    [
      'title' => '4. lépés',
      'description' => 'Az eSIM automatikusan lesz kézbesítve. Kövesse az utasításokat az e-mailjében.',
    ],
    [
      'title' => '5. lépés',
      'description' => 'Telepítse az eSIM profilját, és élvezze az utazást!',
    ],
  ],
  'supported_networks' => 'Támogatott hálózati szolgáltatók',
  'supported_networks_description' => 'Szorosan együttműködünk a világ vezető, megbízható kapcsolati, média- és technológiai márkáival.',
  'and_many_more' => 'és még sok más...',
  'user_reviews' => 'Mit mondanak elégedett felhasználóink',
  'user_reviews_subtitle' => 'Nézd meg, miért bíznak a világ utazói az eSIM-ünkre a zökkenőmentes, megbízható kapcsolódás érdekében útközben.',
  'faq' => 'Gyakran Ismételt Kérdések',
  'popular_destinations' => 'Népszerű úti célok',
  'popular_destinations_description' => 'Fedezd fel a legnépszerűbb eSIM úti céljainkat, és maradj kapcsolatban, bárhova is mész!',
  'see_all_destinations' => 'Nézd meg az összes úti célt',
];
