<?php

//This file is automatically generated. Do not modify.

return [
  'home' => 'Otthon',
  'supported-devices' => 'Támogatott eszközök',
  'destinations' => 'Minden úti cél',
  'about' => 'Rólunk',
  'contact' => 'Kapcsolat',
  'portal_link' => 'Az én Portálom',
];
