<?php

//This file is automatically generated. Do not modify.

return [
  'days' => 'napok',
  'buy_plan' => 'Vásárolj most!',
  'perks' => [
    'instant' => 'Közvetlen kézbesítés',
    'advanced_self_service' => 'Fejlett önkiszolgáló portál',
    '247_support' => '24/7 élő chat támogatás',
    'prepaid' => 'Előre fizetett, feltételek nélkül',
    'no_roaming' => 'Nincsenek roaming díjak',
  ],
  'local_for' => 'Helyi eSIM-ek :countryName számára',
  'not_available_yet' => 'Jelenleg nem kínálunk eSIM-et ehhez az országhoz.',
  'not_available_yet_contact_us' => 'Keményen dolgozunk a globális lefedettségünk bővítésén. Ha Ön érdeklődik az eSIM-ek iránt ebben az országban, kérjük, lépjen kapcsolatba velünk.',
  'top_plan' => 'Legnépszerűbb',
  'all_features' => 'Minden funkció',
  'features' => [
    'feature_one' => 'Lehetséges forró pont',
    'feature_two' => 'Fedezet minden nemzeti hálózaton',
    'feature_three' => 'Egyszerű frissítés a személyes portálodon',
  ],
  'buy_now' => 'Vásárolj most',
  'starting_from' => 'Kezdve a',
  'choose_destination' => 'Keress egy úti célt',
  'how_esim_works' => [
    'title' => 'Hogyan működik az eSIM',
    'subtitle' => 'Az eSIM használatba vétele egyszerű! Kövesd ezeket az egyszerű lépéseket, hogy kapcsolatban maradj.',
    'steps' => [
      [
        'title' => 'Vásárolja meg az eSIM-jét',
        'description' => 'Válaszd ki a célállomást, válassz egy csomagot, amely megfelel az adatigényeidnek, és fejezd be a vásárlást.',
        'image' => '/images/howesimworks/1.png',
      ],
      [
        'title' => 'Kapja meg az eSIM-jét',
        'description' => 'Kapja meg eSIM QR-kódját közvetlenül az emailjében. Azonnal használatra kész.',
        'image' => '/images/howesimworks/2.png',
      ],
      [
        'title' => 'Aktiválás és Csatlakozás',
        'description' => 'Olvasd be a QR-kódot, aktiváld az eSIM-edet, és élvezd a gyors, megbízható adatokat, bárhol is utazol.',
        'image' => '/images/howesimworks/3.png',
      ],
    ],
  ],
  'sub_description' => 'Válaszd ki az alábbi csomagot, és élvezd a zökkenőmentes kapcsolatot :countryName területén a legjobb hálózatokon a legjobb áron.',
];
