<?php

//This file is automatically generated. Do not modify.

return [
  'title' => 'eSIM-szolgáltatás - Előre fizetett virtuális SIM-kártyák utazók számára - :site_name',
  'description' => 'eSIM-szolgáltatás ⏩ Előre fizetett digitális SIM-kártyák turizmushoz és üzleti célokra ⏩ Standard és korlátlan, helyi és globális mobil adatcsomagok ⏩ Nincs szerződés ✅ Nincsenek rejtett roamingdíjak és -költségek ✅ - :site_name',
  'keywords' => 'eSIM, eSIM-szolgáltatás, eSIM-kártya, eSIM-adatok, eSIM-adatcsomag, eSIM-adatcsomagok, eSIM-adatcsomag utazók számára, eSIM-adatcsomag turisták számára, eSIM-adatcsomag cégek számára, eSIM-adatcsomag utazásra, eSIM-adatcsomag Európára, eSIM-adatcsomag az Egyesült Államok számára, eSIM-adatcsomag Ázsiára, eSIM-adatcsomag Afrikára, eSIM-adatcsomag Ausztráliára, eSIM-adatcsomag Dél-Amerikára, eSIM-adatcsomag Észak-Amerikára, eSIM-adatcsomag a Közel-Keletre, eSIM-adatcsomag Oroszországra, eSIM-adatcsomag Kínára, eSIM-adatcsomag Indiára, eSIM-adatcsomag Japánra',
  'routes' => [
    'home' => [
      'title' => 'eSIM-szolgáltatás - Előre fizetett virtuális SIM-kártyák utazók számára - :site_name',
      'description' => 'eSIM-szolgáltatás ⏩ Előre fizetett digitális SIM-kártyák turizmushoz és üzleti célokra ⏩ Standard és korlátlan, helyi és globális mobil adatcsomagok ⏩ Nincsenek szerződések ✅ Nincsenek rejtett roamingdíjak és -költségek ✅ - :site_name',
    ],
    'about' => [
      'title' => 'Rólunk - :site_name',
      'description' => 'Rólunk ⏩ Előre fizetett digitális SIM-kártyák turizmushoz és üzleti célokra ⏩ Standard és korlátlan, helyi és globális mobil adatcsomagok ⏩ Nincsenek szerződések ✅ Nincsenek rejtett roaming díjak és költségek ✅ - :site_name',
    ],
    'supported-devices' => [
      'title' => 'Támogatott Eszközök - :site_name',
      'description' => 'Támogatott Eszközök ⏩ Előre fizetett digitális SIM-kártyák turizmushoz és üzleti célokra ⏩ Standard és korlátlan, helyi és globális mobil adatcsomagok ⏩ Nincs szerződés ✅ Nincsenek rejtett roaming díjak és költségek ✅ - :site_name',
    ],
    'esim-bundle-per-country' => [
      'title' => 'eSIM :countryName - :site_name',
      'description' => 'eSIM :countryName ⏩ Előfizetés nélküli digitális SIM-kártyák turizmushoz és üzleti célokra ⏩ Standard és korlátlan, helyi és globális mobil adatcsomagok ⏩ Nincsenek szerződések ✅ Nincsenek rejtett roamingdíjak és -költségek ✅ - :site_name',
    ],
  ],
];
