<?php

//This file is automatically generated. Do not modify.

return [
  'title' => 'eSIM Szolgáltatás - Előre fizetett virtuális SIM kártyák utazók számára - :site_name',
  'description' => 'eSIM szolgáltatás ⏩ Előre fizetett digitális SIM-kártyák turizmushoz és üzlethez ⏩ Standard és korlátlan, helyi és globális mobiltelefon adatcsomagok ⏩ Nincs szerződés ✅ Nincs rejtett roaming díj és költség ✅ - :site_name',
  'keywords' => 'eSIM, eSIM szolgáltatás, eSIM kártya, eSIM adat, eSIM adatcsomag, eSIM adatcsomagok, eSIM adatcsomag utazók számára, eSIM adatcsomag turisták számára, eSIM adatcsomag üzleti célokra, eSIM adatcsomag utazáshoz, eSIM adatcsomag Európához, eSIM adatcsomag az Egyesült Államokhoz, eSIM adatcsomag Ázsiához, eSIM adatcsomag Afrikához, eSIM adatcsomag Ausztráliához, eSIM adatcsomag Dél-Amerikához, eSIM adatcsomag Észak-Amerikához, eSIM adatcsomag a Közel-Kelethez, eSIM adatcsomag Oroszországhoz, eSIM adatcsomag Kínához, eSIM adatcsomag Indiához, eSIM adatcsomag Japánhoz',
  'routes' => [
    'home' => [
      'title' => 'eSIM Szolgáltatás - Előre fizetett virtuális SIM kártyák utazók számára - :site_name',
      'description' => 'eSIM szolgáltatás ⏩ Előre fizetett digitális SIM kártyák turizmushoz és üzlethez ⏩ Standard és korlátlan, helyi és globális mobiltelefon adatcsomagok ⏩ Nincsenek szerződések ✅ Nincsenek rejtett roaming díjak és költségek ✅ - :site_name',
    ],
    'about' => [
      'title' => 'Rólunk - :site_name',
      'description' => 'Rólunk ⏩ Előre fizetett digitális SIM kártyák turizmushoz és üzlethez ⏩ Standard és korlátlan, helyi és globális mobiltelefon adatcsomagok ⏩ Nincs szerződés ✅ Nincs rejtett roaming díj és költség ✅ - :site_name',
    ],
    'supported-devices' => [
      'title' => 'Támogatott eszközök - :site_name',
      'description' => 'Támogatott eszközök ⏩ Előre fizetett digitális SIM-kártyák turizmushoz és üzlethez ⏩ Standard és korlátlan, helyi és globális mobiltelefon adatcsomagok ⏩ Nincs szerződés ✅ Nincsenek rejtett roaming díjak és költségek ✅ - :site_name',
    ],
    'esim-bundle-per-country' => [
      'title' => 'Megfizethető helyi eSIM ajánlatok :countryName számára - :site_name',
      'description' => 'Megfizethető helyi eSIM ajánlatok :countryName számára ⏩ Előre fizetett digitális SIM kártyák turizmushoz és üzlethez ⏩ Standard és korlátlan, helyi és globális mobiltelefon adatcsomagok ⏩ Nincsenek szerződések ✅ Nincsenek rejtett roaming díjak és költségek ✅ - :site_name',
    ],
  ],
];
