<?php

//This file is automatically generated. Do not modify.

return [
  'title' => 'O nás',
  'subtitle' => 'Navigujte světem bez hranic s námi. Jsme váš konečný partner, který vás udržuje v kontaktu, ať už vás vaše vášeň zavede kamkoli.',
  'our_team' => 'Náš tým',
  'our_team_subtitle' => 'Věříme v posílení cestovatelů spolehlivým a cenově dostupným globálním datovým připojením. Náš různorodý tým je sjednocen v vytváření propojenějšího a přístupnějšího světa pro každého na cestách.',
  'why_us' => 'Proč si vybrat nás',
  'why_us_subtitle' => 'Jsme hrdí na naši spolehlivou službu, konkurenceschopné ceny a přístup orientovaný na zákazníka. Vaše spokojenost je naší nejvyšší prioritou.',
  'why_us_reasons' => [
    [
      'title' => 'Flexibilní plány navržené pro vaše cestovní potřeby',
      'subtitle' => 'Vyberte si z řady cenově dostupných balíčků přizpůsobených různým zemím a regionům. Dáváme vám flexibilitu vybrat si perfektní datový plán, takže platíte pouze za to, co potřebujete, bez skrytých nákladů.',
      'image' => '/images/whyus/nlo2.png',
    ],
    [
      'title' => 'Přímá aktivace, žádné fyzické SIM karty nejsou potřeba',
      'subtitle' => 'Dny výměny fyzických SIM karet jsou pryč. S námi je vaše eSIM doručena přímo e-mailem a může být aktivována během několika minut. Stačí naskenovat QR kód a jste připraveni se připojit.',
      'image' => '/images/whyus/nlo3.png',
    ],
  ],
  'contact' => 'Kontaktujte nás',
  'contact_subtitle' => 'Jsme tu, abychom vám pomohli. Pokud máte nějaké dotazy nebo potřebujete pomoc, prosím, kontaktujte nás.',
];
