<?php

//This file is automatically generated. Do not modify.

return [
  'title' => 'Všechny naše destinace',
  'subtitle' => 'Kdekoliv jdete, máme pro vás připravené eSIM kdekoli. Vyberte si svou destinaci níže a začněte.',
];
