<?php

//This file is automatically generated. Do not modify.

return [
  'title' => 'Podporovaná zařízení',
  'subtitle' => 'Podporujeme širokou škálu zařízení. Zkontrolujte, zda je vaše zařízení na seznamu níže. Zařízení jsou organizována podle výrobce.',
  'models_below' => 'Podporované modely jsou uvedeny níže.',
];
