<?php

//This file is automatically generated. Do not modify.

return [
  'faq' => 'Často kladené otázky',
  'subtitle' => 'Máte nějaké otázky? My máme odpovědi. Najděte vše, co potřebujete vědět o našich eSIM.',
];
