<?php

//This file is automatically generated. Do not modify.

return [
  [
    'question' => 'Co je eSIM a jak mohu použít :organisationName?',
    'answer' => 'eSIM, nebo vestavěná SIM, je digitální SIM karta, která umožňuje uživatelům aktivovat a spravovat více mobilních plánů na jednom zařízení, aniž by potřebovali fyzickou SIM kartu. S eSIM můžete snadno přepínat mezi mobilními poskytovateli a užívat si funkce, jako je přidání další linky pro mezinárodní cestování nebo udržování oddělených datových plánů pro osobní a pracovní použití.',
  ],
  [
    'question' => 'Jak aktivuji mobilní internet eSIM s :organisationName?',
    'answer' => 'Chcete-li se připojit k internetu pomocí :organisationName eSIM, postupujte podle těchto kroků: 1. Přejděte do nastavení Mobilních dat. 2. Zapněte mobilní linku :organisationName. 3. Aktivujte Roaming dat. 4. Vyberte linku :organisationName Internet jako své primární připojení. *Vyhněte se výběru možnosti "Odstranit datový plán", protože to odstraní váš eSIM profil.*',
  ],
  [
    'question' => 'Mohu telefonovat nebo posílat textové zprávy?',
    'answer' => ':organisationName\'s předplacené eSIM plány jsou navrženy pro použití pouze pro data a neobsahují telefonní číslo pro tradiční hovory nebo SMS zprávy. Doporučujeme používat VoIP aplikace jako Facebook Messenger, WhatsApp, Viber, Telegram nebo Skype, abyste zůstali v kontaktu po celém světě bez potřeby standardní mezinárodní SIM karty.',
  ],
  [
    'question' => 'Lze eSIM kartu znovu použít?',
    'answer' => 'Každý QR kód pro eSIM je jedinečný a může být použit pouze na jednom zařízení. Jakmile je profil eSIM smazán, QR kód nelze znovu použít na stejném nebo jiném zařízení, což zajišťuje bezpečnost a exkluzivitu.',
  ],
  [
    'question' => 'Kdy začíná platnost eSIM mobilních datových plánů?',
    'answer' => 'Doba platnosti vašeho eSIM datového plánu začíná okamžitě poté, co se vaše zařízení poprvé připojí k mobilní síti s eSIM.',
  ],
  [
    'question' => 'Mohu prodloužit datum vypršení platnosti svého aktuálního eSIM mobilního datového plánu?',
    'answer' => 'Jistě! Obdržíte několik upozornění na push, když budete téměř na konci svého balíčku. Můžete snadno dobít prostřednictvím svého osobního portálu.',
  ],
  [
    'question' => 'Mohu používat tethering nebo Osobní hotspot s :organisationName?',
    'answer' => 'Ano, můžete sdílet svá mobilní data s jinými zařízeními prostřednictvím vaší :organisationName-eSIM. Jednoduše nainstalujte :organisationName-eSIM na své zařízení a povolte Osobní hotspot ve svých nastaveních. Tato funkce je zahrnuta bez dalších nákladů, ale prosím mějte na paměti, že používání sdílených dat bude odečteno z vašeho plánu.',
  ],
  [
    'question' => 'Mohu si ponechat čísla z mé osobní aplikace pro zasílání zpráv, když používám eSIM od :organisationName?',
    'answer' => 'Ano, můžete nadále používat svůj WhatsApp, Snapchat, Telegram a další aplikace pro zasílání zpráv spolu se svým :organisationName předplaceným eSIM bez jakýchkoli problémů.',
  ],
  [
    'question' => 'Jak mohu převést svůj eSIM na nový telefon?',
    'answer' => 'Než přenesete, ujistěte se, že váš nový smartphone podporuje technologii eSIM. Kontaktujte náš tým podpory, abyste vytvořili nový eSIM profil, poté se přihlaste do svého účtu :organisationName na novém zařízení a nainstalujte QR kód. Ujistěte se, že potvrzujete, že používáte jiné zařízení pro přesné aktualizace nastavení.',
  ],
  [
    'question' => 'Existují smlouvy jako u tradičních poskytovatelů eSIM?',
    'answer' => 'Ne, :organisationName nevyžaduje, abyste podepisovali smlouvy. Můžete aktivovat nebo deaktivovat svou eSIM kartu podle svých přání, v závislosti na vašich plánech. Rádi vám pomůžeme.',
  ],
  [
    'question' => 'Jaký je rozdíl mezi eSIM :organisationName a standardními roamingovými datovými plány od fyzických mobilních operátorů?',
    'answer' => ':organisationName nabízí datové plány bez smlouvy bez skrytých roamingových nákladů. Platíte pouze za data, která používáte, v závislosti na balíčku, který si vyberete, což z něj často činí ekonomičtější volbu.',
  ],
  [
    'question' => 'Proč je moje rychlost dat pomalá?',
    'answer' => 'Rychlost dat může být ovlivněna různými faktory, včetně typu smartphonu, který máte, technologiemi sítě, webovými stránkami nebo aplikacemi, které používáte, a denní dobou. Kromě toho se rychlosti mohou lišit v závislosti na síťové infrastruktuře země. Pokud zažíváte pomalé rychlosti, zkuste restartovat svůj telefon a sdílejte s námi jakékoli výsledky rychlosti, zejména srovnání s a bez :LTE režimu.',
  ],
  [
    'question' => 'Jak mohu zobrazit své balíčky?',
    'answer' => 'Můžete sledovat svá zbývající data a limity v našem zákaznickém panelu.',
  ],
  [
    'question' => 'Co dělá :organisationName odlišným od ostatních eSIM služeb?',
    'answer' => ':organisationName vyniká spoluprací s místními operátory ve více než 200 zemích, nabízejícími cenově dostupné datové balíčky bez zprostředkovatelů. Poskytujeme silné pokrytí a jednoduchý proces aktivace. :organisationName je ideální pro cestovatele hledající mobilní internetová řešení.',
  ],
];
