<?php

//This file is automatically generated. Do not modify.

return [
  'title' => 'Zůstaňte online spojeni v :countryName',
  'subtitle' => 'Cestujete do :countryName? Zůstaňte připojeni s naším eSIM, který zajišťuje okamžitý přístup k internetu po příjezdu.',
  'features' => [
    [
      'title' => 'Spolehlivě a rychle online v :countryName',
      'subtitle' => ':countryName je krásná destinace, která se pyšní živými moderními městy a dechberoucími přírodními krajinami. Vylepšete svou cestovatelskou zkušenost s naším eSIM, který zajišťuje, že zůstanete okamžitě připojeni po příjezdu. 
        Rozlučte se s nepříjemnostmi spojenými s hledáním místní SIM karty nebo s drahým datovým roamingem. S naším eSIM si užijete bezproblémový přístup k 4G/5G sítím od nejlepších poskytovatelů v zemi, což vás udrží online, ať už vaše cesta vede kamkoli.',
      'image' => 'images/features/feature1.jpg',
    ],
    [
      'title' => 'Zůstaňte v kontaktu s blízkými',
      'subtitle' => 'Naše eSIM je navržena pro bezproblémový přístup k internetu, který vás udrží připojené pro všechny vaše online aktivity bez potřeby nového telefonního čísla. Snadno vytvořte hotspot, abyste sdíleli své připojení s ostatními cestovateli nebo rodinou, což je funkce, kterou často blokují jiní poskytovatelé, ale my ji plně podporujeme. Užijte si pohodlí okamžité konektivity na zařízeních kompatibilních s eSIM, což zajišťuje, že vy a vaši blízcí zůstanete online kdykoli a kdekoli. Prosím, potvrďte, zda vaše zařízení podporuje eSIM, abyste se ujistili, že jste připraveni na naše internetové nabídky. Vezměte na vědomí, že volání a textové zprávy nejsou s naší eSIM podporovány.',
      'image' => 'images/features/feature2.jpg',
    ],
  ],
];
