<?php

//This file is automatically generated. Do not modify.

return [
  'all_rights_reserved' => 'Všechna práva vyhrazena.',
  'foreign_currencies_for_reference_only' => 'Zahraniční měny jsou pouze pro orientaci. Fakturace bude v eurech.',
];
