<?php

//This file is automatically generated. Do not modify.

return [
  'from' => ':price/GB',
  'title' => 'Spojte se globálně s našimi eSIM.',
  'subtitle' => 'Prozkoumejte naše eSIM balíčky a zůstaňte připojeni, ať jste kdekoli!',
  'search_destination' => 'Najděte cíl',
  'show_all_esim' => 'Zobrazit všechny eSIM plány',
  'how_it_works' => 'Jak to funguje?',
  'steps' => [
    [
      'title' => 'Krok 1',
      'description' => 'Zkontrolujte, zda je vaše zařízení kompatibilní s eSIM v našem seznamu kompatibility.',
    ],
    [
      'title' => 'Krok 2',
      'description' => 'Vyberte si svou destinaci a požadovaný eSIM datový plán',
    ],
    [
      'title' => 'Krok 3',
      'description' => 'Kupte si eSIM kartu, která nejlépe vyhovuje vašim potřebám.',
    ],
    [
      'title' => 'Krok 4',
      'description' => 'Vaše eSIM bude doručena automaticky. Postupujte podle pokynů ve vaší e-mailové zprávě.',
    ],
    [
      'title' => 'Krok 5',
      'description' => 'Nainstalujte si svůj eSIM profil a užijte si svou cestu!',
    ],
  ],
  'supported_networks' => 'Podporovaní poskytovatelé sítí',
  'supported_networks_description' => 'Úzce spolupracujeme s důvěryhodnými tržními lídry v oblasti konektivity, médií a technologií po celém světě.',
  'and_many_more' => 'a mnohem více...',
  'user_reviews' => 'Co říkají naši spokojení uživatelé',
  'user_reviews_subtitle' => 'Zjistěte, proč se cestovatelé po celém světě spoléhají na naši eSIM pro bezproblémové a spolehlivé připojení na cestách.',
  'faq' => 'Často kladené otázky',
  'popular_destinations' => 'Oblíbené destinace',
  'popular_destinations_description' => 'Objevte naše nejoblíbenější eSIM destinace a zůstaňte připojeni, ať jdete kamkoli!',
  'see_all_destinations' => 'Zobrazit všechny destinace',
];
