<?php

//This file is automatically generated. Do not modify.

return [
  'home' => 'Domov',
  'supported-devices' => 'Podporovaná zařízení',
  'destinations' => 'Všechny destinace',
  'about' => 'O nás',
  'contact' => 'Kontakt',
  'portal_link' => 'Můj Portal',
];
