<?php

//This file is automatically generated. Do not modify.

return [
  'days' => 'dny',
  'buy_plan' => 'Kup nyní!',
  'perks' => [
    'instant' => 'Přímá dodávka',
    'advanced_self_service' => 'Pokročilý samoobslužný portál',
    '247_support' => '24/7 podpora živého chatu',
    'prepaid' => 'Předplacené, bez podmínek',
    'no_roaming' => 'Žádné poplatky za roaming',
  ],
  'local_for' => 'Místní eSIM karty pro :countryName',
  'not_available_yet' => 'V současné době nenabízíme eSIM pro tuto zemi.',
  'not_available_yet_contact_us' => 'Pracujeme tvrdě na rozšíření našeho globálního pokrytí. Pokud máte zájem o eSIMy pro tuto zemi mezitím, prosím kontaktujte nás.',
  'top_plan' => 'Nejoblíbenější',
  'all_features' => 'Všechny funkce',
  'features' => [
    'feature_one' => 'Možný hotspot',
    'feature_two' => 'Pokrytí napříč všemi národními sítěmi',
    'feature_three' => 'Jednoduché vylepšení ve vašem osobním portálu',
  ],
  'buy_now' => 'Koupit nyní',
  'starting_from' => 'Začíná od',
  'choose_destination' => 'Najděte cíl',
  'how_esim_works' => [
    'title' => 'Jak eSIM funguje',
    'subtitle' => 'Začít s eSIM je snadné! Postupujte podle těchto jednoduchých kroků, abyste zůstali připojeni.',
    'steps' => [
      [
        'title' => 'Kupte si svou eSIM',
        'description' => 'Vyberte si svou destinaci, zvolte balíček, který vyhovuje vašim datovým potřebám, a dokončete svůj nákup.',
        'image' => '/images/howesimworks/1.png',
      ],
      [
        'title' => 'Obdržíte svou eSIM',
        'description' => 'Obdržíte svůj eSIM QR kód přímo na svůj e-mail. Připraveno k okamžitému použití.',
        'image' => '/images/howesimworks/2.png',
      ],
      [
        'title' => 'Aktivovat a připojit',
        'description' => 'Naskenujte QR kód, aktivujte svůj eSIM a užívejte si rychlá a spolehlivá data, ať už cestujete kamkoliv.',
        'image' => '/images/howesimworks/3.png',
      ],
    ],
  ],
  'sub_description' => 'Vyberte si svůj balíček níže a užijte si bezproblémové připojení v :countryName na nejlepších sítích za nejlepší cenu.',
];
