<?php

//This file is automatically generated. Do not modify.

return [
  'title' => 'eSIM služba - předplacené virtuální SIM karty pro cestovatele - :site_name',
  'description' => 'eSIM služba ⏩ Předplacené digitální SIM karty pro turistiku a podnikání ⏩ Standardní a neomezené, místní a globální mobilní datové plány ⏩ Žádné smlouvy ✅ Žádné skryté roamingové poplatky a poplatky ✅ - :site_name',
  'keywords' => 'eSIM, eSIM služba, eSIM karta, eSIM data, eSIM datový plán, eSIM datové plány, eSIM datový plán pro cestovatele, eSIM datový plán pro turisty, eSIM datový plán pro podnikání, eSIM datový plán pro cestování, eSIM datový plán pro Evropu, eSIM datový plán pro USA, eSIM datový plán pro Asii, eSIM datový plán pro Afriku, eSIM datový plán pro Austrálii, eSIM datový plán pro Jižní Ameriku, eSIM datový plán pro Severní Ameriku, eSIM datový plán pro Střední východ, eSIM datový plán pro Rusko, eSIM datový plán pro Čínu, eSIM datový plán pro Indii, eSIM datový plán pro Japonsko',
  'routes' => [
    'home' => [
      'title' => 'eSIM služba - Předplacené virtuální SIM karty pro cestovatele - :site_name',
      'description' => 'eSIM služba ⏩ Předplacené digitální SIM karty pro turistiku a podnikání ⏩ Standardní a neomezené, místní a globální mobilní datové plány ⏩ Žádné smlouvy ✅ Žádné skryté roamingové poplatky a poplatky ✅ - :site_name',
    ],
    'about' => [
      'title' => 'O nás - :site_name',
      'description' => 'O nás ⏩ Předplacené digitální SIM karty pro turistiku a podnikání ⏩ Standardní a neomezené, místní a globální mobilní datové plány ⏩ Žádné smlouvy ✅ Žádné skryté roamingové poplatky a poplatky ✅ - :site_name',
    ],
    'supported-devices' => [
      'title' => 'Podporovaná zařízení - :site_name',
      'description' => 'Podporované zařízení ⏩ Předplacené digitální SIM karty pro turistiku a podnikání ⏩ Standardní a neomezené, místní a globální mobilní datové plány ⏩ Žádné smlouvy ✅ Žádné skryté roamingové poplatky a poplatky ✅ - :site_name',
    ],
    'esim-bundle-per-country' => [
      'title' => 'Dostupné místní eSIM nabídky pro :countryName - :site_name',
      'description' => 'Dostupné místní eSIM nabídky pro :countryName ⏩ Předplacené digitální SIM karty pro turismus a podnikání ⏩ Standardní a neomezené, místní a globální mobilní datové plány ⏩ Žádné smlouvy ✅ Žádné skryté roamingové poplatky a poplatky ✅ - :site_name',
    ],
  ],
];
