<?php

//This file is automatically generated. Do not modify.

return [
  'title' => 'eSIM-služba - Předplacené virtuální SIM karty pro cestovatele - :site_name',
  'description' => 'eSIM-služba ⏩ Předplacené digitální SIM karty pro turistiku a podnikání ⏩ Standardní a neomezené, místní a globální mobilní datové plány ⏩ Žádné smlouvy ✅ Žádné skryté roamingové poplatky a náhrady ✅ - :site_name',
  'keywords' => 'eSIM, eSIM-služba, eSIM-karta, eSIM-údaje, eSIM-datový plán, eSIM-datové plány, eSIM-datový plán pro cestovatele, eSIM-datový plán pro turisty, eSIM-datový plán pro firmy, eSIM-datový plán pro cestování, eSIM-datový plán pro Evropu, eSIM-datový plán pro USA, eSIM-datový plán pro Asii, eSIM-datový plán pro Afriku, eSIM-datový plán pro Austrálii, eSIM-datový plán pro Jižní Ameriku, eSIM-datový plán pro Severní Ameriku, eSIM-datový plán pro Blízký východ, eSIM-datový plán pro Rusko, eSIM-datový plán pro Čínu, eSIM-datový plán pro Indii, eSIM-datový plán pro Japonsko',
  'routes' => [
    'home' => [
      'title' => 'eSIM služba - Předplacené virtuální SIM karty pro cestovatele - :site_name',
      'description' => 'eSIM-služba ⏩ Předplacené digitální SIM karty pro turistiku a obchod ⏩ Standardní a neomezené, místní a globální mobilní datové plány ⏩ Žádné smlouvy ✅ Žádné skryté roamingové poplatky a náhrady ✅ - :site_name',
    ],
    'about' => [
      'title' => 'O nás - :site_name',
      'description' => 'O nás ⏩ Předplacené digitální SIM karty pro turistiku a byznys ⏩ Standardní a neomezené, místní a globální mobilní datové plány ⏩ Žádné smlouvy ✅ Žádné skryté roamingové poplatky a náhrady ✅ - :site_name',
    ],
    'supported-devices' => [
      'title' => 'Podporovaná zařízení - :site_name',
      'description' => 'Podporovaná zařízení ⏩ Předplacené digitální SIM karty pro turismus a obchod ⏩ Standardní a neomezené, místní a globální mobilní datové plány ⏩ Žádné smlouvy ✅ Žádné skryté roamingové poplatky a náhrady ✅ - :site_name',
    ],
    'esim-bundle-per-country' => [
      'title' => 'eSIM :countryName - :site_name',
      'description' => 'eSIM :countryName ⏩ Předplacené digitální SIM karty pro turistiku a podnikání ⏩ Standardní a neomezené, místní a globální mobilní datové plány ⏩ Žádné smlouvy ✅ Žádné skryté roamingové poplatky a - :site_name',
    ],
  ],
];
