<?php

//This file is automatically generated. Do not modify.

return [
  'Rens' => [
    'role' => 'Spoluzakladatel',
    'image' => '/images/team/rens.png',
  ],
  'Luuk' => [
    'role' => 'Spoluzakladatel',
    'image' => '/images/team/luuk.png',
  ],
  'Fleur' => [
    'role' => 'Zákaznická podpora',
    'image' => '/images/team/fleur.png',
  ],
  'Patrick' => [
    'role' => 'Vývojář',
    'image' => '/images/team/patrick.png',
  ],
];
