<?php

//This file is automatically generated. Do not modify.

return [
  'title' => 'Om os',
  'subtitle' => 'Naviger verden uden grænser med os. Vi er din ultimative partner, der holder dig forbundet, uanset hvor din passion fører dig.',
  'our_team' => 'Vores Team',
  'our_team_subtitle' => 'Vi tror på at give rejsende mulighed for pålidelig og overkommelig global datatilslutning. Vores mangfoldige team er forenet i at skabe en mere sammenkoblet og tilgængelig verden for alle på farten.',
  'why_us' => 'Hvorfor vælge os',
  'why_us_subtitle' => 'Vi er stolte af vores pålidelige service, konkurrencedygtige priser og kundeorienterede tilgang. Din tilfredshed er vores højeste prioritet.',
  'why_us_reasons' => [
    [
      'title' => 'Fleksible planer designet til dine rejsebehov',
      'subtitle' => 'Vælg fra en række overkommelige pakker skræddersyet til forskellige lande og regioner. Vi giver dig fleksibiliteten til at vælge den perfekte dataplan, så du kun betaler for det, du har brug for, uden skjulte omkostninger.',
      'image' => '/images/whyus/nlo2.png',
    ],
    [
      'title' => 'Direkte aktivering, ingen fysiske SIM-kort nødvendige',
      'subtitle' => 'Dage med at skifte fysiske SIM-kort er forbi. Med os leveres dit eSIM direkte via email og kan aktiveres inden for få minutter. Bare scan QR-koden, så er du klar til at oprette forbindelse.',
      'image' => '/images/whyus/nlo3.png',
    ],
  ],
  'contact' => 'Kontakt os',
  'contact_subtitle' => 'Vi er her for at hjælpe dig. Hvis du har spørgsmål eller har brug for hjælp, bedes du kontakte os.',
];
