<?php

//This file is automatically generated. Do not modify.

return [
  'title' => 'Alle vores destinationer',
  'subtitle' => 'Uanset hvor du går, har vi dækket dig med eSIMs til hver destination. Vælg din destination nedenfor for at komme i gang.',
];
