<?php

//This file is automatically generated. Do not modify.

return [
  'title' => 'Understøttede enheder',
  'subtitle' => 'Vi understøtter en bred vifte af enheder. Tjek om din enhed er på listen nedenfor. Enheder er organiseret efter producent.',
  'models_below' => 'Understøttede modeller er angivet nedenfor.',
];
