<?php

//This file is automatically generated. Do not modify.

return [
  [
    'question' => 'Hvad er en eSIM, og hvordan kan jeg bruge :organisationName?',
    'answer' => 'En eSIM, eller indlejret SIM, er et digitalt SIM-kort, der giver brugerne mulighed for at aktivere og administrere flere mobilplaner på én enhed uden at skulle bruge et fysisk SIM-kort. Med en eSIM kan du nemt skifte mellem mobiludbydere og nyde funktioner som at tilføje en ekstra linje til international rejse eller opretholde separate dataplaner til personlig og erhvervsmæssig brug.',
  ],
  [
    'question' => 'Hvordan aktiverer jeg eSIM mobilinternet med :organisationName?',
    'answer' => 'For at oprette forbindelse til internettet ved hjælp af :organisationName eSIM, følg disse trin: 1. Gå til dine indstillinger for Mobildata. 2. Tænd for :organisationName mobil linje. 3. Aktiver Data roaming. 4. Vælg :organisationName Internet linje som din primære forbindelse. *Undgå at vælge muligheden "Fjern dataplan," da dette vil slette din eSIM-profil.*',
  ],
  [
    'question' => 'Kan jeg lave telefonopkald eller sende tekstbeskeder?',
    'answer' => ':organisationName\'s prepaid eSIM-planer er designet til data-only brug og inkluderer ikke et mobiltelefonnummer til traditionelle opkald eller SMS-beskeder. Vi anbefaler at bruge VoIP-applikationer som Facebook Messenger, WhatsApp, Viber, Telegram eller Skype for at forblive forbundet verden over uden behov for et standard internationalt SIM-kort.',
  ],
  [
    'question' => 'Kan et eSIM-kort genbruges?',
    'answer' => 'Hver QR-kode til en eSIM er unik og kan kun bruges på én enhed. Når eSIM-profilen er slettet, kan QR-koden ikke genbruges på den samme eller en anden enhed, hvilket sikrer sikkerhed og eksklusivitet.',
  ],
  [
    'question' => 'Hvornår begynder varigheden af eSIM mobil dataplaner?',
    'answer' => 'Varigheden af din eSIM dataplans starter straks efter, at din enhed først opretter forbindelse til et mobilnetværk med eSIM\'en.',
  ],
  [
    'question' => 'Kan jeg forlænge udløbsdatoen for min nuværende eSIM mobil dataplan?',
    'answer' => 'Selvfølgelig! Du vil modtage flere push-notifikationer, når du næsten er løbet tør for dit bundle. Du kan nemt tanke op gennem din personlige portal.',
  ],
  [
    'question' => 'Kan jeg bruge tethering eller Personal Hotspot med :organisationName?',
    'answer' => 'Ja, du kan dele dine mobile data med andre enheder via din :organisationName-eSIM. Installer blot :organisationName-eSIM på din enhed og aktiver Personal Hotspot i dine indstillinger. Denne funktion er inkluderet uden ekstra omkostninger, men vær opmærksom på, at brug af tethered data vil blive trukket fra din plan.',
  ],
  [
    'question' => 'Kan jeg beholde mine personlige besked-app numre, mens jeg bruger eSIM fra :organisationName?',
    'answer' => 'Ja, du kan fortsætte med at bruge din WhatsApp, Snapchat, Telegram og andre messaging-apps sammen med din :organisationName forudbetalte eSIM uden problemer.',
  ],
  [
    'question' => 'Hvordan kan jeg overføre mit eSIM til en ny telefon?',
    'answer' => 'Før du overfører, skal du sikre dig, at din nye smartphone understøtter eSIM-teknologi. Kontakt vores supportteam for at oprette en ny eSIM-profil, og log derefter ind på din :organisationName-konto på den nye enhed for at installere QR-koden. Sørg for at bekræfte, at du bruger en anden enhed for nøjagtige opdateringer af indstillingerne.',
  ],
  [
    'question' => 'Er der kontrakter som dem fra traditionelle eSIM-udbydere?',
    'answer' => 'Nej, :organisationName kræver ikke, at du underskriver kontrakter. Du kan aktivere eller deaktiverer dit eSIM-kort, som du ønsker, afhængigt af dine planer. Vi er glade for at hjælpe dig.',
  ],
  [
    'question' => 'Hvad er forskellen mellem :organisationName\'s eSIM og standard roaming dataplaner fra fysiske mobiloperatører?',
    'answer' => ':organisationName tilbyder kontraktfrie dataplaner uden skjulte roamingomkostninger. Du betaler kun for de data, du bruger, afhængigt af den pakke, du vælger, hvilket ofte gør det til et mere økonomisk valg.',
  ],
  [
    'question' => 'Hvorfor er min datahastighed langsom?',
    'answer' => 'Datahastigheden kan påvirkes af forskellige faktorer, herunder hvilken type smartphone du har, netværksteknologi, de websteder eller apps du bruger, og tidspunktet på dagen. Derudover kan hastigheder variere afhængigt af netværksinfrastrukturen i landet. Hvis du oplever langsomme hastigheder, så prøv at genstarte din telefon og del eventuelle hastighedsresultater med os, især sammenligninger med og uden LTE-tilstand aktiveret.',
  ],
  [
    'question' => 'Hvordan kan jeg se mine bundter?',
    'answer' => 'Du kan spore dine resterende data og grænser i vores kundepanel.',
  ],
  [
    'question' => 'Hvad gør :organisationName forskellig fra andre eSIM-tjenester?',
    'answer' => ':organisationName skiller sig ud ved at samarbejde med lokale operatører i over 200 lande, og tilbyder omkostningseffektive datapakker uden mellemled. Vi tilbyder solid dækning og en enkel aktiveringsproces. :organisationName er perfekt til rejsende, der søger mobile internetløsninger.',
  ],
];
