<?php

//This file is automatically generated. Do not modify.

return [
  'title' => 'Hold dig online i :countryName',
  'subtitle' => 'Rejser du til :countryName? Hold forbindelsen med vores eSIM, så du har øjeblikkelig internetadgang ved ankomsten.',
  'features' => [
    [
      'title' => 'Pålideligt og hurtigt online i :countryName',
      'subtitle' => ':countryName er en smuk destination, der byder på livlige moderne byer og betagende naturskønne landskaber. Forbedr din rejseoplevelse med vores eSIM, så du kan forblive forbundet straks ved ankomsten. 
        Sig farvel til besværet med at lede efter et lokalt SIM-kort eller håndtere dyre data-roaming. Med vores eSIM får du problemfri adgang til 4G/5G-netværk fra landets bedste udbydere, så du forbliver online, uanset hvor din rejse fører dig hen.',
      'image' => 'images/features/feature1.jpg',
    ],
    [
      'title' => 'Hold dig forbundet med kære.',
      'subtitle' => 'Vores eSIM er designet til problemfri internetadgang, så du kan forblive tilsluttet til alle dine online aktiviteter uden behov for et nyt telefonnummer. Opret nemt et hotspot for at dele din forbindelse med medrejsende eller familie, en funktion der ofte blokeres af andre udbydere, men som vi fuldt ud understøtter. Nyd bekvemmeligheden ved øjeblikkelig tilslutning på eSIM-kompatible enheder, så du og dine kære kan være online når som helst, hvor som helst. Bekræft venligst, om din enhed understøtter eSIM for at sikre, at du er klar til vores internettilbud. Bemærk venligst, at opkald og sms ikke understøttes med vores eSIM.',
      'image' => 'images/features/feature2.jpg',
    ],
  ],
];
