<?php

//This file is automatically generated. Do not modify.

return [
  'all_rights_reserved' => 'Alle rettigheder forbeholdes.',
  'foreign_currencies_for_reference_only' => 'Udenlandske valutaer er kun til reference. Fakturering vil være i Euro.',
];
