<?php

//This file is automatically generated. Do not modify.

return [
  'from' => ':price/GB',
  'title' => 'Forbind dig globalt med vores eSIMs',
  'subtitle' => 'Udforsk vores eSIM-pakker og forbliv forbundet, uanset hvor du er!',
  'search_destination' => 'Find en destination',
  'show_all_esim' => 'Vis alle eSIM-planer',
  'how_it_works' => 'Hvordan fungerer det?',
  'steps' => [
    [
      'title' => 'Trin 1',
      'description' => 'Tjek om din enhed er eSIM-kompatibel i vores kompatibilitetsliste.',
    ],
    [
      'title' => 'Trin 2',
      'description' => 'Vælg din destination og den ønskede eSIM dataplan',
    ],
    [
      'title' => 'Trin 3',
      'description' => 'Køb det eSIM-kort, der bedst passer til dine behov',
    ],
    [
      'title' => 'Trin 4',
      'description' => 'Din eSIM vil blive leveret automatisk. Følg instruktionerne i din e-mail.',
    ],
    [
      'title' => 'Trin 5',
      'description' => 'Installer din eSIM-profil og nyd din rejse!',
    ],
  ],
  'supported_networks' => 'Understøttede netværksudbydere',
  'supported_networks_description' => 'Vi arbejder tæt sammen med betroede, markedsledende forbindelses-, medie- og teknologimærker over hele verden.',
  'and_many_more' => 'og meget mere...',
  'user_reviews' => 'Hvad vores tilfredse brugere siger',
  'user_reviews_subtitle' => 'Se, hvorfor rejsende verden over stoler på vores eSIM for problemfri, pålidelig forbindelse på farten.',
  'faq' => 'Ofte stillede spørgsmål',
  'popular_destinations' => 'Populære destinationer',
  'popular_destinations_description' => 'Opdag vores mest populære eSIM-destinationer, og forbliv forbundet, uanset hvor du går!',
  'see_all_destinations' => 'Se alle destinationer',
];
