<?php

//This file is automatically generated. Do not modify.

return [
  'home' => 'Hjem',
  'supported-devices' => 'Understøttede enheder',
  'destinations' => 'Alle destinationer',
  'about' => 'Om',
  'contact' => 'Kontakt',
  'portal_link' => 'Min Portal',
];
