<?php

//This file is automatically generated. Do not modify.

return [
  'days' => 'dage',
  'buy_plan' => 'Køb nu!',
  'perks' => [
    'instant' => 'Direkte levering',
    'advanced_self_service' => 'Avanceret selvbetjeningsportal',
    '247_support' => '24/7 live chat support',
    'prepaid' => 'Forudbetalt, ingen betingelser knyttet',
    'no_roaming' => 'Ingen roamingafgifter',
  ],
  'local_for' => 'Lokale eSIMs til :countryName',
  'not_available_yet' => 'Vi tilbyder i øjeblikket ikke eSIMs til dette land.',
  'not_available_yet_contact_us' => 'Vi arbejder hårdt på at udvide vores globale dækning. Hvis du er interesseret i eSIMs til dette land i mellemtiden, bedes du kontakte os.',
  'top_plan' => 'Mest populær',
  'all_features' => 'Alle funktioner',
  'features' => [
    'feature_one' => 'Mulig hotspot',
    'feature_two' => 'Dækning på tværs af alle nationale netværk',
    'feature_three' => 'Simpel opgradering i din personlige portal',
  ],
  'buy_now' => 'Køb nu',
  'starting_from' => 'Starter fra',
  'choose_destination' => 'Find en destination',
  'how_esim_works' => [
    'title' => 'Hvordan eSIM fungerer',
    'subtitle' => 'Det er nemt at komme i gang med eSIM! Følg disse enkle trin for at forblive tilsluttet.',
    'steps' => [
      [
        'title' => 'Køb dit eSIM',
        'description' => 'Vælg din destination, vælg et bundt der opfylder dine databehov, og afslut dit køb.',
        'image' => '/images/howesimworks/1.png',
      ],
      [
        'title' => 'Modtag dit eSIM',
        'description' => 'Modtag din eSIM QR-kode direkte i din e-mail. Klar til brug med det samme.',
        'image' => '/images/howesimworks/2.png',
      ],
      [
        'title' => 'Aktiver og forbind',
        'description' => 'Scan QR-koden, aktiver dit eSIM, og nyd hurtige, pålidelige data, uanset hvor du rejser.',
        'image' => '/images/howesimworks/3.png',
      ],
    ],
  ],
  'sub_description' => 'Vælg dit bundle nedenfor og nyd problemfri forbindelse i :countryName på de bedste netværk til den bedste pris.',
];
