<?php

//This file is automatically generated. Do not modify.

return [
  'Rens' => [
    'role' => 'Medstifter',
    'image' => '/images/team/rens.png',
  ],
  'Luuk' => [
    'role' => 'Medstifter',
    'image' => '/images/team/luuk.png',
  ],
  'Fleur' => [
    'role' => 'Kundesupport',
    'image' => '/images/team/fleur.png',
  ],
  'Patrick' => [
    'role' => 'Udvikler',
    'image' => '/images/team/patrick.png',
  ],
];
