<?php

//This file is automatically generated. Do not modify.

return [
  'title' => 'Om oss',
  'subtitle' => 'Navigera världen utan gränser med oss. Vi är din ultimata partner som håller dig ansluten oavsett vart din passion tar dig.',
  'our_team' => 'Vårt Team',
  'our_team_subtitle' => 'Vi tror på att ge resenärer möjlighet till pålitlig och prisvärd global datakoppling. Vårt mångsidiga team är enat i att skapa en mer uppkopplad och tillgänglig värld för alla som är på språng.',
  'why_us' => 'Varför välja oss',
  'why_us_subtitle' => 'Vi är stolta över vår pålitliga service, konkurrenskraftiga priser och kundorienterade tillvägagångssätt. Din tillfredsställelse är vår högsta prioritet.',
  'why_us_reasons' => [
    [
      'title' => 'Flexibla planer utformade för dina resebehov',
      'subtitle' => 'Välj bland ett utbud av prisvärda paket anpassade för olika länder och regioner. Vi ger dig flexibiliteten att välja den perfekta dataplanen, så att du bara betalar för det du behöver, utan dolda kostnader.',
      'image' => '/images/whyus/nlo2.png',
    ],
    [
      'title' => 'Direkt aktivering, inga fysiska SIM-kort behövs',
      'subtitle' => 'Dagarna med att byta fysiska SIM-kort är över. Med oss levereras din eSIM direkt via e-post och kan aktiveras inom några minuter. Skanna bara QR-koden så är du redo att ansluta.',
      'image' => '/images/whyus/nlo3.png',
    ],
  ],
  'contact' => 'Kontakta oss',
  'contact_subtitle' => 'Vi är här för att hjälpa dig. Om du har några frågor eller behöver hjälp, vänligen kontakta oss.',
];
