<?php

//This file is automatically generated. Do not modify.

return [
  'title' => 'Alla våra destinationer',
  'subtitle' => 'Oavsett vart du går har vi dig täckt med eSIMer för varje destination. Välj din destination nedan för att komma igång.',
];
