<?php

//This file is automatically generated. Do not modify.

return [
  [
    'question' => 'Vad är en eSIM och hur kan jag använda :organisationName?',
    'answer' => 'En eSIM, eller inbäddad SIM, är ett digitalt SIM-kort som gör att användare kan aktivera och hantera flera mobilplaner på en enhet utan att behöva ett fysiskt SIM-kort. Med en eSIM kan du enkelt växla mellan mobiloperatörer och njuta av funktioner som att lägga till en extra linje för internationella resor eller upprätthålla separata dataplaner för personlig och affärsanvändning.',
  ],
  [
    'question' => 'Hur aktiverar jag eSIM mobilinternet med :organisationName?',
    'answer' => 'För att ansluta till internet med :organisationName eSIM, följ dessa steg: 1. Gå till dina inställningar för mobildata. 2. Slå på :organisationName mobil linje. 3. Aktivera dataroaming. 4. Välj :organisationName Internet-linjen som din primära anslutning. *Undvik att välja alternativet "Ta bort dataplan", eftersom detta kommer att radera din eSIM-profil.*',
  ],
  [
    'question' => 'Kan jag ringa telefonsamtal eller skicka textmeddelanden?',
    'answer' => ':organisationName\'s förbetalda eSIM-planer är utformade för databruk och inkluderar inte ett mobiltelefonnummer för traditionella samtal eller SMS-meddelanden. Vi rekommenderar att använda VoIP-applikationer som Facebook Messenger, WhatsApp, Viber, Telegram eller Skype för att hålla kontakten globalt utan behov av ett standard internationellt SIM-kort.',
  ],
  [
    'question' => 'Kan ett eSIM-kort återanvändas?',
    'answer' => 'Varje QR-kod för en eSIM är unik och kan endast användas på en enhet. När eSIM-profilen tas bort kan QR-koden inte återanvändas på samma eller en annan enhet, vilket säkerställer säkerhet och exklusivitet.',
  ],
  [
    'question' => 'När börjar varaktigheten för eSIM-mobil dataplans?',
    'answer' => 'Varaktigheten för din eSIM-data plan börjar omedelbart efter att din enhet första gången ansluter till ett mobilnät med eSIMen.',
  ],
  [
    'question' => 'Kan jag förlänga utgångsdatumet för min nuvarande eSIM mobil dataplans?',
    'answer' => 'Självklart! Du kommer att få flera push-notiser när du nästan har slut på ditt paket. Du kan enkelt fylla på genom din personliga portal.',
  ],
  [
    'question' => 'Kan jag använda tethering eller Personlig Hotspot med :organisationName?',
    'answer' => 'Ja, du kan dela din mobildata med andra enheter via din :organisationName-eSIM. Installera helt enkelt :organisationName-eSIM på din enhet och aktivera Personlig Hotspot i dina inställningar. Denna funktion ingår utan extra kostnad, men vänligen notera att användning av delad data kommer att dras från din plan.',
  ],
  [
    'question' => 'Kan jag behålla mina personliga meddelandeappnummer medan jag använder eSIM från :organisationName?',
    'answer' => 'Ja, du kan fortsätta använda din WhatsApp, Snapchat, Telegram och andra meddelandeappar tillsammans med din :organisationName förbetalda eSIM utan några problem.',
  ],
  [
    'question' => 'Hur kan jag överföra min eSIM till en ny telefon?',
    'answer' => 'Innan du överför, se till att din nya smartphone stöder eSIM-teknik. Kontakta vårt supportteam för att skapa en ny eSIM-profil, logga sedan in på ditt :organisationName-konto på den nya enheten för att installera QR-koden. Se till att du bekräftar att du använder en annan enhet för korrekta inställningsuppdateringar.',
  ],
  [
    'question' => 'Finns det kontrakt som de hos traditionella eSIM-leverantörer?',
    'answer' => 'Nej, :organisationName kräver inte att du skriver under kontrakt. Du kan aktivera eller avaktivera ditt eSIM-kort som du vill, beroende på dina planer. Vi hjälper gärna till.',
  ],
  [
    'question' => 'Vad är skillnaden mellan :organisationName\'s eSIM och standard roaming dataplaner från fysiska mobiloperatörer?',
    'answer' => ':organisationName erbjuder kontraktsfria dataplaner utan dolda roamingkostnader. Du betalar endast för den data du använder, beroende på det paket du väljer, vilket ofta gör det till ett mer ekonomiskt alternativ.',
  ],
  [
    'question' => 'Varför är min datatakt långsam?',
    'answer' => 'Datahastighet kan påverkas av olika faktorer, inklusive typen av smartphone du har, nätverksteknologi, de webbplatser eller appar du använder, och tidpunkten på dagen. Dessutom kan hastigheterna variera beroende på nätverksinfrastrukturen i landet. Om du upplever långsamma hastigheter, försök att starta om din telefon och dela eventuella hastighetsresultat med oss, särskilt jämförelser med och utan :LTE-läge aktiverat.',
  ],
  [
    'question' => 'Hur kan jag se mina paket?',
    'answer' => 'Du kan spåra din återstående data och begränsningar i vår kundpanel.',
  ],
  [
    'question' => 'Vad gör :organisationName annorlunda än andra eSIM-tjänster?',
    'answer' => ':organisationName står ut genom att samarbeta med lokala operatörer i över 200 länder, och erbjuder kostnadseffektiva datapaket utan mellanhänder. Vi erbjuder robust täckning och en enkel aktiveringsprocess. :organisationName är perfekt för resenärer som söker mobila internettlösningar.',
  ],
];
