<?php

//This file is automatically generated. Do not modify.

return [
  'title' => 'Håll dig uppkopplad online i :countryName',
  'subtitle' => 'Reser till :countryName? Håll dig uppkopplad med vårt eSIM, så att du har omedelbar internetåtkomst vid ankomsten.',
  'features' => [
    [
      'title' => 'Pålitligt och snabbt online i :countryName',
      'subtitle' => ':countryName är en vacker destination, med livliga moderna städer och hisnande natursköna landskap. Förbättra din reseupplevelse med vår eSIM, som säkerställer att du är uppkopplad direkt vid ankomst. 
        Säg adjö till besväret med att leta efter ett lokalt SIM-kort eller hantera kostsam dataroaming. Med vår eSIM får du sömlös tillgång till 4G/5G-nätverk från landets främsta leverantörer, vilket håller dig online oavsett vart din resa tar dig.',
      'image' => 'images/features/feature1.jpg',
    ],
    [
      'title' => 'Håll kontakten med nära och kära',
      'subtitle' => 'Vår eSIM är utformad för sömlös internetåtkomst, vilket håller dig ansluten för alla dina onlineaktiviteter utan behov av ett nytt telefonnummer. Skapa enkelt en hotspot för att dela din anslutning med medresenärer eller familj, en funktion som ofta blockeras av andra leverantörer men som vi fullt ut stöder. Njut av bekvämligheten med omedelbar anslutning på eSIM-kompatibla enheter, vilket säkerställer att du och dina nära och kära är online när som helst, var som helst. Vänligen bekräfta om din enhet stöder eSIM för att säkerställa att du är redo för våra interneterbjudanden. Observera att samtal och SMS inte stöds med vår eSIM.',
      'image' => 'images/features/feature2.jpg',
    ],
  ],
];
