<?php

//This file is automatically generated. Do not modify.

return [
  'all_rights_reserved' => 'Alla rättigheter förbehållna.',
  'foreign_currencies_for_reference_only' => 'Utländska valutor är endast för referens. Fakturering kommer att ske i Euro.',
];
