<?php

//This file is automatically generated. Do not modify.

return [
  'from' => ':price/GB',
  'title' => 'Anslut globalt med våra eSIMer',
  'subtitle' => 'Utforska våra eSIM-paket och håll dig uppkopplad, oavsett var du är!',
  'search_destination' => 'Hitta en destination',
  'show_all_esim' => 'Visa alla eSIM-planer',
  'how_it_works' => 'Hur fungerar det?',
  'steps' => [
    [
      'title' => 'Steg 1',
      'description' => 'Kontrollera om din enhet är eSIM-kompatibel i vår kompatibilitetslista.',
    ],
    [
      'title' => 'Steg 2',
      'description' => 'Välj din destination och den önskade eSIM-data planen',
    ],
    [
      'title' => 'Steg 3',
      'description' => 'Köp det eSIM-kort som bäst passar dina behov',
    ],
    [
      'title' => 'Steg 4',
      'description' => 'Din eSIM kommer att levereras automatiskt. Följ instruktionerna i ditt e-postmeddelande.',
    ],
    [
      'title' => 'Steg 5',
      'description' => 'Installera din eSIM-profil och njut av din resa!',
    ],
  ],
  'supported_networks' => 'Stödda nätverksleverantörer',
  'supported_networks_description' => 'Vi arbetar nära med betrodda marknadsledande varumärken inom connectivity, media och teknologi runt om i världen.',
  'and_many_more' => 'och mycket mer...',
  'user_reviews' => 'Vad våra nöjda användare säger',
  'user_reviews_subtitle' => 'Se varför resenärer runt om i världen förlitar sig på vår eSIM för sömlös, pålitlig uppkoppling på språng.',
  'faq' => 'Vanliga frågor',
  'popular_destinations' => 'Populära destinationer',
  'popular_destinations_description' => 'Upptäck våra mest populära eSIM-destinationer och håll dig ansluten, oavsett vart du går!',
  'see_all_destinations' => 'Visa alla destinationer',
];
