<?php

//This file is automatically generated. Do not modify.

return [
  'days' => 'dagar',
  'buy_plan' => 'Köp nu!',
  'perks' => [
    'instant' => 'Direktleverans',
    'advanced_self_service' => 'Avancerad självbetjäningsportal',
    '247_support' => '24/7 live chat support',
    'prepaid' => 'Förbetald, inga villkor kopplade',
    'no_roaming' => 'Inga roamingavgifter',
  ],
  'local_for' => 'Lokala eSIMer för :countryName',
  'not_available_yet' => 'Vi erbjuder för närvarande inte eSIMer för detta land.',
  'not_available_yet_contact_us' => 'Vi arbetar hårt för att utöka vår globala täckning. Om du är intresserad av eSIMs för detta land under tiden, vänligen kontakta oss.',
  'top_plan' => 'Mest populär',
  'all_features' => 'Alla funktioner',
  'features' => [
    'feature_one' => 'Möjlig hotspot',
    'feature_two' => 'Täckning över alla nationella nätverk',
    'feature_three' => 'Enkel uppgradering i din personliga portal',
  ],
  'buy_now' => 'Köp nu',
  'starting_from' => 'Börjar från',
  'choose_destination' => 'Hitta en destination',
  'how_esim_works' => [
    'title' => 'Hur eSIM fungerar',
    'subtitle' => 'Att komma igång med eSIM är enkelt! Följ dessa enkla steg för att hålla dig ansluten.',
    'steps' => [
      [
        'title' => 'Köp din eSIM',
        'description' => 'Välj din destination, välj ett paket som uppfyller dina databehov och slutför ditt köp.',
        'image' => '/images/howesimworks/1.png',
      ],
      [
        'title' => 'Mottag din eSIM',
        'description' => 'Ta emot din eSIM QR-kod direkt i din e-post. Klar att använda omedelbart.',
        'image' => '/images/howesimworks/2.png',
      ],
      [
        'title' => 'Aktivera och Anslut',
        'description' => 'Skanna QR-koden, aktivera din eSIM och njut av snabb, pålitlig data oavsett vart du reser.',
        'image' => '/images/howesimworks/3.png',
      ],
    ],
  ],
  'sub_description' => 'Välj ditt paket nedan och njut av sömlös uppkoppling i :countryName på de bästa nätverken till det bästa priset.',
];
