<?php

//This file is automatically generated. Do not modify.

return [
  'title' => 'eSIM-tjänst - Förbetalda virtuella SIM-kort för resenärer - :site_name',
  'description' => 'eSIM-tjänst ⏩ Förbetalda digitala SIM-kort för turism och affärer ⏩ Standard och obegränsade, lokala och globala mobildataplaner ⏩ Inga kontrakt ✅ Inga dolda roamingavgifter och -ersättningar ✅ - :site_name',
  'keywords' => 'eSIM, eSIM-tjänst, eSIM-kort, eSIM-data, eSIM-dataplans, eSIM-dataplans för resenärer, eSIM-dataplans för turister, eSIM-dataplans för företag, eSIM-dataplans för resor, eSIM-dataplans för Europa, eSIM-dataplans för USA, eSIM-dataplans för Asien, eSIM-dataplans för Afrika, eSIM-dataplans för Australien, eSIM-dataplans för Sydamerika, eSIM-dataplans för Nordamerika, eSIM-dataplans för Mellanöstern, eSIM-dataplans för Ryssland, eSIM-dataplans för Kina, eSIM-dataplans för Indien, eSIM-dataplans för Japan',
  'routes' => [
    'home' => [
      'title' => 'eSIM-tjänst - Förbetalda virtuella SIM-kort för resenärer - :site_name',
      'description' => 'eSIM-tjänst ⏩ Förbetalda digitala SIM-kort för turism och affärer ⏩ Standard och obegränsade, lokala och globala mobildataplaner ⏩ Inga kontrakt ✅ Inga dolda roamingkostnader och avgifter ✅ - :site_name',
    ],
    'about' => [
      'title' => 'Om oss - :site_name',
      'description' => 'Om oss ⏩ Förbetalda digitala SIM-kort för turism och affärer ⏩ Standard- och obegränsade, lokala och globala mobildata-planer ⏩ Inga kontrakt ✅ Inga dolda roamingavgifter och -kostnader ✅ - :site_name',
    ],
    'supported-devices' => [
      'title' => 'Stödda Enheter - :site_name',
      'description' => 'Stödda Enheter ⏩ Förbetalda digitala SIM-kort för turism och affärer ⏩ Standard och obegränsade, lokala och globala mobildataplaner ⏩ Inga kontrakt ✅ Inga dolda roamingavgifter och -avgifter ✅ - :site_name',
    ],
    'esim-bundle-per-country' => [
      'title' => 'eSIM :countryName - :site_name',
      'description' => 'eSIM :countryName ⏩ Förbetalda digitala SIM-kort för turism och affärer ⏩ Standard och obegränsade, lokala och globala mobildataplaner ⏩ Inga kontrakt ✅ Inga dolda roamingavgifter och -ersättningar ✅ - :site_name',
    ],
  ],
];
