<?php

//This file is automatically generated. Do not modify.

return [
  'title' => 'Apie mus',
  'subtitle' => 'Keliaukite po pasaulį be sienų kartu su mumis. Mes esame jūsų galutinis partneris, kuris palaiko jūsų ryšį, kur tik jūsų aistra jus nuveda.',
  'our_team' => 'Mūsų komanda',
  'our_team_subtitle' => 'Mes tikime, kad reikia suteikti galimybę keliautojams naudotis patikima ir prieinama pasauline duomenų ryšio paslauga. Mūsų įvairi komanda yra vieninga, siekdama sukurti labiau sujungtą ir prieinamą pasaulį visiems, kurie yra kelyje.',
  'why_us' => 'Kodėl pasirinkti mus',
  'why_us_subtitle' => 'Mes didžiuojamės savo patikimu aptarnavimu, konkurencingomis kainomis ir klientui orientuotu požiūriu. Jūsų pasitenkinimas yra mūsų aukščiausias prioritetas.',
  'why_us_reasons' => [
    [
      'title' => 'Lankstūs planai, sukurti jūsų kelionės poreikiams',
      'subtitle' => 'Pasirinkite iš įvairių prieinamų paketų, pritaikytų skirtingoms šalims ir regionams. Mes suteikiame jums lankstumo pasirinkti tobulą duomenų planą, todėl mokate tik už tai, ko jums reikia, be jokių paslėptų išlaidų.',
      'image' => '/images/whyus/nlo2.png',
    ],
    [
      'title' => 'Tiesioginis aktyvavimas, nereikia fizinių SIM kortelių',
      'subtitle' => 'Fizinio SIM kortelių keitimo dienos baigėsi. Su mumis jūsų eSIM pristatoma tiesiai el. paštu ir gali būti aktyvuota per kelias minutes. Tiesiog nuskenuokite QR kodą ir esate pasiruošę prisijungti.',
      'image' => '/images/whyus/nlo3.png',
    ],
  ],
  'contact' => 'Susisiekite su mumis',
  'contact_subtitle' => 'Mes esame čia, kad jums padėtume. Jei turite klausimų arba reikia pagalbos, prašome susisiekti su mumis.',
];
