<?php

//This file is automatically generated. Do not modify.

return [
  'title' => 'Visi mūsų tikslai',
  'subtitle' => 'Kur bebūtumėte, mes turime jums sprendimą su eSIM kortelėmis kiekvienam tikslui. Pasirinkite savo tikslą žemiau, kad pradėtumėte.',
];
