<?php

//This file is automatically generated. Do not modify.

return [
  'title' => 'Palaikomos įrenginiai',
  'subtitle' => 'Mes palaikome platų įrenginių spektrą. Patikrinkite, ar jūsų įrenginys yra žemiau pateiktame sąraše. Įrenginiai yra organizuoti pagal gamintoją.',
  'models_below' => 'Palaikomi modeliai išvardyti žemiau.',
];
