<?php

//This file is automatically generated. Do not modify.

return [
  'faq' => 'DUK',
  'subtitle' => 'Ar turite klausimų? Mes turime atsakymus. Rasite viską, ką reikia žinoti apie mūsų eSIMs.',
];
