<?php

//This file is automatically generated. Do not modify.

return [
  [
    'question' => 'Kas yra eSIM ir kaip galiu naudoti :organisationName?',
    'answer' => 'eSIM, arba įmontuota SIM, yra skaitmeninė SIM kortelė, leidžianti vartotojams aktyvuoti ir valdyti kelis mobiliuosius planus viename įrenginyje be fizinės SIM kortelės. Su eSIM galite lengvai keisti mobiliuosius tiekėjus ir mėgautis tokiais privalumais kaip papildomos linijos pridėjimas tarptautiniams kelionėms arba atskirų duomenų planų išlaikymas asmeniniam ir verslo naudojimui.',
  ],
  [
    'question' => 'Kaip aktyvinti eSIM mobiliuosius interneto ryšius su :organisationName?',
    'answer' => 'Norėdami prisijungti prie interneto naudodami :organisationName eSIM, atlikite šiuos veiksmus: 1. Eikite į savo Mobiliojo duomenų nustatymus. 2. Įjunkite :organisationName mobilųjį ryšį. 3. Aktyvuokite Duomenų tarptinklinį ryšį. 4. Pasirinkite :organisationName interneto liniją kaip savo pagrindinį ryšį. *Venkite pasirinkti parinktį "Pašalinti duomenų planą", nes tai ištrins jūsų eSIM profilį.*',
  ],
  [
    'question' => 'Ar galiu skambinti telefonu ar siųsti tekstines žinutes?',
    'answer' => ':organisationName išankstiniai eSIM planai skirti tik duomenų naudojimui ir neapima mobiliojo telefono numerio tradiciniams skambučiams ar SMS žinutėms. Rekomenduojame naudoti VoIP programas, tokias kaip Facebook Messenger, WhatsApp, Viber, Telegram arba Skype, kad galėtumėte bendrauti visame pasaulyje be standartinės tarptautinės SIM kortelės.',
  ],
  [
    'question' => 'Ar eSIM kortelę galima pakartotinai naudoti?',
    'answer' => 'Kiekvienas QR kodas eSIM yra unikalus ir gali būti naudojamas tik viename įrenginyje. Ištrynus eSIM profilį, QR kodas negali būti pakartotinai naudojamas tame pačiame ar kitame įrenginyje, užtikrinant saugumą ir išskirtinumą.',
  ],
  [
    'question' => 'Kada prasideda eSIM mobiliojo duomenų planų trukmė?',
    'answer' => 'Jūsų eSIM duomenų plano trukmė prasideda iš karto po to, kai jūsų įrenginys pirmą kartą prisijungia prie mobiliojo tinklo su eSIM.',
  ],
  [
    'question' => 'Ar galiu pratęsti savo dabartinio eSIM mobiliojo duomenų plano galiojimo laiką?',
    'answer' => 'Žinoma! Jūs gausite kelis pranešimus, kai beveik baigsis jūsų paketas. Galite lengvai papildyti per savo asmeninį portalą.',
  ],
  [
    'question' => 'Ar galiu naudoti tethering arba Asmeninį Hotspot su :organisationName?',
    'answer' => 'Taip, galite dalintis savo mobiliaisiais duomenimis su kitais įrenginiais per savo :organisationName-eSIM. Tiesiog įdiekite :organisationName-eSIM savo įrenginyje ir įjunkite Asmeninį Hotspot savo nustatymuose. Ši funkcija yra įtraukta be papildomų mokesčių, tačiau atkreipkite dėmesį, kad naudojant prijungtus duomenis bus atimta iš jūsų plano.',
  ],
  [
    'question' => 'Ar galiu išsaugoti savo asmeninių žinučių programos numerius, naudodamas :organisationName eSIM?',
    'answer' => 'Taip, galite toliau naudoti savo WhatsApp, Snapchat, Telegram ir kitas žinučių programas kartu su savo :organisationName išankstinio mokėjimo eSIM be jokių problemų.',
  ],
  [
    'question' => 'Kaip galiu perkelti savo eSIM į naują telefoną?',
    'answer' => 'Prieš perduodami, įsitikinkite, kad jūsų naujasis išmanusis telefonas palaiko eSIM technologiją. Susisiekite su mūsų palaikymo komanda, kad sukurtumėte naują eSIM profilį, tada prisijunkite prie savo :organisationName paskyros naujame įrenginyje, kad įdiegtumėte QR kodą. Įsitikinkite, kad patvirtinote, jog naudojate kitą įrenginį, kad gautumėte tikslius nustatymų atnaujinimus.',
  ],
  [
    'question' => 'Ar yra sutarčių, panašių į tradicinių eSIM paslaugų teikėjų?',
    'answer' => 'Ne, :organisationName nereikalauja, kad pasirašytumėte sutartis. Galite aktyvuoti arba deaktyvuoti savo eSIM kortelę, kaip norite, priklausomai nuo jūsų planų. Mes džiaugiamės galėdami jums padėti.',
  ],
  [
    'question' => 'Koks yra skirtumas tarp :organisationName eSIM ir standartinių tarptautinio roaming\'o duomenų planų iš fizinių mobiliojo ryšio operatorių?',
    'answer' => ':organisationName siūlo sutartimis nesusijusius duomenų planus be paslėptų tarptautinių mokesčių. Jūs mokate tik už duomenis, kuriuos naudojate, priklausomai nuo pasirinkto paketo, todėl tai dažnai yra ekonomiškesnis pasirinkimas.',
  ],
  [
    'question' => 'Kodėl mano duomenų greitis lėtas?',
    'answer' => 'Duomenų greitį gali paveikti įvairūs veiksniai, įskaitant turimą išmanųjį telefoną, tinklo technologiją, svetaines ar programas, kurias naudojate, ir paros laiką. Be to, greičiai gali skirtis priklausomai nuo šalies tinklo infrastruktūros. Jei patiriate lėtą greitį, pabandykite perkrauti savo telefoną ir pasidalykite bet kokiais greičio rezultatais su mumis, ypač palyginimais su ir be :LTE režimo.',
  ],
  [
    'question' => 'Kaip galiu peržiūrėti savo bundles?',
    'answer' => 'Galite stebėti savo likusius duomenis ir limitus mūsų klientų skydelyje.',
  ],
  [
    'question' => 'Kuo :organisationName skiriasi nuo kitų eSIM paslaugų?',
    'answer' => ':organisationName išsiskiria bendradarbiaudama su vietiniais operatoriais daugiau nei 200 šalių, siūlydama ekonomiškus duomenų paketus be tarpininkų. Mes teikiame patikimą aprėptį ir paprastą aktyvavimo procesą. :organisationName puikiai tinka keliautojams, ieškantiems mobiliųjų interneto sprendimų.',
  ],
];
