<?php

//This file is automatically generated. Do not modify.

return [
  'title' => 'Likite prisijungę internete :countryName',
  'subtitle' => 'Kelionė į :countryName? Išlaikykite ryšį su mūsų eSIM, užtikrindami, kad turėtumėte momentinį interneto prieigą atvykę.',
  'features' => [
    [
      'title' => 'Patikimai ir greitai internetu :countryName',
      'subtitle' => ':countryName yra nuostabi vieta, pasižyminti gyvybingais moderniais miestais ir kvapą gniaužiančiais gamtos peizažais. Pagerinkite savo kelionės patirtį su mūsų eSIM, užtikrinančia, kad iš karto atvykus liksite prijungti. 
        Atsisveikinkite su varginančiu vietinio SIM kortelės paieškos procesu ar brangiu duomenų tarptinklinimu. Su mūsų eSIM mėgausitės sklandžiu prieiga prie 4G/5G tinklų iš geriausių šalies tiekėjų, leisdami jums būti prisijungus bet kur, kur nuves jūsų kelionė.',
      'image' => 'images/features/feature1.jpg',
    ],
    [
      'title' => 'Būkite prijungti prie mylimų žmonių',
      'subtitle' => 'Mūsų eSIM yra sukurta sklandžiam interneto prieigai, leidžiančiai jums būti prijungtam visiems jūsų internetiniams veiksmams be naujo telefono numerio. Lengvai sukurkite hotspot\'ą, kad galėtumėte dalintis savo ryšiu su kitais keliautojais ar šeima, funkcija, kuri dažnai yra blokuojama kitų paslaugų teikėjų, tačiau visiškai palaikoma mūsų. Mėgaukitės patogumu, kai greitai prisijungiate prie eSIM suderinamų įrenginių, užtikrindami, kad jūs ir jūsų artimieji liktų prisijungę bet kada, bet kur. Prašome patvirtinti, ar jūsų įrenginys palaiko eSIM, kad būtumėte pasiruošę mūsų interneto pasiūlymams. Prašome atkreipti dėmesį, kad skambinimas ir žinučių siuntimas nėra palaikomi su mūsų eSIM.',
      'image' => 'images/features/feature2.jpg',
    ],
  ],
];
