<?php

//This file is automatically generated. Do not modify.

return [
  'all_rights_reserved' => 'Visos teisės saugomos.',
  'foreign_currencies_for_reference_only' => 'Užsienio valiutos yra tik informacinės. Sąskaitos bus išrašomos eurais.',
];
