<?php

//This file is automatically generated. Do not modify.

return [
  'from' => ':price/GB',
  'title' => 'Prisijunkite globaliai su mūsų eSIM\'ais',
  'subtitle' => 'Išnagrinėkite mūsų eSIM paketus ir likite prijungti, kur bebūtumėte!',
  'search_destination' => 'Raskite paskirties vietą',
  'show_all_esim' => 'Rodyti visus eSIM planus',
  'how_it_works' => 'Kaip tai veikia?',
  'steps' => [
    [
      'title' => 'Žingsnis 1',
      'description' => 'Patikrinkite, ar jūsų įrenginys yra eSIM suderinamas mūsų suderinamumo sąraše.',
    ],
    [
      'title' => 'Žingsnis 2',
      'description' => 'Pasirinkite savo kelionės vietą ir pageidaujamą eSIM duomenų planą',
    ],
    [
      'title' => '3 žingsnis',
      'description' => 'Pirkite eSIM kortelę, kuri geriausiai atitinka jūsų poreikius.',
    ],
    [
      'title' => 'Žingsnis 4',
      'description' => 'Jūsų eSIM bus pristatytas automatiškai. Sekite nurodymus savo el. pašte.',
    ],
    [
      'title' => 'Žingsnis 5',
      'description' => 'Įdiekite savo eSIM profilį ir mėgaukitės savo kelione!',
    ],
  ],
  'supported_networks' => 'Palaikomi tinklo teikėjai',
  'supported_networks_description' => 'Mes glaudžiai bendradarbiaujame su patikimais rinkos lyderiais ryšio, žiniasklaidos ir technologijų srityse visame pasaulyje.',
  'and_many_more' => 'ir dar daugiau...',
  'user_reviews' => 'Ką sako mūsų patenkinti vartotojai',
  'user_reviews_subtitle' => 'Sužinokite, kodėl keliautojai visame pasaulyje pasitiki mūsų eSIM, kad gautų sklandų ir patikimą ryšį kelyje.',
  'faq' => 'Dažnai užduodami klausimai',
  'popular_destinations' => 'Populiarios kryptys',
  'popular_destinations_description' => 'Atraskite mūsų populiariausias eSIM kryptis ir likite prijungti, nesvarbu, kur keliaujate!',
  'see_all_destinations' => 'Peržiūrėti visus tikslus',
];
