<?php

//This file is automatically generated. Do not modify.

return [
  'home' => 'Namai',
  'supported-devices' => 'Palaikomos įrenginiai',
  'destinations' => 'Visos kryptys',
  'about' => 'Apie',
  'contact' => 'Kontaktas',
  'portal_link' => 'Mano Portalas',
];
