<?php

//This file is automatically generated. Do not modify.

return [
  'days' => 'dienos',
  'buy_plan' => 'Pirkite dabar!',
  'perks' => [
    'instant' => 'Tiesioginis pristatymas',
    'advanced_self_service' => 'Išplėstinė savitarnos portalas',
    '247_support' => '24/7 gyvas pokalbių palaikymas',
    'prepaid' => 'Išankstinis, jokių sąlygų nenurodytų',
    'no_roaming' => 'Nėra tarptautinių mokesčių',
  ],
  'local_for' => 'Vietinės eSIM kortelės :countryName',
  'not_available_yet' => 'Šiuo metu šiai šaliai nesiūlome eSIM.',
  'not_available_yet_contact_us' => 'Mes sunkiai dirbame, kad išplėstume savo pasaulinį aprėptį. Jei tuo tarpu jus domina eSIMs šiai šaliai, prašome susisiekti su mumis.',
  'top_plan' => 'Populiariausi',
  'all_features' => 'Visos funkcijos',
  'features' => [
    'feature_one' => 'Galimas karštasis taškas',
    'feature_two' => 'Dengimas visose nacionalinėse tinkluose',
    'feature_three' => 'Paprastas atnaujinimas jūsų asmeniniame porte.',
  ],
  'buy_now' => 'Pirkite dabar',
  'starting_from' => 'Pradedant nuo',
  'choose_destination' => 'Raskite vietą',
  'how_esim_works' => [
    'title' => 'Kaip veikia eSIM',
    'subtitle' => 'Pradėti naudotis eSIM yra paprasta! Sekite šiuos paprastus žingsnius, kad išliktumėte prijungti.',
    'steps' => [
      [
        'title' => 'Pirkite savo eSIM',
        'description' => 'Pasirinkite savo kelionės tikslą, pasirinkite paketą, kuris atitinka jūsų duomenų poreikius, ir užbaikite pirkimą.',
        'image' => '/images/howesimworks/1.png',
      ],
      [
        'title' => 'Gaukite savo eSIM',
        'description' => 'Gaukite savo eSIM QR kodą tiesiai į savo el. paštą. Paruoštas naudoti iš karto.',
        'image' => '/images/howesimworks/2.png',
      ],
      [
        'title' => 'Aktyvuoti ir Prijungti',
        'description' => 'Nuskaitykite QR kodą, aktyvuokite savo eSIM ir mėgaukitės greitais, patikimais duomenimis, kur bebūtumėte.',
        'image' => '/images/howesimworks/3.png',
      ],
    ],
  ],
  'sub_description' => 'Pasirinkite savo paketą žemiau ir mėgaukitės sklandžiu ryšiu :countryName geriausiose tinkluose už geriausią kainą.',
];
