<?php

//This file is automatically generated. Do not modify.

return [
  'Rens' => [
    'role' => 'Bendrasavininkas',
    'image' => '/images/team/rens.png',
  ],
  'Luuk' => [
    'role' => 'Bendrasavininkas',
    'image' => '/images/team/luuk.png',
  ],
  'Fleur' => [
    'role' => 'Klientų aptarnavimas',
    'image' => '/images/team/fleur.png',
  ],
  'Patrick' => [
    'role' => 'Kūrėjas',
    'image' => '/images/team/patrick.png',
  ],
];
