<?php

//This file is automatically generated. Do not modify.

return [
  'title' => 'Hakkımızda',
  'subtitle' => 'Sınırları olmayan bir dünyada bizimle gezin. Tutkunuzun sizi götürdüğü her yerde bağlantıda kalmanızı sağlayan nihai ortağınızız.',
  'our_team' => 'Ekibimiz',
  'our_team_subtitle' => 'Seyahat edenleri güvenilir ve uygun fiyatlı küresel veri bağlantısıyla güçlendirmeye inanıyoruz. Farklı ekibimiz, hareket halindeki herkes için daha bağlantılı ve erişilebilir bir dünya yaratma konusunda birleşmiştir.',
  'why_us' => 'Neden bizi seçmelisiniz',
  'why_us_subtitle' => 'Güvenilir hizmetimiz, rekabetçi fiyatlarımız ve müşteri odaklı yaklaşımımızla gurur duyuyoruz. Sizin memnuniyetiniz en yüksek önceliğimizdir.',
  'why_us_reasons' => [
    [
      'title' => 'Seyahat İhtiyaçlarınız için Tasarlanmış Esnek Planlar',
      'subtitle' => 'Farklı ülkeler ve bölgeler için tasarlanmış uygun fiyatlı paketlerden birini seçin. İhtiyacınız olanı ödeyerek, mükemmel veri planını seçme esnekliğini size sunuyoruz, gizli maliyet yok.',
      'image' => '/images/whyus/nlo2.png',
    ],
    [
      'title' => 'Doğrudan aktivasyon, fiziksel SIM kartlara ihtiyaç yok',
      'subtitle' => 'Fiziksel SIM kartlarını değiştirme günleri sona erdi. Bizimle, eSIM\'iniz doğrudan e-posta ile teslim edilir ve dakikalar içinde etkinleştirilebilir. Sadece QR kodunu tarayın ve bağlanmaya hazırsınız.',
      'image' => '/images/whyus/nlo3.png',
    ],
  ],
  'contact' => 'Bize ulaşın',
  'contact_subtitle' => 'Sizi yardımcı olmak için buradayız. Herhangi bir sorunuz varsa veya yardıma ihtiyacınız olursa, lütfen bizimle iletişime geçin.',
];
