<?php

//This file is automatically generated. Do not modify.

return [
  'first' => 'Trustpilot\'ta 4.5/5 olarak derecelendirildi',
  'second' => '24/7 Destek',
  'third' => 'Sadece en iyi networks',
];
