<?php

//This file is automatically generated. Do not modify.

return [
  'title' => 'Tüm destinasyonlarımız',
  'subtitle' => 'Gittiğiniz her yerde, her destinasyon için eSIM\'lerle sizi kapsıyoruz. Başlamak için aşağıdaki destinasyonu seçin.',
];
