<?php

//This file is automatically generated. Do not modify.

return [
  'title' => 'Desteklenen cihazlar',
  'subtitle' => 'Bir dizi cihazı destekliyoruz. Aşağıdaki listede cihazınızın olup olmadığını kontrol edin. Cihazlar üreticiye göre düzenlenmiştir.',
  'models_below' => 'Desteklenen modeller aşağıda listelenmiştir.',
];
