<?php

//This file is automatically generated. Do not modify.

return [
  'faq' => 'SSS',
  'subtitle' => 'Sorularınız mı var? Cevaplarımız var. eSIM\'lerimiz hakkında bilmeniz gereken her şeyi bulun.',
];
