<?php

//This file is automatically generated. Do not modify.

return [
  [
    'question' => 'eSIM nedir ve :organisationName\'ı nasıl kullanabilirim?',
    'answer' => 'eSIM, veya gömülü SIM, kullanıcıların tek bir cihazda fiziksel bir SIM kartına ihtiyaç duymadan birden fazla mobil planı etkinleştirmesine ve yönetmesine olanak tanıyan dijital bir SIM karttır. eSIM ile mobil sağlayıcılar arasında kolayca geçiş yapabilir ve uluslararası seyahat için ek bir hat ekleme veya kişisel ve iş kullanımı için ayrı veri planları sürdürme gibi özelliklerin tadını çıkarabilirsiniz.',
  ],
  [
    'question' => ':organisationName ile eSIM mobil interneti nasıl aktive ederim?',
    'answer' => ':organisationName eSIM kullanarak internete bağlanmak için şu adımları izleyin: 1. Mobil Veri ayarlarınıza gidin. 2. :organisationName mobil hattını açın. 3. Veri dolaşımını etkinleştirin. 4. :organisationName Internet hattını birincil bağlantınız olarak seçin. *"Veri planını kaldır" seçeneğini seçmekten kaçının, çünkü bu eSIM profilinizi siler.*',
  ],
  [
    'question' => 'Telefon görüşmeleri yapabilir miyim yoksa metin mesajları gönderebilir miyim?',
    'answer' => ':organisationName\'ın ön ödemeli eSIM planları yalnızca veri kullanımı için tasarlanmıştır ve geleneksel aramalar veya SMS mesajları için bir cep telefonu numarası içermez. Standart bir uluslararası SIM kartına ihtiyaç duymadan dünya genelinde bağlantıda kalmak için Facebook Messenger, WhatsApp, Viber, Telegram veya Skype gibi VoIP uygulamalarını kullanmanızı öneririz.',
  ],
  [
    'question' => 'Bir eSIM kartı yeniden kullanılabilir mi?',
    'answer' => 'Her bir eSIM için QR kodu benzersizdir ve yalnızca bir cihazda kullanılabilir. eSIM profili silindiğinde, QR kodu aynı veya başka bir cihazda yeniden kullanılamaz, bu da güvenlik ve ayrıcalıklılığı sağlar.',
  ],
  [
    'question' => 'eSIM mobil veri planlarının süresi ne zaman başlar?',
    'answer' => 'eSIM veri planınızın süresi, cihazınızın eSIM ile bir mobil ağa ilk bağlandığı andan itibaren başlar.',
  ],
  [
    'question' => 'Mevcut eSIM mobil veri planımın son kullanma tarihini uzatabilir miyim?',
    'answer' => 'Tabii ki! Paketinize yaklaşırken birden fazla bildirim alacaksınız. Kişisel portalınızdan kolayca bakiye yükleyebilirsiniz.',
  ],
  [
    'question' => ':organisationName ile tethering veya Kişisel Erişim Noktası kullanabilir miyim?',
    'answer' => 'Evet, :organisationName-eSIM\'iniz aracılığıyla mobil verinizi diğer cihazlarla paylaşabilirsiniz. Cihazınıza :organisationName-eSIM\'i kurun ve ayarlarınızda Kişisel Erişim Noktasını etkinleştirin. Bu özellik ek bir ücret olmadan dahil edilmiştir, ancak lütfen bağlı veri kullanmanın planınızdan düşüleceğini unutmayın.',
  ],
  [
    'question' => ':organisationName eSIM kullanırken kişisel mesajlaşma uygulamamın numaralarını saklayabilir miyim?',
    'answer' => 'Evet, :organisationName ön ödemeli eSIM\'inizi kullanırken WhatsApp, Snapchat, Telegram ve diğer mesajlaşma uygulamalarınızı sorunsuz bir şekilde kullanmaya devam edebilirsiniz.',
  ],
  [
    'question' => 'Yeni bir telefona eSIM nasıl aktarabilirim?',
    'answer' => 'Yeni akıllı telefonunuzun eSIM teknolojisini desteklediğinden emin olun. Yeni bir eSIM profili oluşturmak için destek ekibimizle iletişime geçin, ardından yeni cihazda QR kodunu yüklemek için :organisationName hesabınıza giriş yapın. Ayar güncellemeleri için farklı bir cihaz kullandığınızı onayladığınızdan emin olun.',
  ],
  [
    'question' => 'Geleneksel eSIM sağlayıcıları gibi sözleşmeler var mı?',
    'answer' => 'Hayır, :organisationName sözleşme imzalamanızı gerektirmiyor. eSIM kartınızı istediğiniz gibi etkinleştirebilir veya devre dışı bırakabilirsiniz, planlarınıza bağlı olarak. Size yardımcı olmaktan mutluluk duyarız.',
  ],
  [
    'question' => ':organisationName\'nin eSIM\'i ile fiziksel mobil operatörlerin standart dolaşım veri planları arasındaki fark nedir?',
    'answer' => ':organisationName, gizli dolaşım maliyetleri olmadan sözleşmesiz veri planları sunmaktadır. Seçtiğiniz pakete bağlı olarak yalnızca kullandığınız veri için ödeme yaparsınız, bu da genellikle daha ekonomik bir seçenek olmasını sağlar.',
  ],
  [
    'question' => 'Veri hızım neden yavaş?',
    'answer' => 'Veri hızı, sahip olduğunuz akıllı telefonun türü, ağ teknolojisi, kullandığınız web siteleri veya uygulamalar ve günün saati gibi çeşitli faktörlerden etkilenebilir. Ayrıca, hızlar ülkenin ağ altyapısına bağlı olarak değişebilir. Eğer yavaş hızlar yaşıyorsanız, telefonunuzu yeniden başlatmayı deneyin ve özellikle LTE modu etkinleştirildiğinde ve etkinleştirilmediğinde yapılan hız karşılaştırmalarıyla birlikte herhangi bir hız sonucunu bizimle paylaşın.',
  ],
  [
    'question' => 'Paketlerimi nasıl görüntüleyebilirim?',
    'answer' => 'Kalan verilerinizi ve limitlerinizi müşteri panelimizde takip edebilirsiniz.',
  ],
  [
    'question' => ':organisationName\'ı diğer eSIM hizmetlerinden farklı kılan nedir?',
    'answer' => ':organisationName, yerel operatörlerle işbirliği yaparak 200\'den fazla ülkede dikkat çekiyor ve aracılara ihtiyaç duymadan maliyet etkin veri paketleri sunuyor. Güçlü kapsama alanı ve basit bir aktivasyon süreci sağlıyoruz. :organisationName, mobil internet çözümleri arayan gezginler için mükemmeldir.',
  ],
];
