<?php

//This file is automatically generated. Do not modify.

return [
  'title' => ':countryName\'da çevrimiçi kalın',
  'subtitle' => ':countryName\'a mı seyahat ediyorsunuz? Varışta anında internet erişimi sağlamak için eSIM\'imizle bağlantıda kalın.',
  'features' => [
    [
      'title' => 'güvenilir ve hızlı çevrimiçi :countryName',
      'subtitle' => ':countryName güzel bir destinasyondur, canlı modern şehirler ve nefes kesen doğal manzaralar sunmaktadır. Seyahat deneyiminizi eSIM\'imizle geliştirin, varışta anında bağlantıda kalmanızı sağlayın.  
        Yerel bir SIM kart aramanın veya pahalı veri dolaşımıyla uğraşmanın zorluğuna veda edin. eSIM\'imizle, ülkenin en iyi sağlayıcılarından 4G/5G ağlarına kesintisiz erişim sağlayacak, yolculuğunuz nereye giderse gitsin çevrimiçi kalacaksınız.',
      'image' => 'images/features/feature1.jpg',
    ],
    [
      'title' => 'Sevdiklerinizle bağlantıda kalın',
      'subtitle' => 'eSIM\'imiz, yeni bir telefon numarasına ihtiyaç duymadan tüm çevrimiçi aktiviteleriniz için bağlantıda kalmanızı sağlayarak kesintisiz internet erişimi için tasarlanmıştır. Diğer sağlayıcılar tarafından genellikle engellenen, ancak bizim tarafımızdan tamamen desteklenen bir özellik olan bağlantınızı diğer gezginler veya ailenizle paylaşmak için kolayca bir hotspot oluşturun. eSIM uyumlu cihazlarda anında bağlantının rahatlığını yaşayın, böylece siz ve sevdikleriniz her zaman, her yerde çevrimiçi kalabilirsiniz. Internet tekliflerimiz için hazır olduğunuzu sağlamak adına lütfen cihazınızın eSIM\'i destekleyip desteklemediğini onaylayın. Lütfen eSIM\'imizle arama ve mesajlaşmanın desteklenmediğini unutmayın.',
      'image' => 'images/features/feature2.jpg',
    ],
  ],
];
