<?php

//This file is automatically generated. Do not modify.

return [
  'from' => ':price/GB',
  'title' => 'eSIM\'lerimizle küresel olarak bağlantı kurun',
  'subtitle' => 'eSIM paketlerimizi keşfedin ve nerede olursanız olun bağlantıda kalın!',
  'search_destination' => 'Bir destinasyon bul.',
  'show_all_esim' => 'Tüm eSIM planlarını göster',
  'how_it_works' => 'Nasıl çalışır?',
  'steps' => [
    [
      'title' => 'Adım 1',
      'description' => 'Cihazınızın eSIM uyumlu olup olmadığını uyumluluk listemizde kontrol edin.',
    ],
    [
      'title' => 'Adım 2',
      'description' => 'Hedefinizi ve istediğiniz eSIM veri planını seçin',
    ],
    [
      'title' => 'Adım 3',
      'description' => 'İhtiyaçlarınıza en uygun eSIM kartını satın alın.',
    ],
    [
      'title' => 'Adım 4',
      'description' => 'eSIM\'iniz otomatik olarak teslim edilecektir. E-postanızdaki talimatları izleyin.',
    ],
    [
      'title' => 'Adım 5',
      'description' => 'eSIM profilinizi yükleyin ve seyahatinizin tadını çıkarın!',
    ],
  ],
  'supported_networks' => 'Desteklenen ağ sağlayıcıları',
  'supported_networks_description' => 'Dünyanın dört bir yanında güvenilir pazar lideri bağlantı, medya ve teknoloji markalarıyla yakın işbirliği yapıyoruz.',
  'and_many_more' => 've çok daha fazlası...',
  'user_reviews' => 'Memnun kullanıcılarımız ne diyor',
  'user_reviews_subtitle' => 'Seyahat edenlerin dünya genelinde neden hareket halindeyken kesintisiz ve güvenilir bağlantı için eSIM\'imize güvendiğini görün.',
  'faq' => 'Sıkça Sorulan Sorular',
  'popular_destinations' => 'Popüler Destinasyonlar',
  'popular_destinations_description' => 'En popüler eSIM destinasyonlarımızı keşfedin ve nereye giderseniz gidin bağlantıda kalın!',
  'see_all_destinations' => 'Tüm destinasyonları görüntüle',
];
