<?php

//This file is automatically generated. Do not modify.

return [
  'home' => 'Ana Sayfa',
  'supported-devices' => 'Desteklenen cihazlar',
  'destinations' => 'Tüm destinasyonlar',
  'about' => 'Hakkında',
  'contact' => 'İletişim',
  'portal_link' => 'Benim Portalım',
];
