<?php

//This file is automatically generated. Do not modify.

return [
  'days' => 'günler',
  'buy_plan' => 'Şimdi satın al!',
  'perks' => [
    'instant' => 'Direkt teslimat',
    'advanced_self_service' => 'Gelişmiş self-service portal',
    '247_support' => '24/7 canlı sohbet desteği',
    'prepaid' => 'Peşin, herhangi bir koşul yok',
    'no_roaming' => 'Roaming ücreti yok',
  ],
  'local_for' => ':countryName için yerel eSIM\'ler',
  'not_available_yet' => 'Bu ülke için şu anda eSIM sunmuyoruz.',
  'not_available_yet_contact_us' => 'Küresel kapsama alanımızı genişletmek için çok çalışıyoruz. Bu arada, bu ülke için eSIM\'lere ilgi duyuyorsanız, lütfen bizimle iletişime geçin.',
  'top_plan' => 'En popüler',
  'all_features' => 'Tüm fonksiyonlar',
  'features' => [
    'feature_one' => 'Olası sıcak nokta',
    'feature_two' => 'Tüm ulusal ağlar boyunca kapsama',
    'feature_three' => 'Kişisel portalınızda basit bir yükseltme',
  ],
  'buy_now' => 'Şimdi satın al',
  'starting_from' => 'Başlayarak',
  'choose_destination' => 'Bir hedef bulun',
  'how_esim_works' => [
    'title' => 'eSIM nasıl çalışır',
    'subtitle' => 'eSIM ile başlamak kolay! Bağlı kalmak için bu basit adımları izleyin.',
    'steps' => [
      [
        'title' => 'eSIM\'inizi satın alın',
        'description' => 'Hedefinizi seçin, veri ihtiyaçlarınıza uygun bir paket seçin ve satın almanızı tamamlayın.',
        'image' => '/images/howesimworks/1.png',
      ],
      [
        'title' => 'eSIM\'inizi alın',
        'description' => 'eSIM QR kodunuzu doğrudan e-posta ile alın. Hemen kullanıma hazır.',
        'image' => '/images/howesimworks/2.png',
      ],
      [
        'title' => 'Aktif Et ve Bağlan',
        'description' => 'QR kodunu tarayın, eSIM\'inizi etkinleştirin ve seyahat ettiğiniz her yerde hızlı, güvenilir veri keyfini çıkarın.',
        'image' => '/images/howesimworks/3.png',
      ],
    ],
  ],
  'sub_description' => 'Aşağıdaki paketlerden birini seçin ve :countryName\'da en iyi fiyatla en iyi ağlarda kesintisiz bağlantının tadını çıkarın.',
];
