<?php

//This file is automatically generated. Do not modify.

return [
  'title' => 'eSIM Servisi - Seyahat Edenler İçin Ön Ödemeli Sanal SIM Kartlar - :site_name',
  'description' => 'eSIM hizmeti ⏩ Turizm ve iş için ön ödemeli dijital SIM kartları ⏩ Standart ve sınırsız, yerel ve küresel cep telefonu veri planları ⏩ Sözleşme yok ✅ Gizli dolaşım ücretleri ve masrafları yok ✅ - :site_name',
  'keywords' => 'eSIM, eSIM hizmeti, eSIM kartı, eSIM verisi, eSIM veri planı, eSIM veri planları, eSIM gezginler için veri planı, eSIM turistler için veri planı, eSIM iş için veri planı, eSIM seyahat için veri planı, eSIM Avrupa için veri planı, eSIM ABD için veri planı, eSIM Asya için veri planı, eSIM Afrika için veri planı, eSIM Avustralya için veri planı, eSIM Güney Amerika için veri planı, eSIM Kuzey Amerika için veri planı, eSIM Orta Doğu için veri planı, eSIM Rusya için veri planı, eSIM Çin için veri planı, eSIM Hindistan için veri planı, eSIM Japonya için veri planı',
  'routes' => [
    'home' => [
      'title' => 'eSIM Servisi - Seyahat Edenler için Ön Ödemeli Sanal SIM Kartlar - :site_name',
      'description' => 'eSIM hizmeti ⏩ Turizm ve iş için ön ödemeli dijital SIM kartlar ⏩ Standart ve sınırsız, yerel ve küresel cep telefonu veri planları ⏩ Sözleşme yok ✅ Gizli dolaşım ücretleri ve masrafları yok ✅ - :site_name',
    ],
    'about' => [
      'title' => 'Hakkımızda - :site_name',
      'description' => 'Hakkımızda ⏩ Turizm ve iş için ön ödemeli dijital SIM kartları ⏩ Standart ve sınırsız, yerel ve küresel cep telefonu veri planları ⏩ Sözleşme yok ✅ Gizli dolaşım ücretleri ve masrafları yok ✅ - :site_name',
    ],
    'supported-devices' => [
      'title' => 'Desteklenen Cihazlar - :site_name',
      'description' => 'Desteklenen Cihazlar ⏩ Turizm ve iş için ön ödemeli dijital SIM kartlar ⏩ Standart ve sınırsız, yerel ve küresel cep telefonu veri planları ⏩ Sözleşme yok ✅ Gizli dolaşım ücretleri ve masrafları yok ✅ - :site_name',
    ],
    'esim-bundle-per-country' => [
      'title' => ':countryName için Uygun Fiyatlı Yerel eSIM Teklifleri - :site_name',
      'description' => ':countryName için uygun fiyatlı yerel eSIM fırsatları ⏩ Turizm ve iş için ön ödemeli dijital SIM kartlar ⏩ Standart ve sınırsız, yerel ve küresel cep telefonu veri planları ⏩ Sözleşme yok ✅ Gizli dolaşım ücretleri ve masraflar yok ✅ - :site_name',
    ],
  ],
];
