<?php

//This file is automatically generated. Do not modify.

return [
  'title' => 'Om oss',
  'subtitle' => 'Naviger verda utan grenser med oss. Vi er din ultimate partner som held deg tilkobla uansett kvar lidenskapen din fører deg.',
  'our_team' => 'Vårt team',
  'our_team_subtitle' => 'Vi trur på å styrke reisande med pålitelig og rimelig global datatilkobling. Vårt mangfoldige team er samla om å skape ein meir samankopla og tilgjengeleg verda for alle på farten.',
  'why_us' => 'Kvifor velje oss',
  'why_us_subtitle' => 'Vi er stolte av vår pålitelige teneste, konkurransedyktige prisar og kundeorienterte tilnærming. Din tilfredsheit er vår høgste prioritet.',
  'why_us_reasons' => [
    [
      'title' => 'Fleksible planar designa for dine reisebehov',
      'subtitle' => 'Velg frå eit utval av rimelige pakkar tilpassa ulike land og regionar. Vi gir deg fleksibiliteten til å velje den perfekte dataplanen, slik at du berre betaler for det du treng, utan skjulte kostnader.',
      'image' => '/images/whyus/nlo2.png',
    ],
    [
      'title' => 'Direkte aktivering, ingen fysiske SIM-kort nødvendig',
      'subtitle' => 'Dagar med å bytte fysiske SIM-kort er over. Med oss blir din eSIM levert direkte via e-post og kan aktiverast innan få minutt. Bare skann QR-koden, så er du klar til å koble til.',
      'image' => '/images/whyus/nlo3.png',
    ],
  ],
  'contact' => 'Kontakt oss',
  'contact_subtitle' => 'Vi er her for å hjelpe deg. Hvis du har spørsmål eller trenger hjelp, vennligst kontakt oss.',
];
