<?php

//This file is automatically generated. Do not modify.

return [
  'title' => 'Støttede enheter',
  'subtitle' => 'Vi støtter et bredt spekter av enheter. Sjekk om enheten din er på listen nedenfor. Enhetene er organisert etter produsent.',
  'models_below' => 'Støttede modellar er lista opp nedanfor.',
];
