<?php

//This file is automatically generated. Do not modify.

return [
  'title' => 'Hald deg tilknytt online i :countryName',
  'subtitle' => 'Reiser til :countryName? Halda kontakten med vår eSIM, som sikrar at du har umiddelbar internettilgang ved ankomst.',
  'features' => [
    [
      'title' => 'Påliteleg og raskt på nettet i :countryName',
      'subtitle' => ':countryName er ein vakker destinasjon, med livlege moderne byar og fantastiske naturscener. Forbedre reiseopplevinga di med vår eSIM, som sikrar at du er tilkopla med ein gong du kjem fram. 
        Sei farvel til bryderiet med å leita etter eit lokalt SIM-kort eller handtera dyre dataroaming. Med vår eSIM vil du nyta sømlaus tilgang til 4G/5G-nettverk frå landets beste leverandørar, og halda deg på nett uansett kvar reisa di tar deg.',
      'image' => 'images/features/feature1.jpg',
    ],
    [
      'title' => 'Hald deg tilknytt med kjære.',
      'subtitle' => 'Vår eSIM er designet for sømløs internett-tilgang, som holder deg tilkoblet for alle dine online aktiviteter uten behov for et nytt telefonnummer. Lag enkelt et hotspot for å dele tilkoblingen din med medreisende eller familie, en funksjon som ofte er blokkert av andre leverandører, men som vi fullt ut støtter. Nyt bekvemmeligheten av øyeblikkelig tilkobling på eSIM-kompatible enheter, som sikrer at du og dine kjære forblir online når som helst, hvor som helst. Vennligst bekreft om enheten din støtter eSIM for å sikre at du er klar for våre internett-tilbud. Vennligst merk at samtaler og tekstmeldinger ikke støttes med vår eSIM.',
      'image' => 'images/features/feature2.jpg',
    ],
  ],
];
