<?php

//This file is automatically generated. Do not modify.

return [
  'all_rights_reserved' => 'Alle rettar reservert.',
  'foreign_currencies_for_reference_only' => 'Utanlandske valutaar er kun til referanse. Fakturering vil vere i Euro.',
];
