<?php

//This file is automatically generated. Do not modify.

return [
  'from' => ':price/GB',
  'title' => 'Knytt deg globalt med våre eSIM-er',
  'subtitle' => 'Utforsk våre eSIM-pakker og hold deg tilkoblet, uansett hvor du er!',
  'search_destination' => 'Finn ein destinasjon',
  'show_all_esim' => 'Vis alle eSIM-planar',
  'how_it_works' => 'Korleis fungerer det?',
  'steps' => [
    [
      'title' => 'Steg 1',
      'description' => 'Sjekk om enheten din er eSIM-kompatibel i vår kompatibilitetsliste.',
    ],
    [
      'title' => 'Steg 2',
      'description' => 'Velg destinasjonen din og den ønskede eSIM dataplanen',
    ],
    [
      'title' => 'Steg 3',
      'description' => 'Kjøp det eSIM-kortet som passer best for dine behov',
    ],
    [
      'title' => 'Steg 4',
      'description' => 'Din eSIM vil bli levert automatisk. Følg instruksjonene i e-posten din.',
    ],
    [
      'title' => 'Steg 5',
      'description' => 'Installer eSIM-profilen din og nyt turen!',
    ],
  ],
  'supported_networks' => 'Støttede nettverksleverandører',
  'supported_networks_description' => 'Vi arbeider nært med pålitelige markedsledande merkevarer innan tilknyting, media og teknologi over heile verda.',
  'and_many_more' => 'og mykje meir...',
  'user_reviews' => 'Kva våre nøgde brukarar seier',
  'user_reviews_subtitle' => 'Sjå kvifor reisande rundt om i verda er avhengige av vår eSIM for sømlaus, påliteleg tilknyting på farten.',
  'faq' => 'Vanleg stilte spørsmål',
  'popular_destinations' => 'Populære destinasjonar',
  'popular_destinations_description' => 'Oppdag våre mest populære eSIM-destinasjoner og hold deg tilkoblet, uansett hvor du går!',
  'see_all_destinations' => 'Sjå alle destinasjonar',
];
