<?php

//This file is automatically generated. Do not modify.

return [
  'days' => 'dagar',
  'buy_plan' => 'Kjøp no!',
  'perks' => [
    'instant' => 'Direkte levering',
    'advanced_self_service' => 'Avansert sjølvbetjeningsportal',
    '247_support' => '24/7 live chat støtte',
    'prepaid' => 'Forbetalt, ingen vilkår knyttet',
    'no_roaming' => 'Ingen roamingkostnader',
  ],
  'local_for' => 'Lokale eSIM-ar for :countryName',
  'not_available_yet' => 'Vi tilbyr for tida ikkje eSIMar for dette landet.',
  'not_available_yet_contact_us' => 'Vi arbeider hardt for å utvide vår globale dekning. Hvis du er interessert i eSIMs for dette landet i mellomtiden, vennligst kontakt oss.',
  'top_plan' => 'Mest populære',
  'all_features' => 'Alle funksjonar',
  'features' => [
    'feature_one' => 'Moglegheitet for hotspot',
    'feature_two' => 'Dekning på tvers av alle nasjonale nettverk',
    'feature_three' => 'Enkel oppgradering i din personlege portal',
  ],
  'buy_now' => 'Kjøp no',
  'starting_from' => 'Startar frå',
  'choose_destination' => 'Finn ein destinasjon',
  'how_esim_works' => [
    'title' => 'Korleis eSIM fungerer',
    'subtitle' => 'Det er enkelt å komme i gang med eSIM! Følg disse enkle trinnene for å holde deg tilkoblet.',
    'steps' => [
      [
        'title' => 'Kjøp din eSIM',
        'description' => 'Velg destinasjonen din, velg en pakke som møter dine databehov, og fullfør kjøpet ditt.',
        'image' => '/images/howesimworks/1.png',
      ],
      [
        'title' => 'Motta din eSIM',
        'description' => 'Motta eSIM QR-koden direkte i e-posten din. Klar til å bruke med en gang.',
        'image' => '/images/howesimworks/2.png',
      ],
      [
        'title' => 'Aktiver og Koble til',
        'description' => 'Skann QR-koden, aktiver eSIM-en din, og nyt rask, pålitelig data uansett hvor du reiser.',
        'image' => '/images/howesimworks/3.png',
      ],
    ],
  ],
  'sub_description' => 'Velg pakken din nedenfor og nyt sømløs tilkobling i :countryName på de beste nettverkene til den beste prisen.',
];
