<?php

//This file is automatically generated. Do not modify.

return [
  'title' => 'eSIM-tjeneste - Forbetalte virtuelle SIM-kort for reisende - :site_name',
  'description' => 'eSIM teneste ⏩ Forbetalt digital SIM-kort for turisme og næringsliv ⏩ Standard og ubegrensa, lokale og globale mobiltelefon dataplanar ⏩ Ingen kontraktar ✅ Ingen skjulte roamingkostnader og gebyrer ✅ - :site_name',
  'keywords' => 'eSIM, eSIM teneste, eSIM kort, eSIM data, eSIM dataplan, eSIM dataplanar, eSIM dataplan for reisande, eSIM dataplan for turistar, eSIM dataplan for næringsliv, eSIM dataplan for reise, eSIM dataplan for Europa, eSIM dataplan for USA, eSIM dataplan for Asia, eSIM dataplan for Afrika, eSIM dataplan for Australia, eSIM dataplan for Sør-Amerika, eSIM dataplan for Nord-Amerika, eSIM dataplan for Midtausten, eSIM dataplan for Russland, eSIM dataplan for Kina, eSIM dataplan for India, eSIM dataplan for Japan',
  'routes' => [
    'home' => [
      'title' => 'eSIM-tjeneste - Forhåndsbetalte virtuelle SIM-kort for reisende - :site_name',
      'description' => 'eSIM-teneste ⏩ Forbetalt digital SIM-kort for turisme og næringsliv ⏩ Standard og ubegrensa, lokale og globale mobiltelefon dataplanar ⏩ Ingen kontraktar ✅ Ingen skjulte roamingkostnader og gebyrer ✅ - :site_name',
    ],
    'about' => [
      'title' => 'Om oss - :site_name',
      'description' => 'Om oss ⏩ Forbetalte digitale SIM-kort for turisme og næringsliv ⏩ Standard og ubegrensede, lokale og globale mobiltelefon dataplaner ⏩ Ingen kontrakter ✅ Ingen skjulte roamingavgifter og gebyrer ✅ - :site_name',
    ],
    'supported-devices' => [
      'title' => 'Støttede enheter - :site_name',
      'description' => 'Støttede enheter ⏩ Forbetalte digitale SIM-kort for turisme og næringsliv ⏩ Standard og ubegrensede, lokale og globale mobiltelefon dataplaner ⏩ Ingen kontrakter ✅ Ingen skjulte roamingavgifter og gebyrer ✅ - :site_name',
    ],
    'esim-bundle-per-country' => [
      'title' => 'Rimelige lokale eSIM-tilbod for :countryName - :site_name',
      'description' => 'Rimelige lokale eSIM-tilbod for :countryName ⏩ Forbetalte digitale SIM-kort for turisme og næringsliv ⏩ Standard og ubegrensa, lokale og globale mobiltelefon dataplanar ⏩ Ingen kontraktar ✅ Ingen skjulte roamingavgifter og gebyrer ✅ - :site_name',
    ],
  ],
];
