<?php

//This file is automatically generated. Do not modify.

return [
  'title' => 'eSIM-teneste - Prepaid virtuelle SIM-kort for reisande - :site_name',
  'description' => 'eSIM-tjeneste ⏩ Prepaid digitale SIM-kort for turisme og næringsliv ⏩ Standard og ubegrensede, lokale og globale mobile dataplaner ⏩ Ingen kontrakter ✅ Ingen skjulte roamingkostnader og -avgifter ✅ - :site_name',
  'keywords' => 'eSIM, eSIM-tjeneste, eSIM-kort, eSIM-data, eSIM-dataplan, eSIM-dataplanar, eSIM-dataplan for reisande, eSIM-dataplan for turistar, eSIM-dataplan for bedrifter, eSIM-dataplan for reiser, eSIM-dataplan for Europa, eSIM-dataplan for USA, eSIM-dataplan for Asia, eSIM-dataplan for Afrika, eSIM-dataplan for Australia, eSIM-dataplan for Sør-Amerika, eSIM-dataplan for Nord-Amerika, eSIM-dataplan for Midtøsten, eSIM-dataplan for Russland, eSIM-dataplan for Kina, eSIM-dataplan for India, eSIM-dataplan for Japan',
  'routes' => [
    'home' => [
      'title' => 'eSIM-teneste - Prepaid virtuelle SIM-kort for reisande - :site_name',
      'description' => 'eSIM-teneste ⏩ Prebetalte digitale SIM-kort for turisme og næringsliv ⏩ Standard og ubegrensa, lokale og globale mobile dataplanar ⏩ Ingen kontraktar ✅ Ingen skjulte roamingkostnader og -godtgjersler ✅ - :site_name',
    ],
    'about' => [
      'title' => 'Om oss - :site_name',
      'description' => 'Om oss ⏩ Prepaid digitale SIM-kort for turisme og næringsliv ⏩ Standard og ubegrensede, lokale og globale mobil dataplaner ⏩ Ingen kontrakter ✅ Ingen skjulte roamingkostnader og -avgifter ✅ - :site_name',
    ],
    'supported-devices' => [
      'title' => 'Støttede Enheter - :site_name',
      'description' => 'Støttede Enheter ⏩ Prepaid digitale SIM-kort for turisme og forretning ⏩ Standard og ubegrensede, lokale og globale mobil dataplaner ⏩ Ingen kontrakter ✅ Ingen skjulte roamingkostnader og -avgifter ✅ - :site_name',
    ],
    'esim-bundle-per-country' => [
      'title' => 'eSIM :countryName - :site_name',
      'description' => 'eSIM :countryName ⏩ Prepaid digitale SIM-kort for turisme og næringsliv ⏩ Standard og ubegrensede, lokale og globale mobil dataplaner ⏩ Ingen kontrakter ✅ Ingen skjulte roamingkostnader og -avgifter ✅ - :site_name',
    ],
  ],
];
