<?php

//This file is automatically generated. Do not modify.

return [
  'Rens' => [
    'role' => 'Medgrunnleggar',
    'image' => '/images/team/rens.png',
  ],
  'Luuk' => [
    'role' => 'Medgrunnleggar',
    'image' => '/images/team/luuk.png',
  ],
  'Fleur' => [
    'role' => 'Kundestøtte',
    'image' => '/images/team/fleur.png',
  ],
  'Patrick' => [
    'role' => 'Utviklar',
    'image' => '/images/team/patrick.png',
  ],
];
