<?php

//This file is automatically generated. Do not modify.

return [
  'title' => 'Всі наші напрямки',
  'subtitle' => 'Куди б ви не пішли, ми забезпечимо вас eSIM-картами для кожного напрямку. Виберіть ваше місце призначення нижче, щоб почати.',
];
