<?php

//This file is automatically generated. Do not modify.

return [
  'faq' => 'Часті запитання',
  'subtitle' => 'У вас є питання? У нас є відповіді. Знайдіть усе, що вам потрібно знати про наші eSIM.',
];
