<?php

//This file is automatically generated. Do not modify.

return [
  'all_rights_reserved' => 'Усі права захищені.',
  'foreign_currencies_for_reference_only' => 'Іноземні валюти наведені лише для довідки. Виставлення рахунків буде в євро.',
];
