<?php

//This file is automatically generated. Do not modify.

return [
  'home' => 'Головна',
  'supported-devices' => 'Підтримувані пристрої',
  'destinations' => 'Усі напрямки',
  'about' => 'Про',
  'contact' => 'Контакт',
  'portal_link' => 'Мій Portal',
];
