<?php

//This file is automatically generated. Do not modify.

return [
  'Rens' => [
    'role' => 'Співзасновник',
    'image' => '/images/team/rens.png',
  ],
  'Luuk' => [
    'role' => 'Співзасновник',
    'image' => '/images/team/luuk.png',
  ],
  'Fleur' => [
    'role' => 'Підтримка клієнтів',
    'image' => '/images/team/fleur.png',
  ],
  'Patrick' => [
    'role' => 'Розробник',
    'image' => '/images/team/patrick.png',
  ],
];
