<?php

//This file is automatically generated. Do not modify.

return [
  'title' => 'Despre noi',
  'subtitle' => 'Navigați lumea fără frontiere împreună cu noi. Suntem partenerul dumneavoastră suprem care vă menține conectat oriunde vă duce pasiunea.',
  'our_team' => 'Echipa Noastră',
  'our_team_subtitle' => 'Credem în împuternicirea călătorilor cu conectivitate globală de date fiabilă și accesibilă. Echipa noastră diversă este unită în crearea unei lumi mai conectate și accesibile pentru toți cei care sunt în mișcare.',
  'why_us' => 'De ce să ne alegi',
  'why_us_subtitle' => 'Suntem mândri de serviciul nostru fiabil, prețurile competitive și abordarea orientată spre client. Satisfacția dumneavoastră este cea mai mare prioritate a noastră.',
  'why_us_reasons' => [
    [
      'title' => 'Planuri flexibile concepute pentru nevoile tale de călătorie',
      'subtitle' => 'Alegeți dintr-o gamă de pachete accesibile adaptate la diferite țări și regiuni. Vă oferim flexibilitatea de a selecta planul de date perfect, astfel încât să plătiți doar pentru ceea ce aveți nevoie, fără costuri ascunse.',
      'image' => '/images/whyus/nlo2.png',
    ],
    [
      'title' => 'Activare directă, fără a fi necesare cartele SIM fizice',
      'subtitle' => 'Zilele în care schimbam cartele SIM fizice sunt de domeniul trecutului. Cu noi, eSIM-ul tău este livrat direct prin email și poate fi activat în câteva minute. Tot ce trebuie să faci este să scanezi codul QR și ești gata să te conectezi.',
      'image' => '/images/whyus/nlo3.png',
    ],
  ],
  'contact' => 'Contactați-ne',
  'contact_subtitle' => 'Suntem aici pentru a te ajuta. Dacă ai întrebări sau ai nevoie de asistență, te rugăm să ne contactezi.',
];
