<?php

//This file is automatically generated. Do not modify.

return [
  'title' => 'Toate destinațiile noastre',
  'subtitle' => 'Oriunde ai merge, te acoperim cu eSIM-uri pentru fiecare destinație. Alege-ți destinația mai jos pentru a începe.',
];
