<?php

//This file is automatically generated. Do not modify.

return [
  'title' => 'Dispozitive acceptate',
  'subtitle' => 'Sprijinim o gamă largă de dispozitive. Verificați dacă dispozitivul dumneavoastră se află pe lista de mai jos. Dispozitivele sunt organizate după fabricant.',
  'models_below' => 'Modelele suportate sunt enumerate mai jos.',
];
