<?php

//This file is automatically generated. Do not modify.

return [
  'faq' => 'Întrebări frecvente',
  'subtitle' => 'Ai întrebări? Avem răspunsuri. Găsește tot ce trebuie să știi despre eSIM-urile noastre.',
];
