<?php

//This file is automatically generated. Do not modify.

return [
  [
    'question' => 'Ce este un eSIM și cum pot folosi :organisationName?',
    'answer' => 'Un eSIM, sau SIM încorporat, este un card SIM digital care permite utilizatorilor să activeze și să gestioneze mai multe planuri mobile pe un singur dispozitiv fără a avea nevoie de un card SIM fizic. Cu un eSIM, poți comuta cu ușurință între furnizorii de servicii mobile și te poți bucura de caracteristici precum adăugarea unei linii suplimentare pentru călătorii internaționale sau menținerea unor planuri de date separate pentru uz personal și de afaceri.',
  ],
  [
    'question' => 'Cum activez internetul mobil eSIM cu :organisationName?',
    'answer' => 'Pentru a te conecta la internet folosind eSIM-ul :organisationName, urmează acești pași: 1. Mergi la setările tale de Date mobile. 2. Activează linia mobilă :organisationName. 3. Activează Roaming de date. 4. Selectează linia de Internet :organisationName ca fiind conexiunea ta principală. *Evită să selectezi opțiunea "Elimină planul de date," deoarece aceasta va șterge profilul tău eSIM.*',
  ],
  [
    'question' => 'Pot să fac apeluri telefonice sau să trimit mesaje text?',
    'answer' => 'Planurile eSIM preplătite ale :organisationName sunt concepute pentru utilizare exclusiv pentru date și nu includ un număr de telefon mobil pentru apeluri tradiționale sau mesaje SMS. Recomandăm utilizarea aplicațiilor VoIP precum Facebook Messenger, WhatsApp, Viber, Telegram sau Skype pentru a rămâne conectat la nivel mondial fără a avea nevoie de un card SIM internațional standard.',
  ],
  [
    'question' => 'Poate fi reutilizată o cartelă eSIM?',
    'answer' => 'Fiecare cod QR pentru un eSIM este unic și poate fi utilizat doar pe un singur dispozitiv. Odată ce profilul eSIM este șters, codul QR nu poate fi reutilizat pe același dispozitiv sau pe altul, asigurând securitate și exclusivitate.',
  ],
  [
    'question' => 'Când începe durata planurilor de date mobile eSIM?',
    'answer' => 'Durata planului tău de date eSIM începe imediat după ce dispozitivul tău se conectează pentru prima dată la o rețea mobilă cu eSIM.',
  ],
  [
    'question' => 'Pot să extind data de expirare a planului meu actual de date mobile eSIM?',
    'answer' => 'Sigur! Vei primi mai multe notificări push când ești aproape să rămâi fără pachetul tău. Poți să îți reîncarci ușor prin portalul tău personal.',
  ],
  [
    'question' => 'Pot folosi tethering sau Personal Hotspot cu :organisationName?',
    'answer' => 'Da, poți partaja datele tale mobile cu alte dispozitive prin intermediul :organisationName-eSIM. Pur și simplu instalează :organisationName-eSIM pe dispozitivul tău și activează Personal Hotspot în setările tale. Această funcție este inclusă fără costuri suplimentare, dar te rugăm să reții că utilizarea datelor prin tethering va fi dedusă din planul tău.',
  ],
  [
    'question' => 'Pot să păstrez numerele aplicației mele de mesagerie personală în timp ce folosesc eSIM-ul de la :organisationName?',
    'answer' => 'Da, poți continua să folosești WhatsApp, Snapchat, Telegram și alte aplicații de mesagerie împreună cu :organisationName eSIM preplătită fără nicio problemă.',
  ],
  [
    'question' => 'Cum pot să-mi transfer eSIM-ul pe un telefon nou?',
    'answer' => 'Înainte de a transfera, asigură-te că noul tău smartphone suportă tehnologia eSIM. Contactează echipa noastră de suport pentru a crea un nou profil eSIM, apoi conectează-te la contul tău :organisationName pe noul dispozitiv pentru a instala codul QR. Asigură-te că confirmi că folosești un dispozitiv diferit pentru actualizări precise ale setărilor.',
  ],
  [
    'question' => 'Există contracte ca cele ale furnizorilor tradiționali de eSIM?',
    'answer' => 'Nu, :organisationName nu necesită semnarea contractelor. Poți activa sau dezactiva cardul tău eSIM după cum dorești, în funcție de planurile tale. Suntem bucuroși să te ajutăm.',
  ],
  [
    'question' => 'Care este diferența dintre planurile de date eSIM ale :organisationName și planurile de roaming standard de la operatorii mobili fizici?',
    'answer' => ':organisationName oferă planuri de date fără contract, fără costuri ascunse de roaming. Plătești doar pentru datele pe care le folosești, în funcție de pachetul pe care îl alegi, făcându-l adesea o opțiune mai economică.',
  ],
  [
    'question' => 'De ce este lentă viteza mea de date?',
    'answer' => 'Viteza de date poate fi afectată de diversi factori, inclusiv tipul de smartphone pe care îl ai, tehnologia rețelei, site-urile web sau aplicațiile pe care le folosești și ora din zi. În plus, vitezele pot varia în funcție de infrastructura rețelei din țară. Dacă experimentezi viteze lente, încearcă să îți repornești telefonul și împărtășește-ne orice rezultate de viteză, în special comparații cu și fără LTE activat.',
  ],
  [
    'question' => 'Cum pot vizualiza pachetele mele?',
    'answer' => 'Puteți urmări datele și limitele rămase în panoul nostru de clienți.',
  ],
  [
    'question' => 'Ce face :organisationName diferit față de alte servicii eSIM?',
    'answer' => ':organisationName se remarcă prin colaborarea cu operatori locali în peste 200 de țări, oferind pachete de date rentabile fără intermediari. Oferim o acoperire robustă și un proces de activare simplu. :organisationName este perfect pentru călătorii care caută soluții de internet mobil.',
  ],
];
