<?php

//This file is automatically generated. Do not modify.

return [
  'title' => 'Rămâi conectat online în :countryName',
  'subtitle' => 'Călătoriți în :countryName? Rămâneți conectat cu eSIM-ul nostru, asigurându-vă că aveți acces instantaneu la internet la sosire.',
  'features' => [
    [
      'title' => 'Fiabil și rapid online în :countryName',
      'subtitle' => ':countryName este o destinație frumoasă, având orașe moderne vibrante și peisaje naturale uimitoare. Îmbunătățiți-vă experiența de călătorie cu eSIM-ul nostru, asigurându-vă că rămâneți conectat instantaneu la sosire. 
        Spuneți adio neplăcerilor de a căuta un card SIM local sau de a face față costurilor mari ale roaming-ului de date. Cu eSIM-ul nostru, veți avea acces fără întreruperi la rețelele 4G/5G de la cei mai buni furnizori din țară, menținându-vă online oriunde vă duce călătoria.',
      'image' => 'images/features/feature1.jpg',
    ],
    [
      'title' => 'Rămâi conectat cu cei dragi',
      'subtitle' => 'eSIM-ul nostru este conceput pentru accesul fără întreruperi la internet, menținându-vă conectat pentru toate activitățile dumneavoastră online fără a fi nevoie de un nou număr de telefon. Creați cu ușurință un hotspot pentru a împărtăși conexiunea cu alți călători sau cu familia, o caracteristică adesea blocată de alți furnizori, dar complet susținută de noi. Bucurați-vă de confortul conectivității instantanee pe dispozitive compatibile cu eSIM, asigurându-vă că dumneavoastră și cei dragi rămâneți online oricând, oriunde. Vă rugăm să confirmați dacă dispozitivul dumneavoastră suportă eSIM pentru a vă asigura că sunteți pregătit pentru ofertele noastre de internet. Vă rugăm să rețineți că apelurile și mesajele text nu sunt acceptate cu eSIM-ul nostru.',
      'image' => 'images/features/feature2.jpg',
    ],
  ],
];
