<?php

//This file is automatically generated. Do not modify.

return [
  'all_rights_reserved' => 'Toate drepturile rezervate.',
  'foreign_currencies_for_reference_only' => 'Monedele străine sunt doar pentru referință. Facturarea se va face în Euro.',
];
