<?php

//This file is automatically generated. Do not modify.

return [
  'from' => ':price/GB',
  'title' => 'Conectează-te global cu eSIM-urile noastre',
  'subtitle' => 'Explorați pachetele noastre eSIM și rămâneți conectați, oriunde ați fi!',
  'search_destination' => 'Găsește o destinație',
  'show_all_esim' => 'Afișați toate planurile eSIM',
  'how_it_works' => 'Cum funcționează?',
  'steps' => [
    [
      'title' => 'Pasul 1',
      'description' => 'Verifică dacă dispozitivul tău este compatibil cu eSIM în lista noastră de compatibilitate.',
    ],
    [
      'title' => 'Pasul 2',
      'description' => 'Alegeți destinația dorită și planul de date eSIM dorit.',
    ],
    [
      'title' => 'Pasul 3',
      'description' => 'Cumpără cardul eSIM care se potrivește cel mai bine nevoilor tale.',
    ],
    [
      'title' => 'Pasul 4',
      'description' => 'eSIM-ul tău va fi livrat automat. Urmează instrucțiunile din emailul tău.',
    ],
    [
      'title' => 'Pasul 5',
      'description' => 'Instalează-ți profilul eSIM și bucură-te de călătorie!',
    ],
  ],
  'supported_networks' => 'Furnizori de rețea susținuți',
  'supported_networks_description' => 'Colaborăm îndeaproape cu mărci de conectivitate, media și tehnologie de încredere, lideri de piață, din întreaga lume.',
  'and_many_more' => 'și mult mai mult...',
  'user_reviews' => 'Ce spun utilizatorii noștri mulțumiți',
  'user_reviews_subtitle' => 'Vezi de ce călătorii din întreaga lume se bazează pe eSIM-ul nostru pentru conectivitate fără întreruperi și de încredere în mișcare.',
  'faq' => 'Întrebări frecvente',
  'popular_destinations' => 'Destinații populare',
  'popular_destinations_description' => 'Descoperiți cele mai populare destinații eSIM și rămâneți conectați, indiferent de unde mergeți!',
  'see_all_destinations' => 'Vizualizați toate destinațiile',
];
