<?php

//This file is automatically generated. Do not modify.

return [
  'home' => 'Acasă',
  'supported-devices' => 'Dispozitive acceptate',
  'destinations' => 'Toate destinațiile',
  'about' => 'Despre',
  'contact' => 'Contact',
  'portal_link' => 'Portalul meu',
];
