<?php

//This file is automatically generated. Do not modify.

return [
  'days' => 'zile',
  'buy_plan' => 'Cumpără acum!',
  'perks' => [
    'instant' => 'Livrare directă',
    'advanced_self_service' => 'Portal avansat de autoservire',
    '247_support' => 'suport live chat 24/7',
    'prepaid' => 'Preplătit, fără condiții atașate',
    'no_roaming' => 'Fără taxe de roaming',
  ],
  'local_for' => 'eSIM-uri locale pentru :countryName',
  'not_available_yet' => 'În prezent, nu oferim eSIM-uri pentru această țară.',
  'not_available_yet_contact_us' => 'Lucrăm din greu pentru a ne extinde acoperirea globală. Dacă ești interesat de eSIM-uri pentru această țară între timp, te rugăm să ne contactezi.',
  'top_plan' => 'Cele mai populare',
  'all_features' => 'Toate funcțiile',
  'features' => [
    'feature_one' => 'Posibil hotspot',
    'feature_two' => 'Acoperire pe toate rețelele naționale',
    'feature_three' => 'Upgrade simplu în portalul tău personal',
  ],
  'buy_now' => 'Cumpără acum',
  'starting_from' => 'Începând de la',
  'choose_destination' => 'Găsește o destinație',
  'how_esim_works' => [
    'title' => 'Cum funcționează eSIM',
    'subtitle' => 'Începerea utilizării eSIM este ușoară! Urmați acești pași simpli pentru a rămâne conectat.',
    'steps' => [
      [
        'title' => 'Cumpără-ți eSIM-ul',
        'description' => 'Alegeți destinația, selectați un pachet care să corespundă nevoilor dvs. de date și finalizați achiziția.',
        'image' => '/images/howesimworks/1.png',
      ],
      [
        'title' => 'Primiți eSIM-ul dumneavoastră',
        'description' => 'Primiți codul QR eSIM direct în emailul dumneavoastră. Gata de utilizare imediată.',
        'image' => '/images/howesimworks/2.png',
      ],
      [
        'title' => 'Activează și Conectează',
        'description' => 'Scanează codul QR, activează-ți eSIM-ul și bucură-te de date rapide și fiabile oriunde călătorești.',
        'image' => '/images/howesimworks/3.png',
      ],
    ],
  ],
  'sub_description' => 'Alegeți-vă pachetul de mai jos și bucurați-vă de conectivitate fără întreruperi în :countryName pe cele mai bune rețele la cel mai bun preț.',
];
