<?php

//This file is automatically generated. Do not modify.

return [
  'title' => 'eSIM-service - Carduri SIM virtuale prepaid pentru călători - :site_name',
  'description' => 'eSIM-service ⏩ Carduri SIM digitale prepaid pentru turism și afaceri ⏩ Planuri de date mobile standard și nelimitate, locale și globale ⏩ Fără contracte ✅ Fără costuri și taxe ascunse de roaming ✅ - :site_name',
  'keywords' => 'eSIM, eSIM-service, eSIM-kaart, eSIM-gegevens, eSIM-gegevensplan, eSIM-gegevensplannen, eSIM-gegevensplan pentru călători, eSIM-gegevensplan pentru turiști, eSIM-gegevensplan pentru companii, eSIM-gegevensplan pentru călătorii, eSIM-gegevensplan pentru Europa, eSIM-gegevensplan pentru SUA, eSIM-gegevensplan pentru Asia, eSIM-gegevensplan pentru Africa, eSIM-gegevensplan pentru Australia, eSIM-gegevensplan pentru America de Sud, eSIM-gegevensplan pentru America de Nord, eSIM-gegevensplan pentru Orientul Mijlociu, eSIM-gegevensplan pentru Rusia, eSIM-gegevensplan pentru China, eSIM-gegevensplan pentru India, eSIM-gegevensplan pentru Japonia',
  'routes' => [
    'home' => [
      'title' => 'eSIM-service - Carduri SIM virtuale prepaid pentru călători - :site_name',
      'description' => 'eSIM-service ⏩ Carduri SIM digitale prepaid pentru turism și afaceri ⏩ Planuri de date mobile standard și nelimitate, locale și globale ⏩ Fără contracte ✅ Fără costuri și taxe ascunse de roaming ✅ - :site_name',
    ],
    'about' => [
      'title' => 'Despre noi - :site_name',
      'description' => 'Despre noi ⏩ Carduri SIM digitale prepaid pentru turism și afaceri ⏩ Planuri de date mobile standard și nelimitate, locale și globale ⏩ Fără contracte ✅ Fără costuri și taxe ascunse de roaming ✅ - :site_name',
    ],
    'supported-devices' => [
      'title' => 'Dispozitive acceptate - :site_name',
      'description' => 'Dispozitive acceptate ⏩ Carduri SIM digitale prepaid pentru turism și afaceri ⏩ Planuri de date mobile standard și nelimitate, locale și globale ⏩ Fără contracte ✅ Fără costuri și taxe ascunse de roaming ✅ - :site_name',
    ],
    'esim-bundle-per-country' => [
      'title' => 'eSIM :countryName - :site_name',
      'description' => 'eSIM :countryName ⏩ Carduri SIM digitale prepaid pentru turism și afaceri ⏩ Planuri de date mobile standard și nelimitate, locale și globale ⏩ Fără contracte ✅ Fără costuri și taxe ascunse de roaming ✅ - :site_name',
    ],
  ],
];
