<?php

//This file is automatically generated. Do not modify.

return [
  'title' => 'Serviciu eSIM - Carduri SIM Virtuale Preplătite pentru Călători - :site_name',
  'description' => 'serviciu eSIM ⏩ Carduri SIM digitale prepaid pentru turism și afaceri ⏩ Planuri de date pentru telefonie mobilă standard și nelimitate, locale și globale ⏩ Fără contracte ✅ Fără taxe și comisioane ascunse de roaming ✅ - :site_name',
  'keywords' => 'eSIM, serviciu eSIM, card eSIM, date eSIM, plan de date eSIM, planuri de date eSIM, plan de date eSIM pentru călători, plan de date eSIM pentru turiști, plan de date eSIM pentru afaceri, plan de date eSIM pentru călătorii, plan de date eSIM pentru Europa, plan de date eSIM pentru SUA, plan de date eSIM pentru Asia, plan de date eSIM pentru Africa, plan de date eSIM pentru Australia, plan de date eSIM pentru America de Sud, plan de date eSIM pentru America de Nord, plan de date eSIM pentru Orientul Mijlociu, plan de date eSIM pentru Rusia, plan de date eSIM pentru China, plan de date eSIM pentru India, plan de date eSIM pentru Japonia',
  'routes' => [
    'home' => [
      'title' => 'Serviciul eSIM - Carduri SIM virtuale preplătite pentru călători - :site_name',
      'description' => 'serviciu eSIM ⏩ Carduri SIM digitale preplătite pentru turism și afaceri ⏩ Planuri de date pentru telefonie mobilă standard și nelimitate, locale și globale ⏩ Fără contracte ✅ Fără taxe și comisioane ascunse de roaming ✅ - :site_name',
    ],
    'about' => [
      'title' => 'Despre noi - :site_name',
      'description' => 'Despre noi ⏩ Carduri SIM digitale preplătite pentru turism și afaceri ⏩ Planuri de date pentru telefonie mobilă standard și nelimitate, locale și globale ⏩ Fără contracte ✅ Fără taxe și costuri ascunse de roaming ✅ - :site_name',
    ],
    'supported-devices' => [
      'title' => 'Dispozitive acceptate - :site_name',
      'description' => 'Dispozitive acceptate ⏩ Carduri SIM digitale preplătite pentru turism și afaceri ⏩ Planuri de date pentru telefonie mobilă standard și nelimitate, locale și globale ⏩ Fără contracte ✅ Fără taxe și comisioane ascunse de roaming ✅ - :site_name',
    ],
    'esim-bundle-per-country' => [
      'title' => 'Oferte eSIM locale accesibile pentru :countryName - :site_name',
      'description' => 'Oferte eSIM locale accesibile pentru :countryName ⏩ Carduri SIM digitale prepaid pentru turism și afaceri ⏩ Planuri de date pentru telefonie mobilă standard și nelimitate, locale și globale ⏩ Fără contracte ✅ Fără taxe și comisioane ascunse de roaming ✅ - :site_name',
    ],
  ],
];
