<?php

//This file is automatically generated. Do not modify.

return [
  'title' => 'Sobre nosaltres',
  'subtitle' => 'Navega pel món sense fronteres amb nosaltres. Som el teu soci definitiu que et manté connectat on sigui que la teva passió et porti.',
  'our_team' => 'El nostre equip',
  'our_team_subtitle' => 'Creiem en apoderar els viatgers amb una connectivitat de dades global fiable i assequible. El nostre equip divers està unit en la creació d\'un món més connectat i accessible per a tothom que està en moviment.',
  'why_us' => 'Per què triar-nos',
  'why_us_subtitle' => 'Estem orgullosos del nostre servei fiable, preus competitius i enfocament orientat al client. La vostra satisfacció és la nostra màxima prioritat.',
  'why_us_reasons' => [
    [
      'title' => 'Plans flexibles dissenyats per a les teves necessitats de viatge',
      'subtitle' => 'Trieu d\'una gamma de paquets assequibles adaptats a diferents països i regions. Et donem la flexibilitat de seleccionar el pla de dades perfecte, així que només pagues per allò que necessites, sense costos ocults.',
      'image' => '/images/whyus/nlo2.png',
    ],
    [
      'title' => 'Activació directa, no es necessiten targetes SIM físiques',
      'subtitle' => 'Els dies de canviar targetes SIM físiques han acabat. Amb nosaltres, el teu eSIM es lliura directament per correu electrònic i es pot activar en pocs minuts. Només has de escanejar el codi QR i estàs llest per connectar-te.',
      'image' => '/images/whyus/nlo3.png',
    ],
  ],
  'contact' => 'Contacta\'ns',
  'contact_subtitle' => 'Estem aquí per ajudar-te. Si tens alguna pregunta o necessites ajuda, si us plau, contacta\'ns.',
];
