<?php

//This file is automatically generated. Do not modify.

return [
  'title' => 'Tots els nostres destins',
  'subtitle' => 'On vulguis, et tenim la solució amb eSIMs per a cada destinació. Tria la teva destinació a continuació per començar.',
];
