<?php

//This file is automatically generated. Do not modify.

return [
  'title' => 'Dispositius compatibles',
  'subtitle' => 'Donem suport a una àmplia gamma de dispositius. Comproveu si el vostre dispositiu està a la llista següent. Els dispositius estan organitzats per fabricant.',
  'models_below' => 'Els models compatibles es llisten a continuació.',
];
