<?php

//This file is automatically generated. Do not modify.

return [
  'faq' => 'FAQ',
  'subtitle' => 'Tens preguntes? Tenim respostes. Troba tot el que necessites saber sobre les nostres eSIMs.',
];
