<?php

//This file is automatically generated. Do not modify.

return [
  [
    'question' => 'Què és un eSIM i com puc utilitzar :organisationName?',
    'answer' => 'Un eSIM, o SIM integrada, és una targeta SIM digital que permet als usuaris activar i gestionar múltiples plans mòbils en un mateix dispositiu sense necessitat d\'una targeta SIM física. Amb un eSIM, pots canviar fàcilment entre proveïdors mòbils i gaudir de funcions com afegir una línia addicional per a viatges internacionals o mantenir plans de dades separats per a ús personal i empresarial.',
  ],
  [
    'question' => 'Com puc activar Internet mòbil eSIM amb :organisationName?',
    'answer' => 'Per connectar-te a Internet utilitzant l\'eSIM de :organisationName, segueix aquests passos: 1. Ves a la configuració de Dades Mòbils. 2. Activa la línia mòbil de :organisationName. 3. Activa l\'itinerància de dades. 4. Selecciona la línia d\'Internet de :organisationName com a connexió principal. *Evita seleccionar l\'opció "Eliminar pla de dades", ja que això esborrarà el teu perfil d\'eSIM.*',
  ],
  [
    'question' => 'Puc fer trucades telefòniques o enviar missatges de text?',
    'answer' => 'Els plans d\'eSIM prepagats de :organisationName estan dissenyats per a l\'ús exclusivament de dades i no inclouen un número de telèfon mòbil per a trucades tradicionals o missatges SMS. Recomanem utilitzar aplicacions de VoIP com Facebook Messenger, WhatsApp, Viber, Telegram o Skype per mantenir-se connectat a tot el món sense la necessitat d\'una targeta SIM internacional estàndard.',
  ],
  [
    'question' => 'Es pot reutilitzar una targeta eSIM?',
    'answer' => 'Cada codi QR per a un eSIM és únic i només es pot utilitzar en un dispositiu. Un cop s\'elimina el perfil d\'eSIM, el codi QR no es pot reutilitzar en el mateix dispositiu o en un altre, garantint la seguretat i l\'exclusivitat.',
  ],
  [
    'question' => 'Quan comença la durada dels plans de dades mòbils eSIM?',
    'answer' => 'La durada del teu pla de dades eSIM comença immediatament després que el teu dispositiu es connecti per primera vegada a una xarxa mòbil amb l\'eSIM.',
  ],
  [
    'question' => 'Puc ampliar la data de caducitat del meu actual pla de dades mòbils eSIM?',
    'answer' => 'Segur! Rebràs múltiples notificacions push quan estiguis a punt d\'esgotar el teu paquet. Pots recarregar fàcilment a través del teu portal personal.',
  ],
  [
    'question' => 'Puc utilitzar el tethering o el Personal Hotspot amb :organisationName?',
    'answer' => 'Sí, pots compartir les teves dades mòbils amb altres dispositius a través del teu :organisationName-eSIM. Simplement instal·la el :organisationName-eSIM al teu dispositiu i activa el Personal Hotspot a la teva configuració. Aquesta funció està inclosa sense cost addicional, però si us plau, tingues en compte que l\'ús de dades connectades es deduirà del teu pla.',
  ],
  [
    'question' => 'Puc mantenir els meus números de l\'aplicació de missatgeria personal mentre faig servir l\'eSIM de :organisationName?',
    'answer' => 'Sí, pots continuar utilitzant el teu WhatsApp, Snapchat, Telegram i altres aplicacions de missatgeria juntament amb el teu :organisationName eSIM de prepagament sense cap problema.',
  ],
  [
    'question' => 'Com puc transferir el meu eSIM a un nou telèfon?',
    'answer' => 'Abans de transferir, assegureu-vos que el vostre nou telèfon intel·ligent sigui compatible amb la tecnologia eSIM. Contacteu amb el nostre equip de suport per crear un nou perfil eSIM, després inicieu sessió al vostre compte :organisationName en el nou dispositiu per instal·lar el codi QR. Assegureu-vos de confirmar que esteu utilitzant un dispositiu diferent per a actualitzacions de configuració precises.',
  ],
  [
    'question' => 'Hi ha contractes com els dels proveïdors d\'eSIM tradicionals?',
    'answer' => 'No, :organisationName no requereix que signis contractes. Pots activar o desactivar la teva targeta eSIM com desitgis, depenent dels teus plans. Estem encantats d\'ajudar-te.',
  ],
  [
    'question' => 'Quina és la diferència entre l\'eSIM de :organisationName i els plans de dades de roaming estàndard dels operadors mòbils físics?',
    'answer' => ':organisationName ofereix plans de dades sense contracte i sense costos ocults de roaming. Només pagues per les dades que utilitzes, depenent del paquet que triïs, cosa que sovint el converteix en una opció més econòmica.',
  ],
  [
    'question' => 'Per què és lenta la meva velocitat de dades?',
    'answer' => 'La velocitat de dades pot ser afectada per diversos factors, incloent el tipus d\'smartphone que tens, la tecnologia de xarxa, els llocs web o aplicacions que utilitzes, i l\'hora del dia. A més, les velocitats poden variar segons la infraestructura de xarxa del país. Si estàs experimentant velocitats lentes, prova a reiniciar el teu telèfon i comparteix amb nosaltres qualsevol resultat de velocitat, especialment comparacions amb i sense :LTE mode habilitat.',
  ],
  [
    'question' => 'Com puc veure els meus paquets?',
    'answer' => 'Podeu fer un seguiment de les vostres dades restants i límits al nostre panell de clients.',
  ],
  [
    'question' => 'Què fa que :organisationName sigui diferent d\'altres serveis d\'eSIM?',
    'answer' => ':organisationName destaca per la seva col·laboració amb operadors locals en més de 200 països, oferint paquets de dades econòmics sense intermediaris. Oferim una cobertura robusta i un procés d\'activació senzill. :organisationName és perfecte per a viatgers que busquen solucions d\'internet mòbil.',
  ],
];
