<?php

//This file is automatically generated. Do not modify.

return [
  'title' => 'Mantingueu-vos connectats en línia a :countryName',
  'subtitle' => 'Viatjant a :countryName? Mantingueu-vos connectat amb la nostra eSIM, assegurant-vos que tingueu accés instantani a Internet en arribar.',
  'features' => [
    [
      'title' => 'Fiable i ràpid en línia a :countryName',
      'subtitle' => ':countryName és una destinació preciosa, que compta amb ciutats modernes vibrants i paisatges naturals impressionants. Millora la teva experiència de viatge amb la nostra eSIM, assegurant-te que et mantinguis connectat instantàniament en arribar. 
        Digues adéu a la molèstia de buscar una targeta SIM local o de tractar amb costos de roaming de dades. Amb la nostra eSIM, gaudiràs d\'accés sense interrupcions a xarxes 4G/5G dels principals proveïdors del país, mantenint-te en línia on sigui que et porti el teu viatge.',
      'image' => 'images/features/feature1.jpg',
    ],
    [
      'title' => 'Mantingueu-vos connectat amb els éssers estimats',
      'subtitle' => 'La nostra eSIM està dissenyada per a un accés a internet sense interrupcions, mantenint-te connectat per a totes les teves activitats en línia sense la necessitat d\'un nou número de telèfon. Crea fàcilment un hotspot per compartir la teva connexió amb altres viatgers o familiars, una funció sovint bloquejada per altres proveïdors però totalment suportada per nosaltres. Gaudeix de la comoditat de la connectivitat instantània en dispositius compatibles amb eSIM, assegurant-te que tu i els teus éssers estimats estigueu en línia en qualsevol moment i lloc. Si us plau, confirma si el teu dispositiu suporta eSIM per assegurar-te que estàs preparat per a les nostres ofertes d\'internet. Tingues en compte que les trucades i els missatges de text no són compatibles amb la nostra eSIM.',
      'image' => 'images/features/feature2.jpg',
    ],
  ],
];
