<?php

//This file is automatically generated. Do not modify.

return [
  'all_rights_reserved' => 'Tots els drets reservats.',
  'foreign_currencies_for_reference_only' => 'Les monedes estrangeres són només per a referència. La facturació es farà en euros.',
];
