<?php

//This file is automatically generated. Do not modify.

return [
  'from' => ':price/GB',
  'title' => 'Connecta\'t globalment amb les nostres eSIMs',
  'subtitle' => 'Explora els nostres paquets d\'eSIM i mantingues-te connectat, sigui on sigui!',
  'search_destination' => 'Troba una destinació',
  'show_all_esim' => 'Mostra tots els plans d\'eSIM',
  'how_it_works' => 'Com funciona?',
  'steps' => [
    [
      'title' => 'Pas 1',
      'description' => 'Comprova si el teu dispositiu és compatible amb eSIM a la nostra llista de compatibilitat.',
    ],
    [
      'title' => 'Pas 2',
      'description' => 'Trieu el teu destí i el pla de dades eSIM desitjat',
    ],
    [
      'title' => 'Pas 3',
      'description' => 'Compra la targeta eSIM que millor s\'adapti a les teves necessitats',
    ],
    [
      'title' => 'Pas 4',
      'description' => 'El teu eSIM es lliurarà automàticament. Segueix les instruccions del teu correu electrònic.',
    ],
    [
      'title' => 'Pas 5',
      'description' => 'Instal·la el teu perfil eSIM i gaudeix del teu viatge!',
    ],
  ],
  'supported_networks' => 'Proveïdors de xarxa compatibles',
  'supported_networks_description' => 'Treballen estretament amb marques de connectivitat, mitjans i tecnologia de confiança i líders del mercat a tot el món.',
  'and_many_more' => 'i molt més...',
  'user_reviews' => 'El que diuen els nostres usuaris satisfets',
  'user_reviews_subtitle' => 'Vegeu per què els viatgers d\'arreu del món confien en la nostra eSIM per a una connectivitat fluida i fiable en moviment.',
  'faq' => 'Preguntes Freqüents',
  'popular_destinations' => 'Destinacions Populars',
  'popular_destinations_description' => 'Descobreix les nostres destinacions eSIM més populars i mantingues-te connectat, sigui on sigui que vagis!',
  'see_all_destinations' => 'Veure totes les destinacions',
];
