<?php

//This file is automatically generated. Do not modify.

return [
  'days' => 'dies',
  'buy_plan' => 'Compra ara!',
  'perks' => [
    'instant' => 'Entrega directa',
    'advanced_self_service' => 'Portal avançat d\'autoservei',
    '247_support' => 'suport de xat en viu 24/7',
    'prepaid' => 'Prepagat, sense condicions adjuntes',
    'no_roaming' => 'Sense càrrecs de roaming',
  ],
  'local_for' => 'eSIM locals per :countryName',
  'not_available_yet' => 'Actualment no oferim eSIMs per a aquest país.',
  'not_available_yet_contact_us' => 'Estem treballant dur per expandir la nostra cobertura global. Si estàs interessat en eSIMs per a aquest país mentrestant, si us plau, contacta\'ns.',
  'top_plan' => 'Més popular',
  'all_features' => 'Totes les funcions',
  'features' => [
    'feature_one' => 'Possible hotspot',
    'feature_two' => 'Cobertura a través de totes les xarxes nacionals',
    'feature_three' => 'Actualització senzilla al teu portal personal',
  ],
  'buy_now' => 'Compra ara',
  'starting_from' => 'Començant des de',
  'choose_destination' => 'Troba una destinació',
  'how_esim_works' => [
    'title' => 'Com funciona l\'eSIM',
    'subtitle' => 'Començar amb eSIM és fàcil! Segueix aquests passos simples per mantenir-te connectat.',
    'steps' => [
      [
        'title' => 'Compra el teu eSIM',
        'description' => 'Trieu el teu destí, selecciona un paquet que s\'adapti a les teves necessitats de dades i completa la teva compra.',
        'image' => '/images/howesimworks/1.png',
      ],
      [
        'title' => 'Rebreu el teu eSIM',
        'description' => 'Rebiu el teu codi QR eSIM directament al teu correu electrònic. Preparat per a usar immediatament.',
        'image' => '/images/howesimworks/2.png',
      ],
      [
        'title' => 'Activa i Connecta',
        'description' => 'Escaneja el codi QR, activa la teva eSIM i gaudeix de dades ràpides i fiables on sigui que viatges.',
        'image' => '/images/howesimworks/3.png',
      ],
    ],
  ],
  'sub_description' => 'Trieu el teu paquet a continuació i gaudeix d\'una connectivitat sense interrupcions a :countryName en les millors xarxes al millor preu.',
];
