<?php

//This file is automatically generated. Do not modify.

return [
  'title' => 'Servei eSIM - Targetes SIM Virtuals Prepagades per a Viatgers - :site_name',
  'description' => 'servei eSIM ⏩ Targetes SIM digitals de pagament anticipat per al turisme i els negocis ⏩ Plans de dades per a telèfons mòbils locals i globals, estàndard i il·limitats ⏩ Sense contractes ✅ Sense càrrecs i taxes ocults de Roaming ✅ - :site_name',
  'keywords' => 'eSIM, servei eSIM, targeta eSIM, dades eSIM, pla de dades eSIM, plans de dades eSIM, pla de dades eSIM per a viatgers, pla de dades eSIM per a turistes, pla de dades eSIM per a negocis, pla de dades eSIM per a viatges, pla de dades eSIM per a Europa, pla de dades eSIM per a EUA, pla de dades eSIM per a Àsia, pla de dades eSIM per a Àfrica, pla de dades eSIM per a Austràlia, pla de dades eSIM per a Amèrica del Sud, pla de dades eSIM per a Amèrica del Nord, pla de dades eSIM per a Orient Mitjà, pla de dades eSIM per a Rússia, pla de dades eSIM per a Xina, pla de dades eSIM per a Índia, pla de dades eSIM per a Japó',
  'routes' => [
    'home' => [
      'title' => 'Servei d\'eSIM - Targetes SIM Virtuals Prepagades per a Viatgers - :site_name',
      'description' => 'servei eSIM ⏩ Targetes SIM digitals de prepago per al turisme i els negocis ⏩ Plans de dades mòbils locals i globals, estàndard i il·limitats ⏩ Sense contractes ✅ Sense càrrecs i taxes de Roaming ocults ✅ - :site_name',
    ],
    'about' => [
      'title' => 'Sobre nosaltres - :site_name',
      'description' => 'Sobre nosaltres ⏩ Targetes SIM digitals prepagades per al turisme i els negocis ⏩ Plans de dades per telèfon mòbil locals i globals, estàndard i il·limitats ⏩ Sense contractes ✅ Sense càrrecs ni tarifes de roaming ocults ✅ - :site_name',
    ],
    'supported-devices' => [
      'title' => 'Dispositius compatibles - :site_name',
      'description' => 'Dispositius compatibles ⏩ Targetes SIM digitals de prepago per al turisme i els negocis ⏩ Plans de dades per telèfons mòbils locals i globals, estàndard i il·limitats ⏩ Sense contractes ✅ Sense càrrecs ni taxes de Roaming ocults ✅ - :site_name',
    ],
    'esim-bundle-per-country' => [
      'title' => 'Ofertes d\'eSIM locals assequibles per a :countryName - :site_name',
      'description' => 'Ofertes d\'eSIM locals assequibles per a :countryName ⏩ Targetes SIM digitals de pagament anticipat per al turisme i els negocis ⏩ Plans de dades mòbils locals i globals, estàndard i il·limitats ⏩ Sense contractes ✅ Sense càrrecs ni taxes ocultes de Roaming ✅ - :site_name',
    ],
  ],
];
