<?php

//This file is automatically generated. Do not modify.

return [
  'title' => 'eSIM-service - Targetes de SIM virtuals de prepai per a viatgers - :site_name',
  'description' => 'eSIM-service ⏩ Targetes digitals de SIM per a turisme i negocis ⏩ Plans de dades mòbils locals i globals estàndard i il·limitats ⏩ Sense contractes ✅ Sense costos ni càrrecs ocults de roaming ✅ - :site_name',
  'keywords' => 'eSIM, eSIM-servei, eSIM-targeta, eSIM-dades, eSIM-plà de dades, eSIM-plans de dades, eSIM-plà de dades per a viatgers, eSIM-plà de dades per a turistes, eSIM-plà de dades per a empreses, eSIM-plà de dades per a viatges, eSIM-plà de dades per a Europa, eSIM-plà de dades per als EUA, eSIM-plà de dades per a Àsia, eSIM-plà de dades per a Àfrica, eSIM-plà de dades per a Austràlia, eSIM-plà de dades per a Amèrica del Sud, eSIM-plà de dades per a Amèrica del Nord, eSIM-plà de dades per al Pròxim Orient, eSIM-plà de dades per a Rússia, eSIM-plà de dades per a Xina, eSIM-plà de dades per a Índia, eSIM-plà de dades per a Japó',
  'routes' => [
    'home' => [
      'title' => 'eSIM-service - Targetes de SIM virtuals de prepai per a viatgers - :site_name',
      'description' => 'eSIM-service ⏩ Targetes digitals de SIM prepagades per al turisme i negocis ⏩ Plans de dades mòbils estàndard i il·limitats, locals i globals ⏩ Sense contractes ✅ Sense costos ni càrrecs ocults de roaming ✅ - :site_name',
    ],
    'about' => [
      'title' => 'Sobre nosaltres - :site_name',
      'description' => 'Sobre nosaltres ⏩ Targetes SIM digitals de pagament anticipat per al turisme i els negocis ⏩ Plans de dades mòbils locals i globals estàndard i il·limitats ⏩ Sense contractes ✅ Sense costos ni càrrecs ocults de roaming ✅ - :site_name',
    ],
    'supported-devices' => [
      'title' => 'Dispositius compatibles - :site_name',
      'description' => 'Dispositius compatibles ⏩ Targetes SIM digitals de prepago per a turisme i negocis ⏩ Plans de dades mòbils locals i globals estàndard i il·limitats ⏩ Sense contractes ✅ Sense costos ni càrrecs ocults de roaming ✅ - :site_name',
    ],
    'esim-bundle-per-country' => [
      'title' => 'eSIM :countryName - :site_name',
      'description' => 'eSIM :countryName ⏩ Targetes de SIM digitals de prepago per a turisme i negocis ⏩ Plans de dades mòbils locals i globals, estàndard i il·limitats ⏩ Sense contractes ✅ Sense costos ni càrrecs ocults de roaming ✅ - :site_name',
    ],
  ],
];
